### PR TITLE
[pentest] Move SHA3 trigger arm&disarm

### PR DESCRIPTION
**Pull request by nasahlpa**
As discussed offline with @vogelpi, this PR moves the arming and disarming of the SCA trigger for SHA3 before and after the process command is issued. This ensures that we only capture the SCA relevant parts for doing power analysis.

### CODE REVIEW

**Comment by nasahlpa** [comment]
Currently, I've made the change only in the uJSON code but not in the simpleserial code. The reason for this is that I think it might be good to keep the old simpleserial code as it is to keep the measurements we made reproducible. OK for you, @vogelpi?

**Review by vrozic — APPROVED** [review]
Thanks @nasahlpa for fixing this.
In my view, it would be OK to also change `sha3_serial.c`. If we end up needing to reproduce measurements we can always recover the current binaries from ot-sca git history.

**Comment by nasahlpa** [comment]
> Thanks @nasahlpa for fixing this. In my view, it would be OK to also change `sha3_serial.c`. If we end up needing to reproduce measurements we can always recover the current binaries from ot-sca git history.

Thanks for the feedback! Makes sense, I've also applied the change to the simpleserial code.

**Review by vogelpi — APPROVED** [review]
Thanks @nasahlpa for the PR. This looks good. Doing it also for the simpleserial version is a good idea @vrozic .

Looking at this code, I also remembered why we did this. It's because in `fpga_mode` (in the past we only had this mode) it doesn't matter. the trigger will only become high when the hardware engine really starts the processing. As long as it's idle while the message is provided, the trigger stays low.

**Pull request merged**
