### PR TITLE
[pinmux] Add JTAG reset mux

### PR DESCRIPTION
**Pull request by msfschaffner**
This addresses #5600

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
@NoamGottlieb
@arnonsha

**Comment by msfschaffner** [comment]
Technically yes, so I think this is a question for @arnonsha and @NoamGottlieb, whether this is going to be an issue or not...

**Comment by tjaychen** [comment]
o yeah sorry if i was not clear, i did mean those questions for them.

**Comment by arnonsha** [comment]
In functional mode scan_rst is disabled so no problem
In scan mode yes, but **we do not use the TAP** at all. It is just random logic that needs to be scanned as any other FF in OT.

**Comment by tjaychen** [comment]
sounds good. @msfschaffner i'm not sure if we should add a parameter here or not.  I do know in certain designs signals such as `scanmode` are implemented directly in the TAP controller.. so in those situations this would become a problem.  We could just note that could be a problem, and deal with it when we actually run into a design that does that.

**Review by tjaychen — APPROVED** [review]

**Comment by msfschaffner** [comment]
Ok, I have added a comment for that!

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
