### PR TITLE
Backport ci changes

### PR DESCRIPTION
**Pull request by pamaury**
This is a backport of #21580, #21645 and #20836 but I had to fix every single commit with conflicts so please double-check carefully @nbdd0121 and @jwnrt 

I also re-enabled the rom and rom_test jobs but added a condition so that they only run on the master branch. The idea is that we can back-backport this change to master and avoid divergences between the azure files (thanks @nbdd0121 for the suggestion)

### CODE REVIEW

**Comment by pamaury** [comment]
Just to help review: with this change, the only diff between master and earlgray_es_sival for the azure pipelines are:
- condition on rom and rom_ext dependent on branch -> will be backported to master
- branch and bucket for GCP -> different names on master and earlgrey_es_sival so that's fine
- changes introduced by #https://github.com/lowRISC/opentitan/issues/8440 related to ip_gen (probably not needed for  es_sival branch since RTL does not change?)

**Review by jwnrt — APPROVED** [review]
The changes here LGTM, good idea to conditionally re-enable those ROM FPGA tests. I'll have another look at the logs of the CI run once it's finished to make sure it's doing what we expect.

**Review by nbdd0121 — APPROVED** [review]

**Comment by pamaury** [comment]
I had to do so more manual fixing because we have a couple more tests in es_sival and those still had `--bitstream`. I also early-backported part of #21757 to remove manual-tagged tests to avoid running pmod tests.

**Comment by nbdd0121** [comment]
The log says the ROM job is doing bitstream build now

**Comment by pamaury** [comment]
I added a commit to remove the `spi_device_ottf` test, see commit for details.

**Review by jwnrt — APPROVED** [review]
I think removing the SPI device OTTF console test is fine since we don't have it in master anymore.

**Pull request merged**
