### PR TITLE
Rv dm halted

### PR DESCRIPTION
**Pull request by BasitMehmood**
This was failing in regression list so doing PR again.

### CODE REVIEW

**Comment by BasitMehmood** [comment]
@jdonjdon

**Comment by rswarbrick** [comment]
Please could you sort out the commits in this PR? At the moment, the list includes the contents of #20870. I think this PR is just supposed to be the final commit?

**Review by rswarbrick — CHANGES_REQUESTED** [review]
Looking at the code in the final commit, I don't think it quite looks right at the moment.

In particular, I can't see any reads of the `w_data` variable.

**Comment by BasitMehmood** [comment]
> Please could you sort out the commits in this PR? At the moment, the list includes the contents of #20870. I think this PR is just supposed to be the final commit?

ok i am closing this PR and made another separate PR for this sequence.

**Pull request closed without merging**
