### PR TITLE
[pattgen, dv] Add initial testplan for pattgen ip

### PR DESCRIPTION
**Pull request by tunghoang290780**
Re-pushed due to mess-up on git.

Signed-off-by: Tung Hoang <hoang.tung@wdc.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM

**Review by rasmus-madsen — APPROVED** [review]
LGTM

**Review by sriyerg — APPROVED** [review]

**Comment by sriyerg** [comment]
Is this it or are there more to come?

**Comment by tunghoang290780** [comment]
> Is this it or are there more to come?

@sriyerg this PR consists of only the testplan.md file. Next PR will have initial V0 (and/or csr_* tests)

**Review by cindychip — APPROVED** [review]

**Comment by tunghoang290780** [comment]
@weicaiyang @rasmus-madsen @sriyerg @cindychip can you merge this PR? It is blocking other ones

**Comment by cindychip** [comment]
sorry about that. just merged.

**Pull request merged**
