### PR TITLE
[sw/silicon_creator] Add spx signature verification when disabled

### PR DESCRIPTION
**Pull request by alphan**
This PR adds support for SPX signature verification when it's disabled in OTP, i.e. the "do nothing without breaking anything" case.

Please see the individual commits for details.

### CODE REVIEW

**Review by moidx — COMMENTED** [review]
Thanks @alphan!

My only comment is related to the use of `CREATOR_SW_CFG_SIGVERIFY_SPX_EN`. I think with the current field definition/encoding it is harder to fault into `enable` mode. Should we consider reversing this so that it is harder to fault in to `disable` mode?

This would potential require manufacturing to disable PQC before enabling ROM execution. I think it is probably ok to do so if we accept the fact that other OTP writes via JTAG or code injection must work during manufacturing.

**Comment by moidx** [comment]
> Re manufacturing, I think having this disabled in test_unlocked should be enough, don't you think so? We should hopefully be in the final config by the time we transition to a mission mode, right?

Sorry, I forgot about this! Yes, this should be good enough.

**Review by moidx — APPROVED** [review]

**Comment by alphan** [comment]
@moidx, thanks for the quick review! The last push should address your comment. PTAL the [diff](https://github.com/lowRISC/opentitan/compare/60e22440b95e0b05bf469ca2e87e8c4e805780ea..18f8fc448620831f6efc8902affd1b165973c22c) here when you get the chance.

**Comment by moidx** [comment]
Thanks @alphan! LGTM

**Pull request merged**
