### PR TITLE
[verilator] Minor updates for logging and sim termination support 

### PR DESCRIPTION
**Pull request by tjaychen**

### CODE REVIEW

**Comment by tjaychen** [comment]
Related to #551

**Comment by tjaychen** [comment]
yep I think @sriyerg is planning like this for DV, so my plan is to shift to that when it's available (or we can move this over, both are fine with me).

I originally added this for riscv compliance, but since I've switched to using the pytest approach, this PR is actually no longer necessary.  We could close it and just wait for the DV update, it's really up to you guys.

**Comment by imphil** [comment]
Being able to end a simulation is useful functionality, and integrating that is helpful. So please go ahead and merge this PR if you're happy with it!

(It would be nice to extend our software wrappers at one point so that a return from `main()` actually ends the simulation as well, #501)

**Comment by tjaychen** [comment]
i think @mcy is actually looking at something like that (i may be mis-remembering).

**Pull request merged**
