### PR TITLE
[top/dv] Ibex lockstep test fixes

### PR DESCRIPTION
**Pull request by vogelpi**
This is related to #15538 and contains two changes to fix the last two failures observed:
1. Make the test aware of the fact that even if Ibex isn't using the data on RF Read Port b, the returned and potentially glitched data may propagate through the LSU and into `data_wdata_o`. This may result in a mismatch even though the test previously assumed it wouldn't.
2. Increase the delay for expecting a failure when glitching `data_gnt_i` and `data_rdata_i` by one clock cycle.

In general, this waiting for a specific number of clock cycles looks error prone to me. For `data_gnt_i` mismatches should indeed always happen quickly:
- Glitching to 1: the glitched core moves forward and de-asserts `data_req_o` or changes `data_addr_o` (when doing back to back LD/ST).
- Glitching to 0: it doesn't de-assert `data_req_o` or change `data_addr_o`.

But when glitching e.g. `data_rdata_i` or other data input signals I can imagine it could also take more cycles. Should we increase the number of clock cycles for these just in general? What do you think @andreaskurth ?

### CODE REVIEW

**Review by andreaskurth — APPROVED** [review]
LGTM, thanks for tracking these corner cases down, @vogelpi!

**Comment by andreaskurth** [comment]
> But when glitching e.g. `data_rdata_i` or other data input signals I can imagine it could also take more cycles. Should we increase the number of clock cycles for these just in general? What do you think @andreaskurth ?

We could. The reason I kept the number of cycles to wait after the glitch low is to reduce the uncertainty that comes with the glitch propagating out of the core and into the system -- depending on the glitch, many things could fail and we don't want to handle them all. Maybe instead of delaying for a fixed number of cycles, we could sample the major alert in every cycle *up to* a fixed maximum? (And then still complete the test as soon as the alert is detected.)

**Comment by vogelpi** [comment]
> > But when glitching e.g. `data_rdata_i` or other data input signals I can imagine it could also take more cycles. Should we increase the number of clock cycles for these just in general? What do you think @andreaskurth ?
> 
> We could. The reason I kept the number of cycles to wait after the glitch low is to reduce the uncertainty that comes with the glitch propagating out of the core and into the system -- depending on the glitch, many things could fail and we don't want to handle them all. Maybe instead of delaying for a fixed number of cycles, we could sample the major alert in every cycle _up to_ a fixed maximum? (And then still complete the test as soon as the alert is detected.)

Thanks for giving some more background on this. Your proposal of repeatedly checking for some clock cycles sounds like the right thing to do. I'll do a follow-up. In the meantime. I mark this PR as ready to merge.

**Review by msfschaffner — APPROVED** [review]

**Comment by cdgori** [comment]
> Thanks for giving some more background on this. Your proposal of repeatedly checking for some clock cycles sounds like the right thing to do. I'll do a follow-up. In the meantime. I mark this PR as ready to merge.

Sorry for coming very late to the party on this: I think this PR is/was fine but was trying to search/trace for the follow-up with the repeated checking and couldn't find it.  I want to make sure this doesn't get lost.

**Comment by msfschaffner** [comment]
@vogelpi should we create an issue to track this?

**Comment by vogelpi** [comment]
Thanks for the reminder @cdgori ! I've now created an issue here: #16954

**Pull request merged**
