### PR TITLE
[prim/util] Consolidate design scripts and move them to util/design

### PR DESCRIPTION
**Pull request by msfschaffner**
This is a refactor pass of the life cycle state, OTP memory map, sparse FSM and LFSR generator scripts with the intent to consolidate common subfunctions. Further, some of the main OTP and LC state generation procedures are wrapped in classes such that they can be imported in the OTP preload image generator script, which will be added soon.

As part of this refactoring pass, I have moved these generator scripts (including others for keccak and secded) to a common folder under `${PROJ_ROOT}/util/design` to make it easier in the future to share common subfunctions (this is otherwise not really feasible or ugly to achieve when scripts are spread all over the place due to the way python modules have to be imported).

There are several commits in this PR to ease reviewing. I will squash them into 1-2 commits before merging.

### CODE REVIEW

**Comment by msfschaffner** [comment]
Latest force push was just a rebase onto master.

**Review by vogelpi — APPROVED** [review]
This looks good to me. I didn't review the OTP and LC classes though. Thanks for adjusting all references in the repo to the moved scripts.

Note that this PR also adds an empty file `util/design/lib/__init__.py`. This should probably be removed and excluded in the .gitignore?

**Review by cindychip — APPROVED** [review]
LGTM

**Comment by msfschaffner** [comment]
Thanks for the reviews. That's fine, since the OTP and LC classes are anyway more of an intermediate state.

Regarding the `__init__.py` file... I think you are right. I though it was required to make classes importable in this folder, but for Python 3.3 empty `__init__.py` files are created automatically.

**Comment by msfschaffner** [comment]
Last commit removes the `__init__.py` file and squashes some commits.

**Pull request merged**
