### PR TITLE
option to use partner ast_pkg

### PR DESCRIPTION
**Pull request by sha-ron**
Signed-off-by: Sharon Topaz <sharon.topaz@nuvoton.com>
Adding an option to use partner ast_pkg instead of open source ast_pkg

### CODE REVIEW

**Comment by sriyerg** [comment]
This looks fine to me. Over to @tjaychen and @msfschaffner.

**Comment by weicaiyang** [comment]
please fix the CI failure. Looks like some tests timed out as CI ran over 45 mins. Otherwise, LGTM.

**Comment by sha-ron** [comment]
@weicaiyang 
I can't see the log file (getting the following message: "Your account, stopaz@nuvoton.com is not authorized to view this page").
It might be related to the problem described in issue #8191 but I am not sure.
How can I see the failure?

**Comment by weicaiyang** [comment]
> @weicaiyang
> I can't see the log file (getting the following message: "Your account, [stopaz@nuvoton.com](mailto:stopaz@nuvoton.com) is not authorized to view this page").
> It might be related to the problem described in issue #8191 but I am not sure.
> How can I see the failure?

can you rebase on top of master and force push it to see if CI can pass?

**Comment by sha-ron** [comment]
@weicaiyang 
I did and it is ok now. Thanks Weicai.

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
