### PR TITLE
[dvsim] skip copying repo if it's run-only

### PR DESCRIPTION
**Pull request by weicaiyang**
Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by sriyerg** [comment]
What if ¨runtime¨ files such as tcl scripts, exclusion files etc. change?

**Comment by weicaiyang** [comment]
> What if ¨runtime¨ files such as tcl scripts, exclusion files etc. change?

I can't think of many of this type of usage. `run-only` can be simply considered as no update taken.
if it's exclusion file change, on need to use `run-only` as it doesn't have build step.
or do you have any suggestion?

**Comment by sriyerg** [comment]
> > What if ¨runtime¨ files such as tcl scripts, exclusion files etc. change?
> 
> I can't think of many of this type of usage. `run-only` can be simply considered as no update taken.
> if it's exclusion file change, on need to use `run-only` as it doesn't have build step.
> or do you have any suggestion?

There are / could be several more - post processing run result parsing scripts, OTBN ISS python sources etc. If you want to prevent the copy when passing `--run-only` switch, then don´t pass `--remote`. Will that work?

**Comment by weicaiyang** [comment]
> > > What if ¨runtime¨ files such as tcl scripts, exclusion files etc. change?
> > 
> > 
> > I can't think of many of this type of usage. `run-only` can be simply considered as no update taken.
> > if it's exclusion file change, on need to use `run-only` as it doesn't have build step.
> > or do you have any suggestion?
> 
> There are / could be several more - post processing run result parsing scripts, OTBN ISS python sources etc. If you want to prevent the copy when passing `--run-only` switch, then don´t pass `--remote`. Will that work?

no, it will use my local files. Our LSF can't access local file.

> do: couldn't open /usr/local/google/home/weicai/ot/uart/hw/dv/tools/sim.tcl : no such file or directory

**Comment by rswarbrick** [comment]
I think that @sriyerg is much better placed to review this than me, since it depends on how Google's IT works. But I think he's probably right: this looks like it's an excellent way to confuse yourself massively when something doesn't get updated when it should.

**Comment by weicaiyang** [comment]
> I think that @sriyerg is much better placed to review this than me, since it depends on how Google's IT works. But I think he's probably right: this looks like it's an excellent way to confuse yourself massively when something doesn't get updated when it should.

skipping the repo copy can save half minute. If don't re-compile but still copy updated repo, when we open verdi, verdi may use some updated files while waveform is based on old repo. But if we want to use updated C codes for top-level sim (c image is built at run time) but skip the compile, it's needed to copy the repo.

Looks like you guys don't like it and there is not much benefit from it. Let me close it.

**Pull request closed without merging**
