### PR TITLE
[sw/silicon_creator] Use crc32 instead of sha256 to check boot_data integrity

### PR DESCRIPTION
**Pull request by alphan**
Signed-off-by: Alphan Ulusoy <alphan@google.com>

### CODE REVIEW

**Review by moidx — APPROVED** [review]

**Comment by cdgori** [comment]
Sorry for post-merge comment, but this seems like a (potentially) significant change.  

What is covered by the crc32 (formerly sha256) in the boot_data?  crc32 is much weaker as a check, are there any fields where we have concerns about manipulation?

Or maybe there was some other discussion about this change and I missed it?

**Comment by alphan** [comment]
> Sorry for post-merge comment, but this seems like a (potentially) significant change.

No worries, thanks for taking a closer look @cdgori!

> What is covered by the crc32 (formerly sha256) in the boot_data? crc32 is much weaker as a check, are there any fields where we have concerns about manipulation?

`boot_data` is a security- and mission-critical data structure and we would like to ensure the integrity of all of its fields. `boot_data` entries are stored in two flash _info_ pages that are not accessible after `rom_ext`. We also plan to enable ECC and scrambling for these pages (assuming no HW issues). The region covered by the `checksum` field, formerly `sha256`, remains the same: all fields of `boot_data` are covered (except for `checksum`, obviously). Thus, I think this PR does not significantly increase the likelihood of the success of a potential attack while reducing the space and time overhead of integrity protection. We started with `sha256` because it was readily available and convenient to use but switching to `crc32` to reduce overhead was on our to-do list for a while. Please let me know what you think.

**Comment by cdgori** [comment]
crc32 for this makes me uneasy.  The fact that we will have ECC+scramble enabled softens it (somewhat).

The space tradeoff seems like not-a-big-deal  - you're padding the struct out to 64B and it fits within that with either scheme.  Obviously crc32 is going to compute more quickly than sha256, but for 20B of payload I wouldn't expect the time delta to be very noticeable (maybe I am wrong?), and the level of integrity provided by sha256 is massive compared to crc32.  If this is the sole reason to bring a sha256 implementation into the ROM image then maybe I could see the argument.

As far as the fields of `boot_data` - they're all pretty security-sensitive/critical, as you say, but I am most worried about the `min_security_version_*` ones.

I'll have to think about our threat model some more.

Side comment, because I had to look at `boot_data.[ch]` more closely to understand better the struct layout and usage: this patch dropped the comment showing origin of the value you are assigning to kShare0 - previously you had 9 constants generated from the python script and you showed the invocation (and seeding) of that as a comment, but you just kept the 0th one here without any sourcing comment now.  I think we should try to avoid "magic" values like that without some derivation comment.  

In other systems I have worked on, these type of values were actually regenerated as part of the build process, to make sure there weren't any weird bugs in the code particular to the magic values (basically practice "rolling the dice" on these values for the nightly builds such that everyone feels comfortable when it comes time to do the final build).  Not sure if that's an option here.

**Comment by alphan** [comment]
Thanks a lot for your review @cdgori, please see below:

> The space tradeoff seems like not-a-big-deal - you're padding the struct out to 64B and it fits within that with either scheme. 

The struct is padded right now because we don't know how many additional fields we need. I think it would be more accurate to think of that padding as a _placeholder_ rather than wasted space. Any space savings means we can store more in a single entry and better future-proof this data structure. We can always make entries larger, but this would degrade performance during boot and the same argument applies for a given size, albeit at a smaller ratio.

> I'll have to think about our threat model some more. The level of adversary power required for attacking crc32 might still be large enough to make this ok, because I don't think double-glitch is enough.

Thanks! Please let me know if you think we should revisit this.

> Side comment, because I had to look at `boot_data.[ch]` more closely to understand better the struct layout and usage: this patch dropped the comment showing origin of the value you are assigning to kShare0 - previously you had 9 constants generated from the python script and you showed the invocation (and seeding) of that as a comment, but you just kept the 0th one here without any sourcing comment now. I think we should try to avoid "magic" values like that without some derivation comment.

The sourcing comment is gone because the value of that single constant is basically arbitrary and `kShare1` is derived from its value. In the new revision, the comment reads:

```
  /**
   * Shares for producing the `error` value.
   *
   * `kShare0` is an arbitrary constant with a high hamming-weight while
   * `kShare1` is defined such that xoring it with `kErrorBootDataInvalid ^
   * kBootDataIdentifier ^ kShare0` results in `kErrorOk`.
   */
  enum {
    kShare0 = 0xe021e1a9,
    kShare1 = kErrorBootDataInvalid ^ kBootDataIdentifier ^ kShare0 ^ kErrorOk,
  };
```
I thought this was pretty self explanatory but PLMK if you have any suggestions to improve it.

> In other systems I have worked on, these type of values were actually regenerated as part of the build process, to make sure there weren't any weird bugs in the code particular to the magic values (basically practice "rolling the dice" on these values for the nightly builds such that everyone feels comfortable when it comes time to do the final build). Not sure if that's an option here.

I think this probably deserves more discussion but I feel more comfortable checking in the constants and reviewing them multiple times both internally and externally as opposed to generating them on the fly at build time. @cfrantz @moidx any thoughts?

**Comment by cdgori** [comment]
Thanks for raising this at the security meeting - I think we converged on reverting this to sha256.

> The sourcing comment is gone because the value of that single constant is basically arbitrary and kShare1 is derived from its value. In the new revision, the comment reads:
> ...
> I thought this was pretty self explanatory but PLMK if you have any suggestions to improve it.

Crypto people get "weird" around arbitrary constants (there is too much history of maliciously chosen "arbitrary" values).  So there is often a lot of effort put into describing where they come from - first example I could think of was https://www.rfc-editor.org/rfc/rfc5639#appendix-A.1 but lots of similar things exist.  

So, I liked the previous comment that showed the source of running the script and extracted the 9x32-bit values.  Would it be reasonable to run the script configured to generate a single 32-bit value?

> I think this probably deserves more discussion but I feel more comfortable checking in the constants and reviewing them multiple times both internally and externally as opposed to generating them on the fly at build time. @cfrantz @moidx any thoughts? (P.S. this would also break the hermeticity of the build.)

Yes, definitely for discussion - I didn't meant to try to backdoor a major build change here :)  I was more commenting on an approach I had seen used for these sort of values, though I hadn't thought of the hermeticity before.

**Pull request merged**
