### PR TITLE
[ci] Switch over Vivado builds to scalable cloud builder

### PR DESCRIPTION
**Pull request by imphil**
Currently, the FPGA builds are done on legacy lowRISC infrastructure.
This PR moves it over to the same cloud-based infrastructure we use for
private CI. This infrastructure is based on containers in a Kubernetes
cluster, and provides better isolation and scaling properties than
before.

### CODE REVIEW

**Comment by imphil** [comment]
OK, now that I've resolved the underlying infra issues this PR is ready to be reviewed.

* Performance: FPGA build is in the critical path of the CI pipeline. Tests show that we get roughly the same performance as on the current runner (we now use n2-standard-8 GCP machines). We could go with c2-* machines with a higher core frequency for roughly 4 minutes (~10 - 15 percent) improvement at a reasonable cost increase.
* Latency and scaling: Currently we're able to process 2 builds/hour/runner, with 1 runner we did queue up if we had more than 2 pushes/hour and added half an hour of latency for each additional push, easily leading to end-to-end CI latencies of an hour or more. This PR allows us to scale the number of FPGA builders seamlessly with demand. We do not have dynamic scaling implemented currently, but I'll keep monitoring the CI latency and scale as necessary. This should help especially around noon in the US where we regularly exceeded the capacity of the FPGA runner. 
* Tool versions: This PR also switches to Vivado 2020.1 (from 2018.3). I didn't observe any differences.

**Comment by imphil** [comment]
FYI, here's the resource usage of a full Vivado run:

grafik

(the red line is the actual usage, the orange one are requested resources, but there's no limit to go beyond that)

**Comment by tjaychen** [comment]
this is awesome, thanks @imphil 
I'm a little surprised about the vivado version though, i think @msfschaffner and i both observed issues locally with 2019 (not sure about 2020).  Great to hear that 2020 is good though.

**Comment by msfschaffner** [comment]
Thanks @imphil, good to hear that 2020.1 works.
I switch our internal tool version over to 2020.1 as well.

You may also want to update the Vivado version in the docs:
https://docs.opentitan.org/doc/ug/getting_started_fpga/

**Comment by imphil** [comment]
Yeah, 2019.1 had issues, 2019.2 should be fine (IIRC), 2020.1 and 2020.2 works for sure in my testing (as far as CI is concerned, the produced bitstream passes all tests on the FPGA). If you want we can also directly to go 2020.2 (no significant reason for doing so, however).

I just remembered we had https://github.com/lowRISC/opentitan/issues/89, I updated the docs and marked this issue as fixed.

**Review by asb — APPROVED** [review]
Thanks for your work on this Philipp, looks good to me.

I would slightly prefer if the the Vivado upgrade had been split out to a separate PR, but given others seem happy with it, no objection.

**Comment by imphil** [comment]
> I would slightly prefer if the the Vivado upgrade had been split out to a separate PR, but given others seem happy with it, no objection.

Yeah, sorry. We ran a slightly odd setup in that we did the FPGA flashing with Vivado 2020.1, but used 2018.3 to build the bitstream; I realized that quite late during in the preparation of this PR, so it's slightly entangled now. With that confusion cleaned up we should be able to do better from now on.

**Comment by jackieke724** [comment]
> I just remembered we had #89, I updated the docs and marked this issue as fixed.

I just noticed the shift to 2020.1 Vivado from the doc. I think the System Requirements section and vivado installation screenshots in the [doc](https://docs.opentitan.org/doc/ug/install_instructions/#xilinx-vivado) still need an update. 

Btw, I am glad you are finally switching to a newer version, because 2018.3 just randomly gives me abnormal program termination when fetching synth/implementation licenses. Do any of you guys have this issue?

**Pull request merged**
