### PR TITLE
[top] Enable pwrmgr_smoketest in FPGA

### PR DESCRIPTION
**Pull request by tjaychen**
- Various top level fixes to enable `pwrmgr_smoke_test` in FPGA.
- This should unblock certain FPGA development activities.
- As part of this PR, part of the power okay signaling is bypassed, pending more investigation (#9507 )

### CODE REVIEW

**Review by msfschaffner — COMMENTED** [review]
LGTM. Do we have an issue to track the AST problem (so that we do not forget to change it back)? Maybe it also makes sense to add a `TODO(#...)` in the code...

**Comment by tjaychen** [comment]
> LGTM. Do we have an issue to track the AST problem (so that we do not forget to change it back)? Maybe it also makes sense to add a `TODO(#...)` in the code...

yep see #9507 
I honestly was going to add it back into the code..but CI just takes so long that I decided to just live with it for now.

**Comment by alphan** [comment]
Thanks @tjaychen! I tried all three cases that we were interested in with the bitstream from this PR: sw reset request and alert triggered resets work fine. keymgr_functest no longer hangs on wake up but fails (same as what I observed yesterday):

```
I00004 keymgr_functest.c:317] Starting test keymgr_rom_ext_test...
E00005 keymgr_functest.c:258] Error at line: 258
```

We will change the keymgr_functest to use sw reset request (assuming the test doesn't actually require a wake up) but wanted to share what I observed, could be relevant to #9507.

**Comment by msfschaffner** [comment]
> > LGTM. Do we have an issue to track the AST problem (so that we do not forget to change it back)? Maybe it also makes sense to add a `TODO(#...)` in the code...
> 
> yep see #9507 I honestly was going to add it back into the code..but CI just takes so long that I decided to just live with it for now.

Yeah I know. Providing the link to the issue in this PR is fine.

**Review by msfschaffner — APPROVED** [review]

**Review by alphan — APPROVED** [review]
`test/systemtest/earlgrey/config.py` change LGTM, thanks @tjaychen!

**Comment by tjaychen** [comment]
> 

yeah i feel like this might be something different that needs debugging.
When keymgr advance fails, can you check to see what the error status in keymgr is?

We probably need to modify the test to check that the seeds programmed in flash / otp are actually still correct after a low power exit, otherwise keymgr may refuse to advance if those fields are empty.

**Pull request merged**
