### PR TITLE
[kmac, rtl] Fix issues around EDN timeouts

### PR DESCRIPTION
**Pull request by vogelpi**
For details, see commit messages.

### CODE REVIEW

**Review by a-will — APPROVED** [review]
LGTM. Thanks for the quick fix! :)

**Review by msfschaffner — APPROVED** [review]
Thanks @vogelpi!

We should still discuss whether these EDN interfaces in AES and KMAC should use the return-to-zero variant of the synchronizer so that this is safe to reset partially - but we can do that in a follow-up.

**Review by matutem — APPROVED** [review]
LGTM

**Comment by vogelpi** [comment]
Thanks for your reviews everybody. The issue to check / switch the handshake protocol variant is here: #19259

**Pull request merged**
