### PR TITLE
[ci] Upload MMI files to GCP after Vivado build

### PR DESCRIPTION
**Pull request by dmcardle**
See issue #13603

Signed-off-by: Dan McArdle <dmcardle@google.com>

### CODE REVIEW

**Comment by dmcardle** [comment]
Hey Miles, PTAL! Could you recommend another reviewer who is also a committer?

**Comment by dmcardle** [comment]
I think I should also teach Bazel how to fetch the precomputed MMI files (maybe [here](https://cs.opensource.google/opentitan/opentitan/+/master:hw/bitstream/vivado/BUILD;l=67-72;drc=099463e2af6fb9480bd99830851f1d37ff05833c)) along the same lines as [hw/bitstream:test_rom](https://cs.opensource.google/opentitan/opentitan/+/master:hw/bitstream/BUILD;l=46-54;drc=bed33ef9b2340cc6ab1873f515251af8297a4af0).

**Review by milesdai — APPROVED** [review]
LGTM - assuming the MMI files aren't too big. Do you know about how large they are?

**Comment by milesdai** [comment]
> I think I should also teach Bazel how to fetch the precomputed MMI files (maybe [here](https://cs.opensource.google/opentitan/opentitan/+/master:hw/bitstream/vivado/BUILD;l=67-72;drc=099463e2af6fb9480bd99830851f1d37ff05833c)) along the same lines as [hw/bitstream:test_rom](https://cs.opensource.google/opentitan/opentitan/+/master:hw/bitstream/BUILD;l=46-54;drc=bed33ef9b2340cc6ab1873f515251af8297a4af0).

Seems like that would be useful if we wanted to allow people to splice arbitrarily. That would probably be integrated into our local (non-GCP) bitstream cache (see `rules/bitstreams.bzl` and `rules/scripts/bitstreams_workspace.py`)

**Review by timothytrippel — APPROVED** [review]

**Comment by dmcardle** [comment]
@timothytrippel Yes, go for it!

**Pull request merged**
