### PR TITLE
[aes] V2S sign-off

### PR DESCRIPTION
**Pull request by vogelpi**
This resolves lowRISC/OpenTitan#13579.

Before we can merge this, #16001 has to go in which will resolve the remaining block-level issue.

### CODE REVIEW

**Comment by vogelpi** [comment]
FYI @johngt

**Comment by weicaiyang** [comment]
branch and expression coverage are slightly below 90%.
Perhaps the recent coverage improvement PRs can boost them to 90%+. let's wait until those PRs are merged to get better numbers

**Review by andreaskurth — APPROVED** [review]
With #16001 merged, all coverage categories and tests are >90%.

**Comment by vogelpi** [comment]
Update: I've rebased this on top of master to make CI pass (previously the FPGA job timed out). @weicaiyang , the nightly regression has now picked up all the relevant changes, pass rates and coverage are all above the required V2S thresholds:
https://reports.opentitan.org/hw/ip/aes_masking/dv/latest/report.html

**Review by weicaiyang — APPROVED** [review]
Congrats! LGTM

**Comment by andreaskurth** [comment]
The `kokoro` check failed with `IOError: [Errno 2] No such file or directory: '/container/opentitan-public/scratch/HEAD/chip_earlgrey_asic-lint-ascentlint/default/results.hjson'`. I suggest to waive this check for this PR, because the PR does not modify any HDL code that would be linted in that check.

**Comment by vogelpi** [comment]
> The `kokoro` check failed with `IOError: [Errno 2] No such file or directory: '/container/opentitan-public/scratch/HEAD/chip_earlgrey_asic-lint-ascentlint/default/results.hjson'`. I suggest to waive this check for this PR, because the PR does not modify any HDL code that would be linted in that check.

Yes, I wouldn't worry about this. I have seen similar failures in the past.

**Comment by vogelpi** [comment]
> Congrats! LGTM

Thanks @weicaiyang , let's merge this! :-)

**Comment by rasmus-madsen** [comment]
Wuhuuu ! Thank you @vogelpi and @andreaskurth for taking this across the finish line!

**Comment by vogelpi** [comment]
Thanks for all the hard work you've put into AES DV before us @rasmus-madsen! We could start our work from an excellent base and were almost there already - I think you brought us to at least 95% of V2S ;-)

**Pull request merged**
