### PR TITLE
[sw/meson] Update meson version and fix deprecation issues

### PR DESCRIPTION
**Pull request by luismarques**
This updates meson to a sufficiently newer version to enable the use of various meson machine file constructs. Upgrading to versions >= 0.58 would introduce further migration issues, so that can be done in a follow-up patch if necessary.

### CODE REVIEW

**Review by mundaym — APPROVED** [review]
LGTM. As discussed let's hold off merging this one until we have announced this change over email and on Slack though. I suggest we aim to merge this on Tuesday next week and we should rebase the change immediately before merging so the CI is re-run.

This change will require users to re-run `pip3 install --user -r python-requirements.txt`.

**Comment by martin-lueker** [comment]
Hi Luis, Micheal,
   Thanks you very much for tagging me on this.  It looks good, but give me a day to update our environment test this branch.
Thanks,
-Martin

**Review by martin-lueker — APPROVED** [review]
Thanks again for the heads up @mundaym and @luismarques!  I've installed this and tested it in our environments with no problem. (As expected, but it is nerve wracking when things don't work).

**Comment by luismarques** [comment]
> Thanks again for the heads up @mundaym and @luismarques! I've installed this and tested it in our environments with no problem. (As expected, but it is nerve wracking when things don't work).

Thanks for test driving this Martin. I'm glad that it didn't turn out to be problematic. I'll send an email informing that we expect to merge this mid next week.

**Comment by luismarques** [comment]
Closing and reopening to re-trigger CI before merging.

**Comment by luismarques** [comment]
Rebased, fixing conflicts due to recent changes.

**Pull request merged**
