### PR TITLE
[ast] Update internal AST logic

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Signed-off-by: Jacob Levy <jacob.levy@opentitan.org>

### CODE REVIEW

**Comment by Jacob-Levy** [comment]
This AST PR includes the following:
    1. Generat code updates.
    2. AscentLint errors fixes,
    3. NumAlerts to 13 and the extra Alert logic.
    4. lc_clk_byp_req_i/ack_o logic.

**Comment by tjaychen** [comment]
hmmm.. it appears CI is still timing out for you, so there must be some
other issue.
I'll try to pull this PR down and give it a try, but I might not get to it
today.
In the meantime, it would be great if you guys can give dvsim flow a try
and let us know what might be blocking / problematic.

**Comment by Jacob-Levy** [comment]
In my local DV of the AST I am not using dvsim but our DV team does, Will try to work with them on dvsim. on Wednesday
Unfortunatly, I can not access the errors report of the CI (private) annd I asked Philipp help on this issue (I can see all other checks).

**Comment by Jacob-Levy** [comment]
Fix some issues, reset/rebase and re-open a new AST PR.

**Pull request closed without merging**
