### PR TITLE
[python] move from python-requirements.in to pyproject.toml

### PR DESCRIPTION
**Pull request by nbdd0121**
No changes have been made to the dependency versions, except `types-dataclasses` is removed (since we use Python 3.8+)

### CODE REVIEW

**Comment by jwnrt** [comment]
I think Tock has its own requirements file for tockloader. Please could you look at that too?

I think I had to generate its hashed lockfile with `uv` in the end because `pip-compile` was broken on Ubuntu 24.04.

**Comment by nbdd0121** [comment]
The tock requirement file is just a single line mentioning tockloader. I don't know how much value would it provide to convert it to pyproject.toml?

**Review by jwnrt — APPROVED** [review]
This is great, thanks

**Review by pamaury — APPROVED** [review]
Looks good to me.

**Pull request merged**
