### PR TITLE
[gpio,dv] Add sanity check of reading gpio registers

### PR DESCRIPTION
**Pull request by sha-ron**
Add a read of GPIO registers after driving GPIO pins.

### CODE REVIEW

**Review by jdonjdon — APPROVED** [review]

**Comment by sha-ron** [comment]
Thanks @jdonjdon. I pushed the changes but looks like lint is failing again, not sure why.

**Comment by timothytrippel** [comment]
You can run `bazel run //quality: clang_format_fix` instead of trying to fix the formatting issues manually. Then it should pass  :)

**Review by timothytrippel — APPROVED** [review]

**Comment by jdonjdon** [comment]
> Thanks @jdonjdon. I pushed the changes but looks like lint is failing again, not sure why.

Looks like some indentation issues.
Can you run
`bazel run //quality:clang_format_fix`

**Comment by jdonjdon** [comment]
@timothytrippel jinx!

**Pull request merged**
