### PR TITLE
[alert_handler] Latch crashdump when entering escalation

### PR DESCRIPTION
**Pull request by msfschaffner**
This addresses #7644.

In particular, it adds adds a programmable crashdump capture trigger mechanism.
The idea is that SW would configure this so that the alert handler latches the crashdump info upon entering the life cycle scrapping phase for the first time.

WDYT? Is this mechanism too involved?

### CODE REVIEW

**Review by timothytrippel — APPROVED** [review]
LGTM. 

However, now the DIF is missing functionality required to configure these CSRs so I've created an issue to track: #8011 .

**Comment by tjaychen** [comment]
this lgtm, the only feedback i have is whether you think it's possible to only maintain one set of phase configuration, or do we have to have them per class? 

Is this because different classes may advance to different stages of escalation? So as an example, class D may never have NMI.

**Comment by msfschaffner** [comment]
> this lgtm, the only feedback i have is whether you think it's possible to only maintain one set of phase configuration, or do we have to have them per class?
> 
> Is this because different classes may advance to different stages of escalation? So as an example, class D may never have NMI.

yeah exactly. this is ony needed because each class can have a different escalation order, and because the alert handler itself does not know anything about the side effects of the individual escalation actions that it is attached to...

**Review by cindychip — APPROVED** [review]
lgtm

**Pull request merged**
