### PR TITLE
[dv,top] Share common code in pwrmgr_*sleep_all_wake_ups

### PR DESCRIPTION
**Pull request by matutem**
This facilitates the creation of a random version of these tests, and removes redundant code.

Signed-off-by: Guillermo Maturana <maturana@google.com>

### CODE REVIEW

**Review by jdonjdon — APPROVED** [review]
This looks really good.
Can you file an issue "M3 cleanup" category to do for all
pwrmgr_*sleep*  and assign to me?

**Comment by matutem** [comment]
Jaedon, I created https://github.com/lowRISC/opentitan/issues/15324 for the rest of the cleanup.

**Comment by jdonjdon** [comment]
> Jaedon, I created #15324 for the rest of the cleanup.

Great!

**Review by alphan — COMMENTED** [review]
Thanks @matutem, LGTM! apologies for the delay

**Pull request merged**
