### PR TITLE
[dv,top,clkmgr] top ast_clk_outputs test

### PR DESCRIPTION
**Pull request by jdonjdon**
@tjaychen , this is chip_sw_ast_clk_outputs test draft.
I want to check a few things before open to formal review.

This test use clkmgr frequency measure capability to check 3 ast generated clock(io, sys and usb)
1.
I followed spec (https://github.com/lowRISC/opentitan/blob/master/hw/ip/clkmgr/doc/_index.md#clock-frequency--time-out-measurements) to program  CLKMGR.*_MEAS_CTRL_SHADOWED registers.
However, I had to add 3 extra cycle margins to each hi and lo values. So (hi, lo) = expected value +/- 4
Is this ok?

2.
After 100 measurements, test goes lowpower mode for 500us then come back.
WITHOUT disabling measurement.
During the down time, I can see no measurement executed from the wave.
But when I read CLKMGR.RECOV_ERR after wakeup, some garbage values remains.
Should I ignore these garbage values in CLKMGR.RECOV_ERR?

3.
After wake up, I see usb clock does not come back by itself, while the others do.
So I can manually enable usb clock from PWRMGR.CONTROL. But at that point,
ast init is already done without usb clock enable.
Can ast init and usb clock be independent?

Signed-off-by: Jaedon Kim <jdonjdon@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
> @tjaychen , this is chip_sw_ast_clk_outputs test draft. I want to check a few things before open to formal review.
> 
> This test use clkmgr frequency measure capability to check 3 ast generated clock(io, sys and usb) 1. I followed spec (https://github.com/lowRISC/opentitan/blob/master/hw/ip/clkmgr/doc/_index.md#clock-frequency--time-out-measurements) to program CLKMGR.*_MEAS_CTRL_SHADOWED registers. However, I had to add 3 extra cycle margins to each hi and lo values. So (hi, lo) = expected value +/- 4 Is this ok?

yes i think this is okay. This is basically the synchronization latency. Can you double check in the test that's what you observed? Or is there something else that's causing this discrepancy? 
> 
> 
> After 100 measurements, test goes lowpower mode for 500us then come back. WITHOUT disabling measurement. During the down time, I can see no measurement executed from the wave. But when I read CLKMGR.RECOV_ERR after wakeup, some garbage values remains. Should I ignore these garbage values in CLKMGR.RECOV_ERR?

hmmmm this does not sound right. When you say garbage value, I assume that means some errors were registered? Is that right? That should not be the case, the original intent was that if enabled, it should ensure to not register errors during the low power state.  If I'm understanding your right, this sounds like a bug. 
> 
> 
> After wake up, I see usb clock does not come back by itself, while the others do. So I can manually enable usb clock from PWRMGR.CONTROL. But at that point, ast init is already done without usb clock enable. Can ast init and usb clock be independent?

yes ast_init and usb clock can be independent. The usb clock is meant to be something software turns on/off based on its needs.  There should also be a way for you to set both the active and low power state of usb clock, you could set those to be the same. 

> 
> Signed-off-by: Jaedon Kim [jdonjdon@google.com](mailto:jdonjdon@google.com)

**Comment by jdonjdon** [comment]
> > @tjaychen , this is chip_sw_ast_clk_outputs test draft. I want to check a few things before open to formal review.
> > This test use clkmgr frequency measure capability to check 3 ast generated clock(io, sys and usb) 1. I followed spec (https://github.com/lowRISC/opentitan/blob/master/hw/ip/clkmgr/doc/_index.md#clock-frequency--time-out-measurements) to program CLKMGR.*_MEAS_CTRL_SHADOWED registers. However, I had to add 3 extra cycle margins to each hi and lo values. So (hi, lo) = expected value +/- 4 Is this ok?
> 
> yes i think this is okay. This is basically the synchronization latency. Can you double check in the test that's what you observed? Or is there something else that's causing this discrepancy?
> 
it is from synchronizer. (3 clock cycles).  +1 is added  cause 
rtl count clock 'slow' when cnt == min_cnt. vice versa for 'fast'.


> > After 100 measurements, test goes lowpower mode for 500us then come back. WITHOUT disabling measurement. During the down time, I can see no measurement executed from the wave. But when I read CLKMGR.RECOV_ERR after wakeup, some garbage values remains. Should I ignore these garbage values in CLKMGR.RECOV_ERR?
> 
> hmmmm this does not sound right. When you say garbage value, I assume that means some errors were registered? Is that right? That should not be the case, the original intent was that if enabled, it should ensure to not register errors during the low power state. If I'm understanding your right, this sounds like a bug.

This is snapshot. recover_alert is basically ored value of all recover_err_code
image

> 
> > After wake up, I see usb clock does not come back by itself, while the others do. So I can manually enable usb clock from PWRMGR.CONTROL. But at that point, ast init is already done without usb clock enable. Can ast init and usb clock be independent?
> 
> yes ast_init and usb clock can be independent. The usb clock is meant to be something software turns on/off based on its needs. There should also be a way for you to set both the active and low power state of usb clock, you could set those to be the same.
> 
> > Signed-off-by: Jaedon Kim [jdonjdon@google.com](mailto:jdonjdon@google.com)

**Comment by tjaychen** [comment]
> > > @tjaychen , this is chip_sw_ast_clk_outputs test draft. I want to check a few things before open to formal review.
> > > This test use clkmgr frequency measure capability to check 3 ast generated clock(io, sys and usb) 1. I followed spec (https://github.com/lowRISC/opentitan/blob/master/hw/ip/clkmgr/doc/_index.md#clock-frequency--time-out-measurements) to program CLKMGR.*_MEAS_CTRL_SHADOWED registers. However, I had to add 3 extra cycle margins to each hi and lo values. So (hi, lo) = expected value +/- 4 Is this ok?
> > 
> > 
> > yes i think this is okay. This is basically the synchronization latency. Can you double check in the test that's what you observed? Or is there something else that's causing this discrepancy?
> 
> it is from synchronizer. (3 clock cycles). +1 is added cause rtl count clock 'slow' when cnt == min_cnt. vice versa for 'fast'.
> 
> > > After 100 measurements, test goes lowpower mode for 500us then come back. WITHOUT disabling measurement. During the down time, I can see no measurement executed from the wave. But when I read CLKMGR.RECOV_ERR after wakeup, some garbage values remains. Should I ignore these garbage values in CLKMGR.RECOV_ERR?
> > 
> > 
> > hmmmm this does not sound right. When you say garbage value, I assume that means some errors were registered? Is that right? That should not be the case, the original intent was that if enabled, it should ensure to not register errors during the low power state. If I'm understanding your right, this sounds like a bug.
> 
> This is snapshot. recover_alert is basically ored value of all recover_err_code image
> 
> > > After wake up, I see usb clock does not come back by itself, while the others do. So I can manually enable usb clock from PWRMGR.CONTROL. But at that point, ast init is already done without usb clock enable. Can ast init and usb clock be independent?
> > 
> > 
> > yes ast_init and usb clock can be independent. The usb clock is meant to be something software turns on/off based on its needs. There should also be a way for you to set both the active and low power state of usb clock, you could set those to be the same.
> > > Signed-off-by: Jaedon Kim [jdonjdon@google.com](mailto:jdonjdon@google.com)

hmmmm the garbage values don't look good. The idea behind the measurement is that it should appropriately account for the period when the clocks are turned off.  Maybe I should pull this test and have a look.

**Comment by tjaychen** [comment]
okay, the errors are happening because after low power exit, the `ast` clocks are completely uncalibrated again (like at cold boot).
So the measurement values are completely wrong.  This needs a hardware change, we cannot persist the measurement function through a low power transition.  Especially if the `ast` calibration values are lost.

**Comment by jdonjdon** [comment]
commited in here(https://github.com/lowRISC/opentitan/commit/75fd557854f08b9ec213610c228e510bf31a96d7)

**Pull request closed without merging**
