### PR TITLE
[i2c, rtl] Checklist Update for D1 Signoff

### PR DESCRIPTION
**Pull request by igk8**
This PR updates the checklist for D1 signoff.

Signed-off-by: Igor Kouznetsov <igor.kouznetsov@wdc.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Thanks for updating the checklist, @igk8. I have merged in @tunghoang290780's updates in #2568. Could you rebase this PR on `master` and also update the V1 part of it with the date and reviewer names (just as you did for D1)?

Also, once we've merged this in, we should make a second PR that makes the `proj` file state transition, as described in https://docs.opentitan.org/doc/project/development_stages/

**Comment by igk8** [comment]
I have rebased this PR on master and added the reviewers and signoff date to V1, as suggested. Thanks!

**Comment by igk8** [comment]
@msfschaffner I've added myself to the reviewers list.

**Comment by msfschaffner** [comment]
OK you can now make the state transition in the `proj` file (see here: https://docs.opentitan.org/doc/project/development_stages/).

**Pull request merged**
