### PR TITLE
[secded_gen] Add inverted ECC codes and configs

### PR DESCRIPTION
**Pull request by msfschaffner**
This adds inverted Hsiao and Hamming ECC codes in preparation for switching the ECC codes system-wide (i.e., in OTBN, Ibex, the bus etc).

Due to the way our vendoring mechanism works, we have to merge this separately before switching over, so that I can vendor the ECC updates into the Ibex repo, and then vendor Ibex back into OpenTitan.

See also issues #8623 and #6478.

### CODE REVIEW

**Comment by msfschaffner** [comment]
This seems to be working now - PTAL.

**Comment by eunchan** [comment]
Maybe I am dumb. Is the reason of using inverted ECC to make all 0 value invalid value?

**Comment by msfschaffner** [comment]
> Maybe I am dumb. Is the reason of using inverted ECC to make all 0 value invalid value?

Oh sorry I should have mentioned this.
Yes, it basically makes sure that all-zero data does not have an all-zero ECC.

**Review by tjaychen — APPROVED** [review]

**Review by cindychip — APPROVED** [review]
mainly reviewed DV and FPV parts, they all LGTM

**Comment by msfschaffner** [comment]
Alright, thanks for the reviews! 
Merging this in so I can do the vendoring part for Ibex.

**Pull request merged**
