### PR TITLE
[otbn, pre_sca] Modify boolean_to_arithmetic routine against SCA

### PR DESCRIPTION
**Pull request by abdullahvarici**
These changes are done regarding to outcomes of the COCO-Alma tool usage. Moreover, many more rules are put in the OTBN Security Guidance Document. Please see it before developing algorithms on OTBN which handle secret data.

If we don't have these changes, the tool reports there are transient leakage and we may see leakage on the final product even if we don't see a leakage on FPGA experiments.

We are also seeing a stable leakage on the MSB of the intermediate values. We acknowledge that and since the algorithm runs with 64-bit excess randomness, we don't expect that to be possible to use that leakage and retrieve secret values. We also verified that the stable leakage disappeared after running the routine on 320-bit instead of 321-bit.

### CODE REVIEW

**Review by jadephilipoom — APPROVED** [review]
Thanks, Abdullah!

**Comment by abdullahvarici** [comment]
This needs to be rebased after https://github.com/lowRISC/opentitan/pull/18213 has been merged. And also it would be good to have a final review from @jadephilipoom since some extra registers are used in boolean_to_arithmetic routine and I'm not sure if this has any effect on other parts using this routine.

**Comment by vogelpi** [comment]
Update: #18213 went in and I've now rebased this PR on `master`. @jadephilipoom Would you mind taking another look please?

**Review by jadephilipoom — APPROVED** [review]
LGTM!

**Comment by vogelpi** [comment]
Thanks @jadephilipoom !

**Pull request merged**
