### PR TITLE
[opentitantool] Handle writing of large amounts of UART data

### PR DESCRIPTION
**Pull request by jesultra**
In the `Uart` trait, `read()` and `read_timeout()` may be augmented by using the `register_nonblocking_read()` function, for `mio`-style polling for incoming data.  However, the convention is that the `write()` method is always blocking (there is no `register_nonblocking_write()`).

The implementation in `transport/common/uart.rs` does tricks with `port.as_raw_fd()` in order to get a file descriptor out of the `serialport` library for use with the `mio` library.  It seems that a side effect of this is that `mio` puts the file descriptor into non-blocking mode, which may cause `write_all()` to return an `Err()` in response to getting `EAGAIN` from the operating system due to queues being full.

I assume that `write_all()` could make multiple OS `write()` calls, and we have no way of knowing whether the first call succeeded in accepting some of the bytes, before the second call returned `EAGAIN`.

This CL replaces `write_all()` with a loop attempting individual calls to `write()`, keeping track of how much has been sent.  Furthermore, in case of `EAGAIN`, it uses `nix::poll()` to know when to re-try transmitting the rest of the data, in order to honor the synchronous and "write everything" contract.

The goal is to be able to cause HyperDebug to continuously transmit at maximum UART speed, in order to run endurance tests.  This has been verified with a logic analyzer.

### CODE REVIEW

**Comment by nbdd0121** [comment]
Mixing mio-based event loop + sleep sounds like a bad idea. We should really migrate to async asap. @jwnrt

**Comment by jwnrt** [comment]
I haven't worked with `async` very much and don't think I can give much feedback on the approach to take. I will try to review this PR's implementation though.

**Comment by jesultra** [comment]
> Mixing mio-based event loop + sleep sounds like a bad idea. We should really migrate to async asap. @jwnrt

I am not familiar with async.  The biggest headache when figuring out how to design a `Uart` trait allowing e.g. `opentitansession` to manage multiple UART connections as well as multiple open TCP sockets, is that the various underlying libraries for serial ports, FTDI, and generic USB used by the various transports do not all stick to one way of doing non-blocking operations.  Opentitansession already used `mio` for the TCP sockets, and it seemed that at least the serial port library we used could be shoe-horned into also working with `mio` (by means of `.as_raw_fd()`), so that it what I went for.  I saw no immediate need for doing asynchronous writing to UARTS, hence this workaround, which avoids making the trait more complicated.  With this PR, the below test allows sustained maximum speed writing on three HyperDebug UARTS at the same time, which is something that the Chrome OS team wants to test on our OpenTitan firmware.

https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/4895624/3/src/go.chromium.org/tast-tests/cros/remote/bundles/cros/gscdevboard/ti50_uart_throughput.go

**Comment by jesultra** [comment]
Chris suggested in chat:
> Would it be better to set the uart to blocking, write_all(), then possibly restore non-blocking mode?

I do not know how the mio library would take that.  There could be a `mio::Poll` object to which the uart file descriptor has already been added (this highly likely to be the case in `opentitansession`), which could translate into Linux `epoll_ctl()` having been called to register the file descriptor with the OS async polling mechanism.

I do not completely trust that switching in and out of blocking mode would not somehow mess up the OS epoll state.

**Comment by jesultra** [comment]
I have re-written this PR to not use explicit `sleep()`, but instead use `nix::poll()` to be able to wait until this one file descriptor becomes ready for writing.  I am more confident that doing it this way will not interfere with ongoing `epoll_ctl()`-registrations of the same file descriptor, unlike modifying the blocking mode of the descriptor.

**Comment by pamaury** [comment]
I admit I am not up to speed on the mio/etc situation but the latest version makes a lot of sense to me. Note that the [epoll documentation](https://man7.org/linux/man-pages/man7/epoll.7.html) says:
```
Can two epoll instances wait for the same file descriptor?  If
so, are events reported to both epoll file descriptors?

Yes, and events would be reported to both.  However, careful
programming may be needed to do this correctly.
```

**Review by jwnrt — APPROVED** [review]
This version LGTM, thanks @jesultra

**Review by cfrantz — APPROVED** [review]

**Pull request merged**
