### PR TITLE
[edn/dv] Added alerts

### PR DESCRIPTION
**Pull request by senelson7**
Signed-off-by: Steve Nelson <steve.nelson@wdc.com>

### CODE REVIEW

**Review by rasmus-madsen — APPROVED** [review]
LGTM

**Comment by weicaiyang** [comment]
can you include this alert_test? please also add it for CSRNG.

https://github.com/lowRISC/opentitan/blob/40030846f0d617fa191ea1fc45a1f7206b1f2dec/hw/ip/keymgr/dv/keymgr_sim_cfg.hjson#L34

**Review by weicaiyang — APPROVED** [review]
LGTM with a suggestion

**Comment by senelson7** [comment]
Added alert_test.hjson to edn, csrng sim_cfg.hjson files

**Review by mwbranstad — APPROVED** [review]
LGTM

**Review by rasmus-madsen — APPROVED** [review]

**Pull request merged**
