### PR TITLE
[spi_agent] Read commands response addition

### PR DESCRIPTION
**Pull request by kosta-kojdic**
Added device agent response for Read Status commands and Read JEDEC and Read SFDP commands. Assumption is these responses are each 32 bit long.
Added enumeration for given command opcodes.

Signed-off-by: Kosta Kojdic <kosta.kojdic@ensilica.com>

### CODE REVIEW

**Comment by a-will** [comment]
Just to clarify: `Read SFDP` grabs data from a RAM, and it could be up to 256 bytes long. `Read JEDEC` could technically also be that long, since the 3 bytes that aren't continuation codes could have up to 255 of the 0x7F continuation codes in front.

**Comment by kosta-kojdic** [comment]
> Just to clarify: `Read SFDP` grabs data from a RAM, and it could be up to 256 bytes long. `Read JEDEC` could technically also be that long, since the 3 bytes that aren't continuation codes could have up to 255 of the 0x7F continuation codes in front. Last I checked, the current set of JEDEC manufacturer IDs hasn't reached higher than 15 continuation codes, though.

Thanks, if I understand well, if Read SFDP gets data from RAM, is it RAM of spi_device? In that case downstream device agent shouldn't respond to this command?

**Comment by kosta-kojdic** [comment]
> > Just to clarify: `Read SFDP` grabs data from a RAM, and it could be up to 256 bytes long. `Read JEDEC` could technically also be that long, since the 3 bytes that aren't continuation codes could have up to 255 of the 0x7F continuation codes in front. Last I checked, the current set of JEDEC manufacturer IDs hasn't reached higher than 15 continuation codes, though.
> 
> Thanks, if I understand well, if Read SFDP gets data from RAM, is it RAM of spi_device? In that case downstream device agent shouldn't respond to this command?

OK, I see that SW should prepare SFDP data, so I will remove it from device agent responses.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by weicaiyang** [comment]
Sorry, I missed this PR. Please ping me if I forget to review some PRs.

**Pull request merged**
