### PR TITLE
[dv,xprop] Fix some more xprop issues

### PR DESCRIPTION
**Pull request by matutem**
Add (* xprop_off *) attributes in some specific processes.

Signed-off-by: Guillermo Maturana <maturana@google.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
it may be helpful if we could comment in the code why we need to turn xprop off, otherwise, LGTM

**Comment by tjaychen** [comment]
ah wait, @arnonsha / @Jacob-Levy sorry forgot to tag you sooner.

**Comment by arnonsha** [comment]
> it may be helpful if we could comment in the code why we need to turn xprop off, otherwise, LGTM

Yes, I actually don't understand this change.  What is wrong with the original code during xprop simulation ?

@meisnere

**Comment by matutem** [comment]
This will be clear if you inspect the xprop.log file generated at compile-time without this change. The xprop.log file is found in the file-system near the location of the simv. The vcc*sv files modified here complain for assignments with different delays,

**Comment by arnonsha** [comment]
Thanks for explaining

**Pull request merged**
