### PR TITLE
[test] re-enable I2C checking in power virus test

### PR DESCRIPTION
**Pull request by timothytrippel**
This PR contains a few commits that:
1. re-enables I2C RX checking after fixing a bug in the agent configuration reported in #17607,
2. cleans up I2C DIF calls, and
3. adds the power virus test to the list of tests run in pre-submit (note: this may be removed if the runtime is too long).

### CODE REVIEW

**Comment by timothytrippel** [comment]
Looks like adding the power virus test as a presubmit doesn't increase runtimes much, so I have added it to one of the Xcelium regression sets.

**Review by cindychip — APPROVED** [review]
lgtm

**Review by engdoreis — APPROVED** [review]
LGTM. 
Thanks @timothytrippel.

**Review by bilgiday — APPROVED** [review]
Thanks for the changes Tim! LGTM

**Pull request merged**
