### PR TITLE
Rv dm jtag dtm idle hint

### PR DESCRIPTION
**Pull request by BasitMehmood**
@jdonjdon kindly review it. Thanks

### CODE REVIEW

**Comment by jdonjdon** [comment]
@BasitMehmood 

Did you intentionally merge [this]((https://github.com/lowRISC/opentitan/pull/20333/commits/49108bb38f8c8c457e439a1f3f9b59f77249b6da)) ?
Otherwise, you need to rebase first before push your own

**Comment by BasitMehmood** [comment]
> @BasitMehmood
> 
> Did you intentionally merge [this](https://github.com/lowRISC/opentitan/pull/20333/commits/49108bb38f8c8c457e439a1f3f9b59f77249b6da)? Otherwise, you need to rebase first before push your own

No, i did not do it intentionally. i just wanted to merge idle_hint sequence.

**Comment by jdonjdon** [comment]
> > @BasitMehmood
> > Did you intentionally merge [this](https://github.com/lowRISC/opentitan/pull/20333/commits/49108bb38f8c8c457e439a1f3f9b59f77249b6da)? Otherwise, you need to rebase first before push your own
> 
> No, i did not do it intentionally. i just wanted to merge idle_hint sequence.

I think you should create new one with 
[[RV_DM]rv_dm_jtag_dtm_idle_hint](https://github.com/lowRISC/opentitan/pull/20333/commits/4a861662c846dee42f128701924c9624a36770c1) 
[4a86166](https://github.com/lowRISC/opentitan/pull/20333/commits/4a861662c846dee42f128701924c9624a36770c1)
only.

**Comment by BasitMehmood** [comment]
Sure, Thankyou

**Pull request closed without merging**
