### PR TITLE
[I2C/DV] Target Cfg

### PR DESCRIPTION
**Pull request by visbaz**
- Added Addr0 Addr1 Cfg
- Added Tasks Program Txdata And Read Acqdata
- Added Checks Read Acqdata and Task Program Stretch Ctrl
- Added Dut Target Intrs Process

### CODE REVIEW

**Comment by jdonjdon** [comment]
> @jdonjdon @cindychip are these CI failures related to pushed code or something else?...it isnt clear for me from the details of failure ...can you help me with it

It got rejected by lint bot.
Can you clean up all issue 'bot' found?

**Comment by visbaz** [comment]
> > @jdonjdon @cindychip are these CI failures related to pushed code or something else?...it isnt clear for me from the details of failure ...can you help me with it
> 
> It got rejected by lint bot. Can you clean up all issue 'bot' found?

@jdonjdon I have fixed them already and then i see these errors. They dont point to any issues in files either so i was confused.
Errors relate to Bazel coding style and test software with bazel...what could be these ?

**Comment by jdonjdon** [comment]
> > > > @jdonjdon @cindychip are these CI failures related to pushed code or something else?...it isnt clear for me from the details of failure ...can you help me with it
> > > 
> > > 
> > > It got rejected by lint bot. Can you clean up all issue 'bot' found?
> > 
> > 
> > @jdonjdon I have fixed them already and then i see these errors. They dont point to any issues in files either so i was confused. Errors relate to Bazel coding style and test software with bazel...what could be these ? image
> 
> I see this from (https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/build/builds/80515/logs/106) "https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64": x509: certificate has expired or is not yet valid: current time 2022-05-18T09:56:09Z is after 2022-05-18T09:43:13Z 2022-05-18T09:56:09.9276005Z ##[error]Bash exited with code '1'. Let me re-trigger it.

@visbaz looks much better now, I will re-trigger private CI once this is done

**Comment by visbaz** [comment]
> > > > > @jdonjdon @cindychip are these CI failures related to pushed code or something else?...it isnt clear for me from the details of failure ...can you help me with it
> > > > 
> > > > 
> > > > It got rejected by lint bot. Can you clean up all issue 'bot' found?
> > > 
> > > 
> > > @jdonjdon I have fixed them already and then i see these errors. They dont point to any issues in files either so i was confused. Errors relate to Bazel coding style and test software with bazel...what could be these ? image
> > 
> > 
> > I see this from (https://dev.azure.com/lowrisc/4c50229e-f6cb-4f39-8522-585bb3841438/_apis/build/builds/80515/logs/106) "https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64": x509: certificate has expired or is not yet valid: current time 2022-05-18T09:56:09Z is after 2022-05-18T09:43:13Z 2022-05-18T09:56:09.9276005Z ##[error]Bash exited with code '1'. Let me re-trigger it.
> 
> @visbaz looks much better now, I will re-trigger private CI once this is done

@jdonjdon looks like all checks have passed. thanks for triggering CI. please post your reviews on PR.

**Review by jdonjdon — COMMENTED** [review]
LGTM

**Review by jdonjdon — APPROVED** [review]

**Comment by visbaz** [comment]
> LGTM

@jdonjdon or @cindychip please merge to master

**Review by cindychip — APPROVED** [review]

**Pull request merged**
