### PR TITLE
[flash] Design updates and clean-up

### PR DESCRIPTION
**Pull request by tjaychen**
- Clean-up and fix the usage of sizing parameters.  Previous
  design represented flash sizes in bus words, leading to an
  incorrect alignment of page boundaries.  This PR changes
  the parameters to flash word size base and explicitly declares
  the bus widths separately.

- Also add an arbiter count between host and controller arbitration.
  Since host reads are critical to performance, the past design
  always favored hosts, with the understanding under the right access
  patterns this could lead to deadlock.  Recent system changes indeed
  led to such an arbitration starvation, so a counter is added to
  ensure controller will not be starved.

- Round robin is still not preferred because controller does not need
  access priority as long as it can "eventually" finish.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
I really should break out the arbitration count portion into a separate PR, but do take a look if can.
The idea is pretty simple. 

For others, the main change is that sizing parameters are now correctly specified, whereas before I tried to be too cute and specify it in terms of bus sizes, which made things very confusing the deeper it got.

**Comment by tjaychen** [comment]
> LGTM, although I wonder whether it would really be that bad if access where just RR arbitrated. i.e., do you expect that these two paths are competing for access often?

personally i think so. Mostly because if the code becomes scrambled, the odyssey of completing a flash read is probably 4-5+ cycles. The read and de-scramble eventually will be pipelined, which to me means if it's fully round robin we won't be able to take advantage of the fact that something is de-scrambling to hide the latency of a new read. 

To your point about how often they would compete, it should not be often. Because most of the time I expect software to access data on another bank...but you never know.  I still may come back and make this RR.   The cost of the counter is pretty low right now, so I'm inclined to give it a try.

**Comment by tjaychen** [comment]
> I don't think the sw changes will be an issue - given the FLASH_WORD_SZ reflects new 64-bit word flash, and the other parameter change is in this PR.
> 
> Given how fundamental running from flash is to our testing setup, CI should show us if there are issues here, so I'm happy from the software side if CI is passing.

Thanks @lenary ! longer term though, I think all of us need to have a conversation about HOW software would like to make use of the flash controller.  There are lingering questions around memory protection, data alignment and informational access that's not finalized yet (and might not be for some time).

**Comment by lenary** [comment]
> > I don't think the sw changes will be an issue - given the FLASH_WORD_SZ reflects new 64-bit word flash, and the other parameter change is in this PR.
> > Given how fundamental running from flash is to our testing setup, CI should show us if there are issues here, so I'm happy from the software side if CI is passing.
> 
> Thanks @lenary ! longer term though, I think all of us need to have a conversation about HOW software would like to make use of the flash controller. There are lingering questions around memory protection, data alignment and informational access that's not finalized yet (and might not be for some time).

Yeah, these do sound like important issues. This sounds like something that should go through the software review queue, rather than anything else.

**Comment by tjaychen** [comment]
yeah i think it's on there...somewhere.

**Comment by tjaychen** [comment]
not all of these points, so i do need to make that clearer.

**Pull request merged**
