### PR TITLE
[keymgr] Detect spurious done's from kmac as a fault

### PR DESCRIPTION
**Pull request by tjaychen**
Addresses the spurious valid item from kmac d2c list #10823 
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM

**Review by eunchan — APPROVED** [review]

**Comment by tjaychen** [comment]
@weicaiyang should i file an issue to track the DV? Sorry this added fault status is a result from kmac d2s review.

**Comment by weicaiyang** [comment]
> @weicaiyang should i file an issue to track the DV? Sorry this added fault status is a result from kmac d2s review.

No worries. Will verify this in V2S. But should we add this in the countermeasure list? I don't find a countermeasure item for kmac returning error or kmac returning all 1s/0s, either.

**Comment by tjaychen** [comment]
> > @weicaiyang should i file an issue to track the DV? Sorry this added fault status is a result from kmac d2s review.
> 
> No worries. Will verify this in V2S. But should we add this in the countermeasure list? I don't find a countermeasure item for kmac returning error or kmac returning all 1s/0s, either.

ah yes good point. I guess to your point i also didn't add the one-hot command check as a countermeasure.

**Comment by weicaiyang** [comment]
> > > @weicaiyang should i file an issue to track the DV? Sorry this added fault status is a result from kmac d2s review.
> > 
> > 
> > No worries. Will verify this in V2S. But should we add this in the countermeasure list? I don't find a countermeasure item for kmac returning error or kmac returning all 1s/0s, either.
> 
> ah yes good point. I guess to your point i also didn't add the one-hot command check as a countermeasure.

oh, right. We also have a one-hot check.

**Pull request merged**
