### PR TITLE
[tlul] Two minor adapter_reg fixes

### PR DESCRIPTION
**Pull request by tjaychen**
- return all 1's (similar to error case) on rdata for write transactions
- correct the data used for integrity generation

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks for the quick fix

**Comment by tjaychen** [comment]
> LGTM, thanks for the quick fix

@weicaiyang would you mind referencing the original issue just so other reviewers have some context?

**Comment by weicaiyang** [comment]
Sure, linked the issue

**Review by rswarbrick — APPROVED** [review]
This looks good to me. As well as X-propagation problems, this might also avoid unnecessarily sending possibly-sensitive CSR contents over the bus.

**Review by cindychip — APPROVED** [review]

**Comment by cdgori** [comment]
Apologies for comment-after-merge but agree with @rswarbrick - this is good from a "stray read" perspective to me.

**Pull request merged**
