### PR TITLE
[enthropy_src/rtl] added fw override otp fuse

### PR DESCRIPTION
**Pull request by mwbranstad**
A new fuse was added to enable firmwave override functions separate from entropy data register reads.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Hey @mwbranstad,

You still need to add this particular item to the OTP HW_CFG partition here:
https://github.com/lowRISC/opentitan/blob/47fcba2bae2b5b60a6f7b2a666931c5c04fc2499/hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson#L181-L184

Also, can you add a short description of these signals to the design docs? 
If I remember correctly, this has been requested in the last DV test plan review.

**Comment by mwbranstad** [comment]
@msfschaffner thanks for the pointer. I think I forgot to search the all cap version of the fw_read term, and so did not find this instance. I still think some process step is not quite right, but we will see how CI runs. Signal comments added.

**Comment by msfschaffner** [comment]
@mwbranstad this PR seems to be in an odd state. The first commit mixes new OTP mmap changes with unrelated changes from Miguel, and there appear to be two merge commits in this PR as well. 

Can you clean this up such that this becomes one clean commit only?

**Comment by mwbranstad** [comment]
@msfschaffner apparently I cannot fix it. I just regenerated this fix with draft #6825 and it now have 6 comments. I followed the process as clean as I can. I am wondering if our special environment where we run make -C hw regs and top has anything to do with it.

**Comment by mwbranstad** [comment]
@martin-lueker do you have a different theory on this?

**Comment by msfschaffner** [comment]
This should not have anything to do with `make -C hw`. 
I believe the culprit are these merge commits. 
Have you used `git merge` or `git pull` locally recently?
These commands generate such merge commits. 
We try to avoid them at all costs because this breaks our nice linear history (and hence makes it difficult to perform rebases).

Let me try to fix this.

**Comment by msfschaffner** [comment]
OK I hope this is works now.
After manually disentangling the `otp_files` from the commit `[doc] Update Hugo's document index.`, I have reset the `esotp3` branch to our current master, applied the otp changes and squashed them together with the `[enthropy_src/rtl] added fw override otp fuse` commit.
Does this look correct to you @mwbranstad?

You can pull this down by doing
```
git checkout esotp3
git fetch origin
git reset --hard origin/esotp3
```

(I have a local backup of the previous state, if needed).

**Comment by mwbranstad** [comment]
@msfschaffner thanks for repairing! I did not believe the make -C hw theory either, but could not figure out what was different. I did see some unusual merges lately, but did not know it was a problem or what the effects would be. Would be nice to know how I got into that state. Anyway, reviewed these changes and they appear as intended. Thanks again.

**Comment by martin-lueker** [comment]
Thanks for troubleshooting this @msfschaffner!
@mwbranstad: I've definitely had accidental master commits.  
 I use `git config  --global pull.ff only` to help prevent merge commits on master, preventing the spread of this type of issue.  @msfschaffner, do would it be worthwhile to  put that in the git instructions?

**Comment by rswarbrick** [comment]
Re `git pull` behaviour: This isn't really an OpenTitan-specific thing. I think we can probably expect contributors to know how to fetch / rebase / merge code, and we should point at generic git documentation if they're finding that hard.

Instead of configuring `pull.ff`, you might find the `pull.rebase` [git-config](https://www.git-scm.com/docs/git-config) flag helpful. Personally, I separate fetching and rebasing/merging and don't really use `git pull` at all.

**Comment by martin-lueker** [comment]
Hm.  So you never use `git checkout master; git pull master`?  I'm sincerely intrigued to learn more.   This seems to have come up because of an accidental commit to master (which is not hard to do, and a pain to clean up, especially if you are frequently using `--amend`).

I'm just saying that since we have all these explicit instructions on how to use git for OT (which actually recommends frequent use of `git pull upstream master`) we could recommend this actual useful guardrail feature there.  I think the trivial downside would be that it seems to require git 2.0 (which just means a new explicit dependency though an ancient one.)

**Comment by msfschaffner** [comment]
To echo @rswarbrick's point, I also separate fetching / rebasing, and almost never use `git pull` directly.
If I do, I use `git pull --rebase` which ensures that you won't get these merge commits (i.e., it preserves the linear history).

I believe
```
git checkout master; git pull master
```
assumes that you only introduce changes on feature branches locally, and never on the `master` branch.
That way, this will just fast forward your local `master` branch to be aligned with upstream, such that you can then branch off it again using e.g. `git branch XYZ` or ` git checkout -b XYZ` to start some new work.

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
@mwbranstad @martin-lueker if this looks good from your side, can we merge it in?

**Comment by mwbranstad** [comment]
@msfschaffner good on my side.

**Review by martin-lueker — APPROVED** [review]
On the topic of the PR itself: LGTM.  Mark, do you declare this ready?

**Comment by martin-lueker** [comment]
On the topic of git-hygiene:  I think we are all in agreement.   Keeping master a clean copy, and yes `git pull --rebase` or `git pull --ff-only` are good solutions (and IMO `git config pull.ff only` or `git config pull.rebase only` are even better to save typing).   However my point is that none of this are in the [OpenTitan github guidelines for syncing repos](https://docs.opentitan.org/doc/ug/github_notes#update-your-repository-with-changes-in-the-lowrisc-repo) which advises:
```
$ git checkout master
$ git pull upstream master
$ git push origin
```
Ignoring the disaster that git pull can cause.  I think Mark is set with ff-only as the default. Though I'm just wondering what people's thoughts whether that document could use an update?

**Comment by msfschaffner** [comment]
Let's continue this discussion this in a separate issue: #6837

**Comment by sriyerg** [comment]
@cindychip 
PTAL at the DV changes in this PR. Thanks!

**Comment by cindychip** [comment]
Thanks Sri, I missed that PR! Looks like this is not intended. I will create a PR to revert the DV part back.

**Pull request merged**
