### PR TITLE
[keymgr] Add input data checks for rom_digest

### PR DESCRIPTION
**Pull request by tjaychen**
- Address #7346

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by rswarbrick** [comment]
If something goes wrong here that causes the checks to fail, I guess the chip will just lock up? Is there no alert mechanism to say "Ooh! This key looks wrong!" ?

**Comment by tjaychen** [comment]
> If something goes wrong here that causes the checks to fail, I guess the chip will just lock up? Is there no alert mechanism to say "Ooh! This key looks wrong!" ?

o this issue won't cause the chip to lock-up, since keymgr operations are invoked by software and not hardware.
So when software does invoke, it will get an "invalid input" error.

**Comment by rswarbrick** [comment]
Oh, I see! So the failure of this check isn't seen immediately; it's just seen when software asks for something using the data? If so, that makes perfect sense to me.

**Pull request merged**
