### PR TITLE
[ci] remove out-of-Bazel Rust installation in CI

### PR DESCRIPTION
**Pull request by nbdd0121**
There is currently a discrepancy between Rust version in tool_requirements.py and CI (1.60) and in Bazel (1.67). Previously the out-of-Bazel Rust toolchain is used only for rustfmt, and now it is also managed by Bazel since #19231, so we should be able to remove this installation entirely.

Hopefully we can also delay the Azure pipelines runner disk out-of-space issue a bit by removing a Rust installation.

Since we use Rust 1.67 we can also remove a clippy false positive that is fixed in 1.66.

### CODE REVIEW

**Review by HU90m — APPROVED** [review]
I'm in favour of moving this; I'd prefer it to only be specified once (in `third_party/rust/deps.bzl`).

**Review by rswarbrick — APPROVED** [review]
Looks sensible to me, thanks!

**Comment by nbdd0121** [comment]
The CI is failing because this requires an coordinated removal in private CI https://github.com/lowRISC/opentitan-private-ci/pull/28.

@rswarbrick Do you think merging both together is okay, or shall I make the script accepts `--rust-version` but doesn't do anything in the interim before we remove it from the private CI?

**Comment by nbdd0121** [comment]
> @rswarbrick Do you think merging both together is okay, or shall I make the script accepts `--rust-version` but doesn't do anything in the interim before we remove it from the private CI?

I made the change to make the script continue accept `--rust-version`. We can remove this when we make the change in the private CI.

**Comment by rswarbrick** [comment]
Oh, I see! (Sorry, I reviewed the CI change before I saw this message). I don't really have strong feelings, but maybe it makes sense to split this into two parts like you suggested: it feels a little easier to get everything merged without accidentally breaking things for anyone else.

**Pull request merged**
