### PR TITLE
[prim_sha2_pad,hmac/rtl] Multiple fixes for save & restore

### LINKED ISSUE #23163: [hmac/rtl] Save and Restore digest mismatch when SHA digest update is too close to a block boundary
### Description

While testing the Save and Restore, I fell on the case described in this temporary [PR](https://github.com/lowRISC/opentitan/pull/23116#issuecomment-2115572831).

`hash_done` is triggered but the last SHA digest update is because of the `round_q` threshold has been reached just before and not because the block has been processed (24 bits are missing to reach 1024).

I have done a temporary fix which is probably not ideal, I'll share it soon.

FYI : @gdessouky

### PR DESCRIPTION
**Pull request by andreaskurth**
This PR contains multiple fixes to `prim_sha2_pad` and `hmac` for the save & restore feature. Please see the commit messages for details.

### CODE REVIEW

**Review by martin-velay — APPROVED** [review]
OK

**Comment by ballifatih** [comment]
These changes break SHA-384, HMAC-384 on my local side, but SHA/HMAC-256/512 are passing (all streamed). It might take a bit until I can run it as top-level test to see if there is a bug in RTL or SW (hopefully this evening). I don't think it should block merging this PR though.

There are too many incoming changes as PRs, it would be easier for me to run the driver tests once we merge them.

**Comment by gdessouky** [comment]
I am also concerned and I would wait a bit on this PR until the incoming PRs (that both touch RTL and DV) go green and get merged first; there is a lot stalling in the pipeline atm and it will get messy soon.

**Comment by gdessouky** [comment]
From inspecting the RTL, I don't spot anything in the RTL changes that would break the new digest sizes and the basic smoke checks for the new digest sizes have already been merged now in that last PR https://github.com/lowRISC/opentitan/pull/23108/commits, so we will know. I can check if this PR breaks the checks in a a few hours, but I don't want to block any RTL changes right now, so please go ahead. Thanks @andreaskurth!

**Review by gdessouky — APPROVED** [review]

**Comment by andreaskurth** [comment]
I locally ran `util/dvsim/dvsim.py hw/ip/hmac/dv/hmac_sim_cfg.hjson -i all -rx 0.1`, and all tests except `hmac_error`, `hmac_stress_all`, and `hmac_stress_all_with_rand_reset` -- which also failed in the latest nightlies -- pass 100%.

**Comment by gdessouky** [comment]
> I locally ran `util/dvsim/dvsim.py hw/ip/hmac/dv/hmac_sim_cfg.hjson -i all -rx 0.1`, and all tests except `hmac_error`, `hmac_stress_all`, and `hmac_stress_all_with_rand_reset` -- which also failed in the latest nightlies -- pass 100%.

Great, let's merge then! These still fail anyway, one of my outstanding PRs should be fixing `hmac_error`. Thanks for checking @andreaskurth.

**Review by vogelpi — APPROVED** [review]

**Pull request merged**
