### PR TITLE
943 patch governance

### PR DESCRIPTION
**Pull request by evelynmitchell**
This is a documentation fix to correct Issue 943.

### CODE REVIEW

**Comment by sjgitty** [comment]
@asb I'll let you weigh in on this change. At a minimum I think it should be
([see Companies house](link)) - with parenthesis. But your call

**Comment by imphil** [comment]
@evelynmitchell The companies house reference feels a bit out of place in this sentence to me. I've commented on https://github.com/lowRISC/opentitan/issues/943 to get the Articles of Association added to the lowRISC web site.

Would that be sufficient to close this PR?

**Comment by evelynmitchell** [comment]
Yes. That's sufficient.

Evelyn Mitchell

**Comment by asb** [comment]
Thanks for the contribution Evelyn. It sounds like you're happy that we address this by making the Articles of Association more discoverable on the lowRISC website (as discussed in https://github.com/lowRISC/lowrisc-web/issues/40), so I'll mark this PR as closed.

**Pull request closed without merging**
