### PR TITLE
[otbn] Extract instruction operation documentation from Python implementation

### PR DESCRIPTION
**Pull request by rswarbrick**
Here's an example of what the result looks like:

ss

Assuming we go with this rewriting approach (which I think we should), there are some obvious further rewrites for things like flag setting. We might also consider using `<=` (like the SystemVerilog non-blocking assignment syntax) for state updates, but that does rather collide with less-than-or-equal. Maybe there's a nice unicode symbol?

I'm not marking this as closing #2618, because we probably want to add a bit more rewriting first.

### CODE REVIEW

**Comment by rswarbrick** [comment]
Oh, and here's a picture of BN.LID (which shows off double indirection and Python-style indentation):
ss

**Comment by imphil** [comment]
Very nice! The general approach looks great to me and can be merged.

As expected, I have a couple suggestions regarding further rewriting. Feel free to address them (partially) in here, or in a follow-up.

**General comments**
* The `self` looks odd and I'd just remove it. I'd assume all variables/operands in the table above the "operation" section to be available.
* I'd go for simple ASCII `[]` instead of `⟦⟧`.

**Assignments and state updates**
As you mentioned, most assignments (`=`) in the operation section are delayed assignments, taking effect after the operation completes. That's not much of an issue for most code, but looks strange in code like `PC = PC`. 
* I just had a look at another spec, and they effectively have the same "problem" and circumvent it by defining a function for the PC assignment case to hide that a bit (`BranchTo(PC[] + offset, BranchType_DIR);`).
* Another solution would be to use the SystemVerilog delayed assignment operator (`<=`) instead of `=`. This is what cocotb does for example: `PC <= PC` looks good to a hardware designer.
* Always documenting `=` to be a delayed assignment is probably not what we want, as we do have some immediate assignments in our operation sections, for example:
	```python3
	(result, flags) = state.add_with_carry(a, b_shifted, 0)
	WDRs⟦self.wrd⟧ = result # or <=
	```

**State access**
I suggest standardizing on all-caps names for all state, as you started doing for the `GPRs`.

* For CSR access (e.g. `state.read_csr(self.csr)`) and flag access (`state.csrs.flags` for read, `state.set_flags()` for write), I would rewrite to `CSR` and `FLAGS` simply (as you mentioned the commit message).
* I would remove the `s` from `GPRs` and `WDRs`, without the `s` `GPR[2]` reads just as `GPR 2` for example.
* Similar reasoning for `state.pc_next = new_address`, which I would just make `PC = new_address`.

DMEM is an interesting one, as we have the ability to access words of two different sizes. So likely keeping the `store()` and `load()` methods/functions there makes sense (instead of using array-like access). We currently have a slight mix of object-oriented and procedural styles, but I'm not sure if `store_u32_to_dmem(0x1234, value)` is really more consistent than `DMEM.store_u32(0x1234, value)`.


**Helper functions**
* Methods of the `state` object, e.g. `state.add_with_carry()` and `state.get_quarter_word_unsigned()` should likely be just pure functions, e.g. `add_with_carry()`.
* Implementations of these helper functions need to go into the ISA doc as well, replacing the current section "Pseudo-Code Functions for BN Instructions".

**Communication across the "core" boundary**
Some things, like `ECALL` and `state.on_error()` are a bit too much "ISS implementation" at the moment for my taste, but we can come back to that later; we'll probably look into a unified way to describe signaling with the outside-of-`otbn_core`-world from instructions (also used for error reporting). Maybe Python exception syntax?

**Review by imphil — APPROVED** [review]

**Comment by rswarbrick** [comment]
Wow, thanks for the detailed review! I'm going to change back to "normal" array references. The other changes will come in follow-ups.

**Comment by weicaiyang** [comment]
@rswarbrick 
I found this error when I tried to generate the doc by using `./util/build_docs.py --preview`

> subprocess.CalledProcessError: Command '['/usr/local/google/home/weicai/ot/xbar/hw/ip/otbn/util/yaml_to_doc.py', '/usr/local/google/home/weicai/ot/xbar/hw/ip/otbn/data/insns.yml', '/usr/local/google/home/weicai/ot/xbar/hw/ip/otbn/dv/otbnsim/sim/insn.py', '/usr/local/google/home/weicai/ot/xbar/build/docs-generated/otbn-isa']' returned non-zero exit status 1.

Not sure why CI didn't catch this. It probably related to this PR. I checked out below 2 commits. with `4077bec9b`, it failed, with the earlier one, it passed.
PTAL. Thanks

> * 4077bec9b N - (HEAD) [otbn] Use libcst to extract implementations for docs (2 days ago) <Rupert Swarbrick>
> * cf45be18d N - [tlul] Update verilator waiver for tlul_err_resp (2 days ago) <Rupert Swarbrick>

**Comment by imphil** [comment]
A new python dependency was added in this PR. Please rerun pip3 install -r python-requirements.txt -U to get all currently required packages.

**Comment by rswarbrick** [comment]
> I now also sent a PSA to the mailing lists.

Thanks. Sorry, I probably should have done that.

**Comment by weicaiyang** [comment]
> A new python dependency was added in this PR. Please rerun pip3 install -r python-requirements.txt -U to get all currently required packages.
> 
> Edit: I now also sent a PSA to the mailing lists.

No wonder CI passed, mine failed. Thanks Philipp.

**Pull request merged**
