### PR TITLE
[dv/clkmgr] Add basic dv support for alerts

### PR DESCRIPTION
**Pull request by matutem**
Signed-off-by: Guillermo Maturana <maturana@google.com>

### CODE REVIEW

**Review by udinator — APPROVED** [review]

**Review by weicaiyang — APPROVED** [review]
LGTM, looks like design hasn't connected the alert, otherwise, we need to update tb as well.

**Comment by sriyerg** [comment]
CI is failing because the `alert_test` CSR does not exist (side effect of the change in this commit). Looks like you do need the design to be updated first. @msfschaffner for ETA on clkmgr alert hookup.

**Comment by matutem** [comment]
Closing this, since https://github.com/lowRISC/opentitan/pull/7123 subsumes it.

**Comment by msfschaffner** [comment]
> CI is failing because the `alert_test` CSR does not exist (side effect of the change in this commit). Looks like you do need the design to be updated first. @msfschaffner for ETA on clkmgr alert hookup.

Hookup is on the way: #7123

**Pull request closed without merging**
