### PR TITLE
Site docs

### PR DESCRIPTION
**Pull request by towoe**
Some additions for docs site to help orientation.
This branch is more a collection of a few different areas, but might be easier to checkout locally for review.
Let me know what you think and it should be easy to only push one specific improvement and drop another.

### CODE REVIEW

**Comment by imphil** [comment]
I love it! This adds a significant amount of discoverability to our docs, which is much needed.

I'm happy to take this PR as-is, but there are clearly some thoughts for further improvements, which become more obvious with this PR:

- Make the in-page TOCs auto-generated to match the ones on the left.
- Work on structure, e.g. move those READMEs in various places of the tree into a structure that fits nicely into the user guide/reference guide/etc. schema.

**Comment by imphil** [comment]
Ah, and ignore the private PR runs, it fails because you have an umlaut in your name (#2127).

**Comment by imphil** [comment]
@gkelly can you have a look and merge if you're happy?

**Comment by towoe** [comment]
Thanks for the feedback Philipp.
I agree that there are some areas in our documentation which could benefit from some restructuring. My position in the beginning was that it would be nice to keep the documentation accessible for CLI and github, but as we have now quite a lot of text I think it is by far more important to have everything working and in order with Hugo / documentation system.

**Comment by gkelly** [comment]
Running this locally now.

**Comment by gkelly** [comment]
My only real complaint is that the breadcrumbs are rendered fairly hard left:

image

Other than that I'm happy with it.

**Comment by gkelly** [comment]
Actually, I'm going to merge this. The QoL improvements are great, so thanks for doing this @towoe! Minor cosmetics shouldn't block this, IMO.

**Comment by gkelly** [comment]
Rerunning private CI, just because I want to see it roll green, then I'll merge.

**Comment by sjgitty** [comment]
> Ah, and ignore the private PR runs, it fails because you have an umlaut in your name (#2127).

How dare yöu!

I'm currently unable to build locally. I need to find a solution for that, then will try, but don't wait for me to merge @gkelly if you're happy with it.

**Comment by towoe** [comment]
> My only real complaint is that the breadcrumbs are rendered fairly hard left:
> 

Added a commit to address this. 

> Actually, I'm going to merge this. The QoL improvements are great, so thanks for doing this @towoe! Minor cosmetics shouldn't block this, IMO.

But I would appreciate if people with more web experience can follow up to improve the appearance of the site and rewrite the cruel code I added here :)

**Pull request merged**
