### PR TITLE
[rstmgr] Make naming consistent for sw_ctrl_regwen

### PR DESCRIPTION
**Pull request by tjaychen**
- Even though sw_ctrl_regwen is used externally and not in the
  conventional regwen way, making the naming consitent so that
  its purpose is clear.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@weicaiyang originally pointed out we could use the vanilla flavor of `regwen` here. But I realized I changed it to external registers specifically under software request. I've filed a separate issue to eventually support that feature..but for now..at least we can make the naming consistent.

**Comment by weicaiyang** [comment]
> @weicaiyang originally pointed out we could use the vanilla flavor of `regwen` here. But I realized I changed it to external registers specifically under software request. I've filed a separate issue to eventually support that feature..but for now..at least we can make the naming consistent.

sure, SGTM

**Comment by tjaychen** [comment]
@matutem can you let me know what you think?

**Review by matutem — APPROVED** [review]
Thanks, LGTM

**Review by sriyerg — APPROVED** [review]

**Pull request merged**
