### PR TITLE
[top_englishbreakfast] Re-align config with recent changes in top_earlgrey

### PR DESCRIPTION
**Pull request by vogelpi**
This PR contains two commits to address #5242 .

### CODE REVIEW

**Review by alphan — APPROVED** [review]
Script changes LGTM, thanks @vogelpi.

**Review by moidx — APPROVED** [review]
LGTM

**Comment by tjaychen** [comment]
@vogelpi should this script be used in CI somewhere..? Just wondering if that would have caught the issue.

**Comment by imphil** [comment]
@tjaychen the script is used and a bitstream is produced. The bitstream is just never tested, as we don't have have a CW305 board in CI.

**Review by msfschaffner — APPROVED** [review]
LGTM

**Comment by msfschaffner** [comment]
can we merge this such that I can start the rebase of https://github.com/lowRISC/opentitan/pull/5179?

**Comment by msfschaffner** [comment]
Thanks!

**Comment by vogelpi** [comment]
@tjaychen and @imphil : the `prepare_sw.py` script is not used in CI - I had to remove it because it messed up the FPGA tests (see #4672). Now that Philipp laid the ground work to support building different binaries, we could think of adding the script back and e.g. run a simple hello world in on top_englishbreakfast in Verilator (don't think we have a spare FPGA board right now). This would have caught the issue.

**Comment by imphil** [comment]
Uh yeah, you're right about the software part. We currently build two variants of the software (one for the Nexys Video, and one for everything else), and we need three variants. [Looks like I pushed the recent work on that successfully out of my brain already.]

However, we build the hardware in CI, but don't test it yet -- so we currently don't catch cases where the bitstream builds, but is broken.

**Pull request merged**
