### PR TITLE
[top_englishbreakfast] Reduce FPGA utilization

### PR DESCRIPTION
**Pull request by vogelpi**
This PR contains a couple of commits to reduce the FPGA utilization of the English Breakfast top level. This is beneficial for different reasons:
- Lower logic utilization speeds up place & route (CI).
- Lower logic utilization improves SCA reproducibility and reduces noise.
- Reduced pipelining in the crossbar greatly improves the capture performance. For AES, it went up from ~850 traces/s to ~1100 traces/s (+30%).

The Earl Grey top level isn't touched by this PR.

### CODE REVIEW

**Comment by vogelpi** [comment]
@abdullahvarici , assuming CI runs through for this PR. Would you mind doing a test capture for OTBN on the CW310 using the bitstream generated in CI, please?

**Review by andreaskurth — APPROVED** [review]
LGTM. Thanks @vogelpi

**Comment by abdullahvarici** [comment]
Thanks @vogelpi. I've tried the bitstream generated by CI and managed the capture AES SCA traces.

**Comment by vogelpi** [comment]
Perfect, thanks @abdullahvarici and @andreaskurth for your feedback!

**Pull request merged**
