### PR TITLE
[ci] Updates for CI in integrated_dev branch

### PR DESCRIPTION
**Pull request by mundaym**

### CODE REVIEW

**Review by HU90m — APPROVED** [review]
I'm not too familiar with the bitstream caching, but this PR looks good to me.

**Comment by mundaym** [comment]
Merging to unblock CI.

**Comment by mundaym** [comment]
@a-will does this change look OK to you?

**Comment by a-will** [comment]
It looks probably OK to me. I'm not seeing any differences in approach to it vs. `earlgrey_es`, and that appears to have worked fine. In general, bitstreams_workspace.py is supposed to be able to choose a bitstream that is only part of the current branch's git history (except for the `latest` key, which makes it generally ill-advised to use anyway).

In the future, this branch likely could use some of the changes I made to `master` to better handle missing bitstreams in cache entries. My attempts on the integrated repo produced `bitstreams_or()` and such, and those were too high-maintenance.

**Pull request merged**
