### PR TITLE
[regtool] Remove support for alternate-style headers

### PR DESCRIPTION
**Pull request by rswarbrick**
This is unused, and seems not to have been used since the start of
development history.

Signed-off-by: Rupert Swarbrick <rswarbrick@lowrisc.org>

### CODE REVIEW

**Comment by eunchan** [comment]
I am ok with this. AFAIK this exists to support old style c header used inside Google. Maybe need to get opinion from SW folks @gkelly @moidx

**Comment by rswarbrick** [comment]
Hi @gkelly and @moidx. Have you an opinion on this? If we don't have any in-tree use for this style of C header, I'd prefer to delete the code that generated it (particularly because it has bit-rotted: my fault, but I'd rather delete it than fix it!)

**Comment by imphil** [comment]
I did a bit of archaeology and combined that with what I remembered from back in the day when this code was merged, and I'm pretty sure we never had users for it and can hence safely remove it. The `--ctdefines` header style matches what another project was using in the past, but I don't think those headers have ever been used as generated from OpenTitan code, and it's very unlikely that they ever will be.

The code was originally written and merged by @mdhayter.

(Non-public reference, sorry: https://github.com/lowRISC/stwg-base/pull/207)

**Review by imphil — APPROVED** [review]

**Comment by rswarbrick** [comment]
Merging this, in the absence of any response. We can always revert the commit if it turns out we need the code.

**Pull request merged**
