### PR TITLE
[ci] Consolidate Verible linting workflow into one stage

### PR DESCRIPTION
**Pull request by jwnrt**
## Summary

This PR consolidates the two-stage `pr_trigger.yml` and `pr_lint_review.yml` actions for Verible linting into one workflow.

This simplifies the CI setup and makes the logs easier to access (the job actually running the lint will show up in the "checks" section of the PR).

It may also fix an issue we're having with PRs from private forks, but I haven't tested that yet.

This shouldn't change the actual behaviour of the action. It still runs the lint stage at the repo's HEAD context and uses the same configs.

## Details

Running the Verible linter and adding review comments to the pull request previously had to be done in two stages:

1. Triggered on the pull request - prepare config and waiver files as artifacts.
2. Running on the repo's HEAD - run Verible and add review comments.

This was required because Actions running in the context of the pull request did not have write permissions to add comments to pull requests.

This is now possible with the pull_request_target event, which triggers when pull requests change, but runs in the context of the repo's HEAD and has the permissions to create comments.

See https://github.com/lowRISC/ibex/pull/1427 and https://github.com/chipsalliance/verible-linter-action/pull/31 for details.

## Example

Because this action runs at the repo's HEAD context, you can't see it working in this pull request. Here's a pull request on my own fork that shows it working: https://github.com/jwnrt/opentitan/pull/10.

Here are the logs for that Action run: https://github.com/jwnrt/opentitan/actions/runs/5267223554/jobs/9522202725?pr=10

The logs print the Verible config and waivers being used. As with our current setup, the job succeeding just shows that it ran successfully, not that the PR passed all the Verible lints.

### CODE REVIEW

**Review by pamaury — APPROVED** [review]
This looks good to me. I admit that my knowledge of github actions is tiny but I really appreciate the documentation effort @jwnrt !

**Comment by jwnrt** [comment]
Rebased for conflicts with https://github.com/lowRISC/opentitan/pull/18900

**Review by rswarbrick — APPROVED** [review]

**Comment by jwnrt** [comment]
Rebased again for conflicts since we had to do a revert in #19107.

This PR supersedes the change that had to be reverted anyway, so no trouble.

**Review by engdoreis — APPROVED** [review]

**Comment by jwnrt** [comment]
Test PR here, looks like it's working fine: https://github.com/lowRISC/opentitan/pull/19117

**Pull request merged**
