### PR TITLE
[csrng,dv] Break long lines in csrng_if

### PR DESCRIPTION
**Pull request by rswarbrick**
I've done this by changing the assignments with ternary operators into
an always_comb block.

The advantage is that the formatting gets a bit clearer and it's no
longer difficult to squeeze everything under 100 characters. The
disadvantage is that we now have to make sure everything gets assigned
on both branches of the "if" statement.

### CODE REVIEW

**Comment by rswarbrick** [comment]
Other possible approaches:

- Keep the `always_comb`, but assign everything to `'z` at the top
- Go back to ternary operators, but add more newlines

I think I prefer what's in this patch (unsurprising, since that's what I've just pushed up!), but I'm happy to go with either of these other approaches, or something else if you'd prefer.

**Review by senelson7 — APPROVED** [review]
I think the always_comb is the easiest to read so LGTM.

**Review by imphil — APPROVED** [review]
I like it if @senelson7 likes it :smile:

**Review by sriyerg — APPROVED** [review]

**Comment by rswarbrick** [comment]
Hmm, that isn't going to work. The point is that the signals we're driving need to be wires, because we only drive them in one mode (host or device). I'll close this and then do a bit of whitespace shuffling in a different PR to get the same effect.

**Pull request closed without merging**
