### PR TITLE
[top] Reduce async fifo depth

### PR DESCRIPTION
**Pull request by tjaychen**
Fix issue identified in #14204

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by eunchan** [comment]
Wait... Did we support Depth 1 in Async FIFO? Did not know that..

**Review by eunchan — APPROVED** [review]

**Review by weicaiyang — APPROVED** [review]
LGTM with a question
With this fix, the ibex D port can only have max 3 outstanding reqs, right?

**Comment by tjaychen** [comment]
> LGTM with a question With this fix, the ibex D port can only have max 3 outstanding reqs, right?

yes that's right.

**Comment by weicaiyang** [comment]
> > LGTM with a question With this fix, the ibex D port can only have max 3 outstanding reqs, right?
> 
> yes that's right.

Thanks @tjaychen

**Comment by eunchan** [comment]
4 x 3depth of TL transaction removed -> one req/rsp pair size is around 150bit as far as I know. around 2000bits are saved. 16k ~ 20k gates are saved. yay!

**Comment by tjaychen** [comment]
ahhh... i always underestimate the size of these things...

**Comment by tjaychen** [comment]
> Wait... Did we support Depth 1 in Async FIFO? Did not know that..

i'm...not actually sure how well verified depth 1 is...let's find out!

**Comment by weicaiyang** [comment]
> 4 x 3depth of TL transaction removed -> one req/rsp pair size is around 150bit as far as I know. around 2000bits are saved. 16k ~ 20k gates are saved. yay!

wow, what a big save!

**Comment by msfschaffner** [comment]
> > 4 x 3depth of TL transaction removed -> one req/rsp pair size is around 150bit as far as I know. around 2000bits are saved. 16k ~ 20k gates are saved. yay!
> 
> wow, what a big save!

pretty cool ;)

@arnonsha @zi-v FYI, this should compensate for some of the other additions due to bugfixes and the version registers.

**Pull request merged**
