### PR TITLE
[doc] Clarify (UN)LOCKED_OWNERSHIP states

### PR DESCRIPTION
**Pull request by drewmacrae**
The use of OWNED and UNOWNED was confusing and I'd like to discuss
ownership transfer and similar flows with LOCKED_OWNERSHIP and
UNLOCKED_OWNERSHIP. This will distinguish it from UNLOCKED_ROM states
but will also clarify that there can be a Silicon Owner when the device
is in an "UNOWNED"->"OWNERSHIP_UNLOCKED" state.

Added a URL that should be sufficient to request access to the source
files for the svgs I edited to facilitate future edits.
Signed-off-by: Drew Macrae <drewmacrae@google.com>

### CODE REVIEW

**Comment by drewmacrae** [comment]
I'm having a permissions issue here and can't assign this to other reviewers.

**Comment by rswarbrick** [comment]
Don't worry, just mention other people that you think should see it in a comment ("@rswarbrick: Please look at this!") and they'll see the PR.

**Comment by asb** [comment]
> I'm having a permissions issue here and can't assign this to other reviewers.

Hi Drew - you should now have an invite to the OpenTitan GitHub team. If you accept this, you'll be able to assign reviewers.

**Review by moidx — APPROVED** [review]

**Comment by moidx** [comment]
Thanks! @drewmacrae. GitHub now shows "new changes"! Once you are ready to submit, can you squash the commits and post a message so that one of the committers can rebase and merge?

**Comment by drewmacrae** [comment]
I squashed in a fix to the typo mentioned in the comments, and this should be ready to merge.

**Pull request merged**
