### PR TITLE
[chip-level/sival] Add test to testplan

### LINKED ISSUE #20054: [chip-test,si-val]  chip_sw_edn_entropy_reqs
### Test point name

[chip_sw_edn_entropy_reqs](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_edn_testplan.hjson)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

@vogelpi @h-filali

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes): **This test already exists in [chip_sw_edn_entropy_reqs](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/entropy_src_edn_reqs_test.c) and [chip_sw_csrng_edn_concurrency](https://github.com/lowRISC/opentitan/blob/master/sw/device/tests/csrng_edn_concurrency_test.c).**
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard): *testpoint exists in testplan*
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [x] For SiVal test cases, test is running relevant FPGA or silicon regression

### LINKED ISSUE #20143: [chip-test] chip_sw_entropy_src_csrng
### Test point name

https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson#L32

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@vogelpi @andreaskurth @h-filali 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

We should make sure the device side component of this test is indeed running on the FPGA.

> estimate 1

### PR DESCRIPTION
**Pull request by h-filali**
This PR adds another test to the chip_sw_edn_entropy_reqs test
point in the edn test plan. The added test is a pre existing test
called chip_sw_entropy_src_ast_rng_req_test. This test is added since
chip_sw_entropy_src_edn_reqs_test only tests 7 out of the 8 EDN endpoints.
The endpoint for the AST is now also covered.

This PR resolves #20054

### CODE REVIEW

**Comment by rswarbrick** [comment]
For any reviewers, note that the 1st three commits appear as #20273. To review that code, probably better to do it there :-)

**Comment by h-filali** [comment]
> For any reviewers, note that the 1st three commits appear as #20273. To review that code, probably better to do it there :-)

Thanks @rswarbrick.Sorry I forgot to add this, you're absolutely right.

**Comment by rswarbrick** [comment]
If I understand this correctly, the other two commits can be merged separately. Maybe it makes sense to drop the first three from this PR? (The other two look "obviously right", so maybe it's best to get them in immediately?)

**Review by HU90m — APPROVED** [review]

**Review by vogelpi — APPROVED** [review]
LGTM, thanks @h-filali !

**Pull request merged**
