### PR TITLE
[difgen] Call `bazel`

### PR DESCRIPTION
**Pull request by eunchan**
This commit revises `make_new_dif.py` to call `bazel` rather than `ci/bazelisk.sh` to be runnable on air-gapped environments.

### CODE REVIEW

**Review by drewmacrae — CHANGES_REQUESTED** [review]
This works but makes the scripts incompatible with CI and other systems that don't have bazel installed. Though the scripts don't run in CI, so this passes checks, I'm wary of having them intentionally diverge from the scripts that do because it will make them harder to maintain. I should have used ./bazelisk.sh here and not ./ci/bazelisk.sh but that wont affect how it runs in the airgapped environment.

Could you make the failure a warning and continue because you'll need to run clang-format anyway after you edit the DIF?

**Comment by drewmacrae** [comment]
Can you format your commit subjects: "[difgen] Call bazel instead of bazelisk.sh" Or similar?

**Comment by drewmacrae** [comment]
Could you have a BAZEL_CMD environment variable that defaults to "./bazelisk.sh" if unset so you can set it to "bazel" instead, but other systems are unaffected? This should let us fix all the scripts this way, even the ones that are covered in CI.

**Comment by eunchan** [comment]
> Could you have a BAZEL_CMD environment variable that defaults to "./bazelisk.sh" if unset so you can set it to "bazel" instead, but other systems are unaffected? This should let us fix all the scripts this way, even the ones that are covered in CI.
>
Revised in this way.

**Review by drewmacrae — APPROVED** [review]

**Pull request closed without merging**
