### PR TITLE
[earlgrey_1.0.0] Update after CW 34

### PR DESCRIPTION
**Pull request by andreaskurth**
This PR updates `earlgrey_1.0.0` with the following PRs that were merged to `master`:
- #24339

### CODE REVIEW

**Review by sha-ron — APPROVED** [review]

**Review by vogelpi — APPROVED** [review]

**Comment by vogelpi** [comment]
CHANGE AUTHORIZED: sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c

**Comment by andreaskurth** [comment]
CHANGE AUTHORIZED: sw/device/silicon_creator/rom/e2e/release/rom_e2e_self_hash_test.c

**Comment by andreaskurth** [comment]
@timothytrippel `//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_code_last_word_fpga_cw310_rom_with_fake_key` and `//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_code_last_word_fpga_cw310_rom_with_fake_keys` failed in both tries of _CW310 ROM Tests_. Do you think this could be an actual problem?

**Comment by timothytrippel** [comment]
> @timothytrippel `//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_corrupt_b_valid_code_last_word_fpga_cw310_rom_with_fake_key` and `//sw/device/silicon_creator/rom/e2e/boot_policy_flash_ecc_error:a_valid_b_corrupt_code_last_word_fpga_cw310_rom_with_fake_keys` failed in both tries of _CW310 ROM Tests_. Do you think this could be an actual problem?

https://github.com/lowRISC/opentitan/pull/24345/commits/39b3f76a0daf287ec257987d6994333240f1eef2 fixes the issue on master branch.

**Pull request merged**
