### PR TITLE
[sw/sca] Flatten sca directory

### PR DESCRIPTION
**Pull request by moidx**
Flatten sca directory. This will facilitate reuse of some of the sca
test libraries.

Signed-off-by: Miguel Osorio <miguelosorio@google.com>

### CODE REVIEW

**Comment by alphan** [comment]
Thanks @moidx!

* For license header check: Can you update the entry in `util/licence-checker.hjson`?
* For include guards: Can you update them (either by running `util/fix_include_guard.py` or manually)?

**Comment by alphan** [comment]
Also, would it make sense to move the libraries to `.../sca/lib` and leave the executables in `.../sca`?

**Comment by moidx** [comment]
Hi @alphan, I addressed all your comments. PTAL, thanks!

**Review by alphan — APPROVED** [review]
Thanks @moidx, LGTM.

**Pull request merged**
