### PR TITLE
[topgen] Clang-format ignore top_earlgrey.{c,h}

### PR DESCRIPTION
**Pull request by lenary**
There are issues with running different versions of clang-format on
these generated files causing conflicts (see #2035). In order to avoid
making hardware engineers have the right version of clang-format
installed when making a hardware-only change to topgen, we instead
ignore clang-formatting on the C files that topgen generates.

This should cut down on formatting issues introduced by hardware-only
changes, while still ensuring that the software tree is kept
well-formatted.

---

Re-running topgen on `master` has changed some `swaccess` properties (presumably caused by 55b2cdfc - which has changes to top_earlgrey.hjson but not top_earlgrey.gen.hjson), and I think has changed the PLIC ids (I see an extra ID for the power manager, presumably due to 163050b9). Based on this it's not clear whether I was supposed to rerun `topgen` or not.

### CODE REVIEW

**Comment by imphil** [comment]
We did have long discussions on `clang-format off` in the past, and the outcome was that it is *not* allowed in our code base. You can remove some files from the CI check, however.

**Comment by lenary** [comment]
I'm still working on this, but it's turning out to be more work than expected - I want to use `.clang-format` files in the vendor directories to disable formatting of vendored software, but that also involves removing any `.clang-format` files from the versions of the repos that brings in. I'm now working on a `vendor.py` change to make this easier.

**Comment by lenary** [comment]
This is now blocked until #2039 lands and I can add exclusion rules for the `.clang-format` files in the vendored repos without having to integrate upstream changes to the repos.

**Comment by imphil** [comment]
Not really blocked on #2039, you can use your WIP patch to the vendor tool to update the vendor description files without merging the tool updates first.

**Pull request merged**
