### PR TITLE
[otbn] Declare V2S

### PR DESCRIPTION
**Pull request by ctopal**
This PR declares V2S for OTBN.

All checklist items in issue https://github.com/lowRISC/opentitan/issues/15408 are resolved.

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

### CODE REVIEW

**Comment by GregAC** [comment]
Note that we've now got a 100% FPV proof rate and https://github.com/lowRISC/opentitan/pull/14999 will bring our FSM coverage up to the required level.

**Review by GregAC — APPROVED** [review]

**Review by andreaskurth — APPROVED** [review]
:clap:

**Review by msfschaffner — APPROVED** [review]
LGTM - let's wait for the nightly coverage to update, then we can merge it.

**Comment by ctopal** [comment]
Nightly results from today shows +90% FSM coverage already - I suspect it's the race condition fix in PR https://github.com/lowRISC/opentitan/pull/15562 that bumped the number. Please feel free to merge this early if you think this'd be enough @msfschaffner. Otherwise, I can take a look into the tomorrow's result and merge with that.

Screenshot from 2022-10-25 19-32-23

**Comment by msfschaffner** [comment]
If the metrics are fulfilled, we should be good to go! Just make sure to check back again tomorrow ;).

**Comment by msfschaffner** [comment]
Congrats everyone!

**Pull request merged**
