### PR TITLE
[rom_ext] Skip extra OTBN initialization 

### LINKED ISSUE #23222: [otbn] chip failing to boot with OTBN error
### Description

Tests are failing on the CW310 and CW340 FPGAs on master with the following boot error value: `BFV:03424e0d`.

I believe this is `0x03, 'B', 'N', 0x0d` which is OTBN error 3: `kErrorOtbnExecutionFailed`.

https://github.com/lowRISC/opentitan/blob/405b21e625e7481a0d94b0c8077a1c3f1d1373f1/sw/device/silicon_creator/lib/error.h#L125

### PR DESCRIPTION
**Pull request by cfrantz**
On the `master` branch, the ROM loads the OTBN application; the ROM_EXT does not need to.

Fixes #23222.

### CODE REVIEW

**Review by luismarques — APPROVED** [review]

**Review by jwnrt — APPROVED** [review]
Thanks for the proper fix.

Please could you rebase to fix the sign-off lint?

**Comment by jwnrt** [comment]
CI is quite backed up at the moment (~10 hours) but I'd like to see this run if possible. Once the bitstream and FPGA jobs join the queues, feel free to move them to the front using this button in Azure:



Unfortunately I can't work out how to grant this permission if the button doesn't show up for somebody.

**Comment by jwnrt** [comment]
I've signed it off myself, hope you don't mind. Cancelled the rest of the CI queue since they'll all fail anyway.

**Review by a-will — APPROVED** [review]

**Comment by a-will** [comment]
Enough ROM and ROM_EXT tests have run and demonstrated boot works. Merging to unblock CI.

**Pull request merged**
