### PR TITLE
[ott] Defer determination of log severity for USB errors

### PR DESCRIPTION
**Pull request by dmcardle**
The current eager error logging has led to some confusion recently. OpenTitanTool prints the following "ERROR" lines on CI, even though it proceeds to find a suitable device.

    [2022-11-11T03:40:43Z ERROR opentitanlib::util::usb] Could not open device at bus=1 address=97
    [2022-11-11T03:40:43Z ERROR opentitanlib::util::usb] Could not open device at bus=3 address=95

This commit defers the errors until we know how many USB devices were found so we can choose a suitable severity.

Signed-off-by: Dan McArdle <dmcardle@google.com>

### CODE REVIEW

**Comment by alphan** [comment]
Thanks for this tweak @dmcardle! This also bothered me when I was looking for error messages for a CI issue and searching for "error" returned 1562 hits :) I've put up a draft (#16924) just to see how the log would look but this one is clearly more thought out. Can you update this when you get the chance?

**Comment by dmcardle** [comment]
@alphan Hey, thanks for reminding me about this! I'll try to freshen it up today.

**Comment by dmcardle** [comment]
@alphan PTAL! Only private CI failed, and I think it's unrelated to this PR.

**Review by alphan — APPROVED** [review]

**Review by cfrantz — APPROVED** [review]

**Comment by dmcardle** [comment]
I'm seeing a Kokoro failure and airgapped builds failing on CI. I think both are unrelated to this PR, but I documented the latter in #16960.

**Pull request merged**
