### PR TITLE
[prim_alert_receiver] Fix ping during init sequence bug

### PR DESCRIPTION
**Pull request by msfschaffner**
Fix #9803

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Review by cindychip — COMMENTED** [review]
Thanks Michael, I did not see any more timeout errors, but I think we need to fix some assertions regarding this change: 
I have seen these two assertions failed: alert_receiver.PingPending_A and PingRequest0_A.

**Comment by msfschaffner** [comment]
Hey @cindychip, I looked at the assertions with formal and realized that the ping bypass (`PingOkBypassDuringInit_A`) did not work anymore, either. 

I therefore modified the ping request mechanism a little bit:
1) we now always latch incoming ping requests and set `ping_pending_q`, but we only toggle the differential ping request pair going from receiver to sender if we are not in the init states.
2) if `ping_pending_q` is set and `init_trig_i` is asserted, we acknowledge the ping request right away and clear `ping_pending_q`.
3) when we exit the `InitAckWait` state, we check whether `ping_pending_q` is still set. if it is, this means that we got a ping request during the init phase, but after `init_trig_i` has been deasserted. hence, in that case, we toggle the differential ping request pair so that the ping handshake can complete.

**Review by tjaychen — APPROVED** [review]
lgtm. So effectively we are letting the fsm control the `send_ping` condition right?

**Comment by msfschaffner** [comment]
> lgtm. So effectively we are letting the fsm control the `send_ping` condition right?

Yes exactly - sending a ping request was independent from the FSM state before, but due to the init states we need to change that.

**Comment by msfschaffner** [comment]
> Thanks Michael, I did not see any more timeout errors, but I think we need to fix some assertions regarding this change: I have seen these two assertions failed: alert_receiver.PingPending_A and PingRequest0_A.

@cindychip I have updated the design accordingly - let me know if this looks good from your side.

**Review by cindychip — APPROVED** [review]
hey Michael, I am super sorry I missed this review! LGTM and all tests passed

**Comment by msfschaffner** [comment]
Great, thanks!

**Pull request merged**
