### PR TITLE
[lc_ctrl] Correct invalid state error indication

### LINKED ISSUE #9431: [lc_ctrl] State error bit of status register not set for forced FSM state
It appears that the state error bit of the status register is not set in the case of an invalid FSM state as the result of tampering.
Alerts are not triggered either.

The register description states:
<html>
<body>

STATE_ERROR | This bit is set to 1 if either the controller FSM state or the life cycle state is invalid or has been corrupted as part of a tampering attempt. This error will move the life cycle state automatically to ESCALATE and raise a fatal_state_error alert.
-- | --

</body>
</html>

Looking at the FSM code the transition to InvalidSt can be effected in 2 ways.
1. As the result of any of the state_invalid_error bits being set.
2. Due to an unknown state being detected in the FSM.

Only case 1 sets the state_invalid_error_o which appears to be the trigger for the STATE_ERROR flag being set and alerts generated.

### PR DESCRIPTION
**Pull request by msfschaffner**
This corrects the behavior of the invalid state error, and updates the docs to be consistent.

Fixes #9431

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
@NigelScales I believe this should fix #9431, but there is now a new alert source that needs to be accounted for (the invalid FSM state).

**Review by tjaychen — APPROVED** [review]

**Comment by tjaychen** [comment]
> @NigelScales I believe this should fix #9431, but there is now a new alert source that needs to be accounted for (the invalid FSM state).

do we have to have the invalid fsm state alert? Because honestly i think when that happens the whole device will just die wouldn't it?

**Comment by msfschaffner** [comment]
yeah, the system just dies. it just so happens that the error conditions (FSM invalid and LC state invalid) are bundled into the same error, which triggers a fatal alert. (also, the alert still gives you the option to trigger a system-wide reset if needed).

**Comment by tjaychen** [comment]
> yeah, the system just dies. it just so happens that the error conditions (FSM invalid and LC state invalid) are bundled into the same error, which triggers a fatal alert. (also, the alert still gives you the option to trigger a system-wide reset if needed).

o yeah fair point on the reset escalation.

**Pull request merged**
