### PR TITLE
[sysrst_ctrl] Rework the debouncing logic

### PR DESCRIPTION
**Pull request by msfschaffner**
The previous debouncing FSMs had a few issues:
- The debounce timers themselve did not really filter the input signal as a debouncer should do, but just sampled the signal twice - once before starting the timer and once after. The debouncing therefore does not guarantee that the signal has been stable for X cycles.
- There were 4 different implementations of debounce timer FSMs that all implemented roughly the same functionality

To this end, this reworks the debouncing logic and replaces the different timer FSMs by one unified module named `sysrst_ctrl_detect`.
The module reuses `prim_filter_ctr` under the hood in order to further reduce code duplication and standardize on the same debouncing method that is used elsewhere in the design (GPIO, pinmux, USB).

~~Note that this PR is dependent on https://github.com/lowRISC/opentitan/pull/9826, so only the last two commits are relevant.~~
~~That other PR also still has a CI issue that needs to be resolved first.~~

### CODE REVIEW

**Comment by msfschaffner** [comment]
CC @patel-madhuri

**Review by tjaychen — APPROVED** [review]
this lgtm... good catch.

**Comment by msfschaffner** [comment]
Thanks, I'll merge this as it is now.
I think we should at some point revisit with Toshak whether the chosen detection modes / levels (L2H, H2L, H, L etc) are actually intended behavior - but I guess that is for a D3 design review.

**Review by vogelpi — COMMENTED** [review]
I know this is post merge, but the PR looks good to me.

**Comment by msfschaffner** [comment]
Thanks @vogelpi - sorry for rushing it a bit.
I wanted to get it in quickly so that the DV side is unblocked.

CC @patel-madhuri this has been merged now, so we should be able to proceed with test development.

**Pull request merged**
