### PR TITLE
[rom] Add missing dependency for otp image generation.

### PR DESCRIPTION
**Pull request by tjaychen**
Thanks to moidx for tracking this down.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
ah, so should i close this one and wait for #16136?

**Comment by jrvanwhy** [comment]
> ah, so should i close this one and wait for #16136?

#16034 added the watchdog_enable tests. #16136 performs that refactoring that would've prevented the merge skew, but it is based on a commit from before #16034, so it doesn't touch the watchdog_enable tests. Therefore we would have to rebase #16034 on top of a newer commit, update it to fix the watchdog_enable tests, then merge it.

Probably better to just merge this PR for now, and deal with the cleanup (#16136) later when things aren't failing in CI.

**Comment by jrvanwhy** [comment]
> > ah, so should i close this one and wait for #16136?
> 
> #16034 added the watchdog_enable tests. #16136 performs that refactoring that would've prevented the merge skew, but it is based on a commit from before #16034, so it doesn't touch the watchdog_enable tests. Therefore we would have to rebase #16034 on top of a newer commit, update it to fix the watchdog_enable tests, then merge it.
> 
> Probably better to just merge this PR for now, and deal with the cleanup (#16136) later when things aren't failing in CI.

I spoke 1 minute too soon; Alphan just updated #16136 and it should fix the tests too.

**Comment by alphan** [comment]
> > ah, so should i close this one and wait for #16136?
> 
> #16034 added the watchdog_enable tests. #16136 performs that refactoring that would've prevented the merge skew, but it is based on a commit from before #16034, so it doesn't touch the watchdog_enable tests. Therefore we would have to rebase #16034 on top of a newer commit, update it to fix the watchdog_enable tests, then merge it.
> 
> Probably better to just merge this PR for now, and deal with the cleanup (#16136) later when things aren't failing in CI.

I'd suggest waiting for and merging #16136 since it addresses the root cause. I've just rebased and fixed the lint errors in that PR so it should be ready to go once the CI is done.

**Comment by tjaychen** [comment]
sounds good, let me close this one. Thanks all.

**Comment by alphan** [comment]
> sounds good, let me close this one. Thanks all.

Thanks @tjaychen @moidx @jrvanwhy and apologies for the merge skew.

**Pull request closed without merging**
