### PR TITLE
[keymgr] Minor fix

### PR DESCRIPTION
**Pull request by tjaychen**
Address #4665

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by weicaiyang** [comment]
@tjaychen 

This update uncovers another issue.
Advancing to disabled state will have failed status as `adv_dvalid[3]` is always 0.
Screen Shot 2020-12-28 at 3 47 37 PM

/edascratch/weicai-opentitan/ot/rerun_pr_4683/keymgr-sim-vcs/0.keymgr_random/out
verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
ah, good point. I need to wire up the unused values to 1'b1 probably.

**Comment by tjaychen** [comment]
@weicaiyang please have a look.  I should have fixed the latest issue.

**Comment by weicaiyang** [comment]
> @weicaiyang please have a look. I should have fixed the latest issue.

The previous issue is fixed. I also find key version error will cause 2 error codes to be set.
From below codes, if kmac_input_invalid_i is set, both ErrInvalidIn and ErrInvalidOut will occur. Is this expected? I thought key version error should only result in 1 error code.
```
  assign error_o[ErrInvalidIn]  = op_done_o & op_accepted & kmac_input_invalid_i;
  assign error_o[ErrInvalidOut] = op_done_o & op_accepted & ~data_valid;

 assign data_valid = valid_data_chk(kmac_data_i[0]) & valid_data_chk(kmac_data_i[1])
    & !kmac_input_invalid_i & !kmac_op_err;
```

**Comment by tjaychen** [comment]
huh...i guess it does. if you see the code there, i make the output invalid
also when the input is invalid.
Not sure if that's good or bad... i guess it makes sense? if your input is
invalid? the output must be bad also?

**Comment by weicaiyang** [comment]
> huh...i guess it does. if you see the code there, i make the output invalid also when the input is invalid. Not sure if that's good or bad... i guess it makes sense? if your input is invalid? the output must be bad also?

It's a bit unusual. I don't have very strong preference on this. 
Perhaps it's good to document this behavior. Invalid output is defined as a hardware fault error, but now it can be triggered by SW.

**Comment by tjaychen** [comment]
yeah let me think about it.
I think the original intent was that when input is invalid, the update
should not happen.
It was a side effect of that where output is also marked invalid.

It might make sense to split this up.

**Comment by tjaychen** [comment]
@weicaiyang please take a look now. This addresses the output invalid issue.

**Comment by weicaiyang** [comment]
> @weicaiyang please take a look now. This addresses the output invalid issue.

Now it's matching the scoreboard. Thanks

**Review by weicaiyang — APPROVED** [review]

**Pull request merged**
