### PR TITLE
[pwrmgr] change boot state expectation for main power domain

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
can i get a review of this PR?

**Comment by tjaychen** [comment]
can i get a quick +2 on this one? the change is really minor.

**Comment by zi-v** [comment]
LGTM

**Review by msfschaffner — APPROVED** [review]
LGTM

**Pull request merged**
