### PR TITLE
[hjson] Add explicit commas to top_earlgrey.hjson

### PR DESCRIPTION
**Pull request by jwnrt**
## Summary

This PR:

* Adds explicit commas where Hjson implicitly takes a newline to be a comma.
* Fixes a couple of minor typos in comments.

This PR only covers `top_earlgrey.hjson`.

### CODE REVIEW

**Review by marnovandermaas — APPROVED** [review]
This looks reasonable to me. I assume you prefer adding the commas for consistency and as a preference, since HJSON does allow the newlines as well?

**Comment by hcallahan-lowrisc** [comment]
> I'm not sure when the unauthorized changes check will be lifted. Maybe it's worth waiting for the freeze to be over before merging this particular commit?

https://github.com/lowRISC/opentitan/pull/19163

**Comment by jwnrt** [comment]
> #19163

I'll rebase to fix the current conflicts when that merges.

**Review by HU90m — APPROVED** [review]

**Review by hcallahan-lowrisc — APPROVED** [review]
Thanks for the cleanup!

**Pull request merged**
