### PR TITLE
fix(spid): Latch FIFOADDR at correct time

### PR DESCRIPTION
**Pull request by eunchan**
_Related Issue: https://github.com/lowRISC/opentitan/issues/15266_

This PR fixes a bug for unaligned access in TPM read commands.

fifoaddr is latched with the counter being `'h1F`. The counter, however, runs on SPI_CLK, while the latching logic is running on inverted SPI_CLK domain.

As a result, the latching logic captures the fifo address at a cycle earlier with prematured address. So it always assume address[1] as address[0].

This commit fixes the issue by:

1. Convert `sck_fifoaddr_latch` into iSCK domain.
2. To not shift the address one bit more, use `sck_cmdaddr_wdata_q` rather than `sck_cmdaddr_wdata_d`.

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
This works. Thanks
LGTM

**Review by a-will — APPROVED** [review]

**Comment by a-will** [comment]
Random FYI: It looks like we're only guaranteed 2 ns of setup time, which is a relatively small fraction of the clock period (< 5%).

**Comment by eunchan** [comment]
> Random FYI: It looks like we're only guaranteed 2 ns of setup time, which is a relatively small fraction of the clock period (< 5%).

SPI_DEVICE ip mandates all the datapath to satisfy half of SPI_CLK period. So all signals starting from posedge of SPI_CLK becomes stable before negedge of SPI_CLK - t_setup .

**Comment by a-will** [comment]
> > Random FYI: It looks like we're only guaranteed 2 ns of setup time, which is a relatively small fraction of the clock period (< 5%).
> 
> SPI_DEVICE ip mandates all the datapath to satisfy half of SPI_CLK period. So all signals starting from posedge of SPI_CLK becomes stable before negedge of SPI_CLK - t_setup .

I'm talking about what the upstream spi_host will provide us. MOSI is only guaranteed to be stable 2 ns before posedge SPI_CLK. That'll just inform a `set_input_buffer` constraint ;)

**Comment by eunchan** [comment]
Ah.. I see. If that is true, then we will have big problem on passthrough feature (not this logic though).
I thought that the data is valid right after the negedge of SPI_CLK.

**Comment by a-will** [comment]
> Ah.. I see. If that is true, then we will have big problem on passthrough feature (not this logic though). I thought that the data is valid right after the negedge of SPI_CLK.

For what it's worth, this is only at spec level for SPI TPM. I'm not aware of any standard SPI NOR flash spec for setup time on the device side. However, typical values of recent flash parts are going to be similar (maybe 2 ns for setup and 5 ns for hold). At the same time, those parts are able to do reads at speeds greater than 100 MHz.

Your thoughts about how most SPI hosts behave are probably correct, though. In practice, we may have wide compatibility if we don't require a stable value too close to the negedge, but we should check and make sure we understand expectations.

**Pull request merged**
