### PR TITLE
[topgen,clkmgr] Further tidy-ups paving the way for multiple "hint" clocks in a module

### PR DESCRIPTION
**Pull request by rswarbrick**
The first two patches in this queue are all about de-duplicating logic to make sure everything matches. The third patch expands some of the names in clkmgr so that it's possible for a block to expose more than one "idle" hint. We don't actually *do* that yet, but this is a necessary change to make it happen. The final patch is just a tweak to tidy up how we're expand templates.

### CODE REVIEW

**Comment by rswarbrick** [comment]
Hmm, this isn't going to work without doing the wiring work as well. The failing test (clkmgr_smoke) is because we've connected up the `HintIoDiv4Otbn` signal but not `HintMainOtbn` (since, alphabetically, that comes first). Unfortunately, we're checking that `clk_main_otbn` stops, which it doesn't!

I'll close this PR for now and re-open it later with an extra couple of patches earlier in the queue that keep everything working.

**Comment by tjaychen** [comment]
let me know if there's anything you want me to help with @rswarbrick.
Can you remind me, is the plan now to expose multiple `idle` from `otbn`, or stick with one `idle` for multiple clocks?

I think for the level of our design, it's fine to simplify to the latter.  Although if you guys prefer to more complete solution that's fine too.

**Comment by rswarbrick** [comment]
I think the plan is to expose multiple idle signals (because it moves the complexity from clkmgr to the blocks). I've *almost* got things working here: should be able to push up a proper patch sometime tomorrow.

**Comment by rswarbrick** [comment]
Oh drat! It looks like I can't re-open this PR because I've force-pushed to the branch in the meantime. Will start again :-)

**Pull request closed without merging**
