### PR TITLE
[sival] Update testplan 

### PR DESCRIPTION
**Pull request by engdoreis**
This PR updates the Sival stages according to the prioritization made by @moidx on the [sheet](https://docs.google.com/spreadsheets/d/1Uw3iNPvXfG-dN-RRnH11qSQOnwNdGl_4TCFIW1atZwA/edit#gid=2045762255).

### CODE REVIEW

**Review by johngt — COMMENTED** [review]
Based on looking through the Google sheet there are a few tests that need to be changed to reflect the latest status

- chip_sw_aes_interrupt_encryption
- chip_sw_clkmgr_idle_trans
- chip_sw_csrng_lc_hw_debug_en
- chip_sw_edn_boot_mode
- chip_sw_lc_ctrl_transitions
- chip_sw_lc_ctrl_kmac_req
- chip_sw_lc_ctrl_volatile_raw_unlock
- chip_sw_lc_ctrl_jtag_access
- chip_sw_lc_ctrl_otp_hw_cfg
- chip_sw_lc_ctrl_init
- chip_sw_lc_ctrl_broadcast
- chip_sw_lc_ctrl_kmac_error
- chip_sw_lc_walkthrough
- chip_sw_keymgr_sideload_kmac_error
- chip_sw_kmac_app_keymgr
- chip_sw_kmac_app_lc
- chip_sw_kmac_app_rom
- chip_sw_kmac_entropy
- chip_sw_rom_access
- chip_sw_usbdev_setup_rx
- chip_sw_usbdev_config_host
- chip_sw_usbdev_pincfg
- chip_sw_usbdev_tx_rx
- chip_sw_usbdev_stream
- chip_sw_usbdev_iso

**Comment by engdoreis** [comment]
Thanks @johngt for catching that. From your list below, I could only confirm the lc_ctrl ones because the testplan had the wrong name in the hjson, so my script skipped it.
Should be fixed now.

**Comment by moidx** [comment]
Hi @johngt, the NA was used to mark test cases that fell in one of the following two categories:

1. Unfeasible to test in silicon.
2. Already sufficiently covered by other test points. 

We can do another pass on the spreadsheet to add more specific labels, but not sure if using SV4 or SV5 would be intuitive enough for future readers.

**Review by moidx — APPROVED** [review]
Thanks for working on this @engdoreis!

**Pull request merged**
