### PR TITLE
[earlgrey_es] Cherry-pick - fix phy_host_gran_err test

### PR DESCRIPTION
**Pull request by eshapira**
This commit already exists in the master branch, this PR will merge it to earlgrey_es branch.

### CODE REVIEW

**Review by sha-ron — APPROVED** [review]

**Review by jdonjdon — APPROVED** [review]

**Comment by jdonjdon** [comment]
@eshapira 
This time it goes smooth hehr

**Comment by eshapira** [comment]
> @eshapira This time it goes smooth heh

Yes, hopefully now I have the correct way to do it😀

**Review by rswarbrick — APPROVED** [review]

**Comment by eshapira** [comment]
@jdonjdon Can you please take a look on the failing CIs? It's weird that the CIs are failing on this commit after they passed when we committed it to the master branch.

**Comment by eshapira** [comment]
Thanks!

**Pull request merged**
