### PR TITLE
[sw, dif_uart] Add reset routine

### PR DESCRIPTION
**Pull request by silvestrst**
This routine is useful to reset a peripheral to its default state.

This change is related to #1076

### CODE REVIEW

**Comment by silvestrst** [comment]
@alphan I just thought that this way is more flexible, as that removes the burden from boot_rom code to always reset the peripheral at the end. So the issue is if you require a state structure for the reset routine - you actually need to call `dif_device_init` before you can use `dif_device_reset`. However unless your `init` routine resets the peripheral internally, you will inherit some configuration and IRQ state from boot_rom. I actually had issue with my `consecutive_irq_test`, as I had additional IRQ firing, during to the line being asserted in boot_rom before a jump to flash.

Having `mem_region_t` as an input allows, for example, to `reset` the state and then run `init` in flash.

@lenary had some thoughts on whether it could be desirable to inherit some peripheral configuration from the boot_rom, to minimise the gap when we can process IRQs.

I am not sure what is the best way to go about it. We probably either want to force boot_rom to reset all the peripherals it has touched, or allow the drivers in flash to reset them before doing anything else, including `init`.

Another option would to reset the peripheral in the `init` routine, before actually initialising the peripheral.

Would be also interesting to see what @gkelly thinks about it.

**Comment by alphan** [comment]
@silvestrst, I think resetting in init is a good idea to guard against such cases but this is not best approach for peripherals that are also used in boot_rom. Maybe we can explore configuring all peripherals in boot_rom?

**Comment by silvestrst** [comment]
@alphan I have now created PR #1510  where I added a functionality that allows to choose the behaviour of the `init` routine. I might retire this PR later, as I haven't come across any use-cases so far where `reset` routine needs to be used.

**Comment by silvestrst** [comment]
Retiring this in favour of #1510 , at the moment I am not aware of the use-cases that require public reset routine. For the time being, to ensure that the state of the peripheral is consistent after a jump from `boot_rom` to `flash`, it is enough to reset peripherals on `init`.

**Pull request closed without merging**
