### PR TITLE
[opentitanlib,opentitantools,test] migrate structopt to clap

### LINKED ISSUE #17372: [opentitantool] Replace structopt by clap
### Description

The [`structopt`](https://docs.rs/structopt/latest/structopt/) crate is now in maintenance mode and its functionality has been integrated, essentially as-in, in [`clap`](https://docs.rs/clap/latest/clap/). Moving forward, it is worth considering whether we should change to use `clap` instead of `structopt`.

### PR DESCRIPTION
**Pull request by nbdd0121**
Fixes #17372

`structopt` is in maintenance mode and should be migrated to `clap`instead.

This is a fairly mechanical translation by replacing `#[derive(StructOpt)]` with `#[derive(Args)]` on structs, and `#[derive(Subcommand)]` on enums.

A few places using `PathBuf` are tweaked to use `PathBuf::from_str` instead of the built-in value parser in clap, because clap's parser for `PathBuf` rejects empty strings while we do need to accept that.

In total this reduces number of crate dependencies by 8.

### CODE REVIEW

**Comment by cfrantz** [comment]
Can we delay submitting this until after we create the earlgrey branch.

I'm really pleased to see this PR, but I don't want to take the chance of having a tooling regression while we're performing the final integration with the silicon partner.

**Comment by nbdd0121** [comment]
No need to rush! I definitely don't mean to have this merged before 2.5.2 tagging. Just want to submit this and use CI before the quiet week. I am going to switch this PR to draft until branching happens.

**Comment by nbdd0121** [comment]
I will keep this PR in draft state until #18939 is merged. These PRs have merge conflicts, as unfortunately both structopt and strum starts with "s" :(

**Comment by jwnrt** [comment]
I'd support using `/// doc comments` instead of `#[arg(help = "doc comments"]`, but up to you whether you include that in this PR or we consider it separately.

**Review by jrvanwhy — APPROVED** [review]

**Review by jwnrt — APPROVED** [review]

**Review by HU90m — APPROVED** [review]

**Comment by nbdd0121** [comment]
> I'd support using `/// doc comments` instead of `#[arg(help = "doc comments"]`, but up to you whether you include that in this PR or we consider it separately.
> 
> They keep the macro lines shorter, show up in rustdoc, and are easier to read and write.

I also think this is favourable, but probably should go in a different PR since there are also some usages in hsmtool that needs updating.

**Review by engdoreis — APPROVED** [review]
LGTM.

**Review by marnovandermaas — COMMENTED** [review]
Thanks for coming and explaining the scope of this PR to me. I will merge this because other's that are knowledgeable have already reviewed and approved this.

**Pull request merged**
