### PR TITLE
[reggen] simplify descriptions and enums in multireg

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@cindychip do you mind trying this locally to see if it solves the problem you're seeing?
I think it does, but I wanted to double check just in case i saw a different issue.  Let me also know if the resulting output is clear to you, or if we should clean up more.

**Review by cindychip — APPROVED** [review]
Thanks Tim, that is what i am looking for. I checked it locally and looks great.

**Comment by tjaychen** [comment]
thanks merged! do you mind closing the issue also?

**Comment by cindychip** [comment]
Thanks for the reminder and quick fix! Closed

  Cindy Chen

**Pull request merged**
