### PR TITLE
[vendor] Add Wycheproof test vectors

### PR DESCRIPTION
**Pull request by jadephilipoom**
See discussion on #9334

Imports the test vectors from Project Wycheproof using the `util/vendor.py` script so it's easy to update. These are adversarial tests that will be used to check our crypto code.

### CODE REVIEW

**Review by alphan — COMMENTED** [review]
I think these should be under `sw/vendor` but other than that LGTM.

**Comment by jadephilipoom** [comment]
> I think these should be under `sw/vendor` but other than that LGTM.

Now moved to `sw/vendor`, thanks for the catch!

**Comment by alphan** [comment]
@jadephilipoom, it looks like you created the second commit manually. Would you mind using the `--commit` option of the vendor script? (it adds the commit hash from upstream in the message which can be helpful later)

**Comment by jadephilipoom** [comment]
Unfortunately the `--commit` option fails because the commit is blocked by git-secrets if you don't pass `--no-verify` to `git commit` -- the reason is that the test files have test keys in them, so git-secrets understandably gets concerned that you're committing a key and has to be told it's OK explicitly.

**Comment by rswarbrick** [comment]
You could always temporarily hack the vendor script to pass `--no-verify`? :-D

**Review by alphan — APPROVED** [review]

**Comment by alphan** [comment]
Previous CI run was green, confirmed that the new tip is identical to the old one, merged.

**Pull request merged**
