### PR TITLE
[csrng] Move CSRNG version 2.0.0 verification_stage to V2S

### PR DESCRIPTION
**Pull request by vogelpi**
This resolves lowRISC/OpenTitan#22467.

### CODE REVIEW

**Comment by vogelpi** [comment]
CHANGE AUTHORIZED: hw/ip/csrng/data/csrng.hjson

This PR just updates the verification stage without impact on the RTL.

**Review by andreaskurth — APPROVED** [review]
LGTM based on [this V2S analysis](https://github.com/lowRISC/opentitan/issues/22467#issuecomment-2189266234) and [its review](https://github.com/lowRISC/opentitan/issues/22467#issuecomment-2210522580). Great work!

**Comment by andreaskurth** [comment]
CHANGE AUTHORIZED: hw/ip/csrng/data/csrng.hjson

**Comment by vogelpi** [comment]
Thanks @andreaskurth ! And thanks @h-filali for the great work on the entropy complex, I am merging this. The PR doesn't not affect the FPGA tests in any way.

**Pull request merged**
