### PR TITLE
tmp rtl update

### PR DESCRIPTION
**Pull request by jdonjdon**
cmd:
./util/dvsim/dvsim.py ./hw/ip/i2c/dv/i2c_sim_cfg.hjson -i i2c_target_stress_wr -r 1 -s 1 -w fsdb

Test sends 1 transaction with 80 bytes. I ran with PR16108 ( final -1 version)
And slow down read acq_fifo to create acq_fifo overflow.
After acq_fifo full, clock stretch doesn't happen.

### CODE REVIEW

**Comment by tjaychen** [comment]
ah i'm sorry to say, i havent pushed my clock stretch fix PR yet... once the i2c one merges
i will push it.

**Comment by tjaychen** [comment]
@jdonjdon have a look at #16249 
I tested against this PR, and i do in fact see the stretching. The test just stops after some time though, with scl/sda all idle.
I haven't checked the sequence to see if this is the intent.

**Comment by jdonjdon** [comment]
> @jdonjdon have a look at #16249 I tested against this PR, and i do in fact see the stretching. The test just stops after some time though, with scl/sda all idle. I haven't checked the sequence to see if this is the intent.

that was because my driver didn't send stop when scl is stretch. After I fix that, it looks good with #16249

**Comment by jdonjdon** [comment]
@tjaychen, I enable re-start now. With #16249 
Test fails because dut hangs while it sends ack after receiving restart-address.
image

**Pull request closed without merging**
