### PR TITLE
[entropy_src/rtl] add fatal alert

### PR DESCRIPTION
**Pull request by mwbranstad**
ERR_CODE is RO and can be tested with a register.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
LGTM

**Comment by msfschaffner** [comment]
@mwbranstad, this looks good to me, but it looks like you need to do another rebase onto a recent top-level change such that we can merge this in.

**Comment by mwbranstad** [comment]
Just noticed the branch conflict, will rebase.

**Comment by rasmus-madsen** [comment]
Looks like conflict is resolved I will rebase and merge

**Pull request merged**
