### PR TITLE
[ast] Update AST files header with auto-generated information

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Add to files header auto-generated warning:
```
//
// -------- W A R N I N G: A U T O - G E N E R A T E D  C O D E !! -------- //
// PLEASE DO NOT HAND-EDIT THIS FILE. IT HAS BEEN AUTO-GENERATED.
//

```
Signed-off-by: Jacob Levy <jacob.levy@nuvoton.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
looks great! thanks for adding!

**Comment by drewmacrae** [comment]
That just looks like a problematic fetch, I've rerun it and it seems to be behaving better.

**Comment by Jacob-Levy** [comment]
Checks passed!
Can someone approve & merge, thanks!

**Comment by Jacob-Levy** [comment]
@tjaychen  Can you please approve & merge...

**Review by tjaychen — APPROVED** [review]

**Comment by Jacob-Levy** [comment]
@tjaychen Thanks!

**Pull request merged**
