### PR TITLE
[sw] Disassemble only code sections

### PR DESCRIPTION
**Pull request by imphil**
The software build system produces a disassembly file for easier
debugging with all software. This file was produced with
`--disassemble-all`, which disassembles all sections, most of which are
rarely useful when debugging code. This commit changes the disassembler
settings to only disassemble code sections. The change speeds up a
software build on my machine by roughly 50 percent. Producing no
disassembly file at all does not speed up the build any further on my
machine.

### CODE REVIEW

**Comment by imphil** [comment]
CI times also go down considerably, giving us roughly a minute faster end-to-end builds (the SW build step is in the critical path). 

Also, GCC and clang builds are now taking an equal amount of time (roughly), so this fixes https://github.com/lowRISC/opentitan/issues/4481 as well (and is in line with the analysis done there).

Before (master):

grafik


After (this PR):
grafik

**Comment by asb** [comment]
This seems sensible to me, but it would be good to get additional confirmation that there was no particular reason to prefer `--disassemble-all` vs `--disassemble`. @tjaychen: `git blame` tells me that you added this disassembly target - are you happy with this change?

**Review by rswarbrick — APPROVED** [review]
Seems like a good idea to me. I'd generally say that if we have instructions that need disassembling that live in a section with the wrong flags, we should fix the flags.

**Comment by mcy** [comment]
I'm kind of skeptical of this change... I have found disassembly of .data and .rodata to be quite useful in the past.

Deeper question: is there a reason we're even producing these disassembly outputs, instead of letting users `objdump -hDS` at their hearts' content...?

**Comment by imphil** [comment]
> Deeper question: is there a reason we're even producing these disassembly outputs, instead of letting users objdump -hDS at their hearts' content...?

It's just a convenience feature. And as such, there's no need to cover all use cases; if you need to look at something other than what the default disassembly provides you can easily run objdump yourself.

That said, I'm fine removing the disassembly output completely. (It doesn't cost us significant build time producing the version with only `--disassemble`, though.)

**Comment by mcy** [comment]
I'd say remove it. One less thing to have to know how to build.

**Comment by tjaychen** [comment]
if we decide to remove it, could we add some updates to a doc somewhere on what's the best way to create the assembly for debugging purposes? (I for example am not sure what's the best way to do it). 

this might not be true for everyone, but i've found the disassembly useful in debugging weird processor / system bugs.  It's most useful when you get unexpected lock-ups or low power issues.

**Comment by imphil** [comment]
@tjaychen I'm fine with both removing it, or reducing it to contain only executable sections (as proposed in this PR). The goal is only to get build/CI times down, going beyond that and fully removing the disassembly is not strictly necessary to reach that goal. So it's really up to you: is a disassembly with only executable sections sufficient for your debugging? If not, I'd remove it completely and document how to get the previous disassembly back by manually running objdump.

**Comment by tjaychen** [comment]
i think that should be enough for me.
but for my personal education, i would still like to know how to get more
if necessary :)

**Comment by imphil** [comment]
Thanks for your input @tjaychen. So I left the functional change in this patch as it was (disassemble only executable sections, but continue to produce a disassembly), and added a piece of documentation showing how to use objdump to get the disassembly as we had it before.

Since the section in the documentation looked too empty I also added a short note on the use of GDB, which isn't strictly related to this PR, but is hopefully a nice addition anyways.

**Comment by tjaychen** [comment]
thank you Philipp!

**Pull request merged**
