### PR TITLE
[keymgr] keymgr updates and cleanup

### PR DESCRIPTION
**Pull request by tjaychen**
Address #4680 and #4564

### CODE REVIEW

**Comment by weicaiyang** [comment]
We should exclude binding_en in csr test. Will make a PR for this.
But the binding_en seems not right. When it's clear, it's set again in next cycle.

Screen Shot 2021-01-06 at 6 16 52 PM

Waveform: 
/edascratch/weicai-opentitan/ot/fix_binding_en/keymgr-sim-vcs/0.keymgr_csr_rw/out
verdi -ssr Verdi.ses &

**Comment by tjaychen** [comment]
it looks like init hasn't been called in your setup (init is basically
completion of the first advance call).
the way this is done is that until init happens the clearing doesn't take
permanent effect.  This is to prevent accidental self lock-out.

**Comment by weicaiyang** [comment]
> it looks like init hasn't been called in your setup (init is basically completion of the first advance call). the way this is done is that until init happens the clearing doesn't take permanent effect. This is to prevent accidental self lock-out.

I see. Thanks for the clarification.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by tjaychen** [comment]
actually let me clean this up slightly. It's kind of weird it even dips to
begin with.
I know it doesn't make a difference...but looks kind of weird.

**Comment by weicaiyang** [comment]
No sure when I closed this PR, but that's not my intention...
The update looks good to me. Thanks

**Pull request merged**
