### PR TITLE
[sival/otbn] Added test for `chip_sw_otbn_keymgr`.

### PR DESCRIPTION
**Pull request by HU90m**
Covers: https://github.com/lowRISC/opentitan/issues/20120

### CODE REVIEW

**Review by jwnrt — APPROVED** [review]

**Comment by jwnrt** [comment]
@HU90m - this is passing CI for `fpga_cw310_rom_with_fake_keys` and `fpga_cw310_test_rom`, but failing for `fpga_cw310_sival`.

The logs are:

```
I00001 ottf_main.c:154] Running sw/device/tests/keymgr_sideload_otbn_test.c
I00002 keymgr_testutils.c:120] Powered up for the second time, actuate keymgr and perform test.
I00003 keymgr_testutils.c:139] Keymgr entered Init State
I00004 keymgr_testutils.c:146] Using rom, only advancing state...
I00005 keymgr_testutils.c:151] Keymgr entered CreatorRootKey State
I00006 keymgr_testutils.c:157] Keymgr generated identity at CreatorRootKey State
I00007 keymgr_sideload_otbn_test.c:158] Keymgr entered OwnerIntKey State
I00008 keymgr_sideload_otbn_test.c:91] Keymgr generated HW output for OTBN.
I00009 keymgr_sideload_otbn_test.c:69] Starting OTBN program...
I00010 keymgr_sideload_otbn_test.c:103] Clearing the Keymgr generated sideload keys.
I00011 keymgr_sideload_otbn_test.c:69] Starting OTBN program...
E00012 otbn_testutils.c:40] CHECK-fail: OTBN is locked. Error bits: 0x00800020
E00013 keymgr_sideload_otbn_test.c:71] CHECK-STATUS-fail: Internal:["OBT",40]
I00014 status.c:34] FAIL!
```

Do we need to change some OTP setting in sival to get the OTBN unlocked? I'm personally not familiar with it.

**Comment by jwnrt** [comment]
I think those error bits are:

* A KEY_INVALID error was observed.
* An ILLEGAL_BUS_ACCESS error was observed.

from [this documentation page](https://opentitan.org/book/hw/ip/otbn/doc/registers.html#fields-7), unless I counted wrong.

**Comment by HU90m** [comment]
Only the first test case is needed for the SiVal smoke test, so I've added new target that runs a reduced version of the test for SiVal.

**Review by jwnrt — COMMENTED** [review]
Some docs on why the `TEST_SIMPLE_CASE_ONLY` variable is there would be good, maybe also its name could be changed to `SKIP_LOCKING_OTP` for clarity?

Alternatively maybe we have the test check what environment it's in and abort early?

Anyway, this updated version LGTM

**Comment by jwnrt** [comment]
Is `ILLEGAL_BUS_ACCESS` flagged in this version of the test as well? (i.e. when skipping the later test cases)?

**Pull request merged**
