### PR TITLE
[entropy_src] V2S sign-off

### PR DESCRIPTION
**Pull request by vogelpi**
This resolves https://github.com/lowRISC/opentitan/issues/16330.

### CODE REVIEW

**Comment by vogelpi** [comment]
Update: all V2S tasks are done, entropy_src is ready for sign-off :-)

**Comment by weicaiyang** [comment]
The FSM coverage is still below 90% in Wed's nightly. Are we waiting for another nightly result which may show a better number?

**Comment by vogelpi** [comment]
> The FSM coverage is still below 90% in Wed's nightly. Are we waiting for another nightly result which may show a better number?

We ran a full regression locally and @andreaskurth got the results here: https://github.com/lowRISC/opentitan/issues/16063#issuecomment-1318457489

It would be nice if you would approve the PR and we merge it once the dashboard shows the next nightly results tomorrow morning. Alternatively, it's also fine to wait for the next nightly before you approve it. I would just like to get this done before tomorrow evening your time :-)

**Review by weicaiyang — APPROVED** [review]
LGTM as long as FSM can also reach 90%+

**Comment by weicaiyang** [comment]
> > The FSM coverage is still below 90% in Wed's nightly. Are we waiting for another nightly result which may show a better number?
> 
> We ran a full regression locally and @andreaskurth got the results here: [#16063 (comment)](https://github.com/lowRISC/opentitan/issues/16063#issuecomment-1318457489)
> 
> It would be nice if you would approve the PR and we merge it once the dashboard shows the next nightly results tomorrow morning. Alternatively, it's also fine to wait for the next nightly before you approve it. I would just like to get this done before tomorrow evening your time :-)

Good to know we already saw a better FSM coverage locally, just approved.

**Comment by vogelpi** [comment]
Thanks @weicaiyang !

**Comment by msfschaffner** [comment]
Btwy, nightlies should be out shortly. So we can merge this for you @vogelpi once we double checked the results.

**Comment by msfschaffner** [comment]
Hm it looks like something went wrong here - nightlies show quite a drop in coverage:



SCORE | BLOCK | BRANCH | STATEMENT | EXPRESSION | TOGGLE | FSM | ASSERTION | COVERGROUP
-- | -- | -- | -- | -- | -- | -- | -- | --
89.24 | 96.62 | 90.78 | 97.78 | 92.15 | 38.16 | 79.31 | 91.29 | 93.20

<br class="Apple-interchange-newline">

**Comment by vogelpi** [comment]
Thanks for sharing the results, I can't see them at the moment. This doesn't look right. We'll investigate tomorrow.

**Comment by msfschaffner** [comment]
It looks like your CG and UNR fixes did not make it into this nightly batch today, so we may just have to wait another day to get the updated results. That is ok - we can merge this tomorrow.

**Review by martin-lueker — APPROVED** [review]

**Comment by martin-lueker** [comment]
Thanks @vogelpi and @andreaskurth for all your efforts on V2S!

**Comment by andreaskurth** [comment]
> Hm it looks like something went wrong here - nightlies show quite a drop in coverage:
> SCORE 	BLOCK 	BRANCH 	STATEMENT 	EXPRESSION 	TOGGLE 	FSM 	ASSERTION 	COVERGROUP
> 89.24 	96.62 	90.78 	97.78 	92.15 	38.16 	79.31 	91.29 	93.20

I remember seeing those numbers before #16421, and the revision reported in the nightlies is f76c18cba, which as @msfschaffner points out is before #16421 got merged in b6b962ac5ab60d69ba26a692403eee54d0100644. So I'm confident that the next nightlies will show the current and sufficient coverage numbers.

**Comment by andreaskurth** [comment]
> Thanks @vogelpi and @andreaskurth for all your efforts on V2S!

Thank you and your team for all your efforts before us, as well as your support of our efforts! :+1:

**Comment by vogelpi** [comment]
I am happy to have reached this goal but even more excited about the excellent collaboration. This was a great team effort across partner companies, thanks @martin-lueker , @weicaiyang , @msfschaffner , @andreaskurth and everybody else involved in this !

**Comment by msfschaffner** [comment]
From the nightlies today:
<br class="Apple-interchange-newline">
SCORE | BLOCK | BRANCH | STATEMENT | EXPRESSION | TOGGLE | FSM | ASSERTION | COVERGROUP
-- | -- | -- | -- | -- | -- | -- | -- | --
97.96 | 99.07 | 97.42 | 99.65 | 95.11 | 100.00 | 97.87 | 91.29 | 93.67
<br class="Apple-interchange-newline">

Merging!

**Pull request merged**
