### PR TITLE
[doc] Fix-up minor Hugo-isms left over in docs

### PR DESCRIPTION
**Pull request by jwnrt**
This PR:

* Removes the `{{% sectionContent %}}` Hugo macros which I believe generated an index of the chapter in the old Hugo docs. If we want this later, we can fill these pages in.
* Removes the `{#anchor}` tags from Markdown headers.

Mdbook generates anchors for headings automatically (by making the header lower-case, stripping punctuation, and using dashes for spaces).

Some of the `{#anchor}` tags match what Mdbook gives, which is great. For the others, I've grepped for links to those anchors and updated them. The link checker can't check anchors, so we can't easily see if they're correct, but they're better than they used to be.

I've also updated some doc links in a `.py` and `.c` file that came up in greps.

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
Thanks for the cleanup!

**Review by marnovandermaas — APPROVED** [review]
Thanks for making this change James, it might be good to create an issue to fill out some of these empty pages. I've told CI to re-run the failed jobs because I think the errors were unrelated timeouts.

**Review by HU90m — APPROVED** [review]
Looks good thanks

**Comment by mundaym** [comment]
Thanks @jwnrt!

**Pull request merged**
