### PR TITLE
[aes/rtl] Overlap state register clearing with unmasking final output

### PR DESCRIPTION
**Pull request by vogelpi**
Previously, the state register clearing has always been performed in the same cycle in which also the final output register was written. This is perfectly suitable for unmasked implementations or when using fully combinational S-Boxes e.g. masked Canright.

However, DOM S-Boxes take multiple clock cycles to evaluate and provide valid output in the fifth clock cycle. This output then propgates through the rest of the cipher core and is ultimately forwarded to the output registers/mode logic (both unmasked). To cover potential SCA leakage related to this unmasking, the state register should be cleared with PRD simultaneously to the unmasking (happening before the clock edge). The write enable needs thus to be asserted one clock cycle earlier, i.e., in the fourth cycle.

### CODE REVIEW

**Comment by tjaychen** [comment]
@vogelpi just so i understand, is the idea here that before you populate with the unmasked value, you first fill it with pseudo-random values?

**Comment by vogelpi** [comment]
Hey @tjaychen,
not exactly. The problematic leakage in this case doesn't come from writing the register (it still contains the previous output, so the leakage is HD(previous output, new output) which isn't too bad.

I suspect the critical leakage is coming from unmasking the output of the cipher core BEFORE writing the register. More precisely, to not allow the extraction of intermediate results, the output of the cipher core is tied to 0 with a couple of AND gates unless the output is valid. Now this means that if the output becomes valid, these AND gates will produce some leakage HW(new output).

Previously, we probably didn't observe this leakage because we had more noise in the system. I started noticing it when doing area optimizations. To fight the problem, I see two options:
1. Cover this leakage in noise: this is the approach of this PR. We shift another operation producing lots of noise to overlap it with that leakage.
2. Remove the AND gates with a proper MUX and output e.g. the pseudo-random data used for clearing whenever the output is not valid. Then the leakage will be random instead of HW(new output). This is probably safer and I think I should change this PR.

**Comment by vogelpi** [comment]
Update: now added a commit to this PR to also implement Option 2.

**Comment by vogelpi** [comment]
The first commit is not strictly required with the second. Thus, I've factored out the second commit into a separate PR #9909 and I am closing this PR.

**Pull request closed without merging**
