### PR TITLE
[site,doc] Fixup bad links to comportability spec

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**

### CODE REVIEW

**Review by marnovandermaas — APPROVED** [review]
LGTM, thanks! I'll try rerrunning CI.

**Review by marnovandermaas — CHANGES_REQUESTED** [review]
Do we need to fix this from CI?
```
Starting: Check CMDGEN Blocks
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.214.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
ci/scripts/check-cmdgen.sh
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/99541db1-d037-4930-902c-8deab2f4f4dd.sh
INFO:__main__:util/tlgen/README.md:L56: `util/selfdoc.py tlgen` output the following error messages:
ERROR:root:['list of group', 'comma separated group of key:value enclosed in `{}` the second entry of the list is the sub group format']
ERROR:root:['list of group', 'comma separated group of key:value enclosed in `{}` the second entry of the list is the sub group format']

INFO:__main__:hw/ip/aes/doc/interfaces.md:L2: Generated content needs updating.
##[error]Documentation generated using CMDGEN blocks is not up to date.
Update blocks with: ./util/cmdgen.py -u '**/*.md'
##[error]Bash exited with code '1'.
Finishing: Check CMDGEN Blocks
```

**Comment by hcallahan-lowrisc** [comment]
> Do we need to fix this from CI?

Yep, this is CMDGEN working as intended! Pushed a new commit.

@HU90m The two lines beginning with `ERROR:root:` seem to be unhelpful, could that error be squashed?

**Comment by HU90m** [comment]
> The two lines beginning with ERROR:root: seem to be unhelpful, could that error be squashed?

I would feel uncomfortable covering up `stderr` output from commands run by CMDGEN. But yes it would definitely be nice to get rid of the error message. Sorry I haven't found time to track down the cause of this error.

Could open an issue?

**Review by HU90m — APPROVED** [review]
Looks great thanks

**Review by marnovandermaas — APPROVED** [review]
Ok, thanks for clarifying the CI issue.

**Comment by hcallahan-lowrisc** [comment]
Kokoro failure unrelated.

**Pull request merged**
