### PR TITLE
[otp_ctrl] Waive some spurious UNSIGNED/CMPCONST verilator warnings

### PR DESCRIPTION
**Pull request by rswarbrick**
Sadly, the warnings don't have any keywords in their text to let us
waive them more precisely.

### CODE REVIEW

**Comment by rswarbrick** [comment]
@msfschaffner: The CMPCONST warnings come from this code:
```systemverilog
  assign otp_enc_key_mux      = (sel_i <= LastScrmblKey) ? RndCnstKey[scrmbl_key_sel] : '0;
  assign otp_dec_key_mux      = (sel_i <= LastScrmblKey) ? otp_dec_key_lut[scrmbl_key_sel] : '0;
  assign otp_digest_const_mux = (sel_i <= LastDigestSet) ? RndCnstDigestConst[digest_set_sel] : '0;
  assign otp_digest_iv_mux    = (sel_i <= LastDigestSet) ? RndCnstDigestIV[digest_set_sel] : '0;
```
We *could* just drop the `<=` checks entirely, since we hopefully don't care about the value of e.g. `otp_enc_key_mux` when `scrmbl_key_sel` is out of range. Have you considered doing that?

**Comment by msfschaffner** [comment]
That is a possibility, but unfortunately that may give rise to X'es in the design.
Another way would be to pad the arrays being indexed to powers of 2.
Let me take a look at that real quick.

**Comment by rswarbrick** [comment]
I guess my point is that these X's shouldn't ever propagate out of the module, so it shouldn't matter, right?

**Comment by msfschaffner** [comment]
It does matter since it can produce LEC issues down the road. 
The style recommendation is to explicitly avoid that by making sure out of bound indexing operations cannot take place.

In this particular case, it is possible for `sel_i` to be out of bounds in at least one of the arrays, since not all of them have the same length.

**Comment by msfschaffner** [comment]
I PR'ed an RTL fix for this to your PR ;): https://github.com/rswarbrick/opentitan/pull/2

**Comment by rswarbrick** [comment]
> It does matter since it can produce LEC issues down the road.

Oh, I see. I assumed LEC tools were clever enough not to care about some of these internal signals, but apparently not :-) Thanks for the follow-up patch. I'll add it to this PR without squashing: I think the history is probably clearer that way.

**Comment by rswarbrick** [comment]
Hmm: reviewing is a bit tricky here. I've looked at your follow-up and think it looks good. If you're happy with the first one, approve the PR and let's merge :-)

**Review by msfschaffner — APPROVED** [review]

**Pull request merged**
