### PR TITLE
[otbn] Auto-generate decode information in ISA

### PR DESCRIPTION
**Pull request by rswarbrick**
Remove the (slightly bit-rotted) manual decode information and
automatically generate the relevant information in the operand tables.
The results look like

ADD's grd operand:

    insn[11:7]

ANDI's imm operand:

    sign_extend(insn[31:20])

SW's offset operand:

    sign_extend({insn[31:25],insn[11:7]})

BEQ's offset operand:

    sign_extend(PC + {insn[31],insn[7],insn[30:25],insn[11:8],1'b0})

LOOP's bodysize operand:

    insn[31:20] + 1

The big YAML changes are removing the decode blocks and renaming the
variables in the "operation" pseudo-code to match the operand names.

Signed-off-by: Rupert Swarbrick <rswarbrick@lowrisc.org>

### CODE REVIEW

**Comment by rswarbrick** [comment]
For anyone mildly interested who doesn't want to check out the PR and build the docs, here are a couple of screenshots of the resulting operand tables:

A simple example:

ss

Behold, RISC-V's jump offset encoding:

ss

And here's what the +1 offset in LOOP looks like:

ss

**Comment by imphil** [comment]
Thanks Rupert for working on this, I had a closer look at the output (not really at the implementation). 

With this change, we're establishing that the "assembly symbol" (as named in the table) is also the variable to operate on in the "Operation" section. That's fine with me. However: we should be very clear on what this variable now contains, and ideally, what data type it has. 

To motivate that statement, let's look at some user stories for the information in the ISA Manual:

1. As an OTBN assembly programmer I want to know what valid assembly syntax I can use.

2. As an OTBN assembly programmer I want to understand how a particular line of assembly executes.

3. As hardware implementer I want to know how to decode an instruction into its components (to execute it according to the documentation).

4. As a toolchain engineer I want to know how to encode a line of assembly into an instruction.

5. As a toolchain engineer, I want to know how to decode an instruction into its canonical assembly form.


With those user stories in mind, let's see how we get that information from the documentation:

1. To get the valid assembly syntax, the developer looks at the ISA doc, finds the assembly template there, and permitted values for all assembly symbols in the table. Nice, job done.

2. To understand how a line of assembly executes the developer looks up the instruction and the operation section, and needs to map the assembly symbols (as written in the line of assembly) to the  variables used in the operation section of the doc. In this PR, the assumption is that the "Operaton" section uses the assembly symbols and their allowed values. That's currently harder than it needs to due to missing type and width information on the "assembly symbols". (This information can be guessed by looking at the encoding.)

3. To execute an instruction in hardware, the relevant information is now found by reading the Assembly symbol/description table from the back and using the "Decoded as" sentence.

4. To encode an instruction, one essentially needs to reverse-read the "decoded as" section in the "Assembly symbol/Description" table.

5. To do a disassembler a developer currently needs to to through the individual instructions. We should currently have no cases where disassembling could be disambiguous, except for pseudo-instructions. This question isn't really in scope for this PR, I filed https://github.com/lowRISC/opentitan/issues/4871 to track it.

My take-aways:

* We need to make add type information (including width) to the variables we use in the operation section.

* The encoding table is now a nice add-on, but not essential information any more. We could make it "more essential" again by using the variables in that table also in the "Decoded as" sentence. Not sure if that's actually an improvement, though.

* I find the "Decoded as" naming odd/confusing. Reading the table in full, it would e.g. read as "grs2 is decoded as insn[24:20]". But in my mind, going from the (assembly) symobl to bits in the instruction is called "encoding", so it should read "grs2 is encoded as insn[24:20]". This doesn't work well for the "composite" cases, e.g. where we have currently "offset is decoded as sign_extend({insn[11:9],insn[31:25],5'b0})". Maybe just make it "Decoded from ..."? Or a separate column (probably that'll take too much horizontal space)?

**Comment by rswarbrick** [comment]
Force-push addresses some of Philipps comments (we had a long chat on the phone afterwards to come up with something sensible!). We now add a note above the operation section to warn readers that enums / options will appear with their integer values. It looks like this:

ss

We also name the bit ranges that appear in the encoding table, correcting an error when the value was pc-relative or had a constant offset, and making things a bit easier to read. The last patch in the series allows this name to be shorter than the full operand name. For example:

ss

Note that `flag_group` and `shift_bits` have shortened names in the bottom table.

**Comment by GregAC** [comment]
This is looking good, I've got a couple of comments:

1. Could we do anything to make it clearer negative numbers are 2s complement encoded and have 0 offset unless explicitly said? Perhaps we can just add this as a note at the top of the document
2. I think the documentation generated for pc relative operands is a little confusing, e.g. for branch instructions it states:
   > Decode as sign_extend(PC + {OFF_3,OFF_2,OFF_1,OFF_0,1'b0})

   This is to decode to give the field 'offset' but if we've added the PC as part of the decode process it's no longer an offset.

   Then for JALR where we also have an offset but this time added to a register it doesn't mention the addition required in the decode at all.

   Perhaps we switch these field names to `pc_offset` and note it's a PC relative offset somewhere? Then the decode table itself would simply say:
  
   > Decode as sign_extend({OFF_3,OFF_2,OFF_1,OFF_0,1'b0})

**Comment by rswarbrick** [comment]
> Could we do anything to make it clearer negative numbers are 2s complement encoded and have 0 offset unless explicitly said? Perhaps we can just add this as a note at the top of the document

Good point about adding a heading. I'll do so, which also gives a neat place to explain what the capitals etc. mean. I'm not sure what you mean by a zero offset? Any offset like that for loop's `bodysize` operand appears explicitly.

About the offset question: Firstly, JALR looks different from JAL because it is different: the target address for JALR is `grd + offset`, and doesn't depend on current PC.

About the weird fact that "offset" becomes an absolute address: yes, you're right. The `offset` operand name comes from the RISC-V spec. There, they sort of cheat by just explaining everything in sentences. Maybe we should change the operand name to something like `target`, which I think would be much more accurate (it's written as `.+0x100`, not `0x100`, in the source code). That probably belongs in a different PR, though. (@imphil: Are you happy with this proposed change?)

**Comment by GregAC** [comment]
> I'm not sure what you mean by a zero offset?

As in the range available is the natural one you'd expect, e.g. if you have 4 bits you get range -8, ... , 7 unless there's a specific offset.

> Firstly, JALR looks different from JAL because it is different: the target address for JALR is grd + offset, and doesn't depend on current PC.

I brought up JALR as like the branch instruction and JAL it has an offset which it applies to some absolute value to give the target, for branch/JAL this is the PC for JALR it's a register. It just felt a little inconsistent that the absolute value is added is explicitly added to the offset in the decode for branches/JAL but not in JALR.

> Maybe we should change the operand name to something like target, which I think would be much more accurate (it's written as .+0x100, not 0x100, in the source code). That probably belongs in a different PR, though. (@imphil: Are you happy with this proposed change?)

I'd be happy with this approach, would the intent to be to leave JALR with an offset operand or also switch that to target?

**Comment by rswarbrick** [comment]
I've just rebased and added a patch to give a header at the top of the document.

Re zero offsets: Yes, the range is the one you'd expect, unless it says otherwise. And the operand table also gives the valid range explicitly. Is there something you think is missing?

For the "offset rename" question: we'd leave the JALR operand unchanged, since it is an offset added to `grs1` rather than an address that's encoded PC-relative. (This is presumably all an artifact of the fact that RISC-V doesn't distinguish between "the thing you write in your assembly code" and "the value that the processor operates on". Clearly, life would make more sense if the operand was an offset and got added to PC by the processor. The problem is that an assembly file wants to contain things like `JAL x0, foo` rather than `JAL x0, foo-.` and the RISC-V ISA would like to say "offset = foo".)

**Review by imphil — APPROVED** [review]
This PR is a great improvement to the OTBN docs, thanks a lot Rupert for your persistence! I stared at the current version for a while and found only minor things that could potentially be improved. Feel free to disregard things from the list below that you don't agree with, or that don't work out.

* How about adding a space when concatenating variables, e.g. `sign_extend({OFF_1,OFF_0})` -> `sign_extend({OFF_1, OFF_0})`
* On `offset` in branches/jumps: We currently specify "Valid range: .-4096 to .+4094 in steps of 2", which is assembly syntax. At the same time, we want users to know what values the `offset` variable could contain when it is used in the operation section (and there it's just a number without the dot). So maybe we can modify that line to read something like "Valid range: -4096 to +4094 in steps of 2. In assembly, add a dot (`.`) in front of the offset, e.g. `.-4096`"
* My mind still finds the "Decode as GRD" line slightly odd, but it reads OK to me when it's something like "Decode as sign_extend(OFFSET)". So maybe we could go for something like `Decode as GRD` -> `Decode as zero_extend(GRD)`? Not sure though and certainly not a blocker. This could also improve the LOOP case, where "Decode as SZ + 1" would become "Decode as zero_extend(SZ) + 1`, making it clear that we're operating on numbers with no wrapping, etc.
* In the table Syntax | Operation value where we map assembly syntax to values, e.g. in `BN.ADD`, can we rename "Syntax" to "Assembly syntax"?
* In a similar fashion, maybe we can rename "Assembly symbol" to "Symbol", since that symbol is used in the operation table as well.
* We seem to have a reasonable amount of horizontal space available, maybe we can put the "Decode as" content in a separate column?

**Comment by rswarbrick** [comment]
> How about adding a space when concatenating variables, e.g. sign_extend({OFF_1,OFF_0}) -> sign_extend({OFF_1, OFF_0})

Good point. I removed it when the pieces were still the full operand name because the formulas were getting ridiculously long, but the "short form" names should fix that.

> So maybe we can modify that line to read something like "Valid range: -4096 to +4094 in steps of 2. In assembly, add a dot (.) in front of the offset, e.g. .-4096"

Good idea about how to describe PC-relative operands. I've done what you suggested, which I think is better. It still feels a little ungainly, though. We should probably squint at it a bit more after this PR has landed.

> My mind still finds the "Decode as GRD" line slightly odd, but it reads OK to me when it's something like "Decode as sign_extend(OFFSET)". So maybe we could go for something like Decode as GRD -> Decode as zero_extend(GRD)?

Good point. I'm going to use `unsigned` and `signed` (and get rid of `sign_extend`), which should be equally clear but is a bit shorter. There was also a slight mistake before, where we had things like `sign_extend(PC + FOO)` instead of `PC + sign_extend(FOO)`: I've fixed that too.

> In the table Syntax | Operation value where we map assembly syntax to values, e.g. in BN.ADD, can we rename "Syntax" to "Assembly syntax"?

:+1: In fact, I've renamed the headers to "Assembly syntax" and (just) "Value", since this is the only value that's being mentioned. Hopefully a lot clearer and still short.

> In a similar fashion, maybe we can rename "Assembly symbol" to "Symbol", since that symbol is used in the operation table as well.

:+1: Actually, I've gone with just "Operand", since that's what we're naming.

> We seem to have a reasonable amount of horizontal space available, maybe we can put the "Decode as" content in a separate column?

Hmm, maybe. I'm slightly leaning the other way: to remove the table and turn it into a list. I think that might allow slightly better information density. Let's revisit that in a later PR?

**Comment by rswarbrick** [comment]
Here's the resulting layout:

ss

**Pull request merged**
