### PR TITLE
[otp_ctrl/doc] Add documentation regarding re-parameterization after D3/V3

### PR DESCRIPTION
**Pull request by msfschaffner**
This addresses one of the cleanup items in https://github.com/lowRISC/opentitan/issues/13438.

Let me know if you think this should be moved to a different section in the spec.

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
do you think your description here sort applies to blocks in general? I'm wondering if it makes sense to have this as a common blurb somewhere that other blocks can simply link to. 

What do you think? In addition to calling out the common point about V3 needing requalification, you can point out specific parameters of concern.

**Comment by msfschaffner** [comment]
That probably makes sense, yes.

How about we add a D3 checklist item with the following description?
```
### DOC_PARAM_IP

If not otherwise stated in the comportable IP specification, all instantiation parameter combinations are considered legal and do not impact D3/V3 status.
If an IP supports only a subset of parameterizations, it must explicitly document the supported parameterizations in a section called "Parameter Changes after D3/V3" in the design specification.
```

**Comment by tjaychen** [comment]
> That probably makes sense, yes.
> 
> How about we add a D3 checklist item with the following description?
> 
> ```
> ### DOC_PARAM_IP
> 
> If not otherwise stated in the comportable IP specification, all instantiation parameter combinations are considered legal and do not impact D3/V3 status.
> If an IP supports only a subset of parameterizations, it must explicitly document the supported parameterizations in a section called "Parameter Changes after D3/V3" in the design specification.
> ```

that sounds good to me.

**Review by cindychip — APPROVED** [review]

**Comment by msfschaffner** [comment]
I have moved the paragraph a bit further up in the spec into the Hardware Interfaces section where the instantiation parameters are declared.

I will also separately propose the addition to the D3 checklist as discussed above.

**Pull request merged**
