### PR TITLE
CI TESTING - Stdout logging for vivado synth

### PR DESCRIPTION
**Pull request by GregAC**
DO NOT MERGE

Signed-off-by: Greg Chadwick <gac@lowrisc.org>

### CODE REVIEW

**Comment by vogelpi** [comment]
Thanks for trying this out @GregAC. This is useful and I think we should merge it. What is your view @imphil ?

**Comment by GregAC** [comment]
The actual change needed is an edalize change. I've had the change merged into edalize upstream. We just need to decide how we use it (what edalize we point to from python_requirements.txt), two options really:

1. Continue using our `ot` branch in our edalize fork (https://github.com/lowRISC/edalize). Currently everything in `ot` is merged into edalize upstream so it'd just be an edalize release (say the latest v0.2.5) with my patch cherry-picked on top
2. Point directly to a specific edalize commit (this one https://github.com/olofk/edalize/commit/6c4c610442045847a9d4478e159048a9f68a9b4a)

I'd be in favour of 2. no point maintaining a fork if everything we need is in upstream. Of course we'll need to do a little testing to ensure the commit I suggested hasn't broken any of our flows.

@rswarbrick, @imphil were discussing this via email, let's conclude the discussion here.

**Comment by GregAC** [comment]
Just tried out using the latest edalize and sadly it's not that simple. We're also use a fusesoc fork which doesn't seem to work with the latest edalize and rebasing our fusesoc on top of the latest fusesoc isn't straight-forward (to me at least, as I don't know fusesoc internals or understand the nature of our changes).

So short term to get this to work I just add my change to our current edalize `ot` branch. However we should get our fusesoc fork rebased on a more recent version.

**Comment by imphil** [comment]
> Just tried out using the latest edalize and sadly it's not that simple. We're also use a fusesoc fork which doesn't seem to work with the latest edalize and rebasing our fusesoc on top of the latest fusesoc isn't straight-forward (to me at least, as I don't know fusesoc internals or understand the nature of our changes).

It's on my list to get closer to FuseSoC upstream again, but it's a bit of a larger project due to the way we generate primitives. I'll increase the priority on it :-)

Until then, cherry-picking the specific patch should do.

(Or we just keep things as they are, the synthesis output is already visible in CI, just not on stdout.)

**Comment by GregAC** [comment]
> (Or we just keep things as they are, the synthesis output is already visible in CI, just not on stdout.)

True, but it's been handy to have the time-stamps when diagnosing issues with long CI times which you don't get with the current log output post build.

I think I'll just cherry-pick my change on top of the ot edalize branch for now.

**Comment by imphil** [comment]
> I think I'll just cherry-pick my change on top of the ot edalize branch for now.

Sounds good, thanks!

**Comment by GregAC** [comment]
Ok `ot` branch updated to include the change (it's identical to the `ot_test` branch I used for this PR).

No OT changes needed, we should get synthesis logs on stdout for all CI runs now.

**Comment by vogelpi** [comment]
Thanks @GregAC !

**Pull request closed without merging**
