### PR TITLE
[dv] Update V2S checklist

### PR DESCRIPTION
**Pull request by weicaiyang**
Add an item - SIM_COVERAGE_REVIEWED
Also clean up some TODO

Once this is in, will make an PR to update each checklist in IPs
Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by rswarbrick** [comment]
This looks fine, but (as @msfschaffner pointed out in the Google Doc) it should probably go through the TC. Can this wait until next Friday?

**Comment by weicaiyang** [comment]
> This looks fine, but (as @msfschaffner pointed out in the Google Doc) it should probably go through the TC. Can this wait until next Friday?

Make sense. Let's wait until that one is approved.

**Comment by msfschaffner** [comment]
@weicaiyang can you open an issue for the RFC and add the label RFC:Proposal (and add the issue number to the Gdoc)?

**Comment by weicaiyang** [comment]
> @weicaiyang can you open an issue for the RFC and add the label RFC:Proposal (and add the issue number to the Gdoc)?

Done, created a issue https://github.com/lowRISC/opentitan/issues/11090 and added to the gdoc

**Comment by weicaiyang** [comment]
Updated as this [doc](https://docs.google.com/document/d/150V62yLZPwyPYgPIzpIPYsId3-TrhPK86i-9oAtRcjA/edit#). PTAL

**Review by msfschaffner — APPROVED** [review]
LGTM

**Comment by cdgori** [comment]
I had a quick look at the gdoc - LGTM

**Pull request merged**
