### PR TITLE
PWM V1 sign-off

### PR DESCRIPTION
**Pull request by rasmus-madsen**
this PR contains a commit to move PWM to V1 and add it to the nightly regression.
it also addresses the few comments in 
https://docs.google.com/document/d/1KAMccGRvX0Jms6P50PFkE7DlqfkVrDCuLugoknxXBKA/edit#heading=h.xkag959c5d75

lastly it fixes a few compile issues that came to surface with VCS

### CODE REVIEW

**Comment by weicaiyang** [comment]
@rasmus-madsen can you also add this coverpoint?
> Add a coverpoint for changing configuration when the channel is running.

can @martin-lueker clarify this in the design spec as discussed in the V1 meeting? 
> In design spec, we should specify what PWM clock range is.

**Comment by rasmus-madsen** [comment]
@weicaiyang thank you for the review.
I have updated the testplan with the missing covergroup.
the item for the specification is requested in this issue #9999

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks

**Review by martin-lueker — APPROVED** [review]
LGTM. Rasmus I'll fill out #9999.

**Pull request merged**
