### PR TITLE
[util/topgen] Update alert lpg generation

### PR DESCRIPTION
**Pull request by tjaychen**
- fixes https://github.com/lowRISC/opentitan/issues/14954

The alert lpg generation currently uses the clock group, clock domain
and power domain of a particular clock to uniquely identify lpg groups.

As a result, it lumps all the transactional clocks of the same domains
into one group.  This behavior however is not correct, as the
transactional clocks are unique and can be individually gated.

This commit updates the lpg generation to take this into account.

### CODE REVIEW

**Comment by cindychip** [comment]
@tjaychen I rerun @bilgiday 's test, did not see this error anymore, thanks!

**Review by cindychip — APPROVED** [review]
Looks great! thanks Tim

**Comment by tjaychen** [comment]
thanks @cindychip for checking.

**Review by msfschaffner — COMMENTED** [review]
A bit late, but LGTM! Thanks for fixing this.

**Pull request merged**
