### PR TITLE
[sw, tests]: Update entropy complex enablement in ast_clk_rst_inputs.c

### PR DESCRIPTION
**Pull request by walaahattab**
Adjust the disablement of EDN module in accordance with the [programmers_guide](https://opentitan.org/book/hw/ip/edn/doc/programmers_guide.html).

### CODE REVIEW

**Comment by walaahattab** [comment]
CC: @sha-ron

**Review by HU90m — APPROVED** [review]

**Review by h-filali — APPROVED** [review]
Thanks for updating this! Once the CI passes this LGTM.
Could you maybe squash the lint fix commits into the initial commit?

**Review by andreaskurth — COMMENTED** [review]
Thanks @walaahattab, the change LGTM but please squash all commits into the first one (see our [contribution guide](https://opentitan.org/book/doc/contributing/detailed_contribution_guide/index.html#do-we-rebase-and-merge-or-squash-multiple-commits-into-a-single-one) for more info).

One way to do this is `git rebase -i 7f6e574bb^` (i.e., the hash of the first commit plus a `^` to say that you want to rebase on top of the commit before that), then change the `pick` for the bottom three commits to `fixup`, save and exit, then `git push --force`.

**Comment by andreaskurth** [comment]
Just ran `util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_ast_clk_rst_inputs` locally on this PR, and it passed 3/3 runs.

**Review by andreaskurth — APPROVED** [review]

**Pull request merged**
