### PR TITLE
[util] Automatically generate rstmgr exclusion

### PR DESCRIPTION
**Pull request by tjaychen**
- Automatically exclude resets that are not used at the top level.

- Should address #15426

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
hey all, i don't really know if i'm doing this right, so please have a look and let me know.

**Comment by matutem** [comment]
My preference is to use "cover*.cfg" files rather than ".el" files for these sorts of exclusions. These files are tool-specific (just like *.el files are). One example is at  hw/top_earlgrey/dv/cov/chip_cover_reg_top.cfg, except for your purpose you would need to do "-node <net name>", where - means ignore coverage.

**Comment by sriyerg** [comment]
> My preference is to use "cover*.cfg" files rather than ".el" files for these sorts of exclusions. These files are tool-specific (just like *.el files are). One example is at hw/top_earlgrey/dv/cov/chip_cover_reg_top.cfg, except for your purpose you would need to do "-node ", where - means ignore coverage.

I am working on adding a `constfile` that can be added to the coverage collection via `-cm_constfile` switch. I feel like that will be even better than a `-cm_hier` cfg file, since it allows VCS to do constant propagation analysis and automatically mark the fanouts of these as unreachable.

**Comment by tjaychen** [comment]
sounds good @sriyerg .
do you want me to wait on that for now? I can follow whatever format you think makes sense and add to it.

**Comment by sriyerg** [comment]
> sounds good @sriyerg . do you want me to wait on that for now? I can follow whatever format you think makes sense and add to it.

Yes please!

**Comment by matutem** [comment]
We talked about having these exclusions get placed in .cfg rather than .el files: .el files generally tag each exclusion wiith CHECKSUM and ANNOTATION. It is not clear they are indispensable or if the exclusion will work if they are not present. In .cfg files the syntax is "-node <node name>", and no additional tagging is needed.

**Comment by sriyerg** [comment]
> sounds good @sriyerg . do you want me to wait on that for now? I can follow whatever format you think makes sense and add to it.

VCS unfortunately does not support MDAs in constfiles (I added you to an email thread with SNPS AE). Since `resets_o` is an MDA (struct), we will not be able to use this approach. We will need to go with @matutem's suggestion instead, and have these implemented in a `-cm_hier` coverage hierarchy file. Here's an example:
https://github.com/lowRISC/opentitan/blob/d2dce395b2128e5acc40fa772cfd565e4754c82a/hw/top_earlgrey/dv/autogen/xbar_tgl_excl.cfg#L9

**Comment by tjaychen** [comment]
sorry this has taken awhile.
@sriyerg / @matutem can you let me know if i did this right?

**Review by sriyerg — APPROVED** [review]

**Comment by sriyerg** [comment]
You can verify if this was done correctly by running a smoke regr with coverage:
```
$ util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i smoke --cov
```
and check the generated report located at  `/path/to/scratch/<branch>/chip_earlgrey_asic-sim-vcs/cov_report/dashboard.html`.

**Comment by tjaychen** [comment]
ah sounds good, i did run that sim, but didnt really know what ot check, let me try that.

**Comment by tjaychen** [comment]
merging! thanks for the reviews all.

**Pull request merged**
