### PR TITLE
[prim_multibit_sync] Add multibit synchronizer primitive with consistency check

### PR DESCRIPTION
**Pull request by msfschaffner**
This adds a multibit synchronizer primitive with data consistency check.

This can be used for instance to synchronize the redundantly encoded life cycle enable signals to different clock domains.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by eunchan** [comment]
I assume the data won't change fast enough to meet this consistency check. Then, I personally prefer the handshake synchronizer which doesn't have to have 2flops for sync + 2 flos for consistency check per bit. The handshake cdc only needs one flop at the receiver clock domain but the enable signal (one bit) needs to cross the domain.

**Comment by tjaychen** [comment]
ah we should probably clarify the purpose of this module.
I think this module is indeed not how we would normally do cdc, it's meant
specifically for the "critical signal" broadcast where we don't want to
rely on control signals (because that potentially can become a single point
of failure).
Michael is that what you had in mind? If so we should probably describe
that clearly in the header and recommend users to use the more conventional
schemes otherwise.

**Comment by cdgori** [comment]
> ah we should probably clarify the purpose of this module. I think this module is indeed not how we would normally do cdc, it's meant specifically for the "critical signal" broadcast where we don't want to rely on control signals (because that potentially can become a single point of failure). Michael is that what you had in mind? If so we should probably describe that clearly in the header and recommend users to use the more conventional schemes otherwise.

yes, this is basically a loaded gun pointed right at someone's foot in terms of ways to fail at CDC, so let's be really careful about how we comment/describe the intended usage of this prim.

**Comment by msfschaffner** [comment]
Ah yeah I should have clarified this more. This is meant to be used for the multibit life cycle signals, where I assumed that we do not want to introduce a full handshake to synchronize this over for the point you raised, Tim.

I made it a general prim for reusability, but in hindsight this may not have been the best idea... shall we make this LC specific by naming it `prim_lc_tx_sync`, and using life cycle-related structs as I/Os?

Also, do we think this synchronization mechanism is fine for LC (I was thinking to use 2 checkers), or do we want to use a different consistency check?

**Comment by msfschaffner** [comment]
Ah I now see that we initially wanted to go even further and add (optional) capabilities to trigger alerts if the synchronization fails.

NEW  Secure Transmit _ Decode

Let me go over this again and add a proper hysteresis handler as initially proposed.

**Comment by tjaychen** [comment]
ah Michael, the original thing I did was probably overkill.  I can't really
remember... but the essence of it is very similar to what you showed.
I don't think it's a bad thing to leave it as a prim, because i'm sure we
will find uses for this outside of life cycle. I think we just need to
plaster it warnings to only use this if you know why.  Because otherwise
CDC tools are going to freak out.

**Comment by msfschaffner** [comment]
yeah I think the only thing that is really different with respect to what you had is the timeout and alert behavior. 

ok in that case, let me add a big warning to the description.

**Comment by msfschaffner** [comment]
I have added the following to the header:

```
//
// WARNING: DO NOT USE THIS MODULE IF YOU DO NOT HAVE A GOOD REASON TO DO SO.
//
// This module is only meant to be used in special cases where a handshake synchronizer
// is not viable (this is for instance the case for the multibit life cycle signals).
// For handshake-based synchronization, consider using prim_sync_reqack.
//
[...]
// Note: CDC tools will likely flag this module due to re-convergent logic.
```

WDYT?

**Comment by tjaychen** [comment]
LGTM!

**Review by tjaychen — APPROVED** [review]

**Comment by msfschaffner** [comment]
Thanks for the reviews! Merging...

**Pull request merged**
