### PR TITLE
Add the project name to the copyright header

### PR DESCRIPTION
**Pull request by mundaym**
This change was generated by editing `quality/BUILD.bazel` with the desired change and then running the following command:

```
./bazelisk.sh run //quality:license_check --test_output=streamed | \
        sed '1,/Failed:/d' | \
        xargs sed -i '0,/Copyright lowRISC contributors\./s//Copyright lowRISC contributors (OpenTitan project)./'
```

### CODE REVIEW

**Review by GregAC — APPROVED** [review]
I presume this PR will gain an extra commit that actually does the change? Or due to the size of it is the plan merge this (skipping CI) and then push directly to master with the header change commit by someone who can directly push to the master branch?

**Comment by mundaym** [comment]
@GregAC that was just me forgetting to add the changes when I last force pushed. The changes should be complete now.

**Comment by mundaym** [comment]
@andreaskurth this won't ever pass CI due to lint failures. Please feel free to merge if you are happy with the PR and think now is a good time to absorb this change.

**Comment by vogelpi** [comment]
Thanks for the PR @mundaym . @andreaskurth and I have discussed to merge this later today after fixing the whitespace and Python lint errors. I've now taken care of this and rebased the PR on master.

**Comment by vogelpi** [comment]
Please don't merge this yet. There are more occurrences of the old header and I am working my way through those right now.

**Comment by vogelpi** [comment]
CI passed after adjusting any other occurrences of the old copyright headers except from vendored in code and I've merged this now.

**Pull request merged**
