### PR TITLE
Update Verible to latest upstream

### PR DESCRIPTION
**Pull request by imphil**
Verible is providing lint and formatting tooling and is evolving
rapidly in response to OpenTitan requirements.

It is an optional productivity tool; developers are recommended to have
it installed to run lint and early/experimental formatting on their own
machine. Lint is also done in CI.

Update Verible to the latest upstream version to unblock other work,
e.g. #4613 and to include recent lint improvements.

### CODE REVIEW

**Comment by imphil** [comment]
The UART commit is only in here to get a green CI, I'll expect reviews and merging in https://github.com/lowRISC/opentitan/pull/6436.

**Comment by imphil** [comment]
@msfschaffner If you're OK with this change, can you update the version on the machine you're doing the nightly reports on (before we merge this PR)?

**Comment by martin-lueker** [comment]
Question: Does the "getting starting" documentation now get auto-generated from these files, or do we need to put something there as well?

**Comment by imphil** [comment]
@martin-lueker Yes, the tool version numbers in our documentation are generated from data in tool_requirements.py:

https://github.com/lowRISC/opentitan/blob/165ddec05a4d2795fee832aac580ff281308d1d7/doc/ug/install_instructions/index.md#L57

**Review by martin-lueker — APPROVED** [review]
Great Thanks @imphil.  LGTM.  
Also, I gave it the new version on both my personal machine and made a module for our compute server, it works in both places.  I'll be looking forward to seeing what we can do with Henner's latest formatter changes.

**Comment by msfschaffner** [comment]
@eunchan is currently running the lint cronjob (since I was out on vacation). 
@eunchan can you update the Verible installation locally such that this can move forward?

**Review by msfschaffner — APPROVED** [review]
LGTM, but let's wait for @eunchan before merging

**Comment by imphil** [comment]
Great, thanks!

**Pull request merged**
