### PR TITLE
[AST] Fix Oscillators models instability

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Signed-off-by: Jacob Levy <jacob.levy@nuvoton.com>

### CODE REVIEW

**Comment by Jacob-Levy** [comment]
Initialized the free running oscillator to start at '0' for the first half of the period.

**Comment by Jacob-Levy** [comment]
Updated 2 AST files from "[clkmgr] Address several d2s items. #11094" PR.

**Comment by Jacob-Levy** [comment]
CI(private) passed locally.

```
          [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]  
00:14:42  [    build    ]: [Q: 000, D: 000, P: 044, F: 000, K: 000, T: 044] 100% 
00:41:49  [     run     ]: [Q: 000, D: 000, P: 115, F: 000, K: 000, T: 115] 100% 
```
Rebase & push.

**Comment by tjaychen** [comment]
thanks for the quick fix @Jacob-Levy 
@matutem 

any objections to me merging once CI passes?

**Pull request merged**
