### PR TITLE
[RV_DM]JTAG_dtm_idle_hint_vseq

### PR DESCRIPTION
**Pull request by BasitMehmood**
This test verify that jtag debugger does not need to stay any longer than advertized idle time indicated in dtmcs register.
@jdonjdon. kindly review it.Thanks

### CODE REVIEW

**Comment by jdonjdon** [comment]
@BasitMehmood ,based on https://github.com/jdonjdon/opentitan/blob/f618305a909e43a3a3f157b56fd73abc6772d0c2/hw/ip/rv_dm/data/rv_dm_testplan.hjson#L158-L166

"legal DMI access" means you should send proper command like, [this](https://github.com/lowRISC/opentitan/blob/master/hw/vendor/pulp_riscv_dbg/doc/debug-system.md#protocol). not arbitrary peek poke of dmi registers.

cc: @a-will

**Comment by BasitMehmood** [comment]
> @BasitMehmood ,based on https://github.com/jdonjdon/opentitan/blob/f618305a909e43a3a3f157b56fd73abc6772d0c2/hw/ip/rv_dm/data/rv_dm_testplan.hjson#L158-L166
> 
> "legal DMI access" means you should send proper command like, [this](https://github.com/lowRISC/opentitan/blob/master/hw/vendor/pulp_riscv_dbg/doc/debug-system.md#protocol). not arbitrary peek poke of dmi registers.
> 
> cc: @a-will

proper command means initiate request on request channel and check the response on response channel along with handshake mechanism? because there is another indirect method to do legal dmi access by writing to dmi register.

**Comment by BasitMehmood** [comment]
@jdonjdon 
https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/jtag_dmi_agent/README.md#jtag_dmi_reg_frontdoor
i have done dmi access according to this.

**Comment by jdonjdon** [comment]
> @jdonjdon https://github.com/lowRISC/opentitan/blob/master/hw/dv/sv/jtag_dmi_agent/README.md#jtag_dmi_reg_frontdoor i have done dmi access according to this.

I see that. Let me get back to you on this.

**Comment by jdonjdon** [comment]
@BasitMehmood ,
Test looks good as it.

**Review by jdonjdon — APPROVED** [review]

**Review by jdonjdon — APPROVED** [review]

**Pull request merged**
