### PR TITLE
[lc_ctrl] Updates for secure manufacturing

### PR DESCRIPTION
**Pull request by msfschaffner**
This addresses #7330, #4526. In particular:
- the number of `TEST_UNLOCKED` states is doubled from 4 to 8
- the `DEVICE_ID` field size is doubled from 256bit to 512bit
- the `NVM_DEBUG` enable signal is disabled in the last `TEST_UNLOCKED` state.

This also aligns the `lc_ctrl` DV environment.
@cindychip let me know if something should be done in a different way.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by tjaychen** [comment]
on the `nvm_en` disable, i think we should check with @zi-v one more time.

Last I talked to Ziv, he wanted to reserve a set of test states for the foundry level testing, and then another for the package testing. 
I'm not sure if the second to last test state should be the one with the disable.   I just wanted to confirm if after programming of the wafer secret, will the process always be "advance to last locked state"?

**Comment by msfschaffner** [comment]
Ok sure, I am not going to merge this before I have his approval.

For clarity, we currently have the following sequence of test states:
```
LcStRaw:                        NVM_DEBUG = Off, ISO_PART_WR = Off, ISO_PART_RD = Off    
--------------------------------------------          
LcStTestUnlocked0,              
LcStTestLocked0,                  
LcStTestUnlocked1,                  
LcStTestLocked1,                    
...                             
LcStTestUnlocked6,                  
LcStTestLocked6:                NVM_DEBUG = On , ISO_PART_WR = On, ISO_PART_RD = Off    
--------------------------------------------       
LcStTestUnlocked7:              NVM_DEBUG = Off, ISO_PART_WR = On, ISO_PART_RD = Off     
--------------------------------------------
LcStProd,                            
LcStProdEnd:                    NVM_DEBUG = Off, ISO_PART_WR = On, ISO_PART_RD = On 
--------------------------------------------
LcStDev:                        NVM_DEBUG = Off, ISO_PART_WR = On, ISO_PART_RD = Off     
--------------------------------------------
LcStRma:                        NVM_DEBUG = On,  ISO_PART_WR = On, ISO_PART_RD = On     
```

**Comment by tjaychen** [comment]
yeah so the part that isn't super clear to me right now.. is how conditional the secret injection is. I'm also not sure if after injection, we can automatically assume it'll always be going to the final locked state, or it's another intermediate lock state that can be unlocked for retest.  

Because technically speaking, we would like that injection to be as final as possible, but if there's any need for re-test, either they shouldn't put it in, or it has to be another intermediate state.  

Did that make sense at all..?

**Comment by msfschaffner** [comment]
So we basically still need to clarify:
1) whether the move to the last `TEST_UNLOCKED` state + injection is conditional on all previous tests passing, implying that no further retests will be needed once the injection has been performed,
2) or whether we need to provision more than one `TEST_UNLOCKED` state with `NVM_DEBUG = OFF` to facilitate retests AFTER secret injection.

Did I understand you correctly?

**Comment by tjaychen** [comment]
yes exactly.
do you think the questions make sense?

**Comment by msfschaffner** [comment]
yes - let's wait for @zi-v to clarify.

**Comment by zi-v** [comment]
Only the lest TEST_UNLOCKED needs to be with NVM_DEBUG = OFF

**Review by cfrantz — APPROVED** [review]
The changes to `lifecycle.[ch]` LGTM.

**Review by cindychip — COMMENTED** [review]
Looks like CI is complaining: 
the `get_exp_token` from testunlock2 to testlock4 state returns an invalid token from DV.

**Comment by msfschaffner** [comment]
> Looks like CI is complaining:
> the `get_exp_token` from testunlock2 to testlock4 state returns an invalid token from DV.

Thanks @cindychip - yes my DV changes were not fully correct. This should work now.

**Review by cindychip — APPROVED** [review]
Awesome, thanks for fixing all the DV parts :)

**Comment by msfschaffner** [comment]
This became dependent on https://github.com/lowRISC/opentitan/pull/7394.

**Comment by imphil** [comment]
Let's rerun the tests here first to see if we really ran out of memory during the synthesis. I cannot see anything in the kubernetes logs in that regard, it might have been something else.

**Comment by msfschaffner** [comment]
Note: this became dependent on https://github.com/lowRISC/opentitan/pull/7392 and 

> Let's rerun the tests here first to see if we really ran out of memory during the synthesis. I cannot see anything in the kubernetes logs in that regard, it might have been something else.

I have restarted them a couple of times, and the outcome is always the same. Locally FPGA builds seem to complete just fine with the same Vivado version (2020.2).

**Comment by imphil** [comment]
Turns out 12 GB of available memory are not enough, but 16 GB are.

We didn't really come close to the memory threshold before, but I wouldn't be surprised if Vivado tried to allocate a huge buffer, got a null pointer, and simply crashed. It's a bit surprising that it happened early in the synthesis. But thankfully nothing money can't fix.

This is the memory utilization of the runner that was doing the CW310 job that got killed here (12 GB of memory available)
grafik

With 16 GB available:
grafik

**Comment by msfschaffner** [comment]
Thanks for debugging this failure @imphil! More memory it is then...

**Pull request merged**
