### PR TITLE
[bazel] Add a quick-bazel script to rerun CI

### PR DESCRIPTION
**Pull request by drewmacrae**
Signed-off-by: Drew Macrae <drewmacrae@google.com>

### CODE REVIEW

**Comment by drewmacrae** [comment]
The CI currently runs a sortof tricky invocation to avoid building verilator and anything that depends on it. This should let us reproduce failures reliably locally.

**Review by rswarbrick — CHANGES_REQUESTED** [review]
Please also switch the code in `azure-pipelines.yml` to use this script.

**Comment by drewmacrae** [comment]
> Please also switch the code in `azure-pipelines.yml` to use this script.

I did it this way to stay consistent with the other scripts in the jobs directory, Should I change them all this way to generate a single source of truth? Change only this job? or Leave all 3 as they are with a script synced to the job represented in azure-pipelines.yml

**Comment by rswarbrick** [comment]
Oh! I strongly believe that everything should have "one source of truth". Historically, everything was just smushed into the azure pipelines file, but I spent a bit of time a while ago moving the 'quick CI' checks into scripts and out of the top-level file. (Running through those scripts in order is still duplicated, sadly, because you need to split them up to get decent error reporting). Similarly, the `build-chip-verilator.sh` script factors things out.

Is there an example where we're duplicating the shell script?

**Comment by mcy** [comment]
I agree with Rupert. If it doesn't run in CI, it doesn't exist.

**Comment by drewmacrae** [comment]
> Oh! I strongly believe that everything should have "one source of truth". Historically, everything was just smushed into the azure pipelines file, but I spent a bit of time a while ago moving the 'quick CI' checks into scripts and out of the top-level file. (Running through those scripts in order is still duplicated, sadly, because you need to split them up to get decent error reporting). Similarly, the `build-chip-verilator.sh` script factors things out.
> 
> Is there an example where we're duplicating the shell script?

The other scripts in ci/jobs are duplicated and had similar language about keeping them in sync. I've included the script directly in CI now and I've updated ci/jobs/quick-bazel.sh to reflect that it's not duplicated.

**Comment by rswarbrick** [comment]
Ah! The confusion is about the distinction between `ci/jobs` and `ci/scripts`. The stuff in `ci/jobs` is indeed duplicated but you'll see that it just runs down checks in order. It would be lovely to call e.g. `ci/jobs/quick-lint.sh` from the Azure pipeline but that doesn't work particularly well because you don't get nice reporting of the partial steps. The stuff in `ci/scripts` is not supposed to be duplicated.

My idea was that the `azure-pipelines.yml` would either call directly to `ci/scripts/my-thing.sh` if the whole job is reported as one step. If we need multiple stages, we have to list them separately in the YAML (boo!) but the `ci/jobs/my-job.sh` wrapper is handy for reproducing things locally. That's the idea, at any rate.

So I'm really sorry to ask for another change, but could you just move the script to `ci/scripts/quick-bazel.sh` to match the structure of the existing code? Once that's done, this looks perfect.

**Review by mcy — APPROVED** [review]

**Review by rswarbrick — APPROVED** [review]

**Pull request merged**
