### PR TITLE
[i2c] Increase depth of ACQ FIFO to 268 bytes 

### PR DESCRIPTION
**Pull request by andreaskurth**
This change allows the I2C HW IP module to absorb a max-length SMBus Block Write,
which consists of 1 command code byte, 1 byte defining the number of data bytes in the
block write, up to 255 data bytes, and 1 optional Packet Error Code
(PEC) byte; thus up to 258 bytes in total (from SMBus Specification
version 3.2, section 6.5.7).  Our I2C HW IP module additionally puts the
byte after the Start condition (which contains the address and the R/Wn
bit) and a byte for the Stop condition into the FIFO; thus the total
increases to 260 bytes.

To account for any oversights we may have made in the analysis of the
protocol, we add an extra 8 bytes as margin, thus 268 bytes.

Note that this is larger than required by MCTP, which would be 75 bytes:
- "The size of a transmission unit is defined as the size of the packet
  payload that is carried in an MCTP packet.  The [...] minimum
  transmission unit size for MCTP is 64 bytes.  A message terminus that
  supports MCTP control messages shall always accept valid packets that
  have a transmission unit equal to or less than the baseline
  transmission unit." (from MCTP Base Specification version 1.3.0,
  section 8.3)
- MCTP packets have a 4 byte header followed by the packet payload and
  they are encapsulated between a header and a tailer that is specific
  to the physical medium (from MCTP Base Specification version 1.3.0,
  section 8.1).  For MCTP on SMBus, header and tailer consist of 4 and 1
  byte, respectively (see above).
- Thus 4 + 4 + 64 + 1 = 73 bytes plus two bytes for Start and Stop
  (based on our HW IP module; see above) gives 75 bytes.

If the ACQ FIFO cannot absorb a full SMBus Block Write or MCTP control
message, real-time constraints to process bytes from the ACQ FIFO are
imposed on SW controlling the I2C HW module.  The maximum allowed delays
depend on the protocol:
- SMBus allows target devices to stretch the clock by up to 25 ms per
  message (t_LOW:CEXT in Table 14, 15, and 16 of the SMBus Specification
  version 3.2).
- MCTP allows target devices to stretch the clock by at most 250 us per
  byte (from MCTP SMBbus/I2C Transport Binding Specification version
  1.2.0, section 6.18).

In order to not impose such real-time constraints on SW for top-level
designs that use I2C with SMBus or MCTP, this commit makes the ACQ FIFO
sufficiently deep that any max-length transaction can be absorbed.  If
SW doesn't drain the ACQ FIFO once it's full before the next message,
that message should get NACK'd and the controller has to retry later --
but protocol compliance holds and the I2C lines are not blocked.
Currently our I2C HW IP module doesn't implement this NACKing, but this
will be resolved in a separate commit (see the PR of this commit for
details and links).

Block-level tests pass, except for the known failures listed in #21755, thus not caused by this PR.

### CODE REVIEW

**Comment by a-will** [comment]
> For MCTP control messages, clock stretching is only allowed by the
requester (from MCTP SMBbus/I2C Transport Binding Specification
version 1.2.0, section 6.19).

FYI, I think this was a mistake in understanding. The particular line reads

> Response specifications are given assuming that the requester is able to operate at full speed on the bus.
> That is, clock stretching, if any, is solely generated by the requester.

In other words, it is qualifying that the timing requirements do not account for clock stretching being done by the target, not that it requires clock stretching to only be done by the requester. (The latter would be a requirement that goes too far, since the bus could have non-MCTP devices on it.)

**Review by msfschaffner — APPROVED** [review]
RTL changes LGTM

**Review by a-will — APPROVED** [review]

**Review by hcallahan-lowrisc — APPROVED** [review]
Having not read the spec(s) myself and going by the details in the PR message, all of these changes seem reasonable to me.

**Review by alees24 — COMMENTED** [review]
The implementation of the changes looks fine, however I think the depth of 258 is inappropriate:
- the ACQ FIFO must also accommodate at least one START entry and one STOP entry as I understand things.
- is there a risk that RESTARTs will also need to be captured, eg. a host may choose to decompose the full message into smaller chunks internally and use RESTARTs between those chunks of the full message?
- if we're taking the hit of deepening the FIFO as far as 258 entries, I would - aside from the above points - suggest padding a little further to allow for errors in calculation/protocol undertanding at this stage anyway.

One further point, an open question since I'm afraid I haven't yet read/understood enough - can you explain the claim that any subsequent message will be NAKed, please? Do you mean in the I2C target hardware; I couldn't see evidence of that, looking quickly.

**Comment by andreaskurth** [comment]
Thanks for your feedback, @hcallahan-lowrisc and @alees24.

> -  the ACQ FIFO must also accommodate at least one START entry and one STOP entry as I understand things.

Good catch, so that will be two additional entries, totaling to 260 bytes. I'll amend the PR.

> -  is there a risk that RESTARTs will also need to be captured, eg. a host may choose to decompose the full message into smaller chunks internally and use RESTARTs between those chunks of the full message?

In general I2C, I think that would be possible because a controller can use a REPEATED START (Sr) to 'chain' data transfers to the same or different devices (from I2C Specification rev. 7.0, section 3.1.10). However, as I2C doesn't limit the length of data transfers ("The number of bytes that can be transmitted per transfer is unrestricted" -- from I2C Specification rev. 7.0, section 3.1.5), I don't think we should take this into account for the depth of the ACQ FIFO.

In SMBus, a Sr is "used to switch from write mode to read mode in a combined format protocol (e.g., Byte Read)" (from SMBus Specification version 3.2, section 2.4). The SMBus protocols that make use of Sr are (exhaustive list, from SMBus Specification version 3.2, section 6.5):
(a) Read Byte and Read Word (6.5.5)
(b) Process Call (6.5.6)
(c) Block Read (6.5.7)
(d) Block Write-Block Read Process Call (6.5.8)

In cases (a), (b), and (c), the controller wants to read data from the target and always sends a fixed number of bytes (3 to 5) to the target before switching the direction to read. In case (d), the controller first writes up to M (>= 0) bytes to the target before reading up to N (>= 0) bytes; and M + N must be <= 255. So in the worst case for the ACQ FIFO, M = 255 and N = 0, which means 1 start byte, 1 command code byte, 1 byte count byte, 255 data bytes, and 1 repeated start byte (no PEC byte from controller); total 259 bytes. For the number of words to store in the ACQ FIFO, it doesn't matter if the last word is a Sr or a P byte.

> -  if we're taking the hit of deepening the FIFO as far as 258 entries, I would - aside from the above points - suggest padding a little further to allow for errors in calculation/protocol undertanding at this stage anyway.

I agree, but we probably don't want to add too many extra entries. How about 272?

**Comment by a-will** [comment]
> For MCTP on SMBus, however, there is a window during which a target device is allowed to NACK (see MCTP SMBbus/I2C Transport Binding Specification version
1.2.0, section 6.14), and I think implementing that cannot be done in SW alone

The timing of the NACKing behavior is the primary reason MCTP scoping provided for a special higher-level hardware controller for Block Write protocols, hehe.

What we have now is effectively a logical layer for signaling and transfer framing with a really barebones frontend data / packet layer. The core does signals to bits/bytes and bits/bytes to signals, but it only bolts on FIFO status to drive that layer's control inputs. An abstraction with a more formalized "nack_byte_i" might be a useful input to the FSM, so a higher layer could choose to reject data independently and direct some of the transitions.

In turn, the logical layer module would expose a little of its state (when a relevant transfer starts + transaction boundaries), so the packet module(s) know when a new transfer started, whether this was a read transfer that immediately followed a write transfer in the same transaction (repeated-start style), etc.

**Comment by andreaskurth** [comment]
Merging as just discussed with @msfschaffner

**Pull request merged**
