### PR TITLE
[RV DM] Initial commit of C++ DV structure

### PR DESCRIPTION
**Pull request by tomroberts-lowrisc**
- Move existing UVM components to a separate directory
- Add skeleton of TB infrastructure
- No functionality included, only structure

Signed-off-by: Tom Roberts <tomroberts@lowrisc.org>

### CODE REVIEW

**Comment by tjaychen** [comment]
apologies if you guys have discussed this already, but it feels cleaner to have the structure...

dv
-> uvm
-> cpp

instead of parallel dv / uvm_dv directories.

I believe ibex also takes this approach.  Then a single README under dv/ can probably clearly explain the purpose of each.

**Comment by tomroberts-lowrisc** [comment]
Thanks @tjaychen - agreed, that would be much cleaner. I'll make the change.

**Comment by sriyerg** [comment]
Considering there is already a UVM testbench in the works, it will be worth to understand the the value of having two separate approaches for verifying the same block.

**Comment by tomroberts-lowrisc** [comment]
The C++ tb is an experiment in enabling open-source tools for verification. We targeted the debug module for this experiment because:

1. It is not a comportable block in the same way that other peripherals are (and so would not benefit from as much standardisation)
2. Although the UVM TB was started, it was not currently under active development

If we can't get enough confidence or metrics out of the C++ approach then the UVM TB will always be there, but I think it is worth experimenting with.

On the other hand, if the UVM TB is further on than we thought, or if there is a lot of development work already in-progress, then we should re-think this.

**Pull request closed without merging**
