### PR TITLE
[csrng/hjson] Update AES countermeasure descriptions

### PR DESCRIPTION
**Pull request by mwbranstad**
Based on review feedback, the AES countermeasures have been updated
to reflect the AES block coverage for security when used by CSRNG.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
this looks fine to me. 
i know @msfschaffner mentioned we could just a broad countermeasure list to refer to AES under csrng, but this is fine too.

**Review by tjaychen — APPROVED** [review]

**Comment by sriyerg** [comment]
@mwbranstad, the addition / removal of countermeasures will trigger a CI fail due to #10556, which auto-generates testplans from countermeasures the first time (and checks for staleness subsequent times). 

You will need to manually rebase, run `make -C hw/`, fix the errors and re-push. I apologize for the inconvenience.

**Comment by mwbranstad** [comment]
> @mwbranstad, the addition / removal of countermeasures will trigger a CI fail due to #10556, which auto-generates testplans from countermeasures the first time (and checks for staleness subsequent times).
> 
> You will need to manually rebase, run `make -C hw/`, fix the errors and re-push. I apologize for the inconvenience.

@sriyerg I ran this script and it found errors, but the feedback is expecting updates to the aes hjson and testplan. Is this how its supposed to work?

**Comment by mwbranstad** [comment]
@vogelpi does this make sense to you?
WARNING: Countermeasure MAIN.FSM.GLOBAL_ESC is referenced in the Hjson of the aes block at /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes.hjson, but doesn't appear in the RTL.
WARNING: Countermeasure BUS.INTEGRITY is referenced in the Hjson of the aes block at /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes.hjson, but doesn't appear in the RTL.
/wdc/proj/cto/top/work/mark.branstad/opentitan/util/regtool.py --sec-cm-testplan /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes.hjson
WARNING: Countermeasure MAIN.FSM.GLOBAL_ESC is referenced in the Hjson of the aes block at /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes.hjson, but doesn't appear in the RTL.
WARNING: Countermeasure BUS.INTEGRITY is referenced in the Hjson of the aes block at /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes.hjson, but doesn't appear in the RTL.
ERROR: The generated security countermeasures testplan /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes_sec_cm_testplan.hjson is stale. Please manually update it with the newly added (or removed) countermeasures.

**Comment by msfschaffner** [comment]
> this looks fine to me. i know @msfschaffner mentioned we could just a broad countermeasure list to refer to AES under csrng, but this is fine too.

In the long run we probably need to discuss a bit more how such imported IPs should be handled in this case. But I am fine with this approach for the time being.

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
@mwbranstad do you have any local changes within `aes.hjson`? If not, try rebasing onto the newest state on master to get rid of this. You should not be getting errors from the `aes.hjson`, but only from `csrng.hjson`.

**Comment by tjaychen** [comment]
just FYI, i pulled to head of tree, and had issues with both `csrng` and `aes`. 
I ended up just removing the `sec_cm_testplan.hjson` files for each and re-running `make -C hw all`, that seems to have done the trick for me.

**Comment by sriyerg** [comment]
> ERROR: The generated security countermeasures testplan /wdc/proj/cto/top/work/mark.branstad/opentitan/hw/ip/aes/data/aes_sec_cm_testplan.hjson is stale. Please manually update it with the newly added (or removed) countermeasures.

The last error is due to the change I made in #10556 (and exactly what my earlier coment was about. To fix this, you need to update the `aes_sec_cm_testplan.hjson` with the changes you made to the list of countermeasures.

**Comment by sriyerg** [comment]
> just FYI, i pulled to head of tree, and had issues with both `csrng` and `aes`. I ended up just removing the `sec_cm_testplan.hjson` files for each and re-running `make -C hw all`, that seems to have done the trick for me.
> 
> since these are JUST created, it's probably still okay to do this for now. In the future once tests are added we'll need to hand edit. @sriyerg can you confirm?

Yes, you are right - an easier way to address this is delete the `*_sec_cm_testplan.hjson`, rerun `make -C hw`, check-in the newly generated `*_sec_cm_testplan.hjson`, re-push.

**Pull request merged**
