### PR TITLE
[reggen] Enum Value Definition Fixes

### LINKED ISSUE #3804: `alert_handler.hjson` contains binary literals.
It looks like some binary literals slipped into https://github.com/lowRISC/opentitan/blob/master/hw/ip/alert_handler/data/alert_handler.hjson, which aren't available in C11; this results in build errors from pulling in the generated header.

I don't think it'll be a long term-issue, because this kind of thing will be automatically tested once very HJSON is pulled in by C. It might not be the worst idea to add all of them as a Meson target, though? For now I'm passing `-Wno-gnu-binary-literals` until this gets fixed.

### PR DESCRIPTION
**Pull request by lenary**
Reggen has been generating enum values already, directly using the
definitions from the hjson. This causes issues when binary literals are
included in the string, as we don't allow those in C/C++ code, so this
change moves to emitting all values as hexadecimal values.

The other change this makes is to add '_VALUE_` between the register
field name and the enum name, so that there are no collisions between
the offset/mask definitions and the enum values.

Closes #3804.

### CODE REVIEW

**Comment by lenary** [comment]
Before:
```
// Current escalation state of Class D. See also !!CLASSD_ESC_CNT.
#define ALERT_HANDLER_CLASSD_STATE(id) (ALERT_HANDLER##id##_BASE_ADDR + 0xe8)
#define ALERT_HANDLER_CLASSD_STATE_REG_OFFSET 0xe8
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_MASK 0x7
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_OFFSET 0
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_IDLE 0b000
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_TIMEOUT 0b001
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_TERMINAL 0b011
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_PHASE0 0b100
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_PHASE1 0b101
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_PHASE2 0b110
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_PHASE3 0b111
```

After:
```
// Current escalation state of Class D. See also !!CLASSD_ESC_CNT.
#define ALERT_HANDLER_CLASSD_STATE(id) (ALERT_HANDLER##id##_BASE_ADDR + 0xe8)
#define ALERT_HANDLER_CLASSD_STATE_REG_OFFSET 0xe8
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_MASK 0x7
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_OFFSET 0
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_IDLE 0x0
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_TIMEOUT 0x1
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_TERMINAL 0x3
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_PHASE0 0x4
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_PHASE1 0x5
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_PHASE2 0x6
#define ALERT_HANDLER_CLASSD_STATE_CLASSD_STATE_VALUE_PHASE3 0x7
```

**Review by mcy — APPROVED** [review]

**Review by gkelly — APPROVED** [review]
Needs HW approval.

**Comment by rswarbrick** [comment]
Looks good (and should be merged forthwith!) but maybe we should be converting to integers at parse time to avoid this sort of problem in future? (Which would also make the types a bit less unpredictable)

**Comment by lenary** [comment]
> Looks good (and should be merged forthwith!) but maybe we should be converting to integers at parse time to avoid this sort of problem in future? (Which would also make the types a bit less unpredictable)

Totally agree, though `validate.py` is a bit of a nightmare at the moment. It's fair to say reggen is more spaghetti than code today.

**Review by msfschaffner — APPROVED** [review]
Thanks, LGTM from my side!

**Review by sriyerg — APPROVED** [review]

**Comment by sriyerg** [comment]
LGTM!

**Pull request merged**
