### PR TITLE
Update lowrisc_ibex to lowRISC/ibex@ce7e383

### PR DESCRIPTION
**Pull request by imphil**
Update code from upstream repository
https://github.com/lowRISC/ibex.git to revision
ce7e38351e28bf54cbc7c2856ce6b65b9d2a3fbb

* [DV] Add Verilator memory initialization from ELF (Tobias Wölfel)
* [rtl] Implement FENCE.I (Greg Chadwick)
* [make] Add CS Register testbench targets (Tobias Wölfel)
* Update gitignore to include simple system files (Tobias Wölfel)
* Update gitignore for tag file (Tobias Wölfel)
* Update google_riscv-dv to google/riscv-dv@d691906 (lowRISC/ibex#491)
  (udinator)
* [DV] streamline Makefile gen flow (lowRISC/ibex#488) (udinator)
* [DV] Update flow to match RISCV-DV changes (lowRISC/ibex#487)
  (udinator)
* Update google_riscv-dv to google/riscv-dv@39ca859 (lowRISC/ibex#486)
  (udinator)
* [DV] Test accesses to higher privileged CSRs (lowRISC/ibex#483)
  (udinator)
* [dv] Prepare CS registers TB for CI (Tom Roberts)

### CODE REVIEW

**Comment by imphil** [comment]
This needs more updates to the spidpi module, I'll follow up tomorrow.

**Comment by imphil** [comment]
Necessary fixes are now awaiting review in the Ibex repository, I'll update this PR once they're in.

**Comment by vogelpi** [comment]
The changes look good to me, but I think we should first merge #1066. Otherwise #1066 has be rebased once more. WDYT?

**Comment by towoe** [comment]
The changes outside of `hw/dv` all look good to me. I did some local check of with pytest with ELF (and also VMEM) based on this PR and could not see any problems. @imphil maybe only azure had some issue?

**Comment by imphil** [comment]
Seems that we get random timeouts on the tests with this PR. I'll see if I can reproduce locally.

**Comment by imphil** [comment]
So, test failure was a missing libelf dependency when running the system tests. Fixed that, ready for review.

**Comment by vogelpi** [comment]
I have just created a PR into your branch @imphil to keep the USB top working.

**Comment by imphil** [comment]
merged and updated. Thanks @vogelpi

**Pull request merged**
