### PR TITLE
[csrng/dv] V0->V1

### PR DESCRIPTION
**Pull request by senelson7**
Signed-off-by: Steve Nelson <steve.nelson@wdc.com>

Successful V1 review so updates checklist and hjson file to reflect V1

### CODE REVIEW

**Review by mwbranstad — APPROVED** [review]
LGTM

**Comment by weicaiyang** [comment]
https://reports.opentitan.org/hw/ip/csrng/dv/latest/results.html
can you check why some of the csrng_csr_hw_reset are failing? CSR tests are part of the smoke test which is in V1 items. 
We run smoke for all the IPs in CI. It's good to make sure all CSR tests are very stable, otherwise, it may block the other's PR from merging.
This is probably easy to fix, then it's ready for V1.

**Comment by senelson7** [comment]
Depends on PR #5191 to fix csrng_csr_hw_reset tests.

**Comment by senelson7** [comment]
Mark moved the fix to PR #5195 which has been merged and now all V1 tests pass 100%. So based on Weicai's comment, this PR can be approved/merged.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by mateenfaisal** [comment]
Yippee :) @senelson7, the OT HW dashboard is still showing CSRNG at V0.

**Comment by senelson7** [comment]
Well the csrng.prj.hjson file says V1 now but they just merged it a little while ago so maybe the documentation hasn’t updated yet. Let me know if I need to do something else.

Steve Nelson
Design/Verification Engineer
507-261-8577
--
Western Digital
Rochester, MN

**Comment by weicaiyang** [comment]
> Well the csrng.prj.hjson file says V1 now but they just merged it a little while ago so maybe the documentation hasn’t updated yet. Let me know if I need to do something else.

the Opentitan document can't be generated correctly. It may be related to #5180. Already pinged Rupert to check.

**Comment by imphil** [comment]
I filed https://github.com/lowRISC/opentitan/issues/5306 for that, it's a problem with the doc builder.

**Pull request merged**
