### PR TITLE
[otp_ctrl] Add OTP memory map generation to CI

### PR DESCRIPTION
**Pull request by msfschaffner**
This adds the OTP memory map translation script to the `hw/Makefile` and adds a check to CI to make sure the memory map and generated files are in sync.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Review by imphil — APPROVED** [review]

**Comment by imphil** [comment]
CI shows that it works :-)

**Comment by msfschaffner** [comment]
Haha yes. Now that we've tested this, let me make sure that these files are up to date ;).

**Comment by tjaychen** [comment]
lgtm!

**Comment by msfschaffner** [comment]
This has to wait until #3905 goes in (due to updates in the OTP hjson template).

**Pull request merged**
