### PR TITLE
[ci] Update EOL GitHub Actions

### PR DESCRIPTION
**Pull request by jwnrt**
actions/checkout@v2 and actions/upload-artifact@v2 use Node.js 12, which will be deprecated from GitHub's Ubuntu runner in the summer of 2023.

Update: also updated actions/github-script@3.1.0 to v6 to use Node.js 16. This is used in the `pr-lint-review` pipeline which isn't run on this pull request's context, so isn't checked here.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### CODE REVIEW

**Review by pamaury — APPROVED** [review]
This looks good to me. Are there any risks of breakage due to this or it should be completely transparent for us?

**Comment by jwnrt** [comment]
`actions/checkout@v3` and `actions/upload-artifact@v3` should be safe updates, and we can see them working in this PR.

[`actions/github-script`](https://github.com/marketplace/actions/github-script) I'm a bit more wary of. We're only running it in the `pr_lint_review` workflow which for this PR runs using the repo's HEAD configuration and not this PR's updated version, so I can't see it working. See https://github.com/lowRISC/ibex/pull/1427 for why it works like this.

This action is updated from v3 to v6 which is a fairly large jump. It runs some Node.js script directly, which in theory could break between Node.js 12 and 16. I don't see any easy way of testing this without just merging the PR. I think the worst that would happen is we don't get verible lints posted to PRs as review comments.

If we don't want to blind-update this action in the `pr_lint_review` workflow, I'm happy to exclude it - we no longer need this split of two workflows where one runs in the HEAD context (see https://github.com/chipsalliance/verible-linter-action/pull/31), and I'm planning on making this change today in which case we no longer need this action.

**Review by engdoreis — APPROVED** [review]
LGTM, I think you could merge this PR in an Idle day and if it breaks we quickly revert the last commit.

**Comment by jwnrt** [comment]
> LGTM, I think you could merge this PR in an Idle day and if it breaks we quickly revert the last commit.

The `github-script` update did break CI :smile: - here's the revert for that commit: https://github.com/lowRISC/opentitan/pull/19107

**Pull request merged**
