### PR TITLE
[otp_ctrl] Transition into D2

### PR DESCRIPTION
**Pull request by msfschaffner**
This is a draft PR, preparing to move OTP into D2. There are a few items we need to discuss first (see checklist comments in this PR) before we can move on.

Also, these two PRs still need to go in prior to D2: https://github.com/lowRISC/opentitan/pull/4705, https://github.com/lowRISC/opentitan/pull/4702

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Just a short update here: this D2 transition is basically gated by the OTP/LC KMAC hashing interface change. Once that has been implemented, we should be good to go.

**Comment by cindychip** [comment]
Hey Michael, are we still planning to change the `otp_keymgr_key_o ` to generate from kmac?

**Comment by msfschaffner** [comment]
Do you mean the token hashing interface?

**Comment by msfschaffner** [comment]
Yes that is still the plan, but we are going to perform that as part of the post-D2 hardening steps.

**Review by cindychip — COMMENTED** [review]
LGTM on the dv side

**Review by cindychip — APPROVED** [review]

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
