### PR TITLE
[aes/syn] Update GTECH flow for AES wrapper

### PR DESCRIPTION
**Pull request by msfschaffner**
This separate synthesis target for the AES wrapper is only intended to produce a mapping of the wrapper alone. The motivation for synthesizing AES and the wrapper separately is that we can ensure that no sort of optimization takes place across the hierarchy boundary between them (the wrapper is TB code whereas the AES is actual synthesizable code).

In order to achieve this we just remove the aes module from the working lib after elaboration.

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Review by tjaychen — APPROVED** [review]

**Review by vogelpi — APPROVED** [review]
LGTM, thanks @msfschaffner!

**Comment by msfschaffner** [comment]
The last force push aligns the AES security parameters in the wrapper with the top-level.

**Comment by vogelpi** [comment]
FYI, the security parameters were chosen like this on purpose to reduce 1) the simulation run time and 2) the number of test points for the initial experiments. With the real parameters, the module runs about 5 times longer and is at least 4 times bigger. But I agree that we are mainly interested in seeing what happens for the real thing.

**Comment by msfschaffner** [comment]
Ok, understood. 
However, since we need to synthesize the wrapper for the final experiments I thought we should rather switch on the real thing now to get accurate results...

**Pull request merged**
