### PR TITLE
[dv, top] Add chip_sw_keymgr_sideload_kmac_vseq

### PR DESCRIPTION
**Pull request by weicaiyang**
Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by weicaiyang** [comment]
@ballifatih 
The keymgr test sequence in chip-level are organized as follows.
1. the key_derivation test covers all kinds of keymgr operation as well as sideload operations, but it doesn't involve other security IP to really use the sideload to issue an operation. This test checks the sideload key on the IP boundary.
2. keymgr_sideload_* test uses the sideload key to do some kmac/aes/otbn operations. For keymgr_sideload_kmac, we need to add a check to compare the digest output of the kmac sideload operation.

This PR refactors the DV sequence a bit, so that we can reuse most part of the chip_sw_keymgr_key_derivation_vseq for other sideload tests. I didn't thoroughly test this PR. Can you help to take over this PR (I may introduce some bugs) and continue adding the check for the kmac sideload operation?

**Comment by gdessouky** [comment]
@weicaiyang 
So my understanding is that this same keymgr_sideload_* test would also be used to test the AES sideloading, with a check to compare the AES output with that of the SW, do I have that right?

**Comment by weicaiyang** [comment]
> @weicaiyang So my understanding is that this same keymgr_sideload_* test would also be used to test the AES sideloading, with a check to compare the AES output with that of the SW, do I have that right?

yes, the same structure applies to the aes sideload test. Looks like @vrozic is taking that test. Added him to review this PR as well.

**Comment by ballifatih** [comment]
I am also available for helping with this. I think I can take over the KMAC direction from this PR, since @gdessouky seems to have taken the AES sideload test. I think my familiarity with KMAC might be handy.

**Comment by weicaiyang** [comment]
> I am also available for helping with this. I think I can take over the KMAC direction from this PR, since @gdessouky seems to have taken the AES sideload test. I think my familiarity with KMAC might be handy.

Great, thanks @ballifatih
If you find any issue in this PR, please let @gdessouky know. She may run into the same issue since she needs to implement the aes one based on this PR

**Comment by ballifatih** [comment]
I could't push on top of this PR, please see #16058 for sideload-kmac

**Pull request closed without merging**
