### PR TITLE
[ci] Backport GitHub Actions migrations from `master`

### PR DESCRIPTION
**Pull request by jwnrt**
Includes the following pull requests:

1. https://github.com/lowRISC/opentitan/pull/25094
2. https://github.com/lowRISC/opentitan/pull/24717
3. https://github.com/lowRISC/opentitan/pull/25002
4. https://github.com/lowRISC/opentitan/pull/25171
5. https://github.com/lowRISC/opentitan/pull/25182
6. https://github.com/lowRISC/opentitan/pull/25162
7. https://github.com/lowRISC/opentitan/pull/25292

### CODE REVIEW

**Review by nbdd0121 — APPROVED** [review]
Thanks!

**Comment by nbdd0121** [comment]
Commit 1fc67b1 misses cherry-pick message.

**Comment by jwnrt** [comment]
Nice catch, fixed

**Comment by jwnrt** [comment]
GitHub changes the commit hashes on merge, fixed again...

**Comment by nbdd0121** [comment]
Needs https://github.com/lowRISC/opentitan/pull/24868 first

**Comment by jwnrt** [comment]
Indeed, well spotted

**Pull request merged**
