### PR TITLE
[sw, dif_uart] DIF_HW_USAGE_REVIEWED complete

### PR DESCRIPTION
**Pull request by silvestrst**
As part of the DIF S2 signoff, we ensure that the peripheral is being used correctly by the DIF. This review happened with Eunchan Kim, Silvestrs Timofejevs, Sam Elliott and Garret Kelly.

We have identified the following TODOs:

- [x] uart.TIMEOUT_CTRL is required (uart.OVRD and uart.VAL is not required). For some background, please see:
https://github.com/lowRISC/opentitan/issues/2292

- [x] Should document the RX and TX FIFO reset semantics. Specifically that if a byte is in transit, the RX, TX FIFO reset will not cancel the operation (#4728). For some background please see:
https://github.com/lowRISC/opentitan/issues/2812

- FIFO size is hardcoded in the DIF, but it is fine as it is not expected to change (even with different parameterisation).

- Semantics of send and receive byte functions were deemed good.

- Static assert in the code should not be a problem, as it is unlikely that it would ever exceed 28 bits (requires very high clock frequency).

- [x] Bitwise operators where applicable should be changed to use the `bitfield` library (#4728).

- [x] RX and TX FIFO reset is duplicated in the reset and configuration functions. The consensus is to keep it in the reset function, but remove from the configure function (#4728).

- [x] ~~RX and TX FIFO reset functions must write `1' and then `0`. Should add `0` write following the `1` write in the reset function and FIFO reset API functions (#4728).~~

### CODE REVIEW

**Comment by lenary** [comment]
Can you include the DIF implementation changes in this PR as well?

**Comment by lenary** [comment]
For clarification: this PR doesn't need to migrate to the bitfield library, but the FIFO reset changes, the TIMEOUT_CTRL stuff, and the updates to documentation should be in this PR.

**Comment by silvestrst** [comment]
> Can you include the DIF implementation changes in this PR as well?

Yup, that is the idea, I forgot to mention it in the description.

**Comment by mateenfaisal** [comment]
@silvestrst, how about adding another reviewer?

**Review by gkelly — APPROVED** [review]

**Review by alphan — APPROVED** [review]

**Review by eunchan — APPROVED** [review]

**Pull request merged**
