### PR TITLE
[rstmgr] Fix dump capture conditions

### LINKED ISSUE #7918: [rtl/rstmgr] Disable alert and cpu capture for low power exit
Cpu and alert info is captured on resets in order to provide additional details regarding the reset cause. When such capture happens the hardware disables subsequent captures until software re-enables it writing into the `cpu_info_ctrl.en` and `alert_info_ctrl.en` CSR fields.

Capture is also triggered by resets due to a low power exit, even though this is not a reset that will need diagnostics. This is problematic since it is possible a low power exit reset is closely followed in time by some hardware triggered exit if software has had no time to re-enable captures. This would mean the latter reset would not capture information, and instead the captured info would correspond to the uninteresting low power exit reset.

This can be resolved easily by dropping the low power exit from the causes of reset capture... it even reduces the logic.

### PR DESCRIPTION
**Pull request by tjaychen**
- Fixes #7918
- Remove unnecessary dump capture

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by matutem — COMMENTED** [review]
I don't understand this: the dump_capture_i of cpu and alert info is not changed, so we still capture the same. What seems to have changed is the logic to disable the capture, so it is only disabled for hw resets.

I expected the logic for dump_capture itself to change.

**Comment by tjaychen** [comment]
i decided to go this way because if a low power and actual reset collided (with low power slightly ahead), the act of low power would actually cause the dump sources to be wiped out (since the dump sources are not always on). So when you actually capture again, you would get nothing. 

This is not something you would observe at block level tests, unless you modeled the stimulus behavior to disappear on low power as well.

**Comment by tjaychen** [comment]
@matutem can you let me know what you think?

**Review by matutem — APPROVED** [review]
This leaves ndm_reset to sort out. I gueess ndmresety should never overlap with low powert, so what happens when ndm and hw reset collide, the hw reset will capture. So this sounds good.

LGTM

**Pull request merged**
