### PR TITLE
[prim/assert] Disable req stable assertion

### PR DESCRIPTION
**Pull request by weicaiyang**
Valid can be dropped even ready is low
detail discussion #3354

Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by eunchan** [comment]
I am not sure which one is good removing assertion here or removing the assertion by not setting the parameter. @msfschaffner ?

**Comment by weicaiyang** [comment]
> I am not sure which one is good removing assertion here or removing the assertion by not setting the parameter. @msfschaffner ?

it sounds good to use a parameter to disable. WDYT @msfschaffner

**Comment by tjaychen** [comment]
o yeah i think removing via parameter is definitely better.  We do have cases where the requests have to assert and not go away.

**Comment by weicaiyang** [comment]
There is already a parameter for disabling these assertions. I have updated the PR. PTAL. Thanks

**Review by eunchan — APPROVED** [review]

**Comment by sriyerg** [comment]
> o yeah i think removing via parameter is definitely better. We do have cases where the requests have to assert and not go away.

Can that be considered a violation / deviation from the spec? Perhaps worth documenting this as well. @eunchan

**Review by sriyerg — APPROVED** [review]

**Pull request merged**
