### PR TITLE
[flash_ctrl,dv] rma test fix

### PR DESCRIPTION
**Pull request by jdonjdon**
Revert back check with random data after RMA

Signed-off-by: Jaedon Kim <jdonjdon@google.com>

### CODE REVIEW

**Comment by jdonjdon** [comment]
cmd:
./util/dvsim/dvsim.py ./hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i flash_ctrl_hw_rma -r 1 -s 1 -v m --waves

**Comment by jdonjdon** [comment]
@tjaychen This rma test.
After RMA, TB is expecting ramdom rd data but dut returns all 1's.

**Comment by tjaychen** [comment]
> @tjaychen This rma test. After RMA, TB is expecting ramdom rd data but dut returns all 1's.

excellent, thank you.

**Review by tjaychen — APPROVED** [review]

**Comment by jdonjdon** [comment]
fixed by #14250

**Pull request closed without merging**
