### PR TITLE
[flah_ctrl/dv] Changing Red to Redundancy

### PR DESCRIPTION
**Pull request by eshapira**
Very small PR, changing redundancy related variables & parameters names in flash_ctrl files from red/Red to redundancy/Redundancy.

Signed-off-by: Eitan Shapira <eitanshapira89@gmail.com>

### CODE REVIEW

**Comment by imphil** [comment]
Thanks for your pull request. I'll let others approve the PR, but just because I've seen that how a couple times: it should be `flash_ctrl`, not `flah_ctrl` :smile: No need to change it for this PR, but for the next ones.

**Comment by eshapira** [comment]
@imphil Thanks for noticing :)
I know of course that it's should be flash_ctrl, I just actually didn't noticed until now that I keep missing that 's'.

**Review by weicaiyang — APPROVED** [review]
LGTM, `Red` can be considered as an abbreviation of `Redundancy`. Can you explain why you prefer to change it? Thanks

**Comment by eshapira** [comment]
Sorry, I should have explained it. I did those changes to sri's request and now I agree with him in fact that this is better, because red is not informative enough. Thanks!

**Comment by weicaiyang** [comment]
> Sorry, I should have explained it. I did those changes to sri's request and now I agree with him in fact that this is better, because red is not informative enough. Thanks!

thanks for the explanation.

**Pull request merged**
