### PR TITLE
[flash_ctrl] Update stale sec_cm hjson for flash_ctrl

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
This is interesting... why did CI not catch this?

**Comment by tjaychen** [comment]
> This is interesting... why did CI not catch this?

i dont think the script actually fails, it just prints out more or less a warning.
I can't remember if CI explicitly looks for "ERROR" anymore.

**Comment by sriyerg** [comment]
I have made a potential fix in https://github.com/lowRISC/opentitan/pull/16798. Waiting to see CI fail to validate it.

**Review by sriyerg — APPROVED** [review]

**Comment by msfschaffner** [comment]
> Oh I see it now, yes. That's my bad (I forgot to add this in all places then).
> 
> Yeah it looks like this still passes in CI, even though the script prints `ERROR`.

Great, thanks for doing this!

**Pull request merged**
