### PR TITLE
Add a missing )

### PR DESCRIPTION
**Pull request by kupiakos**
also a newline, blame github

### CODE REVIEW

**Comment by rswarbrick** [comment]
Thank you for the contribution! You'll need to add a sign-off line (which is why the "quick lint" CI check is failing). See https://github.com/lowRISC/opentitan/blob/master/CONTRIBUTING.md for details.

To check things are right without having to re-push, you can run `ci/lint-commits.sh master`.

**Comment by kupiakos** [comment]
I'll edit the description when I get around to cloning the repo locally. Have you considered changing the CLA requirements so that the sign-off line is not required for trivial (typo) edits? The Github edit UI doesn't really provide an opportunity to fix without creating a new PR entirely.

**Comment by rswarbrick** [comment]
Ah, I see. I didn't realise that this was done from the GitHub UI. I don't think we've thought seriously about that. Personally, I like the idea that "fix silly typo" is a gateway drug to people contributing code, so I'm kind of ok with the slightly irritating flow :-)

**Comment by jwnrt** [comment]
Closing because this script was deleted in https://github.com/lowRISC/opentitan/commit/9846b6d945fe2ff96a68bda803a708888b2f5cf3

**Pull request closed without merging**
