### PR TITLE
[doc/rstmgr] Remove redundant "!"s in hjson

### PR DESCRIPTION
**Pull request by matutem**
Signed-off-by: Guillermo Maturana <maturana@google.com>

### CODE REVIEW

**Comment by imphil** [comment]
The `!!` indicate a register, and cause the text to be linked to the register definition. You can see that at work at https://docs.opentitan.org/hw/ip/rstmgr/doc/#register-table

grafik

https://github.com/lowRISC/opentitan/blob/8484ee48059293e41bb8fa87bf8ecf3061af9159/util/reggen/html_helpers.py#L13-L22

The single exclamation mark is a mistake and should be fixed.

**Review by tjaychen — DISMISSED** [review]

**Comment by tjaychen** [comment]
oops accidentally approved. I think as @imphil said, the right fix is probably to make them `!!`

**Comment by matutem** [comment]
@imphil Perhaps this feature only operates in "desc" fields? I get an error when used in a "regwen" field.

**Review by tjaychen — APPROVED** [review]
thanks!

**Pull request merged**
