### PR TITLE
[tlul,prim] Do some splitting up in prim.core and avoid depending on prim:all in TLUL core files

### PR DESCRIPTION
**Pull request by rswarbrick**
The main motivation for this is to cut down the dependency tree for my rom_ctrl work (I've been messing around trying to run Symbiyosys on it), but I think this should be a win in general.

### CODE REVIEW

**Review by imphil — APPROVED** [review]
Thanks, the prim:all catch-all core really needs to go if we want to keep the dependency tree manageable. The prim:all core file has a comment in the beginning which hints that this file should be split up, but isn't really clear enough about it.

Can you add a big "DEPRECATED, DO NOT ADD ANYTHING NEW TO IT AND DONT DEPEND ON IT" warning somewhere?

**Comment by rswarbrick** [comment]
> Can you add a big "DEPRECATED, DO NOT ADD ANYTHING NEW TO IT AND DONT DEPEND ON IT" warning somewhere?

My take on this is that people who Should Know Better (TM) already depend on prim:all, despite a project-wide agreement that it should go away. I'm not sure a deprecation warning will make any difference: it probably makes more sense to just do the work to split it up.

**Comment by rswarbrick** [comment]
@imphil: I *think* I've diagnosed things correctly for the first patch, but would you mind checking over it to make sure I got this right?

**Review by imphil — APPROVED** [review]
Yes, the "Make prim:flop_2sync depend on prim:flop" is a correct workaround. The commit message isn't fully correct -- we resolve dependencies for generated cores, but don't run generators again and take these dependencies into account as well.

We in theory would have:
prim_flop_2sync -> generator -> prim_generic_flop_2sync depends on prim_flop -> generator -> depends on prim_generic_flop

So we would need to run a generator n times until the dependency tree has settled and no new generators are found -- that's not supported.

An alternative solution, and maybe the better one, is to change prim_generic_flop_2sync to actually use flip_generic_flop. If a user chose already to use the generic implementation for prim_generic_flop_2sync, maybe they also want the generic implementation of prim_flop?

Or alternatively, get rid of the target-dependent prim_generic_flop_2sync and implement it directly in prim_flop_2sync and then make only have target-dependent implementations of prim_flop. 

I only see the xilinx and generic libraries, so I'm not sure if we rely on one or the other behavior in our tapeout libraries; so let's probably keep the workaround for now (maybe add a comment to the code) and sort this out another day.

**Comment by rswarbrick** [comment]
Thanks for the explanation, that's really helpful. I'll update the comment to match and, yes, let's punt on a better fix for another day.

**Pull request merged**
