### PR TITLE
[hw,dma] Add a chunk_done interrupt

### PR DESCRIPTION
**Pull request by Razer6**
This PR adds a new chunk_done interrupt. This interrupt is raised for chunked mem2mem transfers when a single chunk is transferred and the SW needs to start the transfer of a new chunk. When transferring the last chunk, only the `done` interrupt is raised.

This PR is based upon https://github.com/lowRISC/opentitan/pull/24108

### CODE REVIEW

**Review by alees24 — CHANGES_REQUESTED** [review]
I think the logic here is correct, thank you, but please do heed my remarks about tightening the interrupt behavior so that it properly conforms to the Comportable IP requirements, otherwise the common, shared tests will fail for this block.

Interrupts are described [here](https://opentitan.org/book/doc/contributing/hw/comportability/index.html?highlight=interrupt#interrupt-handling).

Presently the tests will pass because the implementing intr_state/enable/test-related logic assumes that they are all Event type interrupts, and nothing is causing a Status-type (dma_done or dma_error) interrupt to be asserted by the device within those tests.

It is not clear whether the intention was for them to be Event type and rely upon the `status` register for the history, or if they're supposed to be Status type and the `intr_state.de` _should_ be driven by the `status.q` bit as presently.

**Comment by Razer6** [comment]
@alees24 After the chunk_done status PR was merged, this one adds a status-type interrupt to the chunk_done. The PR intentionally uses interrupt index 1, where previously the memory limit IRQ was to not shuffle around the other IRQ.

**Review by andreaskurth — APPROVED** [review]
RTL changes LGTM; I'll defer to others for feedback on the DV changes. Thx @Razer6!

**Review by alees24 — CHANGES_REQUESTED** [review]
There's a missing `chunk_done` assertion in the DmaShaWait state that leads to a premature assertion of `done`:
```
@@ -1005,6 +1005,7 @@ module dma
               // In non-hardware handshake mode, finishing one chunk should raise the done IRQ
               // and done bit, and release the go bit for the next FW-controlled chunk.
               clear_go     = !control_q.cfg_handshake_en;
+              chunk_done   = !control_q.cfg_handshake_en;
               ctrl_state_d = DmaIdle;
             end else begin
               ctrl_state_d = DmaAddrSetup;
```
There are more issues on the DV side, which has been somewhat lagging behind the RTL changes lately, since this block is unfortunately not yet running in regressions/CI. I'll supply the DV updates shortly.

Thanks.

**Comment by Razer6** [comment]
Thank's for spotting this. I just added this change to the commit.

**Review by alees24 — APPROVED** [review]
I think this is good to merge now, thank you. Locally I'm just seeing the range_regwen_rd_A assertion failure on dma_stress_all and dma_memory_region_lock sequences, because of the missing changes in the autogen FPV register checking code.

**Comment by alees24** [comment]
Merging because the salient CI tests have completed; DMA not present in Earl Grey.

**Pull request merged**
