### PR TITLE
[integrated_dev] Restrict RTL changes for Darjeeling and its HW IP blocks

### PR DESCRIPTION
**Pull request by andreaskurth**
At the same time remove restrictions on changes for Earlgrey (on the `integrated_dev` branch).

### CODE REVIEW

**Comment by andreaskurth** [comment]
CHANGE AUTHORIZED: BLOCKFILE

**Comment by msfschaffner** [comment]
CHANGE AUTHORIZED: BLOCKFILE

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
Let's announce this in the WG tomorrow and then merge.

**Comment by andreaskurth** [comment]
RTL blocker announced by email -- merging.

**Pull request merged**
