### PR TITLE
[ci] New nightly job for the BoB

### PR DESCRIPTION
**Pull request by engdoreis**
This PR:
 - Refactor the i2c testutils function that configures the pinmux to improve readability.
 - Change the i2c tests that requirers the BoB from i2c0 to i2c2.
 - Create a CI nightly job to run the tests.

### CODE REVIEW

**Review by pamaury — APPROVED** [review]
The azure pipeline modification looks good to me.

**Review by hcallahan-lowrisc — APPROVED** [review]
This looks sensible to me, thanks @engdoreis. The cleanup in the testutils is nice.

I'm not sure when we would do it, but we should start thinking about a way to check the hardware configuration of the test runner to make sure, for example, that the BoB is present and attached. (obviously this is a more longstanding issue). 

Maybe we could add a simple 'is_present' test which reads from all devices on the BoB and just checks they are all there? Maybe as a way to bail-out early from the entire nightly job.

**Review by jwnrt — APPROVED** [review]

**Review by johngt — COMMENTED** [review]
AFAICT it looks good to me.
So I2C0 to I2C2
Adding labels for manual tests and BoB.

@engdoreis is there a chance that these tests will block if there is a runner that doesn't have the BoB connected? How does it detect that a BoB is not present on a runner? I assume that it can't - but will the test fail gracefully and say that the tests could not complete, or will it block?

**Comment by johngt** [comment]
> I'm not sure when we would do it, but we should start thinking about a way to check the hardware configuration of the test runner...
> 
> Maybe we could add a simple 'is_present' test...
Just seen that @hcallahan-lowrisc raised the same issues.
Re. @pamaury points; We should probably speak to @colinoflynn about having versions of the boards if we think this is something we are going to support long term and have multiple versions of. I think for now we can get away with the current implementation. Having some support for checking the hardware present though is something that will be needed.

**Comment by engdoreis** [comment]
> AFAICT it looks good to me. So I2C0 to I2C2 Adding labels for manual tests and BoB.
> 
> @engdoreis is there a chance that these tests will block if there is a runner that doesn't have the BoB connected? How does it detect that a BoB is not present on a runner? I assume that it can't - but will the test fail gracefully and say that the tests could not complete, or will it block?

The test will fail, and we could infer by the logs that the BoB is not present, but I'll in the feature add a proper detection mechanism with a more friendly message, I'm tracking in this[ issue](https://github.com/orgs/lowRISC/projects/36/views/1?pane=issue&itemId=25448882).
In case of failure anything will be blocked, that's the reason I preferred to exercise these tests in a nightly job for now as we don't want PRs being blocked due to infrastructure issues.

**Comment by pamaury** [comment]
If we are going to need runners with different configurations, we can integrate that into Azure and tag the runners using the environment file (like we do for the pools) to indicate what hardware is present. I am sure those tags can also be then passed to tests if they need to adjust the configuration based on the hardware (like different board versions).

**Pull request merged**
