### PR TITLE
[aes] Update development stages

### PR DESCRIPTION
**Pull request by vogelpi**
This PR is updates the design stages of AES to represent the current state (once #5427 is merged). In addition, the PR also adds the checklist for the DIF.

### CODE REVIEW

**Comment by vogelpi** [comment]
FYI @mateenfaisal

**Comment by vogelpi** [comment]
@rasmus-madsen you did a lot of work to push the design to V2. It would be great if you could also update the V stages/status accordingly. We can do it in this or in a separate PR. WDYT?
@alphan could you please quickly cross check the DIF status?

**Review by rasmus-madsen — APPROVED** [review]

**Comment by rasmus-madsen** [comment]
> @rasmus-madsen you did a lot of work to push the design to V2. It would be great if you could also update the V stages/status accordingly. We can do it in this or in a separate PR. WDYT?
> @alphan could you please quickly cross check the DIF status?

Lets keep that to a separate PR I have a few more things to get in. but with D going to D2 I can get to V2 shortly

**Comment by vogelpi** [comment]
Sounds good, thanks for your feedback @rasmus-madsen .

**Review by alphan — APPROVED** [review]

**Pull request merged**
