### PR TITLE
[site,doc] Update Gcloud build steps to use existing container

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**
With the recent changes to the `util/site/build-docs.sh` script, we now require additional dependencies for the build. Move the cloud-build to use the existing container, which already has these dependencies present.

The only difference is the need to overwrite the ENTRYPOINT of the container image, as the Gcloud environment has a different setup.

### CODE REVIEW

**Comment by hcallahan-lowrisc** [comment]
Triggered a build manually with this configuration and everything worked ok.
(@HU90m you can see the latest reggen changes live now)

**Review by HU90m — APPROVED** [review]
Brilliant! Thanks Harry

Looks like you need to remove the old container from `azure-pipelines.yml`.

**Comment by hcallahan-lowrisc** [comment]
> Brilliant! Thanks Harry
> 
> Looks like you need to remove the old container from `azure-pipelines.yml`.

Good point! Thanks

**Review by marnovandermaas — COMMENTED** [review]
Thanks for working on this @hcallahan-lowrisc. Let me know once this is ready.

**Comment by hcallahan-lowrisc** [comment]
Moved the cleanup of bazel directories into the `build-docs.sh` script rather than a cloudbuild step. Also removed some other large, unneeded directories.

**Review by marnovandermaas — COMMENTED** [review]
Thanks for this fix @hcallahan-lowrisc. I think the Kokoro failure is unrelated to this PR, maybe rebasing onto the main branch will fix this? I do not see those AST lint errors in upstream at the moment. Other than that I would be happy to merge this once Hugo has a look and CI passes.

**Comment by hcallahan-lowrisc** [comment]
rebased

**Comment by marnovandermaas** [comment]
Rerunning failed CI jobs, I'll approve it once this is passing.

**Comment by marnovandermaas** [comment]
Failure due to timeout is not due to this PR, it is also affecting other PRs.

**Review by marnovandermaas — APPROVED** [review]
Thanks for making this change. When @HU90m approves it I will merge it.

**Review by HU90m — APPROVED** [review]
Looks good, thanks Harry

**Pull request merged**
