### PR TITLE
[otbn/rsa] Add SCA hardening for sel_sqr_or_sqrmul

### PR DESCRIPTION
**Pull request by aewag**
As I cannot add reviewers I link you @jadephilipoom @johannheyszl @vogelpi 

This commit hardens two sources of leakage

- DMEM writeback: The selected temporary result, either sqr or sqrmul depending on the current exponent bit, is written to the DMEM. At this DMEM address the sqr result is stored. In the case of selecting the sqr result the HD of the selected result and the DMEM value is zero and in the other case a high value. This allows to distinguish exponent bits. The hardening overwrites the value at the DMEM address with a random value.
- SEL instruction: BN.SEL selects one of the two source WDRs based on the carry flag. The selection depends on the current exponent bit. This allows to distinguish exponent bits. The hardening randomizes the WDRs which contain the sqr or sqrmul results. The randomization is performed for each limb.

EDIT:
Grep into OTBN ISA SIM log to show functionality

```
000000ec | csrrs          x23, urnd, x0                  | [x23 = 0xb078d8e1, otbn.INSN_CNT = 0x000554cb]
000000f0 | andi           x23, x23, 1                    | [x23 = 0x00000001, otbn.INSN_CNT = 0x000554cc]
000000f4 | xor            x22, x22, x23                  | [x22 = 0x00000003, otbn.INSN_CNT = 0x000554cd]
000000f8 | xor            x9, x9, x23                    | [x09 = 0x00000002, otbn.INSN_CNT = 0x000554ce]
000000fc | xor            x11, x11, x23                  | [x11 = 0x00000003, otbn.INSN_CNT = 0x000554cf]
--
000000ec | csrrs          x23, urnd, x0                  | [x23 = 0xcb607848, otbn.INSN_CNT = 0x00055761]
000000f0 | andi           x23, x23, 1                    | [x23 = 0x00000000, otbn.INSN_CNT = 0x00055762]
000000f4 | xor            x22, x22, x23                  | [x22 = 0x00000003, otbn.INSN_CNT = 0x00055763]
000000f8 | xor            x9, x9, x23                    | [x09 = 0x00000003, otbn.INSN_CNT = 0x00055764]
000000fc | xor            x11, x11, x23                  | [x11 = 0x00000002, otbn.INSN_CNT = 0x00055765]
--
000000ec | csrrs          x23, urnd, x0                  | [x23 = 0x69d25f37, otbn.INSN_CNT = 0x0005576b]
000000f0 | andi           x23, x23, 1                    | [x23 = 0x00000001, otbn.INSN_CNT = 0x0005576c]
000000f4 | xor            x22, x22, x23                  | [x22 = 0x00000002, otbn.INSN_CNT = 0x0005576d]
000000f8 | xor            x9, x9, x23                    | [x09 = 0x00000002, otbn.INSN_CNT = 0x0005576e]
000000fc | xor            x11, x11, x23                  | [x11 = 0x00000003, otbn.INSN_CNT = 0x0005576f]
```

### CODE REVIEW

**Comment by johannheyszl** [comment]
@aewag and I worked on this fix. It effectively prevents a leak that was uncovered in pentesting. Alex also tested that it maintains correct function. 

More thoughts welcome @jadephilipoom

**Review by johannheyszl — APPROVED** [review]
co-developed and approve

**Review by vogelpi — APPROVED** [review]
Thanks for fixing this and the clear commit messages and comments in the code! Nice work!

Before merging this we should also get @jadephilipoom 's feedback I think.

**Comment by jadephilipoom** [comment]
Just to be more precise about what I mean asking about `bn.sel`: based on our current [coding guidelines](https://opentitan.org/book/doc/contributing/style_guides/otbn_style_guide.html?highlight=bn.sel#handling-secret-shares), I'd expect a version that uses `bn.sel` but has some dummy instructions to clear internal logic not to leak. Something like this:
```
sel_sqr_or_sqrmul:
  /* iterate over all limbs */
  loop      x30, 8
    /* load limb from dmem */
    bn.lid    x11, 0(x21)

    /* load limb from regfile buffer */
    bn.movr   x9, x8++

    /* randomize dmem with value from URND (one extra dummy call to clear) */
    bn.addi   w31, w31, 0 /* dummy */
    bn.wsrr   w0, URND
    bn.sid    x0, 0(x21)

    /* select a limb and store to dmem */
    bn.sel    w0, w2, w3, FG0.C
    bn.sid    x0, 0(x21++)

    /* dummy call to clear */
    bn.addi   w31, w31, 0

  ret
```
If  this is just a matter of stylistic preference and it seemed nicer to use the indirect registers, that's fine -- just trying to understand the rationale from the PR description about the the select instruction.

**Comment by jadephilipoom** [comment]
> @jadephilipoom is there a reason you switch x9 vs. x11 when loading the two select candidates? Otherwise let's try this:

Nope, looks like a bug on my part. Thanks for the catch!

**Comment by jadephilipoom** [comment]
Johann let me know over slack that this snippet still produced incorrect answers, so I debugged it properly and can verify that this version passes the full `rsa_1024_dec_test`, so I have high confidence this time (the bug was that the `bn.addi`s zero `FG0.C`):

```
  /* iterate over all limbs */
  loop      x30, 8
    /* load limb from dmem */
    bn.lid    x9, 0(x21)

    /* load limb from regfile buffer */
    bn.movr   x11, x8++

    /* randomize dmem with value from URND (one extra dummy call to clear) */
    bn.addi   w31, w31, 0, FG1 /* dummy */
    bn.wsrr   w0, URND 
    bn.sid    x0, 0(x21)

    /* select a limb and store to dmem */
    bn.sel    w0, w2, w3, FG0.C
    bn.sid    x0, 0(x21++)

    /* dummy call to clear */
    bn.addi   w31, w31, 0, FG1
``

**Comment by johannheyszl** [comment]
nice, yes this makes a lot of sense hehe. I stared at the code quite long but understand how I missed it :)

**Comment by johannheyszl** [comment]
This has been addressed through #25694 and can be closed.

**Comment by johannheyszl** [comment]
Thanks @jadephilipoom for the collaboration and offline chats along the way - I see #25694 is now merged, which basically applies our public coding guidelines to bring this code up to speed and it passes testing. Great example for OT project collab.

**Pull request closed without merging**
