### PR TITLE
Harder loops 2

### PR DESCRIPTION
**Pull request by alphan**

### CODE REVIEW

**Review by moidx — APPROVED** [review]

**Comment by arnonsha** [comment]
@alphan,
After this PR I cannot create rom with fake keys:
```
bazel build //sw/device/silicon_creator/rom:rom_with_fake_keys
$TEST_TMPDIR defined: output root default is '/home/users/arnons' and max_idle_secs default is '15'.
INFO: Analyzed target //sw/device/silicon_creator/rom:rom_with_fake_keys (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
.../opentitan/sw/device/silicon_creator/rom/BUILD:158:21: Linking sw/device/silicon_creator/rom/rom_with_fake_keys_fpga_cw305.elf failed: (Exit 1): clang failed: error executing command external/crt/toolchains/lowrisc_rv32imcb/wrappers/clang -o bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/silicon_creator/rom/rom_with_fake_keys_fpga_cw305.elf -Wl,-whole-archive ... (remaining 85 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/proc/self/cwd/external/lowrisc_rv32imcb_files/bin/riscv32-unknown-elf-ld: section .chip_info LMA [000000000000ff80,000000000000ff87] overlaps section .rodata LMA [000000000000f360,000000000000ff94]
clang-16: error: ld command failed with exit code 1 (use -v to see invocation)
.../opentitan/sw/device/silicon_creator/rom/BUILD:158:21: Linking sw/device/silicon_creator/rom/rom_with_fake_keys_fpga_cw310.elf failed: (Exit 1): clang failed: error executing command external/crt/toolchains/lowrisc_rv32imcb/wrappers/clang -o bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/silicon_creator/rom/rom_with_fake_keys_fpga_cw310.elf -Wl,-whole-archive ... (remaining 85 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/proc/self/cwd/external/lowrisc_rv32imcb_files/bin/riscv32-unknown-elf-ld: section .chip_info LMA [000000000000ff80,000000000000ff87] overlaps section .rodata LMA [000000000000f360,000000000000ff94]
clang-16: error: ld command failed with exit code 1 (use -v to see invocation)
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //sw/device/silicon_creator/rom:rom_with_fake_keys up-to-date (nothing to build)
INFO: Elapsed time: 1.177s, Critical Path: 0.85s
INFO: 10 processes: 6 internal, 4 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Rom generation is part of NTIL nightly runs. Please advise.

@meisnere
@jonmichelson 
@msfschaffner

**Comment by arnonsha** [comment]
bisecting shows this is the bad commit:
86fb0c67029eba35e80bc145b7f7a7b27b044139

**Comment by luismarques** [comment]
There are multiple PRs failing now seemingly due to this, so this isn't affecting only the nightly runs.
Shall we revert this until it can be reworked @alphan ?

**Comment by dmcardle** [comment]
If it reverts cleanly and CI is happy, I would say go ahead.

I think as a general policy we should feel empowered to revert commits to unblock other PRs.

**Comment by luismarques** [comment]
> I think as a general policy we should feel empowered to revert commits to unblock other PRs.

I'm generally in favor of that, as it seems to work well for LLVM.

@alphan is looking at this now so let's just wait a few minutes to see if we can fix it forward instead of reverting. I'll be back in a little bit, so I hereby delegate any reverting PR responsibilities ;)

**Pull request merged**
