### PR TITLE
[rv_dm, sival] Enable openocd debug test for sival

### LINKED ISSUE #19879: [chip-level,si-val] chip_rv_dm_perform_debug
### Test point name

[chip_rv_dm_perform_debug](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/chip_testplan.hjson#L421C16-L421C36)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [ ] existing tests `rom_e2e_jtag_debug_test_*` are DV-only
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate X

### PR DESCRIPTION
**Pull request by nbdd0121**
This also fixes the test plan to use the correct text.

Fix #19879

### CODE REVIEW

**Review by pamaury — APPROVED** [review]
The testplan change looks good to me. I assume that the existing rv_dm debug test does everything in the testplan already?

**Comment by nbdd0121** [comment]
Yeah, it's copied from the cross-referenced testplan

**Review by jwnrt — APPROVED** [review]

**Comment by nbdd0121** [comment]
For some reason asm_watchdog_{bite,bark} is now broken. The test plan only requires the debug_test, so I broke up the test suite into 5 individual tests and only enable the debug_test for sival exec_env. I'll leave the broken tests for later investigation.

**Review by pamaury — APPROVED** [review]
Looks good to me. I didn't check every line change on the file split. Another approach could have been to keep a single rust harness but introduce a CLI option to select which test to run, e.g.
```test_cmd = " --elf={rom:elf} --test=asm_interrupt_handler"```

**Pull request merged**
