### PR TITLE
[doc] Compact HW Dashboard

### PR DESCRIPTION
**Pull request by eunchan**
Removed the details of the stages and make it hovering text. The table
is compact now and get more space for `notes` column.

### CODE REVIEW

**Comment by sjgitty** [comment]
@eunchan thanks for doing this, I was hoping to cook something like this up. Unfortunately I'm not at a place where I can render this. Do you mind creating a screenshot and adding it here?

I was also thinking maybe of adding colors in the future to give even more a quick glance of maturity, but I'm not sure that would render well.

**Comment by eunchan** [comment]
image

**Comment by eunchan** [comment]
Cannot capture the hover message here. But If you move your mouse over V3, it shows `Verification Complete`.

**Comment by sjgitty** [comment]
Sounds good. One more minor thing, while you have it open. Can you make the three stages align=center within their cell? Otherwise looks good, especially if we can get the signoff values shrunk to just markdown links like you've done in a different PR

**Comment by eunchan** [comment]
Revised. Now version, hw-stages have `text-align: center;` css property.

**Pull request merged**
