### PR TITLE
[edn/doc] topology diagram to show all endpoint buses as 32b

### PR DESCRIPTION
**Pull request by mwbranstad**
Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
sorry Mark i keep on forgetting.  But if we fix the number of end points, is the edn bit-width parameterizeable? Or was it the other way around?

**Comment by mwbranstad** [comment]
@tjaychen we decided on a variable number of endpoints with a fixed bus width, and choose 32b as a happy medium point. The assumption is that if an endpoint needs more or less bits per request, they can use the prim_packer_fifo to upscale/downscale the bits within the endpoint module.

**Comment by tjaychen** [comment]
sounds good.
Thanks Mark.

**Comment by mwbranstad** [comment]
@tjaychen hey Tim, if that works, can you approve this small PR?

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
