### PR TITLE
[doc,util] Consistent spelling

### PR DESCRIPTION
**Pull request by marnovandermaas**
This is a cleanup PR that makes consistent spelling. Mainly choosing the spelling that is already used most commonly in the repository:
- randomise -> randomize
- behaviour -> behavior
- initialise -> initialize

I have also had to resolve some lint issues because of how linting is setup up on commits.

### CODE REVIEW

**Comment by marnovandermaas** [comment]
I have removed changes to files that are protected by the unauthorized change block.

**Comment by rswarbrick** [comment]
I'm not sure whether it's really worth doing this. The net result is that we'll have a style guide that requires American English in all our code. I don't feel very strongly, but I can only really see an argument for doing this if we think it will aid comprehensibility.

**Comment by marnovandermaas** [comment]
>

**Comment by marnovandermaas** [comment]
> I'm not sure whether it's really worth doing this. The net result is that we'll have a style guide that requires American English in all our code. I don't feel very strongly, but I can only really see an argument for doing this if we think it will aid comprehensibility.

Yes, I guess counting frequency will bias toward American English, so maybe this PR is not the best idea. I do like to have some consistency, so maybe a better rule is to enforce consistency within a file?

**Pull request closed without merging**
