### PR TITLE
[artys7] Re-activate ArtyS7

### PR DESCRIPTION
**Pull request by wallento**
This is a draft PR to revive the ArtyS7 board:
- Minor updates to the toplevel after changes in the codebase
- Requires smaller flash size, hence it depends on #2175 
- Add SPI/JTAG via an external FT232H (e.g., Adafruit breakout board)

Still working on documentation upgrades to reflect it.

### CODE REVIEW

**Comment by wallento** [comment]
Shall we make it configurable to use an external FT232H? I think its not very usable without it..

**Comment by imphil** [comment]
> Shall we make it configurable to use an external FT232H? I think its not very usable without it..

Just require it. There's no point in creating a use case that we actually don't need (with "we" being "you" here :smile:)

**Comment by msfschaffner** [comment]
@wallento I am sorry, I may have made your life a bit harder with #1999 and #2114 which update the pinmux and instantiate a new padctrl instance (for Bronze). The easiest way to carry these changes over to the Arty S7 target would probably be to just copy the new Nexysvideo top from #2114...

**Comment by moidx** [comment]
Closing due to inactivity. Please feel free to re-open if planning to rebase and implement these changes.

**Pull request closed without merging**
