### PR TITLE
[entropy_src/dv] Recover from RNG failures

### PR DESCRIPTION
**Pull request by martin-lueker**
This commit refactors the RNG and Base VSeq's to recover from simulated
failures of the RNG push-pull agent.

The interrupt handler thread in then the RNG Vseq  has been reorganized
to take advantage of the fact that the main thread is now responsible
for doing random reconfigurations whenever any failure has been
detected.  A RNG-failure recovery sequence has then been added to the
main thread.  The health test interrupt thus just triggers a shutdown
of all background operations and a transition to the main thread.

Furthermore, the random health-check statistics gathering operations
(which were previously only performed after health test failures), have
now been added to a general disable_dut task in the base entropy_src
vseq, along with the associated random variables.

Signed-off-by: Martin Lueker-Boden <martin.lueker-boden@wdc.com>

### CODE REVIEW

**Review by mwbranstad — COMMENTED** [review]
Seems like a reasonable refactoring, LGTM, others to approve.

**Review by weicaiyang — COMMENTED** [review]
LGTM

**Comment by martin-lueker** [comment]
Thanks, @weicaiyang.   Can I get an approval?

**Review by mwbranstad — APPROVED** [review]
Since @weicaiyang gave a LGTM review, approving now.

**Pull request merged**
