### PR TITLE
[reggen] Prefer explicit utf-8 encoding

### PR DESCRIPTION
**Pull request by sriyerg**
This fixes the chip level nightly breakage.

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

### CODE REVIEW

**Review by cindychip — APPROVED** [review]
Thanks for fixing that!

**Comment by eunchan** [comment]
Does it mean that one of the Hjson files had non-ascii content?

**Comment by rswarbrick** [comment]
Yep:
```
$ git ls-files '*.hjson' | env LC_ALL=C xargs grep -lP '[^\0-\x7f]'
hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
```

This turns out to be some "smart quotes". Fixed with #6349. I'll try to knock together a CI check for this later: I think we've agreed to avoid non-ASCII characters in source code.

**Comment by eunchan** [comment]
Thank @rswarbrick for addressing this.

**Pull request merged**
