### PR TITLE
[prim_arbiter] Add binary tree implementation for RR arbiter

### PR DESCRIPTION
**Pull request by msfschaffner**
I have been playing around with the RR arbiter after I added the FPV testbench for it, and tried a similar optimization as for the RV_PLIC in #893. Here are some normalized synthesis results in an over constrained synthesis with DC (with data width set to 32):

```
+----------------+----------+----------+---------+-----------------+
| implementation | # inputs |    WNS   |   TNS   | Normalized Area |
+----------------+----------+----------+---------+-----------------+
| original       |     8    |   0.09   |   3.3   |       100%      |
| binary tree    |     8    |   0.0    |   0.0   |        77%      |
+----------------+----------+----------+---------+-----------------+
| original       |    16    |   0.32   |  27.9   |       100%      |
| binary tree    |    16    |   0.0    |   0.0   |        80%      |
+----------------+----------+----------+---------+-----------------+
| original       |    32    |   0.55   |  75.2   |       100%      |
| binary tree    |    32    |   0.07   |   4.3   |        90%      |
+----------------+----------+----------+---------+-----------------+
| original       |    64    |   0.84   | 201.3   |       100%      |
| binary tree    |    64    |   0.15   |  26.2   |       114%      |
+----------------+----------+----------+---------+-----------------+
| original       |   128    |   1.06   | 460.5   |       100%      |
| binary tree    |   128    |   0.24   |  88.7   |       105%      |
+----------------+----------+----------+---------+-----------------+
```
Here is an additional test synthesis on FPGA:

- 1ns timing constraint (overconstrained)
- 0ns input/output delay
- device: xc7a200tffv1156-1
- Vivado 2018.3
- Data width set to 16 because of IO limits

```
+----------------+----------+----------+---------+-------+
| implementation | # inputs |    WNS   |   TNS   | #LUTs |
+----------------+----------+----------+---------+-------+
| original       |    32    |  -3.59   |  -46.5  |  226  |
| binary tree    |    32    |  -2.25   |  -47.9  |  155  |
+----------------+----------+----------+---------+-------+
```

It looks like the binary tree implementation can achieve better timing under high timing pressure. Area wise it can get a bit larger than the original implementation, though, when synthesized into ASIC logic gates. On FPGA, bintree seems to map better in any case (probably since Vivado does not optimize the PPC part well).

In a top-level sim I do not see a big impact on the area/timing of the crossbar (PPC tends to be a tick smaller in terms of area). Hence I suggest to keep both implementations alive and default to `PPC` at the moment since it is a simpler, more understandable implementation, and may result in somewhat smaller area when the design is not under tight timing pressure. `BINTREE` could be used if the arbiter module is really on the critical path and/or has to arbitrate among many requesters.

FPV passes for both implementations.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by eunchan** [comment]
OK both implementations look like increasing O(logN). There look like constant X to the logic depth.. which PPC implementation is around 1.8X than BINTREE. Maybe XOR operation at the end may result the diff. 

Anyway its good to have both implementations. Thanks for the work!

**Comment by msfschaffner** [comment]
Yes you are right, both implementations should have the same scaling behavior. I.e., area wise, both should be O(N), and timing wise both should be O(log(N)) if the synthesis tool correctly optimizes the PPC part.

Anyway, PPC seems to result in somewhat smaller implementations on ASIC logic when timing pressure is low, Whereas BINTREE is better on FPGA and high timing pressure. So there is a trade off to be made, and hence it is good to keep both implementations around, I think.

**Comment by cindychip** [comment]
Thanks Michael, assertion related LGTM. The RTL looks cool to me, but probably better let RTL designers approve it :)

**Comment by eunchan** [comment]
The implementation looks good to me. 
As Michael mentioned, in some case PPC is better , and BINTREE is better on FPGA. So, I think it is better to derive the parameter from a package file, which can be changed depending on the implementation target. 

Also, It will be easier to understand if the module is separated into two modules `prim_arb_ppc`, `prim_arb_bintree` and `prim_arbiter` instantiates based on the parameter. WDYT?

**Comment by msfschaffner** [comment]
@eunchan sure, I have split the module into two modules. For now there are only two places where the arbiter module is instantiated (`prim_sram_arbiter` and `tlul_socket_m1`). In order to not mess up the dependencies on packages, I have placed the TLUL related parameter inside the `tlul_pkg`, and in the sram arbiter I just expose it as a module parameter. Both default to `"PPC"` at the moment. If needed, we can make these selections dependent on the target later on (once we have the ASIC target in place).

**Pull request merged**
