### PR TITLE
[topgen] Don't dump hjson by default

### PR DESCRIPTION
**Pull request by rswarbrick**
This might be handy for debugging, but it isn't really needed most of
the time. We're also currently checking it in: since it changes
frequently, this causes a whole host of merge conflicts for no real
benefit.

### CODE REVIEW

**Review by imphil — APPROVED** [review]
I hope you realize that this change will significantly bring down our productivity as measured in lines changed. And it'll be your fault.

**Comment by eunchan** [comment]
I think we have more dumps of hjson (e.g: xbar) . Do you think also it is good to move them optionally?

**Review by eunchan — APPROVED** [review]

**Comment by tjaychen** [comment]
could we add a note to this in the topgen usage documentation (i honestly can't remember where it is)

**Comment by imphil** [comment]
> could we add a note to this in the topgen usage documentation (i honestly can't remember where it is)

https://docs.opentitan.org/doc/rm/topgen_tool/

But don't overdo the docs there, I'm looking into rewriting some of it as well.

**Comment by msfschaffner** [comment]
Just a note here that we may have to devise a way to access some of the generated `RndCnsts` for scripts like the ROM generation + scrambling.

If this generated Hjson is not checked in anymore, there are a couple of options I can think of:
1) always run topgen first, and then consume the generated debug Hjson in the script that needs access to the `RndCnsts`
2) write out the `RndCnsts` into a separate HJSON file and check it in
3) split out the `RndCnsts` generation into a class that can be imported in other scripts. As long as you provide that class with the seed and `RndCnst` definitions/order from `top_*.hjson`, you are able to regenerate the constants deterministically on the fly.
4) Don't use `RndCnsts` for the ROM scrambling. Instead, create a separate script that generates the netlist constant and the ROM contents.

For OTP/LC I have done something similar to 4), since I needed to impose some more constraints on the generated life cycle constants.

For the ROM checker scrambling key, one of the other methods could probably work as well, since there are no additional constraints that need to be imposed.

**Review by msfschaffner — APPROVED** [review]

**Comment by imphil** [comment]
@msfschaffner Good point. I'm currently looking at restructuring some of topgen and I'll keep that in mind. I'll follow up with what I'm actually planning once I know myself (I thought I did a couple times now, and then always found another "interesting feature" that I forgot about).

**Comment by eunchan** [comment]
If current Random Constants is consumed from top_*.gen.hjson, I think it would be better to hold this PR until we find solutions.

**Comment by msfschaffner** [comment]
@eunchan, AFAIK we do not consume them from the generated hjson file at the moment. OTP/LC already uses a different mechanism, and the ROM generation / scrambling script does not yet exist.

**Comment by eunchan** [comment]
OK. Thanks for explanation,

**Comment by rswarbrick** [comment]
At the moment, the PR fails CI because of downstream stuff that depends on the contents of the hjson. I'll have a look this morning to see whether there's an easy fix.

**Comment by rswarbrick** [comment]
Hmm, that's not going to work easily. Let's close this for now and put up with the churn. Hopefully, we can clean up some of the topgen stuff in future.

**Pull request closed without merging**
