### PR TITLE
[doc] Fix typos, mostly in Markdown files

### LINKED ISSUE #14805: Fix typos in documentation (Markdown, code comments, etc.)
* #14794 
* #14802 
* #15154

### PR DESCRIPTION
**Pull request by dmcardle**
Fixes #14805

### CODE REVIEW

**Review by timothytrippel — APPROVED** [review]

**Comment by dmcardle** [comment]
I noticed this was failing the quality check, so I rebased on a new commit where I ran `util/fix_trailing_whitespace.py`.

**Review by tjaychen — APPROVED** [review]
lgtm.

btw, dumb question, did you actually read through all of these?? or is there some spell check tool we can apply to an entire repo or something?

**Comment by dmcardle** [comment]
> lgtm.
> 
> btw, dumb question, did you actually read through all of these?? or is there some spell check tool we can apply to an entire repo or something?

No, I didn't read every file, but I did read the context for each change :)

Basically, I ran `find . -name '*.md'` and executed `aspell check`, which pops up a curses interface and walks you through possible misspellings. There's a lot of noise, so I ended up ignoring 80% of the suggestions. Not quite ready for automation. (I'm pretty sure I've seen a spelling-correction bot on the Chromium Gerrit instance before — I may take a peek at how that works.)

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
Thanks for the cleanup!

**Pull request merged**
