### PR TITLE
[bazel] e2e_bootup_no_rom_ext_signature not broken

### PR DESCRIPTION
**Pull request by drewmacrae**
With this test marked as broken it wont run on the cw310

Signed-off-by: Drew Macrae <drewmacrae@google.com>

### CODE REVIEW

**Review by alphan — APPROVED** [review]
Hmm, I thought I removed this in #13193, didn't I?

**Comment by drewmacrae** [comment]
We were testing this in CI earlier, but I just pushed a change that drops it.

**Comment by drewmacrae** [comment]
Yeah, I was working with an out of date fetch

**Comment by alphan** [comment]
> Yeah, I was working with an out of date fetch

Ah, ok, thanks!

**Pull request closed without merging**
