### PR TITLE
[tlul_sram_byte] Remove temporary read-modify-write workarounds

### PR DESCRIPTION
**Pull request by msfschaffner**
This removes a temporary workaround (#7461) that has been put into place avoid
failures in DV until the scoreboard has been rewritten.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by weicaiyang** [comment]
@msfschaffner 

TL interface gets stuck in this case. There are 2 accepted write transaction. Design asserts d_valid for one cycle then drop. After that, there is no more d_valid. Can you take a look?

Screen Shot 2021-12-08 at 4 43 21 PM

Please use this command to open the waves.
> ot_debug -j smart:5084d1ac-bf8a-4c4c-b649-bcaa3503b04f

**Comment by weicaiyang** [comment]
@msfschaffner 

I reran with your push, but I still see the `d_valid` drops without `d_ready` and no longer asserts in this waveform.
ot_debug -j smart:34512a7d-760a-4b6b-ad23-cb25e841e4b2

**Comment by msfschaffner** [comment]
Hey @weicaiyang - yes I see it. I am still rewriting parts of that module. Will ping you again once I am done (you may see more force pushes here in the meantime).

**Comment by msfschaffner** [comment]
@weicaiyang I think I found all bugs now - or at least the ones that were failing in that batch regression ;).
Can you take a look on your end as well?

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks @msfschaffner 
Most of tests are passing. I found an DV issue as well, will fix it soon.

**Comment by weicaiyang** [comment]
> LGTM, thanks @msfschaffner Most of tests are passing. I found an DV issue as well, will fix it soon.

Hmmm, it's more like a design issue.

**Comment by tjaychen** [comment]
sorry i'm a bit late to the party, has an issue been files for the
potential design issue?

**Comment by weicaiyang** [comment]
> sorry i'm a bit late to the party, has an issue been files for the potential design issue?

I updated SRAM TB so that we can remove the temp design workaround (#7461). While removing the workaround, we discovered a few design issues like no d_valid for request. @msfschaffner has fixed all the issues. But we didn't file any issue.

**Pull request merged**
