### PR TITLE
[rstmgr, top] Support for Shadow Resets

### PR DESCRIPTION
**Pull request by tjaychen**
- Generate shadow resets at the leaf level. This will
  trigger shadow registers to fire if the contents become different.

- Shadow resets are not done at the root node because a reset of
  the root will wipe many downstream resets.

- The shadow resets may release at different times. As a result,
  it is necessary to add some downstream back-pressure to present
  this case from becoming an issue.  This will be done in a different
  PR based on the results of the cdc regfile proposal.

- Update aes / alert_handler to accept shadow resets. Other modules,
  if updated with shadow resets, will need to change accordingly.

- Need to double check the shadow reset does not get removed by synthesis.

### CODE REVIEW

**Comment by eunchan** [comment]
So, If i understad correctly, this PR is for creating a shadow reset port IF shadow registers exist in the IP. 
The behavior of shadow reset is not yet determined in this PR (assuming it is controlled at the top-level?)

**Review by eunchan — APPROVED** [review]

**Review by msfschaffner — APPROVED** [review]

**Comment by tjaychen** [comment]
> So, If i understad correctly, this PR is for creating a shadow reset port IF shadow registers exist in the IP.
> The behavior of shadow reset is not yet determined in this PR (assuming it is controlled at the top-level?)

actually the shadow reset is implemented in this PR also. It just ends up being a copy of the normal one.

**Review by cindychip — APPROVED** [review]
lgtm

**Comment by tjaychen** [comment]
cindy do you think i should file an issue to track the extra DV related to
this?

**Comment by cindychip** [comment]
Hi Tim, yes please, that would be great.

**Comment by tjaychen** [comment]
assuming CI passes, i will merge this in eod tomorrow unless there are objectiosn.

**Comment by cindychip** [comment]
I filed an issue here: https://github.com/lowRISC/opentitan/issues/7845 to track the DV work :)

**Comment by tjaychen** [comment]
> I filed an issue here: #7845 to track the DV work :)

Thanks @cindychip ! I finally got this passing!

**Pull request merged**
