### PR TITLE
[spi_device] Latch read command address only for Readbuffer

### PR DESCRIPTION
**Pull request by eunchan**
Related Issue: https://github.com/lowRISC/opentitan/issues/14538

This commit revises logic to latch read address only pointing to the
read buffer space.

However, this still does not track the last byte host read. It latches
the address field in the read command. The issue is being tracked in
https://github.com/lowRISC/opentitan/issues/14586

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks

**Comment by weicaiyang** [comment]
Found a very corner case

When a mailbox read happens to read all the way to the last byte (not crossing), `addr_in_mailbox` drops and the address is latched in `last_read_addr`.
Screen Shot 2022-08-25 at 3 44 26 PM

waves:
/mnt/disks/filestores/opentitan-shared/users/weicai/scratch/buf_update/spi_device-sim-vcs/18.spi_device_flash_all/latest

**Comment by eunchan** [comment]
Oh, I misunderstood the logic. Actually the logic latches the read address not only in the address field but also while reading the address fully.

**Comment by eunchan** [comment]
Copied from #14586 

Hum, logic is already tracking the read address. However, it tracks the next byte address not the current one except when it latches the address field.

So, suggestion is:

- do not latch address field
- latch the current address in `MainOutput`

**Comment by weicaiyang** [comment]
now the address is one byte less than before.
Assume we send 1 byte, what is the last_read_addr, 0 or 1? (with this change it's 0. without, it's 1)

In passthrough mode, the address will be latched to `last_read_addr`. Is it expected?

**Comment by eunchan** [comment]
> now the address is one byte less than before. Assume we send 1 byte, what is the last_read_addr, 0 or 1? (with this change it's 0. without, it's 1)
>
What I expect with the change is (for example):

Read command 0x000A then read two bytes. -> the `last_read_addr` is 0x000B (as host read 0x000A, 0x000B).
Does it match to your observation?
 
> In passthrough mode, the address will be latched to `last_read_addr`. Is it expected?
>
Yes. That is expected. The logic runs always.

**Comment by weicaiyang** [comment]
> What I expect with the change is (for example):
Read command 0x000A then read two bytes. -> the last_read_addr is 0x000B (as host read 0x000A, 0x000B).
Does it match to your observation?

an extreme corner case - after reset, issue a read for 1 byte, last_read_addr will be 0, right?

> In passthrough mode, the address will be latched to last_read_addr. Is it expected?
Yes. That is expected. The logic runs always.

Should it be a future release to fix it? Assume user uses passthrough mode, then switch to flash mode. last_read_addr can be confusing

**Comment by eunchan** [comment]
> > What I expect with the change is (for example):
> > Read command 0x000A then read two bytes. -> the last_read_addr is 0x000B (as host read 0x000A, 0x000B).
> > Does it match to your observation?
> 
> an extreme corner case - after reset, issue a read for 1 byte, last_read_addr will be 0, right?
>
No. It should show the exact address the host read. (for example, if read 0x00000A, then `last_read_addr` is 0x00000A).
> 
> > In passthrough mode, the address will be latched to last_read_addr. Is it expected?
> > Yes. That is expected. The logic runs always.
> 
> Should it be a future release to fix it? Assume user uses passthrough mode, then switch to flash mode. last_read_addr can be confusing
>
Tracking which address host read in passthrough seems to be useful in my opinion. it would be good to add an option to enable/disable the track.

**Comment by weicaiyang** [comment]
> > > What I expect with the change is (for example):
> > > Read command 0x000A then read two bytes. -> the last_read_addr is 0x000B (as host read 0x000A, 0x000B).
> > > Does it match to your observation?
> > 
> > 
> > an extreme corner case - after reset, issue a read for 1 byte, last_read_addr will be 0, right?
> 
> No. It should show the exact address the host read. (for example, if read 0x00000A, then `last_read_addr` is 0x00000A).
> 
> > > In passthrough mode, the address will be latched to last_read_addr. Is it expected?
> > > Yes. That is expected. The logic runs always.
> > 
> > 
> > Should it be a future release to fix it? Assume user uses passthrough mode, then switch to flash mode. last_read_addr can be confusing
> 
> Tracking which address host read in passthrough seems to be useful in my opinion. it would be good to add an option to enable/disable the track.

sounds good. Thanks

**Comment by weicaiyang** [comment]
BTW, we need to update the spec. Now it shows 0xABCD_E07F

>  For instance, if the host system issues 0xABCD_E000 and reads 128 (or 0x80) bytes, the LAST_READ_ADDRESS after the transaction will show 0xABCD_E080

**Pull request merged**
