### PR TITLE
[uart,rtl] Increase buffer size to 128

### LINKED ISSUE #16549: Hardware assisted UART -> USB forwarding
Before OpenTitan, Google has been using internally developed Security Chips, and has recently chosen to use Rust and TockOS as basis for the firmware on those chips.  TockOS discourages performing device driver logic in interrupt handler context, as doing so necessarily means that Rust security guarantees cannot be verified by the compiler.  Most device drivers use "bottom half" handlers exclusively, which run in ordinary kernel context, but can suffer from significant latency compared to actual interrupt handlers.  On the previous Google Security Chip, only two device drivers needed to rely on low-latency interrupt handling for their correctness: the I2C target driver, and the UART driver.

OpenTitan I2C hardware has clock stretching features, and ability to recover transaction boundaries through its acq_fifo, meaning that on OpenTitan, the Google I2C driver does not need low-latency handling.  This leaves only the UART driver.  We further worry that flash erase/write for instance could cause latency even for interrupt context code, and this amplifies the desire to look for ways of eliminating the need for low-latency processing of the OpenTitan UARTs.

The single task that requires low-latency processing is forwarding of incoming UART data to a particular USB device endpoint,  such that an external debugger (SuzyQ) can be used to extract logging info from other chips in the device (AP, EC, FPMCU).

I realize that what I am asking here is a major and invasive feature, and I should probably have asked a year ago, but I want to put it in writing now anyway, since the potential benefit is significant.

### Feature request
The UART IP will have a new "USB RX mode" bit, which controls whether incoming complete bytes from the hardware shift register go into the RX FIFO as they currently do, or instead go directly into one of the 32 buffers of the USB IP.
When enabled, two of the USB buffers are reserved for use by this UART, and should not be accessed by the CPU.  (The allocation could be static, that is e.g. UART0 can only use buffer 0 and buffer 1, UART1 can only use buffer 2 and buffer 3, etc.)
When enabled, the UART IP will directly manipulate the INCFG[..] control signals to a particular endpoint (allowing a configurable endpoint would be nice, but static allocation would be OK as well,) in such a way that once either a 64-byte USB buffer has become full, or the UART RX timeout expires while there are some characters in one 64-byte buffer and the other 64-byte buffer is empty, then the RDY signal is asserted to the USBDEV IP.

There are many details to the proposal, which need to be worked out.

### PR DESCRIPTION
**Pull request by GregAC**
This a draft as it's incomplete but creating the PR now for visibility.

There are regression failures with this change I have yet to look into plus we need to discuss the appropriate size to move to and what we switch watermark levels to.

Fixes #16549

### CODE REVIEW

**Comment by GregAC** [comment]
@jesultra this increases UART buffer sizes to 64 from 32. Can you confirm:

- If 64 is the appropriate buffer size
- If the new watermarking levels are appropriate, see table below

| TX/RXILVL setting | RX watermark level | TX watermark level |
|-|-|-|
| 0 | 1 | 4 |
| 1 | 8 | 8 |
| 2 | 16 | 16 |
| 3 | 32 | 32 |
| 4 | 62 | - |

**Comment by johngt** [comment]
Based on conversation - the understanding is to move to 128 bytes and increase watermark bits; 3 to 4.

**Comment by cfrantz** [comment]
> To confirm you want settings like this?
> 
</snip>
> We can of course have a 126 level for the TX as well but maybe doesn't make a huge amount of sense (RX FIFO almost full obviously useful, TX FIFO just beginning to empty less so).

Agreed about 126 for TX.  I also think the TX watermark level of 1 is dubious, but I'm giving consideration to the value of symmetry in the programming interface.

As long is it isn't burdensome to implement, your previous table (1-126 for RX, 1-64 for TX) looks good to me.

**Review by msfschaffner — APPROVED** [review]
Thanks @GregAC - I am fine with these changes.

Regarding the levels, I have a slight preference towards symmetry as well.

**Review by marnovandermaas — APPROVED** [review]
LGTM, thanks Greg!

**Comment by marnovandermaas** [comment]
Rerunning failed CI tests.

**Review by msfschaffner — APPROVED** [review]
LGTM

**Pull request merged**
