### PR TITLE
[kemgyr] Fix input checks when kmac masking is disabled

### PR DESCRIPTION
**Pull request by tjaychen**
- the input check module already had the feature, but the
  parameter was not hooked up.

Also revert #13058

### CODE REVIEW

**Review by moidx — APPROVED** [review]
Tested on CW310.

**Comment by tjaychen** [comment]
> Tested on CW310.

nice!

**Comment by milesdai** [comment]
#13058 disables the fpga test for keymgr temporarily while this PR is in flight. Could you rebase on top of it and re-enable the test (just add the change to undo #13058) in this PR?

**Comment by timothytrippel** [comment]
#13058 has been merged.

**Comment by tjaychen** [comment]
> #13058 disables the fpga test for keymgr temporarily while this PR is in flight. Could you rebase on top of it and re-enable the test (just add the change to undo #13058) in this PR?

Sounds good, i've reverted that commit in my latest push, can you have a look?

**Comment by milesdai** [comment]
> > #13058 disables the fpga test for keymgr temporarily while this PR is in flight. Could you rebase on top of it and re-enable the test (just add the change to undo #13058) in this PR?
> 
> Sounds good, i've reverted that commit in my latest push, can you have a look?

Yup - LGTM!

**Pull request merged**
