### PR TITLE
[usbdev,dv] include sequence name in testplan

### PR DESCRIPTION
**Pull request by MubashirSaleem775**
Incorporates the sequence name into the test plan to ensure its inclusion in future regression testing.

### CODE REVIEW

**Comment by MubashirSaleem775** [comment]
@rswarbrick please review this.

**Comment by rswarbrick** [comment]
Thanks for making this change. It's not quite going to work, because the test name needs quotes around it (`["usbdev_in_stall"]`) and these missing quotes are causing CI to fail. Would you mind fixing this up?

**Comment by MubashirSaleem775** [comment]
@rswarbrick

**Comment by rswarbrick** [comment]
The CI failure is a slightly flaky FPGA test (and definitely not caused by this change). Happy to merge.

**Review by rswarbrick — APPROVED** [review]

**Pull request merged**
