### PR TITLE
[pwm] Wire up integrity alert 

### PR DESCRIPTION
**Pull request by msfschaffner**

### CODE REVIEW

**Comment by tunghoang290780** [comment]
@msfschaffner @weicaiyang @cindychip Do I need to check alert signals at the unit level?

**Review by tunghoang290780 — APPROVED** [review]
LGTM!

**Comment by msfschaffner** [comment]
> @msfschaffner @weicaiyang @cindychip Do I need to check alert signals at the unit level?

Yes, although I believe for this particular one @weicaiyang is developing partially automated tests.
Is that right @weicaiyang?

**Comment by weicaiyang** [comment]
> > @msfschaffner @weicaiyang @cindychip Do I need to check alert signals at the unit level?
> 
> Yes, although I believe for this particular one @weicaiyang is developing partially automated tests.
> Is that right @weicaiyang?

Right, the automatic tests (tl_intg_err and alert_test) should cover this alert, so we don't need to add other tests for it.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Pull request merged**
