### PR TITLE
[dif/alert_handler] Remove artificial alert # limit

### PR DESCRIPTION
**Pull request by mcy**
Closes https://github.com/lowRISC/opentitan/issues/3826

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
looks good from my side.

**Comment by mateenfaisal** [comment]
You may want to add @asb as a reviewer.

**Review by gkelly — APPROVED** [review]
Reaffirming that this looks good. @mcy, if this is ready to go can you merge?

**Comment by asb** [comment]
No need for me to review this, as it's had plenty of eyes on it with @msfschaffner and @gkelly.

**Comment by moidx** [comment]
Hi @mcy, do you still want to submit this change?

**Comment by timothytrippel** [comment]
This fix seems outdated now that [#6136](https://github.com/lowRISC/opentitan/pull/6136) has been merged. Specifically, [#6136](https://github.com/lowRISC/opentitan/pull/6136) has been merged, which unpacks the enable/class-assignment registers so there no bit-index computations needed now.

I will simplify this fix in a new PR, and mark as closed upon merge of the new PR.

**Pull request closed without merging**
