### PR TITLE
[alert_handler] Move into D2S

### PR DESCRIPTION
**Pull request by msfschaffner**
This PR should not be merged before #10272 has landed.

### CODE REVIEW

**Review by tjaychen — APPROVED** [review]
pending merge of the dependent PR.

**Comment by msfschaffner** [comment]
Thanks!

This has now been rebased onto #10272.

**Review by vogelpi — APPROVED** [review]
LGTM!

**Review by cdgori — COMMENTED** [review]
post-merge but all LGTM

**Pull request merged**
