### PR TITLE
[rstmgr] unr review clean up

### PR DESCRIPTION
**Pull request by tjaychen**
- fixes https://github.com/lowRISC/opentitan/issues/11121
- remove software checks for leaf resets that do not require it.

### CODE REVIEW

**Comment by tjaychen** [comment]
@matutem can you give this a try?

**Comment by matutem** [comment]
This is excellent: we won't need a UNR file with this until V3!

**Review by matutem — APPROVED** [review]
LGTM

**Comment by tjaychen** [comment]
> This is excellent: we won't need a UNR file with this until V3!

o were you able to double check this actually achieves what we want?

**Pull request merged**
