### PR TITLE
[entropy complex blocks] D2S reviews completed

### LINKED ISSUE #10095: CSRNG D2S Review AIs
Action Items:

- [x] [mark, chris] discuss offline how to rename LOGIC.INTEGRITY -> ref: https://github.com/lowRISC/opentitan/pull/10118
- [x] [mark, chris] need to align standardized names with terminology in comportability spec ->  ref: https://github.com/lowRISC/opentitan/pull/10118
- [x] [chris] align countermeasure spreadsheet 
- [x] [miguel] to follow up on {Key,v} register issue with labs -> https://github.com/lowRISC/opentitan/issues/10477 (issue opened so checking this as completed)
- [x] [mark] add MUBI protection for “flag0” -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] add comment describing that repetition checks are done in EDN. same thing for the repetition check, comment on why only 64bits are checked. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark, chris] do not decode MUBI at the top and route single bit, but use a non-flopped sync and consume multiple MUBI where used in RTL -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] remove csrng_track_sm FSM, add observation points to existing sparse FSMs. ->  not changing
- [x] [mark] csrng_cmd_stage counter error: feed this signal into FSM to locally escalate. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] csrng_ctr_drbg_gen counters: this would be a good one to harden. Decision is to add prim_count to 32bit counter. Need to check whether 96bit counter should be duplicated as well. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] Bus Consistency: would make sense to wire up the alerts with the main FSM. Local escalation. -> Not doing, statistically possible, so a recov, not fatal alert. Confirm with Chris.
- [x] [mark, chris, vogelpi] u_prim_fifo_genbits: This should probably be changed to OutputZeroIfEmpty = 0. -> https://github.com/lowRISC/opentitan/pull/10132
- [x] [mark] list LC gate for debug as a CM in Hjson. -> ref: https://github.com/lowRISC/opentitan/pull/10118
- [x] [mark] Add a prim_mubi4_sync block to buffer the flag0 field. -> https://github.com/lowRISC/opentitan/pull/10132

### LINKED ISSUE #10096: Entropy_Src D2S Review AIs
Action Items:
- [x] [Martin] Close on chip-level test issue (V1?)
- [x] [Martin] Update testbench to include entropy dropping event due to health check failure
- [x] [Tim, msf] need to add new asset (RNG) and countermeasure names (REGWEN) -> #10070
- [x] [Tim, msf] File issue for potential FIFO enhancement: add prim_count for pointers -> #10069
- [x] [Mark] Remove qualification of FSM invalid state signals and prim_count -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Martin] File issue for future improvements: split out fatal error conditions into indication CSRs -> It was determined that the ERROR_CODE status register does this function, so no issue was opened.
- [x] [Mark] use >= instead of == for counters -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Martin] file issue to clean up recursively instantiated module #10160
- [x] [Chris/Mark] audit MUBIs -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [Mark] make LOGIC.INTEGRITY more specific by adding an instance name -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [Mark] document fatal FIFO alerts-> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] document why multiple parameters are not shadowed in the CSRs (maybe in a short security section) -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Chris/Mark] go through Hjson and update all CM/ASSET names according to feedback -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [Mark] add countermeasure names to RTL comments, format to be used  “// SEC_CM: [INSTANCE].ASSET.CM_TYPE”. See also https://github.com/lowRISC/opentitan/issues/10071, https://github.com/lowRISC/opentitan/pull/10118
- [x] [Msf] create an issue for the tooling extensions needed for checking the above annotations #10071
- [x] [Mark] exchange “entropy_src_cntr_reg” with “prim_count” and hook up to alerts, don’t forget to add labels -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] add sha3 CM labels -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] add mubi fields to prim_mubi4_sync, then fan out to consumers -> https://github.com/lowRISC/opentitan/pull/10126
- [x] [Mark] complete PR for issue https://github.com/lowRISC/opentitan/issues/10388 -> https://github.com/lowRISC/opentitan/pull/10520

### LINKED ISSUE #10262: EDN D2S Review AIs
- [x] [msf] talk to tim about burying MUBI/LC signals, maybe add sec_buf to the sync?
- [x] [mark] use prim_mubiX_sync (flopless) to create multiple copies and consume the MUBI at the endpoints with multiple decoding functions (applies to CSRNG, entropy_src, EDN) -> https://github.com/lowRISC/opentitan/pull/10132, https://github.com/lowRISC/opentitan/pull/10448
- [x] [mark] consider describing in the Hjson description which FSMs are protected. -> https://github.com/lowRISC/opentitan/pull/10448
- [x] [mark] rename LOGIC.INTEGRITY to something like ENTROPY_IN.BUS.CONSISTENCY to make it more specific -> https://github.com/lowRISC/opentitan/pull/10118
- [x] Pending comment fix related to this CM: #10032
- [x] [mark] add security note to documentation for the user to do a 32bit consistency check since EDN only does this at the 64bit level. Note that this may only be needed for high-quality entropy consumers. E.g. only if FIPS bit is being checked. -> also make an issue for OTBN, keymgr, tag Tim and OTBN guys. -> https://github.com/lowRISC/opentitan/pull/10448
- [x] [mark] Regarding boot request mode: add security note to documentation. This is not important if we do not care about the FIPS bit, but if we do care about the FIPS bit, consumers need to pull entropy until the FIPS bit is set to 1 to make sure the quality is guaranteed.  -> also make an issue for OTBN, keymgr, tag Tim and OTBN guys. -> https://github.com/lowRISC/opentitan/pull/10448
- [x] [mark] Need to align standardized names with terminology -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [chris] Need to add a countermeasure to the spreadsheet for any Mubi used, EDN.CTRL.MUBI
- [x] [mark] Add EDN.CONFIG.REGWEN -> https://github.com/lowRISC/opentitan/pull/10118
- [x] [chris] Update spreadsheet
- [x] [mark] documentation says es_fifo_err interrupt cause is (push & full) | (pop & empty) - it’s missing (full & empty) condition from the RTL -> https://github.com/lowRISC/opentitan/pull/10448

### PR DESCRIPTION
**Pull request by mwbranstad**
Approval of this PR will close all related review issues and signify
that entropy_src, csrng, and edn blocks have completed D2S checkpoints.
Closes #10095.
Closes #10096.
Closes #10262.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Comment by cdgori** [comment]
I added the RTL and security council roles from all 3 D2S reviews (ES, CSRNG, EDN) as reviewers to this PR.  But, this is marked as draft still (I believe pending #10621 merging and resolution of AES countermeasure labeling from #10132).

If those 2 are done, this looks good from my side.

**Comment by msfschaffner** [comment]
Thanks @mwbranstad. I'll mark this as ready for review with the understanding that it should not be merged until the other PRs you mentioned have landed.

**Comment by msfschaffner** [comment]
@mwbranstad I realized that not all D2S checklist items have been checked off.
I've added a commit in this PR to do that (rebased so that it comes before the `.prj.hjson` update commit).

**Review by cdgori — APPROVED** [review]
I think #10132 updates are in (I see the AES block countermeasure tags in the hjson), so approving this but it's not to be merged before #10621

**Comment by msfschaffner** [comment]
Alright, all updates should be in by now.

If we all agree that https://github.com/lowRISC/opentitan/issues/9853 does not gate D2S, we can move this in and declare D2S for the entropy complex.

**Review by msfschaffner — APPROVED** [review]
LGTM from my side, but would be good to get another vote.

**Comment by cdgori** [comment]
I see #10621 is merged now, and I also agree that #9853 is functional (or 99% functional) and shouldn't gate D2S.  I think we are good to merge this and move all 3 entropy blocks to D2S!

**Comment by msfschaffner** [comment]
Thanks for checking @cdgori. I think we can proceed then. If anyone spots something that slipped through the cracks, please reach out or flag it via an issue.

**Pull request merged**
