### PR TITLE
[otbn] Update block architecture diagram

### LINKED ISSUE #3517: [otbn] Update (block diagram in) documentation to match RTL implementation
Now we have the bignum side RTL we should update the specification so diagrams and descriptions better match reality.

Also include data/control path for security hardening discussions.

> estimate 8

### PR DESCRIPTION
**Pull request by GregAC**
Direct link to new diagram: https://raw.githubusercontent.com/GregAC/opentitan/31585a31a42431ffea8af9e2d7f9b5d57c4bc311/hw/ip/otbn/doc/otbn_blockarch.svg

I've aimed to include all control/data paths without it turning into too much of a rats nest!

The controller does monitor bits of data for generating errors and such which aren't on there. Plus the loop stack can get iterations from the base register file which also isn't explicitly on there.

Signed-off-by: Greg Chadwick <gac@lowrisc.org>

Fixes #3517

### CODE REVIEW

**Comment by rswarbrick** [comment]
Very swish! One nitty comment: I wonder whether the two crossing green lines in the LSU need a "kink" to make it clear that they aren't joined? I know it's kind of obvious that they can't be, but the diagram doesn't have "blobs" on intersections where they do.

The only other nitty comment is that you can lose one wiggle by moving the vertical green line between the WDRs, BN ALU and MAC to the right. (Having flashbacks to hours spent playing in gschem!)

**Review by rswarbrick — APPROVED** [review]

**Review by imphil — APPROVED** [review]
Nice! 

(For next time: can you add a `Fixes: #xxx` line to the commit to have a better link to the issue?)

**Comment by GregAC** [comment]
Implemented @rswarbrick's suggested changed. There's now a little wriggle at all places where two lines of the same colour cross.

Direct link is now: https://github.com/lowRISC/opentitan/blob/d63a5468cefb66d7ea896fa88bf2634f22e2cdcd/hw/ip/otbn/doc/otbn_blockarch.svg

Fixes line was added in an update immediately after my first push.

**Comment by rswarbrick** [comment]
> Fixes line was added in an update immediately after my first push.

Ah, but I think that doesn't work unless it appears in the PR description. My personal feeling is that GitHub issue numbers are kind of optional in commit messages (since I have this naive belief that I should be able to understand the commit history without a web browser!). You can always link an issue with the "linked issues" button on the right.

**Comment by rswarbrick** [comment]
Thanks for adding the kink! If you fancy doing this before pushing, maybe the GPRs should start at x2? (Since x0 is constant and x1 is the call stack) - I noticed it in the meeting on Wednesday but forgot to mention it, sorry!

**Comment by GregAC** [comment]
> Ah, but I think that doesn't work unless it appears in the PR description.

The issue in question does have a line saying: 'GregAC added a commit to GregAC/opentitan that referenced this issue 2 days ago' and the commit is the only place it's referenced, but yes it doesn't appear in 'linked issues', guess you have to remember to include it in the commit message first time round so it ends up in the PR description as you say.

**Comment by GregAC** [comment]
Ok GPRs are now x2 .. x32 I moved the call stack on top and added an '(x1)' to it also

https://github.com/lowRISC/opentitan/blob/b78e0eb89752523c6fb631a17f9d38b1faa5768d/hw/ip/otbn/doc/otbn_blockarch.svg

**Review by rswarbrick — APPROVED** [review]
Looks great!

**Pull request merged**
