### PR TITLE
[rv_core_ibex] Minor cleanup

### PR DESCRIPTION
**Pull request by tjaychen**
- re-name reg to cfg, this removes the reg_reg duplication
- cfg is appropriate here since there is almost no function
  attached to that interface
- minor clean-up of various hjson / python to remove things no
  longer used.

### CODE REVIEW

**Review by imphil — APPROVED** [review]
LGTM. Can you squash into a single commit before merging to make the changes atomic?

**Comment by tjaychen** [comment]
ah yes, thanks for reminding me again.
is there any way you think...we can stop merge if there is more than one
commit, to force everyone (okay me) to squash?
i seem to always forget for whatever reason.

**Comment by imphil** [comment]
> is there any way you think...we can stop merge if there is more than one
> commit, to force everyone (okay me) to squash?

Not really, because there are good reasons to have more than one commit in a PR. For example here: https://github.com/lowRISC/opentitan/pull/7371

(Not that it matters here, but this PR would also be a good example for "multiple commits in a PR": Have one commit per logical change, e.g. one for the reg -> cfg rename, another one for removing some dead code in the Hjson, etc.)

**Comment by rswarbrick** [comment]
>> is there any way you think...we can stop merge if there is more than one
>> commit, to force everyone (okay me) to squash?
>>
> Not really, because there are good reasons to have more than one commit in a PR. For example here: #7371

Well, it is *technically* possible, but we'd need to configure CI somehow to run on each commit in the PR, to make sure nothing broke "in the middle". Of course, that would massively amplify the CI burden, so it's probably not a great idea.

**Pull request merged**
