### PR TITLE
[entropy_src/sec] remove LFSR mode

### PR DESCRIPTION
**Pull request by mwbranstad**
Deemed as a security risk, this mode has been removed.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@moidx once we move this, `entropy_smoketest` will probably fail, i wonder if for verilator / fpga then we should go add a `prim_lfsr` inside ast. what do you think? Or should we change `entropy_smoke` slightly to inject values ?

**Comment by mwbranstad** [comment]
@moidx @tjaychen I also am expecting that the dif test will fail. First with the compile, then functionally. We need to remove all references to CONF bit 1 (ENABLE_FIELD), and RATE and SEED. Last I looked, the AST model had an LFSR in it already, but need to confirm.

**Comment by moidx** [comment]
I think for mask ROM development/testing it would be nice to move the LSFR into ast. This way I am hoping to avoid having to impact the production code, and simplify the end to end integration cases.

**Comment by mwbranstad** [comment]
Redoing this, with new PR #8527

**Comment by tjaychen** [comment]
thanks Mark.
let me know if you need my help with anything.
My last PR got everything working on dv / fpga / verilator, but there's
been another software change, and i haven't checked yet.

**Pull request closed without merging**
