### PR TITLE
[bazel] Create FUSESOC_IGNORE

### PR DESCRIPTION
**Pull request by eunchan**
This commit defines `fusesoc_ignore` rule to create FUSESOC_IGNORE for
hw copied files.

### CODE REVIEW

**Comment by eunchan** [comment]
@timothytrippel I was able to create FUSESOC_IGNORE for verilator build but cannot do that for `opentitan_functest()`. I tried to revise the deps inside `opentitan_test.bzl` but unfortunately, i need to dig deeper to call `//hw:fusesoc_ignore` from ROM image creation.

**Comment by timothytrippel** [comment]
I think I'm a bit confused, is this the issue you are encountering: https://cs.opensource.google/opentitan/opentitan/+/master:rules/opentitan_test.bzl;drc=ef8edfd167497921814db3a885b99c723521d1e5;l=62
? I.e., the sim_dv device is copying all these files over to the runfiles location of sim_dv build targets. This might be silly, but is it possible to make the FUSESOC_IGNORE genrule a src/dependency of `@//hw:all_files` in hw/BUILD?

because I would think when depending on the Verilator sim binary target, that bazel will place the FUSESOC_IGNORE in the hw/ folder that gets copied into the bazel workspace as part of the Verilator sim dependency build, right?

**Review by timothytrippel — APPROVED** [review]
nice work! Thanks for solving this.

**Comment by eunchan** [comment]
@timothytrippel I revised the `dv_param()` based on your recommendation. It works! :) Could you review again?

**Review by timothytrippel — APPROVED** [review]
Ah great, glad it works, thanks for updating this!

**Pull request merged**
