### PR TITLE
[keymgr] Adjust keymgr_en handling

### PR DESCRIPTION
**Pull request by tjaychen**
- addresses https://github.com/lowRISC/opentitan/issues/16234
- The disable control was not correctly handled in the init states or
  in when an operation is completed on exactly the same cycle.

- Address both scenarios by allowing "early" disable error and not
  always wait for the fsm to transition.

### CODE REVIEW

**Comment by tjaychen** [comment]
I have a few hundred seeds and it seemed to be clean, let me know if you see otherwise. 
I didn't really check other parts of keymgr regression yet though...

**Review by weicaiyang — APPROVED** [review]
Thanks for fixing this. LGTM

**Comment by tjaychen** [comment]
do you want to quickly run through this and see if it causes any other fallout?

**Comment by weicaiyang** [comment]
> do you want to quickly run through this and see if it causes any other fallout?

sure, I will have a try.

**Comment by weicaiyang** [comment]
> do you want to quickly run through this and see if it causes any other fallout?

With this fix, tests are all passing except stress_*, which we can worry about later. Thanks

**Comment by tjaychen** [comment]
sounds good, then i will merge!

**Pull request merged**
