### PR TITLE
[site] Remove Node.js-based block diagram (plus some cleanup)

### PR DESCRIPTION
**Pull request by jwnrt**
## Summary

This PR:

* Removes the Node.js-based Earlgrey block diagram and associated infra.
  * Replaced with the based diagram added in https://github.com/lowRISC/opentitan/pull/17552.
* Fix for tooltips showing amber colours for test passing percentages between 45 and 50 which should have been red.

### CODE REVIEW

**Review by andreaskurth — APPROVED** [review]
LGTM, thanks @jwnrt

**Comment by andreaskurth** [comment]
Not merging yet to allow other reviewers to chime in and due to the description stating
> Opening as a draft for now so I can include other fixes if they come up in the next few days.

**Review by HU90m — APPROVED** [review]
LGTM

**Review by hcallahan-lowrisc — APPROVED** [review]
Goodbye npm. Nice to node ya!

**Pull request merged**
