### PR TITLE
[keymgr] Clean-up and bug fix for keymgr

### LINKED ISSUE #7902: [keymgr] last strb is 0 when LC turns off keymgr
@tjaychen 
usually `strb` is never 0 when the valid is high. We also have assertion to check that and I think KMAC TB probably never test the case that `strb` is valid with value 0.

When LC turns off keymgr in the middle of an operation, we will see the last `strb` is set to 0.
Screen Shot 2021-08-24 at 10 54 44 AM

Since this interacts with KMAC, we probably can't test this corner scenario in chip-level. If we do want to have this case in the keymgr side, we may need to test it at KMAC block-level TB as well.

cc @eunchan @udinator

### PR DESCRIPTION
**Pull request by tjaychen**
This PR started off as an attmempt to fix #7902,
however in the process of doing so, it was discovered there
are more issues with how keymgr handled dummy transactions
in the disabled state.

This PR attempts to fix those issues.

The first commit will be rebased away once #7941 is merged.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by weicaiyang** [comment]
> > > yeah i saw that. This was okay to me since when we go into wipe, we also
> > > already assert this operation is invalid.
> > > This to me feels like another layer of assurance that we will not accept
> > > any random key version.
> > 
> > 
> > OK. This is fine too. Let me update scb to align with design.
> > Another case.
> > When en is off during advancing from StReset, looks like we will wipe the data after this advance is done and then update to StInvalid. Neither error or alert will be generated for this case. Is this expected?
> > Screen Shot 2021-08-27 at 1 58 21 PM
> 
> hmmmmm.. it feels like for consistency sake, this should be made an invalid_op.

Agree. I treat it as an invalid_op in scb.

**Comment by tjaychen** [comment]
should we file that one as a separate PR? this one has gotten pretty long
and loaded heh.
Do things seem pretty consistent otherwise to you?

**Review by weicaiyang — APPROVED** [review]
yes, this is very long already. Let's do it in another PR.
LGTM, thanks for making LC disable behavior much more consistent.

**Comment by tjaychen** [comment]
sounds good. Thanks @weicaiyang. Let me know if you see anything else weird.

**Pull request merged**
