### PR TITLE
[csrng/rtl] instantiate and generate bug fixes

### PR DESCRIPTION
**Pull request by mwbranstad**
Fixes rtl problems that now enable instantiate and generate to work.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Review by rasmus-madsen — APPROVED** [review]
I would use a loop or a streaming operation for the function - but other than that LGT;

**Review by senelson7 — APPROVED** [review]
LGTM. Please merge to help with verify AES model/prediction.

**Comment by mwbranstad** [comment]
Steaming operating is much more terse, swapping that for the present function calls.

**Review by moidx — APPROVED** [review]

**Review by msfschaffner — APPROVED** [review]

**Review by cdgori — COMMENTED** [review]
Post merge, but LGTM

**Pull request merged**
