### PR TITLE
[hw, top_earlgrey] Align peripherals in different domains to PoT

### PR DESCRIPTION
**Pull request by silvestrst**
This change would make it possible to describe peripherals using less
ePMP regions.

`ram_ret` base address `0x40520000` => `0x40600000` aligns the whole
 peripherals in AON domain address space blob to PoT
 2^21 (`0x40600000` - `0x40400000` = 0x200000).

`periph` clock domain peripherals start with `0x40000000` and end with
`0x40400000`, which is 2^22 (`0x40400000` - `0x40000000` =
`0x400000`), so it is already aligned.

The `main` clock domain peripheral address space blob starts with
`0x4100_0000` and the upper boundary is `u32` size, so no changes to
`.hjson`.

Questions:

- Is this sensible?
- Any concerns?
- Where and how is the best place to document this?

### CODE REVIEW

**Comment by msfschaffner** [comment]
No issues with this change from my side.

If we decide to move forward with this change, it should be reflected in @eunchan's system memory map here:
https://docs.google.com/spreadsheets/d/1ptfdrG5RWiYHKtjYyDO1ubGYPPlN_4YQfzRKO1G1Mls/edit#gid=0

Note however that there is another cleanup PR https://github.com/lowRISC/opentitan/pull/5057#discussion_r569682192 that is about to land, and this may conflict with your changes here.

**Comment by silvestrst** [comment]
> Note however that there is another cleanup PR #5057 (comment) that is about to land, and this may conflict with your changes here.

Thanks, I just regenerated the files on top of that change.

**Review by imphil — APPROVED** [review]
LGTM from my side.

@tjaychen can you please explicitly approve this PR if you're OK with it?

And after landing, @silvestrst please update the spreadsheet.

**Comment by silvestrst** [comment]
@tjaychen could you please have a quick look, @imphil suggested that this change needs your approval.

**Comment by tjaychen** [comment]
i'm sorry i completely missed this PR. let me have a look.

**Comment by tjaychen** [comment]
this is all fine with me, would you mind updating the top_earlgrey spreadsheet? Or i can do that too to match.

**Comment by silvestrst** [comment]
> this is all fine with me, would you mind updating the top_earlgrey spreadsheet? Or i can do that too to match.

Will do - I dropped a note there, just waiting for this PR to land and then update it.

**Pull request merged**
