### PR TITLE
[sensor_ctrl] Add IO status change as an interrupt

### PR DESCRIPTION
**Pull request by tjaychen**
First seven commits will be rebased away. 
Dependent on #12074 and #12079

### CODE REVIEW

**Review by eunchan — APPROVED** [review]
LGTM. I didn't know that plic unittest is now autogenerated :) One thing less to work when interrupts are revised.

**Review by a-will — APPROVED** [review]

**Comment by tjaychen** [comment]
> LGTM. I didn't know that plic unittest is now autogenerated :) One thing less to work when interrupts are revised.

actually is it auto-gen'd? because i completely forgot about it and CI just failed heh

**Comment by timothytrippel** [comment]
> > LGTM. I didn't know that plic unittest is now autogenerated :) One thing less to work when interrupts are revised.
> 
> actually is it auto-gen'd? because i completely forgot about it and CI just failed heh

Do you mean `sw/device/lib/dif/dif_rv_plic_unittest.cc` or `sw/device/tests/autogen/plic_all_irqs_test.c`? Because the latter is the only that is autogen'd IIRC.

**Review by timothytrippel — APPROVED** [review]
LGTM, thanks @tjaychen !

**Pull request merged**
