### PR TITLE
[otbn] Reduce RTL loop stack depth to match ISS

### PR DESCRIPTION
**Pull request by GregAC**
We could alter the size in ISS instead to 9, I presumed it wasn't too critical. @felixmiller any thoughts?

### CODE REVIEW

**Comment by rswarbrick** [comment]
Is a 7-deep stack going to be much smaller when synthesized? If not, maybe it makes more sense to bump the limit in the ISS?

**Comment by GregAC** [comment]
It will probably reduce area by some small amount but it's not a real saving (or cause for concern if we increase size).

My main deciding factor for effective stack size was "everyone loves powers of two", should anyone have an actual reason for a stack size I'm happy to take that instead :)

**Comment by rswarbrick** [comment]
Ah, yes that's a good point. I was (stupidly) thinking this moved away from the blessed powers of two, but forgot the extra entry.

**Review by rswarbrick — APPROVED** [review]

**Comment by GregAC** [comment]
Probably should have had a simpler, 'make effective loop stack size 8' commit message! Ah well

**Comment by felixmiller** [comment]
@GregAC Sorry just seeing this. Currently I think, the max loop depth that is used anywhere in SW is 3. I would say from a SW perspective it would also be fine to limit it to 4 for now (if this gives us considerable area benefit)

**Pull request merged**
