### PR TITLE
[AST] Re-PR to sync with the latest opentitan master

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Signed-off-by: Jacob Levy <jacob.levy@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Thanks @Jacob-Levy. 

As I mentioned on the other PR, you could have just force-pushed this rebased version onto that branch such that you don't have to reopen a new PR.

Also, since this PR now contains one squashed commit with all changes, it would be good if the commit message where more indicative of the changes therein. 
I.e., the sync onto the latest state of master was only needed because the other PR got out of sync, but as a standalone commit it should probably rather summarize the actual changes.
This is a bit nitpicky, I know. Just mentioning it for future reference.

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
Sorry that this is still unresolved, can you look at the conflict and rebase it again?

**Comment by Jacob-Levy** [comment]
This conflict was not there yesterday.... Is it related to Tim's work on reggen?

**Comment by msfschaffner** [comment]
Hi @Jacob-Levy ,

I disentangled the commits and uploaded your rebased commit.
Can you quickly check if looks good?

**Comment by Jacob-Levy** [comment]
Looks good! Thanks.

**Comment by msfschaffner** [comment]
Done!

**Comment by tjaychen** [comment]
thanks!

**Pull request merged**
