### PR TITLE
refactor(rv_timer)!: Rearrange INTERRUPT regs

### PR DESCRIPTION
**Pull request by eunchan**
**This commit breaks the SW API**

Put INTR related CSRs prior to the comparator registers for SW to
compute the INTR easily.

### CODE REVIEW

**Comment by msfschaffner** [comment]
Thanks @eunchan for doing this! RTL side LGTM. 
I leave the final approval to @alphan since he requested this change on #2740.

**Comment by eunchan** [comment]
Need to revise https://github.com/tock/tock/blob/master/chips/earlgrey/src/timer.rs too.

**Review by alphan — APPROVED** [review]
Thanks @eunchan!

**Comment by eunchan** [comment]
image
Let me squash last three commits and merge.

**Comment by alphan** [comment]
> Need to revise https://github.com/tock/tock/blob/master/chips/earlgrey/src/timer.rs too.

@jon-flatley Would you mind taking this on?

**Comment by jon-flatley** [comment]
I've updated the rv_timer registers for Tock here https://github.com/tock/tock/pull/3122. It's been a while since I've been in the loop on Tock developments, but does this change make sense prior to reving the version of the bitstream used by Tock to a version that reflects this RTL change? Happy to discuss this in the [relevant PR ](https://github.com/tock/tock/pull/3122) rather than here.

**Pull request merged**
