### PR TITLE
Doc headers

### PR DESCRIPTION
**Pull request by towoe**

### CODE REVIEW

**Comment by gkelly** [comment]
How come this demotes the `# Overview` headers?  Why not pull the other heads to `#`-level?

**Comment by towoe** [comment]
Restricted the update to only `doc/` files.

**Comment by eunchan** [comment]
I've revised the site style (CSS) to make the title to have `.title` class and other headers to be demoted in CSS style.

**Comment by towoe** [comment]
> How come this demotes the `# Overview` headers? Why not pull the other heads to `#`-level?

Because I thought the overview is already a subsection. And my habit was to use `#` for the file title, only a personal preference, not based on any markdown rules.

**Comment by imphil** [comment]
Superseded by https://github.com/lowRISC/opentitan/pull/876

**Pull request closed without merging**
