### PR TITLE
[sw/silicon_creator] Use sec_mmio for FLASH_CTRL_EXEC_REG in flash_ctrl

### LINKED ISSUE #9287: [sw/silicon_creator] Should `flash_ctrl_exec_set()` use `sec_mmio`?

### PR DESCRIPTION
**Pull request by alphan**
Fixes #9287

Signed-off-by: Alphan Ulusoy <alphan@google.com>

### CODE REVIEW

**Review by moidx — APPROVED** [review]
I think it would also be good to use `sec_mmio` on the final flash permissions (once we add them).

**Comment by tjaychen** [comment]
@a-will FYI, since he's working on flash DIFs.

**Comment by alphan** [comment]
> I think it would also be good to use `sec_mmio` on the final flash permissions (once we add them).

Yes, `flash_ctrl_info_mp_set()` already uses `sec_mmio`, I'm planning to use `sec_mmio` for regwen registers as well.

**Review by mundaym — APPROVED** [review]

**Comment by alphan** [comment]
@mundaym, I also had to initialize `sec_mmio` in `mask_rom_epmp_test.c` because it uses the mask_rom linker script which places the `sec_mmio` context in a separate section that is not initialized. PLMK if you have any comments. Merging this now.

**Comment by mundaym** [comment]
> @mundaym, I also had to initialize `sec_mmio` in `mask_rom_epmp_test.c` because it uses the mask_rom linker script which places the `sec_mmio` context in a separate section that is not initialized. PLMK if you have any comments. Merging this now.

Thanks Alphan. The change looks good to me.

**Pull request merged**
