### PR TITLE
[otp_ctrl] Remove entropy_src chicken switches

### PR DESCRIPTION
**Pull request by msfschaffner**
This carries over a change from `integrated_dev` that removes unnecessary chicken switches for the entropy complex. 
Note however that this time we do not remove `EN_CSRNG_SW_APP_READ` since that may still be useful.
See the following discussion for context https://github.com/lowRISC/opentitan-integrated/pull/319#discussion_r1304821593.

This is in preparation for moving debug-related chicken switches into a new `HW_CFG1` partition, similarly as this has been done on `integrated_dev`.

:chicken:

### CODE REVIEW

**Review by jwnrt — APPROVED** [review]
Software and test changes LGTM

**Review by moidx — APPROVED** [review]
`EN_CSRNG_SW_APP_READ` will have to be set to true in most cases (including to meet FIPS certification requirements). 

It would be nice to document what use cases require `EN_CSRNG_SW_APP_READ = False` given that the SW CSRNG channel in this configuration would not be usable.

**Comment by msfschaffner** [comment]
@vogelpi if this looks good to you, can you merge it? Thanks!

**Review by vogelpi — APPROVED** [review]
Thanks for the PR @msfschaffner , removing these two switches is okay. They enable the following functionality:
- otp_en_entropy_src_fw_over allows enabling the firmware override mode. This is required for evaluation related to certification (in PROD LC state) and to enable the software fallback mode. This gives firmware access to unconditioned entropy only.
- otp_en_entropy_src_fw_read allows routing (un-)conditioned entropy to a separate output path. This is required for KATs especially around the conditioner, which is probably also relevant for certification (in PROD LC state).

I agree to keep the `EN_CSRNG_SW_APP_READ` switch and I agree to better document this / adapt the use of it. I'll open an issue for that.

**Comment by vogelpi** [comment]
The issue is here #21141

**Pull request merged**
