### PR TITLE
[kmac,dv] Increase timeouts for some tests

### PR DESCRIPTION
**Pull request by martin-velay**
A bunch of tests are actually failing for simple timeout reason. I took the worst case to compute this new value.

### CODE REVIEW

**Review by rswarbrick — COMMENTED** [review]
I think something has got a little mangled with the git history here and we've got some of another PR (which gets reverted in the final commit). Would you mind tidying it up?

**Review by rswarbrick — COMMENTED** [review]
I assume this is supposed to be a single commit, which contains just the additions to `kmac_base_sim_cfg.hjson`. If so, that looks sensible. Would you mind adding a note to the commit message that explains why 500ms is the right number?

**Comment by martin-velay** [comment]
@rswarbrick, all your comments have been addressed now. Thanks for your review

**Review by rswarbrick — APPROVED** [review]
Looks sensible to me, and thanks for the explanation.

**Pull request merged**
