### PR TITLE
[opentitantool/signer] Remove rom_ext_image_signer

### PR DESCRIPTION
**Pull request by jon-flatley**
Now that opentitan tool supports image signing there is no need for the dedicated signer tool.

Configure bazel to use opentitantool for signing and remove the old signer tool.

### CODE REVIEW

**Comment by jon-flatley** [comment]
Leaving this as WIP until #12608 gets merged.

**Comment by jon-flatley** [comment]
Taking this out of Draft status, however I do see an issue now that the new signer tool is fully integrated.

It seems that the existing ASN.1 encoded DER files are incompatible with those generated and consumed by the `rsa = "0.5.0"` crate that opentitanlib depends on. @alphan do we know if there is a source of truth for how these DER files are supposed to be formatted, or is this just a disagreement between the `rsa` crate and `mundane`? If it is okay to convert these DER files to the format accepted by the `rsa` crate I think that would be the easiest solution here.

**Comment by jon-flatley** [comment]
Both mundane and the rsa crate reference [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280) for their public key formatting, but I can't find any literature on private keys. I wrote a little tool that uses a patched version of mundane and the rsa crate to convert between the two private key formats; the public key format used by both appear identical.

**Review by alphan — APPROVED** [review]
Thanks @jon-flatley. Please take a look at the links that we looked at offline for the file formats. We should use the same format as the current files in the repo in both directions, i.e. load/save. Feel free to handle the `mundane` removal and the `rsa` version bump in a separate PR.

Can you also check that we can successfully build signed binaries, i.e. `_test_key_0.signed.bin`.

**Comment by jon-flatley** [comment]
Thanks @cfrantz for integrating the manifest generation into bazel! Your changes LGTM!

**Review by cfrantz — APPROVED** [review]

**Pull request merged**
