### PR TITLE
[flash_ctrl,dv] interrupt mode test

### PR DESCRIPTION
**Pull request by jdonjdon**
cmd:

./util/dvsim/dvsim.py ./hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i flash_ctrl_intr_rd -r 1 -s 2425417413 -v m --waves

Signed-off-by: Jaedon Kim <jdonjdon@google.com>

### CODE REVIEW

**Comment by jdonjdon** [comment]
This is TB issue.
There are similar issue is fixed in other PR, so we need to revisit this after aa new PR merge.
I will put the new PR number later.

**Comment by tjaychen** [comment]
i'm not completely sure if i should review this one or #13862, but both the read / write routines look good to me. 
let me know which one i should eventually approve.

**Comment by jdonjdon** [comment]
> i'm not completely sure if i should review this one or #13862, but both the read / write routines look good to me. let me know which one i should eventually approve.

Please review #13862. I will follow up this PR

**Comment by jdonjdon** [comment]
Fixed in #14262

**Pull request closed without merging**
