### PR TITLE
[rom_ext] Update RSA terms in rom_ext mainfest doc

### PR DESCRIPTION
**Pull request by felixmiller**
Just some nits regarding RSA terminology

### CODE REVIEW

**Review by gkelly — APPROVED** [review]

**Comment by lenary** [comment]
We should make the equivalent changes to the manifest.hjson file and the parser function names. Maybe @silvestrst can help you with the required changes?

This is also blocked by #4328, which does updates to the same file. Can you check over that PR?

**Comment by silvestrst** [comment]
> Maybe @silvestrst can help you with the required changes?

Happy to do the changes, will aim to do them by the end of today.

**Comment by lenary** [comment]
> This is also blocked by #4328, which does updates to the same file. Can you check over that PR?

Actually, that PR has not been reviewed, so I can rebase it onto these changes, if we also change the manifest.hjson/parser/tests to use Felix's names. Let's aim to land this PR first.

**Comment by silvestrst** [comment]
@lenary @felixmiller - just pushed the requested change. CI is still running but it should be fine.

**Review by lenary — APPROVED** [review]
LGTM

**Review by gkelly — APPROVED** [review]

**Pull request merged**
