### PR TITLE
[DO NOT MERGE] remove intermodule error?

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@eunchan do you mind having a look at this?

Without this change, we are getting errors during topgen for some of the intermodule signals like the ones below
```
      // HW_CFG broadcast
      'otp_ctrl.otp_hw_cfg'    : ['lc_ctrl.otp_hw_cfg', 'keymgr.otp_hw_cfg'],
```

However, it feels like to me the commented out checks are already done as part of the `one-to-N` checks. So we don't have to do them again.  What do you think?

**Comment by eunchan** [comment]
the commented code is for checking one-to-N. Which case is the request has N width and its `rsps` are N entires. Each index connects to its rsp entry. 

`broadcast` is a case that req width is 1 and `rsps` are N. so that req connects to `rsps` at the same time. The current code looks like slightly revised from what I coded. I think we can skip the commented section only when the request width is 1.

**Comment by tjaychen** [comment]
> the commented code is for checking one-to-N. Which case is the request has N width and its `rsps` are N entires. Each index connects to its rsp entry.
> 
> `broadcast` is a case that req width is 1 and `rsps` are N. so that req connects to `rsps` at the same time. The current code looks like slightly revised from what I coded. I think we can skip the commented section only when the request width is 1.

wait @eunchan , but isn't one-to-N already checked in the code above?

**Comment by eunchan** [comment]
> > the commented code is for checking one-to-N. Which case is the request has N width and its `rsps` are N entires. Each index connects to its rsp entry.
> > `broadcast` is a case that req width is 1 and `rsps` are N. so that req connects to `rsps` at the same time. The current code looks like slightly revised from what I coded. I think we can skip the commented section only when the request width is 1.
> 
> wait @eunchan , but isn't one-to-N already checked in the code above?
> 
> also the other part is that connections that are meant to be broadcast are currently erroring, so i feel like something is off.

Yeah right. When I coded, I thought I coded to support only one-to-N not broadcast (width 1 connects to N rsps). Somehow the code is changed to the current. I agree the above code already checks.  the latter is failed due to the otp_ctrl_otp_hw_cfg 's type is set to `broadcast` I think. Then checking below is not necessary. 

There are multiple cases the old topgen did not support:

1. multibit logic broadcast/ one-to-N case.
2. struct broadcast. 

I think `otp_ctrl.otp_hw_cfg` falls into second category. I will take a look.

**Comment by tjaychen** [comment]
o sorry eunchan, i should have clarified.
The actual RTL generated works just fine for the struct broadcast.
It's only topgen that's creating an error.
So i was thinking this check could just be commented out since it's already
checked.

Sorry if that wasn't clear.

**Review by eunchan — APPROVED** [review]
I see. We can comment out.

**Pull request closed without merging**
