### PR TITLE
[top, pinmux] Fix pinmux to ast connections

### PR DESCRIPTION
**Pull request by tjaychen**
Pinmux to ast connections cannot fully go through pinmux and instead has to be tapped at specific points.

### CODE REVIEW

**Comment by tjaychen** [comment]
@Jacob-Levy / @arnonsha i also updated the open source version of ast to the right connection widths. 
Please have a look.

**Comment by tjaychen** [comment]
@msfschaffner regarding the inversion thing, I can make a separate fix to move the inversion post sampling into the pinmux.
let me know what you think.  I feel like that would be slightly easier than making exceptions, but you would know better i think.

**Comment by msfschaffner** [comment]
So @arnonsha initially suggested to just output the raw uninverted form of the pads in the pad wrappers.
Once we have that, we could basically just connect the entire `mio_in_raw` and `dio_in_raw` arrays directly to AST, without having to loop this into the top-level and back again.

I am currently working myself through templating the tops and padring, and could provision these outputs in the padring.

**Comment by tjaychen** [comment]
o i see. That works too i think.
so does this mean all the scan_idx stuff would be removed from pinmux then?
I guess the strap / tap stuff would still go through pinmux right?

**Comment by tjaychen** [comment]
How do you feel about external clock?
Because that one does not technically stay external clock all the time.
Does that make more sense as a direct connection or route via pinmux?

**Comment by msfschaffner** [comment]
Does the external clock have to go through the clkmgr, or is the switching handled inside AST?
Because if it is the latter, they could just take it from any of the `mio_in_raw` signals in the array that we would connect anyways.

Propagation of the clock would be blocked inside the pinmux, as long as no peripheral input is configured to connect to that specific pad.

**Comment by tjaychen** [comment]
it doesn't have to go through clkmgr, but a direct connection is a little
strange because it's not functionally always an external clock.
Although come to think of it, that would be the same inside pinmux as
well.

So yeah tapping directly from the pad ring is probably the best choice.
This would also eliminate a ton of clock paths they would otherwise see.

**Comment by msfschaffner** [comment]
Yes that is true, but inside AST I guess it would just connect to a clock mux, right?

So, it probably does not really matter at which point we tap it out if we do not do any additional gating/muxing on it (outside of AST) .

It can still be a MIO pad, so that it can be used for other functional stuff later on.

**Comment by msfschaffner** [comment]
Testing SW just has to be careful not to change the output or pad attribute configuration of that MIO pad as long as it's used as an external clock.

**Pull request closed without merging**
