### PR TITLE
[top/otp] Rework OTP HW CFG broadcast to address coverage and lint issues

### PR DESCRIPTION
**Pull request by msfschaffner**
This is an initial step to address #6713.
While it does not solve the tooling shortcomings entirely, it does address the lint and coverage issues that are a result of the `hw_cfg_i` wildcard connections to each IP.

PS: commits will be squashed once this is approved.

### CODE REVIEW

**Review by udinator — APPROVED** [review]
The SRAM changes LGTM - can you run the `executable` test just to make sure nothing somehow broke?

**Comment by msfschaffner** [comment]
Latest force push contains another change in `sram_ctrl` which switches the OTP fuse signals over to the common `otp_en_t`.

@udinator I ran the executable test and it passes.

**Review by sriyerg — APPROVED** [review]
Thanks @msfschaffner for the prompt fix!

**Review by mwbranstad — APPROVED** [review]
This seems much cleaner and clearer. There is another otp input for entropy_src, but it is hung up in PR #6512. We would want to make the same type of change there.

**Pull request merged**
