### PR TITLE
[keymgr] Advance to D2

### PR DESCRIPTION
**Pull request by tjaychen**
Advance keymgr to D2.

Pending on #7562

### CODE REVIEW

**Comment by weicaiyang** [comment]
@tjaychen 
last time we discussed that we may want to remove the HMAC sideload interface, is it still the case?
we have some planned counter measurements for keymgr defined [here](https://docs.google.com/spreadsheets/d/1SWjFstWxDtBt-taKqIyxDIzdtaIeHYe3hjXoMLlf0sU/edit#gid=0). When will we implement those?

**Comment by tjaychen** [comment]
o i forgot about the hmac, thanks for the reminder.
It's not super clear at the moment when the security countermeasures have
to land (D2 or D3), but I can add them to D2 also if you prefer.

**Comment by weicaiyang** [comment]
> o i forgot about the hmac, thanks for the reminder. It's not super clear at the moment when the security countermeasures have to land (D2 or D3), but I can add them to D2 also if you prefer.

If we have finalized those countermeasures and know how to implement them, I would prefer to have them for D2, since D2 has an item `FEATURE_FROZEN`

**Comment by tjaychen** [comment]
sounds good.
then let me work on that.

**Comment by tjaychen** [comment]
@weicaiyang all known keymgr features are in. Including countermeasures that have been discussed.
I'll do one more passover, but i think we can advance to D2 now.

**Comment by tjaychen** [comment]
looks like there is still 
#7149 
#1920 

i'll quickly get those resolved and we can push this to D2.

**Comment by weicaiyang** [comment]
> looks like there is still
> #7149
> #1920
> 
> i'll quickly get those resolved and we can push this to D2.

Thanks Tim. SGTM

**Review by weicaiyang — APPROVED** [review]
don't forget to fix #5922, otherwise LGTM, thanks

**Comment by tjaychen** [comment]
> don't forget to fix #5922, otherwise LGTM, thanks

i'm going to treat that one as a bug since it's not a new feature :)

**Pull request merged**
