### PR TITLE
Revert "[bazel] Add bazel to CI and containers"

### PR DESCRIPTION
**Pull request by drewmacrae**
This reverts commit bc4274a6c61dc642785e7f3f82b6c13a358aa5b4.
https://github.com/lowRISC/opentitan/pull/10307 didn't have the Signed-off-by line and I can't figure out how to update the commit message since it wasn't published through the normal path.

Signed-off-by: Drew Macrae <drewmacrae@google.com>

### CODE REVIEW

**Review by martin-lueker — APPROVED** [review]
Hahaha, I just created the same PR

**Comment by martin-lueker** [comment]
I approve.  Thank you Drew.

**Comment by martin-lueker** [comment]
> This reverts commit [bc4274a](https://github.com/lowRISC/opentitan/commit/bc4274a6c61dc642785e7f3f82b6c13a358aa5b4). #10307 didn't have the Signed-off-by line and I can't figure out how to update the commit message since it wasn't published through the normal path.
> 
> Signed-off-by: Drew Macrae [drewmacrae@google.com](mailto:drewmacrae@google.com)

Also, to edit your commit, to add the sign-off you can fetch your branch to your local machine and then in that branch run: `git commit -s --amend`.  Then just force push it back and you are good!

**Comment by martin-lueker** [comment]
Hi @drewmacrae, is this ready to merge as soon as CI is done?

**Comment by drewmacrae** [comment]
Yes

**Pull request merged**
