### PR TITLE
[rom_ctrl, dv] Updated V1 status in rom_ctrl checklist 

### PR DESCRIPTION
**Pull request by prajwalaputtappa**

### CODE REVIEW

**Comment by rswarbrick** [comment]
@sriyerg / @weicaiyang: For some background, we think that the `rom_ctrl` testbench is probably almost ready to go to V1. @prajwalaputtappa has just gone through the checklist to make sure we've done all the non-review-meeting tasks. Once this goes in, let's try to schedule a testplan review.

**Comment by weicaiyang** [comment]
> @sriyerg / @weicaiyang: For some background, we think that the `rom_ctrl` testbench is probably almost ready to go to V1. @prajwalaputtappa has just gone through the checklist to make sure we've done all the non-review-meeting tasks. Once this goes in, let's try to schedule a testplan review.

Great! SGTM

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks

**Review by sriyerg — APPROVED** [review]
Mark the FPV ones as NA, if there is no FPV work done on this block.

**Comment by rswarbrick** [comment]
Oh, good point. @prajwalaputtappa, would you mind making that tweak?

**Comment by prajwalaputtappa** [comment]
> Oh, good point. @prajwalaputtappa, would you mind making that tweak?

I have made the FPA ones as N/A

**Comment by rswarbrick** [comment]
I'm not sure that's quite right: did you forget to do a force-push?

**Comment by prajwalaputtappa** [comment]
> I'm not sure that's quite right: did you forget to do a force-pu

> I'm not sure that's quite right: did you forget to do a force-push?

Sorry, @rswarbrick. I think I'd forgotten to do the force push. I believe it is reflecting now. Please check again.

**Pull request merged**
