### PR TITLE
[ci] Run hyperdebug tests in CI

### PR DESCRIPTION
**Pull request by pamaury**
Note that this requires to build the hyperdebug bitstream which adds a nontrivial load to the CI now we are building three bitstreams (cw310, hyperdebug, cw340).

### CODE REVIEW

**Comment by a-will** [comment]
> Note that this requires to build the hyperdebug bitstream which adds a nontrivial load to the CI now we are building three bitstreams (cw310, hyperdebug, cw340).

If CI resources are scarce, I think we really shouldn't be building CW340 in PRs right now.

I don't claim to know everyone's needs, but for those I am aware of... The first transition we're interested in is CW310+SAM3X --> CW310+Hyperdebug. Then once the hyperdebug variant becomes stable, we could deprecate the SAM3X variant and relegate its test jobs to master-only or nightly-only, if it is still of passing interest. If we're still lacking resources, that deprecation may free some up to rope in CW340 (which is a candidate for another transition later, but not agreed upon).

We're not quite at feature parity just yet, though: The JTAG work for hyperdebug is nearing completion, but it's not yet merged. In addition, we'll want to decide whether to release the designs for the breakout board to all, then incorporate that board into the CW310 hyperdebug variant. The Pmod connectors are currently only partially connected.

As @msfschaffner mentioned recently, the leads will probably need to have a discussion about the roadmap.

**Comment by a-will** [comment]
FYI: All the hyper310 tests are marked with `manual` tags, so they won't get picked up by the wildcard yet ;)

**Comment by pamaury** [comment]
The hyperdebug bitstream build does not seem to consistently work. I have re-run the PR three times, the bitstream has failed to build two out of three so far.

**Comment by a-will** [comment]
> The hyperdebug bitstream build does not seem to consistently work. I have re-run the PR three times, the bitstream has failed to build two out of three so far.

I'm not sure why this has started happening only in the past few days or so, but it looks like placement is getting stuck in a rut, challenging Vivado's ability to close hold timing on our relatively poor clock tree.

The particular failures for this run are actually false failures, as Vivado is timing a transition from `clk_main` to `clk_io` through a synchronizer. I'll see if I can model this in the XDC, similar to what I did for CW340 (but without the separately-generated frequency, since that would require more precious buffers).

**Comment by timothytrippel** [comment]
> > Note that this requires to build the hyperdebug bitstream which adds a nontrivial load to the CI now we are building three bitstreams (cw310, hyperdebug, cw340).
> 
> If CI resources are scarce, I think we really shouldn't be building CW340 in PRs right now.

Yes I agree with this ^^

**Review by timothytrippel — APPROVED** [review]

**Comment by a-will** [comment]
My constraints PR is merged. You can try rebasing, and this may pass more reliably.

**Comment by a-will** [comment]
It looks like the `manual` tag was hiding analysis errors due to an incomplete bitstream cache entry. There are a couple paths we can take:

1. I can bring over code from the other repo to make the cached entry resolve back to the vivado-built one when it's not present. I think I'd implement it a little differently this time, so there doesn't need to be so many changed lines...
2. We make the FPGA test jobs dependent on all bitstream jobs and build a full cache entry.

**Comment by pamaury** [comment]
@a-will could we solve the problem by changing the way the bitstreams are imported so that it doesn't touch the cache at all if requested? At the moment, we are creating a target for both the vivado build and the cache entry and *then* selecting, but it would be better to just have one target that's either vivado or an alias to @bitstreams

**Comment by a-will** [comment]
> @a-will could we solve the problem by changing the way the bitstreams are imported so that it doesn't touch the cache at all if requested? At the moment, we are creating a target for both the vivado build and the cache entry and _then_ selecting, but it would be better to just have one target that's either vivado or an alias to @bitstreams

So I'm not sure what you're requesting there. The vivado build and cache entry are necessarily two different targets, as they are built in different ways.

What I did in the other repo was add yet another mux in every user of the `@bitstreams` external repo. bitstreams_workspace.py would spit out a Starlark file that contained a list of designs available in the cache, and all the references to `@bitstreams` in our workspace would have to check whether the design existed in the cache and mux back in the Vivado build.

For this round, I'd write the list of required designs in bitstreams_workspace.py, then for designs that are missing in a cache entry, it would slot in BUILD targets that would alias the Vivado-built targets in our workspace. That way, there's no need for a large set of mux entries in the opentitan workspace's BUILD files.

**Comment by pamaury** [comment]
> > @a-will could we solve the problem by changing the way the bitstreams are imported so that it doesn't touch the cache at all if requested? At the moment, we are creating a target for both the vivado build and the cache entry and _then_ selecting, but it would be better to just have one target that's either vivado or an alias to @bitstreams
> 
> So I'm not sure what you're asking there. The vivado build and cache entry are necessarily two different targets, as they are built in different ways.
> 
> What I did in the other repo was add yet another mux in every user of the `@bitstreams` external repo. bitstreams_workspace.py would spit out a Starlark file that contained a list of designs available in the cache, and all the references to `@bitstreams` in our workspace would have to check whether the design existed in the cache and mux back in the Vivado build.
> 
> For this round, I'd write the list of required designs in bitstreams_workspace.py, then for designs that are missing in a cache entry, it would slot in BUILD targets (in the `@bitstreams` repo) that would alias the Vivado-built targets in our workspace. That way, there's no need for a large set of mux entries in the opentitan workspace's BUILD files.
> 
> Edit: Now in #19756

I had something like #19758 in mind. I am not sure if it solves the problem.

**Comment by a-will** [comment]
> I had something like #19758 in mind. I am not sure if it solves the problem.

It solves a bunch of other problems, but not this one, haha. We'd still end up with a reference to the missing hyperdebug bitstream that we expected from the cache. That cleanup will be nice, though!

**Pull request merged**
