### PR TITLE
[util/topgen] Dynamic chip_info section generation

### PR DESCRIPTION
**Pull request by sameo**
Add a per-ROM chip_info section dynamically, based on the TOP hjson ROM controllers.

### CODE REVIEW

**Review by engdoreis — APPROVED** [review]
LGTM, but I would wait for another option before merging this PR.

**Review by rswarbrick — APPROVED** [review]
Looks sensible to me.

**Comment by sameo** [comment]
> LGTM, but I would wait for another option before merging this PR.

Did you mean another review? Or else, what other options do you have in mind?

**Comment by engdoreis** [comment]
> > LGTM, but I would wait for another option before merging this PR.
> 
> Did you mean another review? Or else, what other options do you have in mind?

Sorry, I meant opinion. As Rupert has approved, we are good to merge it.

**Review by HU90m — APPROVED** [review]

**Pull request merged**
