### PR TITLE
[dv/edn] Signoff for V2S

### PR DESCRIPTION
**Pull request by cindychip**
This PR signoff EDN for V2S.

Signed-off-by: Cindy Chen <chencindy@opentitan.org>

### CODE REVIEW

**Comment by cindychip** [comment]
V2 TODO: #11489
V2S TODO: #16268

Regression results:
image

**Review by senelson7 — APPROVED** [review]

**Review by sriyerg — APPROVED** [review]
Nice, congrats @cindychip!

**Review by mwbranstad — APPROVED** [review]
LGTM

**Review by msfschaffner — APPROVED** [review]
LGTM!

**Comment by cindychip** [comment]
https://github.com/lowRISC/opentitan/pull/16372 this PR further improves functional coverage for CSRNG agent.

**Pull request merged**
