### PR TITLE
[sw/vendor] vendoring in FreeRTOS kernel for testing

### PR DESCRIPTION
**Pull request by timothytrippel**
This vendors in the (slightly patched) FreeRTOS kernel for use in the chip-level test infrastructure.

### CODE REVIEW

**Comment by timothytrippel** [comment]
PR #7922 dependency merged, and duplicate commits removed.

**Comment by timothytrippel** [comment]
This partially addresses #8015.

**Comment by moidx** [comment]
@asb this PR is mainly just brining in vendor code. Can you take a look and let us know if you have any concerns? Thanks!

**Comment by asb** [comment]
> @asb this PR is mainly just brining in vendor code. Can you take a look and let us know if you have any concerns? Thanks!

No concerns about vendoring this in.

**Pull request merged**
