### PR TITLE
[rom_ctrl, pwrmgr, top] Connect rom_ctrl check into pwrmgr

### PR DESCRIPTION
**Pull request by tjaychen**
- connect rom_ctrl check output into pwrmgr
- if check is successful, pwrmgr allows cpu to execute
- FI hardening to follow later

### CODE REVIEW

**Review by rswarbrick — APPROVED** [review]
This looks good. Am I right in thinking I should be able to remove the "SkipCheck" parameter from `rom_ctrl` once this has gone in?

**Comment by tjaychen** [comment]
> This looks good. Am I right in thinking I should be able to remove the "SkipCheck" parameter from `rom_ctrl` once this has gone in?

o i wasn't sure if the hash portion of the rom population was done (was actually planning on checking with you).  If that's there, then i think we can definitely remove. But if it's not there yet, we would have to skip checks for dv / verilator / fpga right?

**Comment by rswarbrick** [comment]
Duh, that's a really good point! Once we've got the wiring with KMAC, I guess we can either fake things (pretending the hash matched, but still computing the digest) or I can just get on and do the Python work properly :-)

**Comment by tjaychen** [comment]
> Duh, that's a really good point! Once we've got the wiring with KMAC, I guess we can either fake things (pretending the hash matched, but still computing the digest) or I can just get on and do the Python work properly :-)

i'm sure once you look at it, it will be done in a day! and i'll be introducing another PR tomorrow to remove this!

**Pull request merged**
