### PR TITLE
[site] Add hover styling to the tiles on the Docs homepage

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**
Currently there is no-feedback that these blocks are interactive. Style when hovered to give the user more feedback that they are indeed buttons.

### CODE REVIEW

**Review by jwnrt — APPROVED** [review]
LGTM, thanks!

Would you mind adding a different colour for the dark mode? The text looks like this:

image

**Comment by hcallahan-lowrisc** [comment]
Good point! Done.
Dark mode definitely needs some TLC in the future.

Screenshots with the 'HW' tile hovered. It's quite subtle in a screenshot, but much more noticeable when interactive. 

image

image

**Review by marnovandermaas — APPROVED** [review]
Looks fine to me, funny that the black theme is basically defined twice...

**Review by HU90m — APPROVED** [review]
really nice

**Review by vrozic — APPROVED** [review]

**Comment by jwnrt** [comment]
> Dark mode definitely needs some TLC in the future.

For sure, maybe we should have an open issue for that.

The dashboard page in particular is quite difficult to read in the dark theme

**Pull request merged**
