### PR TITLE
[rom_ext,dice] update certs if firmware updates detected

### PR DESCRIPTION
**Pull request by timothytrippel**
[rom_ext] add ability to update DICE certs

This adds a mechanism to the ROM_EXT to update the DICE attestation certs if the attestation keys have changed due to either:
1. a ROM_EXT update,
2. an Owner firmware update, and/or
3. an ownership transfer.

This partially addresses #21583.

### CODE REVIEW

**Review by cfrantz — APPROVED** [review]

**Comment by timothytrippel** [comment]
@jwnrt I had to add the last commit to get this to pass CI. Please let me know if I am missing anything.

**Review by jwnrt — APPROVED** [review]
The last commit looks fine, thanks for the change. I thought we'd been running it in ROM_EXT environments though... was it the otp setting that broke something?

**Comment by timothytrippel** [comment]
> The last commit looks fine, thanks for the change. I thought we'd been running it in ROM_EXT environments though... was it the otp setting that broke something?

I think it it was that the manual override of the settings previously did not set the rom_ext slot: https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/BUILD;drc=38d0d95f72734ec6c617d22daeb2c12099b4a1b2;l=236

**Comment by timothytrippel** [comment]
CI failures not related to this PR. Merging.

**Pull request merged**
