### PR TITLE
[TOP] ANALOGSIM macro-base solution

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Signed-off-by: Jacob Levy <jacob.levy@opentitan.org>

### CODE REVIEW

**Comment by imphil** [comment]
@Jacob-Levy Is this PR still relevant, or should we close it?

**Comment by Jacob-Levy** [comment]
I will check this when I return from vacation on October 3rd.

**Comment by Jacob-Levy** [comment]
@sha-ron @arnonsha
This PR is still relevant but it need to be updated to the new top level generation.
The PR will be updated andwill be re-isue.
@sha-ron @arnonsha

**Comment by Jacob-Levy** [comment]
The changes now needed in different files...

**Pull request closed without merging**
