### PR TITLE
[RDC] Tie BROUT to 0

### PR DESCRIPTION
**Pull request by eunchan**
`u_ast.rglssm_brout` is OR-ed with POR_N. Tying the signal to make POR_N
to take effect.

### CODE REVIEW

**Review by tjaychen — APPROVED** [review]
so is this idea that they don't know the value of BROUT is, and it could cause it to silence the reset line?

**Comment by eunchan** [comment]
> 

Right. The tool analyzes the design statically. So does not know the FSM inside the module transit to eventual state lowering BROUT to 0. So, it assumes the reset could be attenuated by BROUT signal.

**Comment by tjaychen** [comment]
> > 
> 
> Right. The tool analyzes the design statically. So does not know the FSM inside the module transit to eventual state lowering BROUT to 0. So, it assumes the reset could be attenuated by BROUT signal.

let me double check with Nuvoton also. I think this behavior is correct...but it is slightly strange that something internal can block pin reset. I hope this doesn't result in a chicken-and-egg issue.

**Comment by eunchan** [comment]
> > Right. The tool analyzes the design statically. So does not know the FSM inside the module transit to eventual state lowering BROUT to 0. So, it assumes the reset could be attenuated by BROUT signal.
> 
> let me double check with Nuvoton also. I think this behavior is correct...but it is slightly strange that something internal can block pin reset. I hope this doesn't result in a chicken-and-egg issue.
>
Should be fine. The reset (after BROUT OR-ed) affects the top_earlgrey logics, not inside AST. BROUT is generated in AST.

**Comment by eunchan** [comment]
FPGA is not affected by this change. Let me merge 
image

**Pull request merged**
