### PR TITLE
[topgen] Fix flake8 lint errors

### PR DESCRIPTION
**Pull request by eunchan**

### CODE REVIEW

**Comment by msfschaffner** [comment]
This needs a rebase onto the newest changes in master...

**Comment by tjaychen** [comment]
sorry looks like i forgot to check on my last merge. I'll try to remember going forward.

**Comment by eunchan** [comment]
> sorry looks like i forgot to check on my last merge. I'll try to remember going forward.

Don't worry. :) Anyway you can add flake8 to your pre-commit hook to prevent flake8 error from merging to the master.

**Comment by eunchan** [comment]
Can someone approve this? :)

**Pull request merged**
