### PR TITLE
[hw,i2c,dv] Add check for unexpected interrupts

### PR DESCRIPTION
**Pull request by crteja**
Add check for unexpected interrupts in `host_stretch_timeout` sequence

### CODE REVIEW

**Review by marnovandermaas — COMMENTED** [review]
Changes the code looks good to me. Do you see any unexpected interrupts when running the tests?

**Comment by crteja** [comment]
No, there were no unexpected interrupts.

**Review by marnovandermaas — APPROVED** [review]
Ok, looks good to me. It would be good to have someone else have a look at this as well before merging.

**Comment by vogelpi** [comment]
It looks like this PR got completely forgotten. I've come across this via the M3 label. This is not security critical, so I've now moved this to M4.

I've now rebased this on master and ran 100 tests, they all passed. @marnovandermaas , @hcallahan-lowrisc , @alees24 do you think this still matters or should be close the PR and not merge it? FYI @andreaskurth

**Comment by marnovandermaas** [comment]
I think it makes sense to check whether interrupts are firing unexpectedly. Not sure if merging this will affect @hcallahan-lowrisc work on I2C DV.

**Comment by hcallahan-lowrisc** [comment]
These potential changes are a very loose check of interrupts, basically only testing that no interrupts we have not marked in advance are asserted at any point during the vseq. Better modelling of the interrupts at block level is definitely desirable, but is a much wider problem that this focussed check in a single leaf vseq. As such, I'm moving this back to M5.

**Comment by moidx** [comment]
Decided to go with the proposal in #18980 instead.

**Pull request closed without merging**
