### PR TITLE
[doc] Move AST interfaces table to new file, convert table to .md

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**
Table was previously HTML inside a .md file, switching to a native .md table allows it to be styled by our stylesheets.

Some small cleanups to the prose as well.

### CODE REVIEW

**Review by msfschaffner — COMMENTED** [review]
This looks like a reasonable cleanup.
@zi-v does this work for you? 
It would make the documentation more maintainable.

**Comment by hcallahan-lowrisc** [comment]
p.s. you can see the results of this refactor on the staging site : 
https://staging.opentitan.org/book/hw/top_earlgrey/ip/ast/index.html
https://staging.opentitan.org/book/hw/top_earlgrey/ip/ast/doc/interfaces.html

**Comment by zi-v** [comment]
Thanks. I am fine with this change

**Review by HU90m — APPROVED** [review]
[Looks good](https://github.com/hcallahan-lowrisc/opentitan/blob/ast_docs_cleanup/hw/top_earlgrey/ip/ast/doc/interfaces.md#table)!

**Review by msfschaffner — APPROVED** [review]

**Pull request merged**
