### PR TITLE
[bazel] make go toolchain dependency config work in airgapped env

### PR DESCRIPTION
**Pull request by timothytrippel**
This updates the way the go toolchain is downloaded/included in our Bazel workspace to enable Bazel builds in an airgapped environment. Specifically, #15044 exposed a bug in our go toolchain dependency that caused Bazel builds to fail in the airgapped environment.

The fix for this was two fold:

1. manually specify the exact toolchain tarballs to be downloaded using the `go_download_sdk` repo rule, instead of the `go_register_toolchain` rule which attempts to automatically find the right toolchain to download by downloading a file from the Internet that is not cacheable, and therefore not accessible in an airgapped environment, and

2. fork and patch `rules_go` to only download go toolchains using the `ctx.download_and_extract` action (instead of the `ctx.download` action) which caches said downloads in the repository cache that is moved to the airgapped environment. See https://github.com/lowRISC/rules_go/commit/07fe5f4939195410832b230383e7e45f4fa42712 for more details.

### CODE REVIEW

**Comment by timothytrippel** [comment]
Note: this depends on #15216, which reimplements #15044 as #15044 had to rolled back (in #15118) due to airgapped environment breakages it caused.

Please only review the last commit.

**Comment by timothytrippel** [comment]
Also note, this should be merged immediately after #15126 to prevent breakages again.

**Comment by timothytrippel** [comment]
Since this PR has already been rebased on the changes from #15126, @cfrantz and I have decided to just close #15126 and keep all changes in this PR to make the merging process simpler and avoid further airgapped breakages.

**Comment by tjaychen** [comment]
> This updates the way the go toolchain is downloaded/included in our Bazel workspace to enable Bazel builds in an airgapped environment. Specifically, #15044 exposed a bug in our go toolchain dependency that caused Bazel builds to fail in the airgapped environment.
> 
> The fix for this was two fold:
> 
> 1. manually specify the exact toolchain tarballs to be downloaded using the `go_download_sdk` repo rule, instead of the `go_register_toolchain` rule which attempts to automatically find the right toolchain to download by downloading a file from the Internet that is not cacheable, and therefore not accessible in an airgapped environment, and
> 2. fork and patch `rules_go` to only download go toolchains using the `ctx.download_and_extract` action (instead of the `ctx.download` action) which caches said downloads in the repository cache that is moved to the airgapped environment. See [lowRISC/rules_go@07fe5f4](https://github.com/lowRISC/rules_go/commit/07fe5f4939195410832b230383e7e45f4fa42712) for more details.

i have a dumb question.  Assuming you fixed 2, wouldn't it be okay to not fix 1..? Because I thought this meant that during the prep process (which can reach the internet) it would be able to determine the version, and the change in 2 would actually cache it.

**Comment by timothytrippel** [comment]
Sorry let me back up a bit here to shed some light on why both need to be fixed, as they are two separate issues, and why I didn't just fix them both by patching the rules. Sorry in advance for the long-winded response but hopefully this clears things up :)

**Issue 1**
There are two ways to register what I will call a "go toolchain/sdk" using repository rules provided in `rules_go`:
1. using the [`go_register_toolchain()` repo rule](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_register_toolchains), for which you can specify a version number or let the rule pick the latest version, or
2. using the [`go_download_sdk()` repo rule](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go_download_sdk), for which you specify the exact tarball URL(s) and sha256 hashes of the toolchains you want `rules_go` to download, using the `sdks` attribute.

When you take a closer look, under the hood, the `go_register_toolchain()` repo rule actually [calls](https://github.com/bazelbuild/rules_go/blob/b6f10d71719c0c944cbd6c219a0a0eea6dc0d3b4/go/private/sdk.bzl#L426) the `go_download_sdk()` repo rule, passing it the version string you provided to the `go_register_toolchain()` repo rule, if you provided one. So they actually both invoke the same starlark code, the `go_download_sdk()` repo rule's implementation function, its just that with the `go_register_toolchain()` repo rule you can only pass a version string, where as with the `go_download_sdk()` repo rule you can pass a `string_list_dict` of mappings between platforms (e.g., linux_amd64) and toolchain tarball filename strings (that are used to build the URL to download them from) and expected hashes. Admittedly its odd they refer to these as "SDKs" and as "toolchains" when under they hood both repo rules point to the same tarball URLs.

The reason we want to use the `go_download_sdk()` repo rule over the `go_register_toolchain()` repo rule to "register a go toolchain/sdk" in our Bazel workspace is because it allows us to bypass some of the `go_download_sdk()` repo rule's implementation function that is problematic for airgapped compatibility. Specificially, if the `go_download_sdk()` repo rule's implementation function is invoked by the `go_register_toolchain()` repo rule, it will not have the `sdks` attribute set, and will execute the starlark code block [here](https://github.com/bazelbuild/rules_go/blob/b6f10d71719c0c944cbd6c219a0a0eea6dc0d3b4/go/private/sdk.bzl#L61) that runs a [`ctx.download` action](https://github.com/bazelbuild/rules_go/blob/b6f10d71719c0c944cbd6c219a0a0eea6dc0d3b4/go/private/sdk.bzl#L71) that downloads a file from the Internet that maps a version string to a tarball URL to actually download the toolchain/sdk from (since these URLs are not manually provided). This is a problem b/c Bazel does not seem to cache files downloaded with the `ctx.download` action in its repository cache, as it does with files downloaded using the `ctx.download_and_extract` action. We had previously run in to this issue with our rust toolchain a while back, hence I was able to (relatively)-quickly spot the issue :).

After I solved this issue with some reconfigurations of our Bazel workspace, I ran into another issue, described below.

**Issue 2:**
 As it turns out, after the `go_download_sdk()` repo rule's implementation function has figured out the URL to actually download the toolchain/sdk tarball from, it must go download it. It does so in a Bazel macro called `[_remote_sdk`](https://github.com/bazelbuild/rules_go/blob/b6f10d71719c0c944cbd6c219a0a0eea6dc0d3b4/go/private/sdk.bzl#L201). Again, in this macro we encountered a similar underlying issue that we saw above. [Due to an outstanding bug](https://github.com/bazelbuild/rules_go/blob/b6f10d71719c0c944cbd6c219a0a0eea6dc0d3b4/go/private/sdk.bzl#L206) in how Bazel rejects files with invalid unicode names, the `rules_go` authors decided to use a `ctx.download` action to download the tarball URL followed by a `ctx.execute` action to unpack the tarball, instead of using the `ctx.download_and_extract` rule that is compatible with airgapped builds. So to solve this issue, I had to fork and patch `rules_go`, so we now use a slightly modified version than what is upstream.

**In Summary**
There were two separate issues that had to be addressed, but they both are caused by the same underlying issue, which is that Bazel does not seem to cache files downloaded with the `ctx.download` action in its repository cache, instead it only caches files downloaded with the `ctx.download_and_extract` action.

The reason I did not just address issue 1 by further patching `rules_go`, e.g.,
1. to enable passing the `sdks` attribute to the `go_register_toolchain()` repo rule --> this would defeat the purpose of having `go_register_toolchain()` repo rule altogether, it would make more sense to just remove the `go_register_toolchain()` repo rule altogether, which seemed like a much larger API change, which would be harder to upstream, and
2. to switch the `ctx.download` action that downloads the toolchain metadata file with a `ctx.download_and_extract` action --> the metadata file is not a tarball its just a JSON file, there is nothing to "extract"

Lastly, I wanted to keep the patch I made as small as possible to make it easier to eventually upstream.

**Comment by eunchan** [comment]
Thanks for the detailed explanation @timothytrippel ! So, it seems bazel doesn't fully support the airgapped environment. The bazel doc ([link](https://bazel.build/docs/external#offline-builds)) however mentioned that `ctx_download()` also caches. So, does this mean bazel has a bug?

**Comment by tjaychen** [comment]
thanks @timothytrippel ! i think i mostly understand... i still have some lingering questions, but that should not block this PR :) 
thank you for triaging this and fixing.

**Review by tjaychen — APPROVED** [review]

**Comment by timothytrippel** [comment]
No problem!

@eunchan Sorry I should clarify, based on my previous encounter with this issue, it seems both the `ctx.download` and `ctx.download_and_extract` actions populate the cache, however, I was hypothesizing that only the `ctx.download_and_extract` action seems to first check the cache before downloading.

This seems to be vaguely hinted at in the bazel repository rules documentation, so I am unsure if it is a bug. Specifically, the description for the `sha256` parameter of the `download` action only states: "the expected SHA-256 hash of the file downloaded. This must match the SHA-256 hash of the file downloaded ..."; while the description for the `sha256` parameter of the `download_and_extract` action also states: "... If provided, the repository cache will first be checked for a file with the given hash; a download will only be attempted if the file was not found in the cache. After a successful download, the file will be added to the cache."

I am running some additional experiments to verify this is indeed the behavior we are seeing, and this was not simply do to compounding a bunch of fixes hehe. If so, I will file an issue with the upstream bazel project.

**Comment by timothytrippel** [comment]
Ok after more thorough experimentation, I have determined my initial intuition was slightly wrong above. Specifically, the `ctx.download` action **does** cache files in the repository cache, and **does** check the repository cache before downloading files (even though the Bazel documentation was slightly vague about this, as mentioned above), but only if a `sha256` parameter is provided to the `ctx.download` action. So **Issue 1** still required the same fix, but for a slightly different reason: specifically, the go toolchain/sdk metadata file that was downloaded via a `ctx.download` [action](https://github.com/bazelbuild/rules_go/blob/b6f10d71719c0c944cbd6c219a0a0eea6dc0d3b4/go/private/sdk.bzl#L71) invoked when using the `go_register_toolchain()` repo rule did not pass a `sha256` parameter.

Issue 2 **does not** require patching / forking the `rules_go` Bazel rules as the reason the toolchain tarballs were not being loaded into repository cache originally was because the `@go_sdk//...` repo was not being fetched in the `prep-bazel-airgapped-build.sh` script. So a separate issue was masking this. This has been fixed, and we can use the upstream `rules_go` as we originally did.

I have updated the last commit to reflect the results of my latest experiments, but I will keep the original comments as is in this thread for full transparency of these endeavors. I apologize for any confusion I may have caused, but I think we have finally gotten to the bottom of these Bazel mysteries!

**Pull request merged**
