### PR TITLE
[keymgr] Minor keymgr fixes

### PR DESCRIPTION
**Pull request by tjaychen**
- Obey valid/ready handshake even during error case when sending random data
- Re-organize each module to contain its own lfsr_en

### CODE REVIEW

**Comment by tjaychen** [comment]
@weicaiyang this should hopefully address the issue where during error scenarios valid / ready handshake is not obeyed.
Let me know if this works. 

Right now, when `keymgr_en_i` is dropped, things could still go haywire, but I'm going to follow that up with a separate fix.

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks for the quick fix.
Please also document the update of `keymgr_en_i` in your following fix

**Comment by tjaychen** [comment]
i'm sorry? the update of keymgr_en_i?

**Comment by weicaiyang** [comment]
> i'm sorry? the update of keymgr_en_i?

you mention "Right now, when keymgr_en_i is dropped, things could still go haywire, but I'm going to follow that up with a separate fix", I think you will have one more update for `keymgr_en_i`

**Comment by tjaychen** [comment]
ooo yes of course.

**Comment by tjaychen** [comment]
sorry before that, does this PR actually address the problem you're seeing?
I didn't have the same test in my area, so i only ran it with the smoke
test.

**Comment by weicaiyang** [comment]
> sorry before that, does this PR actually address the problem you're seeing? I didn't have the same test in my area, so i only ran it with the smoke test.

Yes, I have checked the waveform, which looks good.

**Pull request merged**
