### PR TITLE
[doc] D2S / V2S Milestone updates

### PR DESCRIPTION
**Pull request by msfschaffner**
This is a draft for the D2S/V2S milestone update that we have recently discussed in our silicon meeting.
It updates the documentation and all checklists in the repo.

I picked `security complete` and `security testing complete` as descriptions for D2S and V2S, but maybe `countermeasures complete` and countermeasure testing complete` would be a better fit...

Let me know if you have any suggestions for improved wording.

### CODE REVIEW

**Review by sriyerg — APPROVED** [review]
Thanks @msfschaffner for taking this on!

**Comment by sriyerg** [comment]
> Let me know if you have any suggestions for improved wording.

"security countermeasures implemented" 
"security countermeasures verified"

... expanding on `SEC_CM_` prefixes on these checklist items.

**Comment by msfschaffner** [comment]
That sounds good! I have changed the terminology accordingly.

**Comment by msfschaffner** [comment]
Merging this now so it does not get stale.
Let me know if you think the milestone description should be worded differently.

**Pull request merged**
