### PR TITLE
[dvsim] Use bash when running make underneath

### LINKED ISSUE #5552: [dv] `BUILD_ROOT=${sw_build_dir}` doesn't work for tcsh
Thanks @snpsverif for finding this issue.

It's fine when we run in bash, but seems like we need to use `setenv BUILD_ROOT ${sw_build_dir}` for tcsh
how can we code this better to support tcsh as well?

https://github.com/lowRISC/opentitan/blob/d20804dfa0f1699919dd8c189561a9ec9078d697/hw/dv/tools/dvsim/sim.mk#L59

@sriyerg @rswarbrick any thoughts?

### PR DESCRIPTION
**Pull request by sriyerg**
Fixes #5552.

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

### CODE REVIEW

**Comment by sriyerg** [comment]
@snpsverif, please retry after this is merged. I hope this fixes the issue.

**Comment by weicaiyang** [comment]
@sriyerg thanks for addressing this.
I created a small case
```
SHELL := /bin/bash

all:
	@echo "[make]: all"
	BUILD_ROOT=a
	flock --timeout 3600 ./ --command "echo ok"
	flock --timeout 3600 ./ --command "BUILD_ROOT=b"
```

Enter tcsh to run it and the command in flock seems not to switch to bash. Here is the output.

> [make]: all
> BUILD_ROOT=a
> flock --timeout 3600 ./ --command "echo ok"
> ok
> flock --timeout 3600 ./ --command "BUILD_ROOT=b"
> BUILD_ROOT=b: Command not found.
> make: *** [sim.mk:10: all] Error 1
>

**Comment by sriyerg** [comment]
> @sriyerg thanks for addressing this.
> I created a small case
> 
> ```
> SHELL := /bin/bash
> 
> all:
> 	@echo "[make]: all"
> 	BUILD_ROOT=a
> 	flock --timeout 3600 ./ --command "echo ok"
> 	flock --timeout 3600 ./ --command "BUILD_ROOT=b"
> ```
> 
> Enter tcsh to run it and the command in flock seems not to switch to bash. Here is the output.
> 
> > BUILD_ROOT=a
> > flock --timeout 3600 ./ --command "echo ok"
> > ok
> > flock --timeout 3600 ./ --command "BUILD_ROOT=b"
> > BUILD_ROOT=b: Command not found.
> > make: *** [sim.mk:10: all] Error 1

I tried this locally and it worked for me. PTAL, thanks.

**Comment by rswarbrick** [comment]
This is fine, I guess, but it's not really necessary. Make uses /bin/sh if SHELL isn't set. The problem you're crashing into in #5552 is that `FOO=bar my_cmd` is a bashism. Just use `env FOO=bar my_cmd` and everything should work.

**Comment by sriyerg** [comment]
> This is fine, I guess, but it's not really necessary. Make uses /bin/sh if SHELL isn't set. The problem you're crashing into in #5552 is that `FOO=bar my_cmd` is a bashism. Just use `env FOO=bar my_cmd` and everything should work.

Good point, updated. Given that we also do have bash-specific recipes in there (stdout/stderr redirection for example), its probably safer to also have the SHELL explicitly set to bash.

**Comment by rswarbrick** [comment]
Hmm, ok. I couldn't actually find the redirection you're talking about, though. What do we have that isn't supported by `bin/sh`?

**Comment by imphil** [comment]
I wouldn't bother finding all cases where we use bash-isms and just force the shell to be /bin/bash. It's an endless game of whack-a-mole with no real benefit. So your change LGTM Sri!

**Comment by weicaiyang** [comment]
> I tried this (latest force push) locally and it worked for me. PTAL, thanks.

it works for me too, thanks

**Review by weicaiyang — APPROVED** [review]
thanks for fixing this

**Pull request merged**
