### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by wallento**
Two very minor fixes I stumbled over..

### CODE REVIEW

**Comment by imphil** [comment]
Wow, you got PR ID 5000!

**Comment by imphil** [comment]
On the second patch: The use of "Markdown monospace" is required in our style guide and consistently used in all DIFs. The rendering in https://docs.opentitan.org/sw/apis/dif__spi__device_8h.html#a0d956fdd9e75bbd1aed5eb873c310502 is correct, but as you mentioned, it's broken in the Hugo-rendered documentation:

grafik

Instead of changing the markup in the code, we somehow need to fix the Hugo shortcode that renders the DIF. Maybe you can have a look at that? If not, please file an issue and drop the change itself for someone else to look at a proper fix.

**Comment by wallento** [comment]
Yeah, for me the priority was to get the remaining part of the sentence. I can pick it up to look into the difgen file, but seems @towoe already looks into.
May I suggest that if it is a policy to have signal names in monospace (why not linked?), it should also be mandatory to use them. I saw a mix of prose describing signal names and signal names..

**Comment by towoe** [comment]
Looks like a problem with xml/xslt, but not sure at which point the data is cut of.
As you, @wallento, are so good with Python I would be happy if you can give it a try, otherwise an issue with your finding would also be appreciated.

So it makes sense to drop this commit here as other descriptions are also affected by this.

**Comment by wallento** [comment]
I think it happens outside the Python realm, but will open an issue, someone put a lot of work in this stuff and should know the fix..

**Comment by towoe** [comment]
> May I suggest that if it is a policy to have signal names in monospace (why not linked?), it should also be mandatory to use them. I saw a mix of prose describing signal names and signal names..

I think we have a policy regarding the documentation, but if you a saw a mixture I guess we need to clean this up.
https://docs.opentitan.org/doc/rm/c_cpp_coding_style/#public-function-api-documentation

**Comment by wallento** [comment]
Removed the second commit.
I have to highlight I was not chasing the 5000, but opened a drive-by while reading docs. Sorry to whoever was after it ;)

**Comment by towoe** [comment]
Thanks 5k Stefan!

**Review by towoe — APPROVED** [review]

**Review by gkelly — APPROVED** [review]

**Pull request merged**
