### PR TITLE
Revert "[usbdev] Fixes for I/O modes and expand their tests"

### PR DESCRIPTION
**Pull request by imphil**
This reverts commit 66c509296798cdd9dbeba4deeb381d0cecf3b429.

This commit is suspected to increase FPGA synthesis times by 2x and
seems to cause routing congestion. We'll need to have a closer look
what's going on there, but revert the change first to get CI latencies
back to normal.

### CODE REVIEW

**Comment by imphil** [comment]
The job execution times are too noisy to be sure that this commit is actually at fault, let's see how the CI run looks.

**Comment by imphil** [comment]
This revert brings the FPGA build time down from roughly 60 minutes to 25 minutes. In both cases the design violates timing (and has actually been doing so for quite a while), but the USB commit made things significantly worse.

Let's get this one merged to bring down CI latencies for everyone, and then look at the FPGA timing more closely in a follow-up.

**Review by eunchan — APPROVED** [review]
Probably some kind of timing arc was created? Anyway let's merge this and debug.

**Comment by mdhayter** [comment]
Even before this commit I found some versions of Vivado taking a lot of memory and my machine spending most of its time swapping. >16GB IIRC.

**Comment by vogelpi** [comment]
I can confirm @mdhayter 's comment. I was doing quite a few CI runs and local FPGA builds yesterday - both before and after merging this PR. The whole thing seems to be non-determinstic. I suspect that a different PR merged on Friday or over the weekend actually causes the troubles.

**Comment by mdhayter** [comment]
For completeness, Vivado 2020.1 on my laptop does not show the excessive memory use I saw from earlier versions.

**Pull request merged**
