### PR TITLE
[bazel] use coreutils `expand` instead to expand tabs

### PR DESCRIPTION
**Pull request by nbdd0121**
coreutils has an `expand` utility that can expand tab into spaces. This eliminates this  script that calls bash to call perl to remove tab.

### CODE REVIEW

**Review by rswarbrick — APPROVED** [review]
Nice! I didn't know that tool existed :-D

**Review by hcallahan-lowrisc — APPROVED** [review]
@jwnrt Perl deps being removed :o

**Review by jwnrt — APPROVED** [review]
LGTM, thanks @nbdd0121 

I’m guessing that C++ formatting script was just unused? I don’t see references to it in the repo

**Comment by nbdd0121** [comment]
> I’m guessing that C++ formatting script was just unused? I don’t see references to it in the repo

Yes, I mentioned this in the commit message:
> This was used in `cc_side_outputs.bzl`, which was already removed.

**Pull request merged**
