### PR TITLE
[test] Move crypto test profiling code to its own file.

### PR DESCRIPTION
**Pull request by jadephilipoom**
Minor refactor I'd been planning on for a while; the profiling code should live in its own file so that multiple tests can use it.

### CODE REVIEW

**Review by moidx — APPROVED** [review]
Cool! I wonder if this should live somewhere under `sw/device/lib/..`: `{testing, base, runtime, utils}`. It seems it could be used in other places.

**Comment by jadephilipoom** [comment]
> Cool! I wonder if this should live somewhere under `sw/device/lib/..`: `{testing, base, runtime, utils}`. It seems it could be used in other places.

It is used in a few places: `sw/device/tests/otbn_rsa_test.c` and `sw/device/tests/otbn_ecdsa_op_irq_test.c`, plus `sw/device/silicon_creator/lib/sigverify/sphincsplus/test/verify_test.c`. Maybe I'll move it to `sw/device/lib/testing`, then, and update the other call sites :slightly_smiling_face:

**Comment by moidx** [comment]
Sounds good. This is more of nit. Feel free to move it later as well.

**Comment by jadephilipoom** [comment]
> Sounds good. This is more of nit. Feel free to move it later as well.

CI's failing anyway, so it's easy to do now :slightly_smiling_face:

**Comment by jadephilipoom** [comment]
Updated now. I added a `profile_end_and_print` that also prints the log message for you, since many of the other usage points seemed to be doing that in `profile_end` and it made sense to me.

**Pull request merged**
