### PR TITLE
[reggen] Add a _BIT suffix to bit index constants

### PR DESCRIPTION
**Pull request by mcy**
Also includes a global refactor to use the new names, which unfortunately need to come in the same commit.

The following arcane incantation was used to generate the script that generated this PR.
```sh
grep -ohP '\w+_BIT' build-out/sw/device/lib/**/*.h > bit_names
perl -pi -e 's/(\w+)_BIT/perl -pi -e '"'"'s#\\b$1\\b#$1_BIT#g'"'"' \$1/g' bit_names
for f in ...; do echo $f; ./bit_names $f; done
```

### CODE REVIEW

**Comment by silvestrst** [comment]
> Enjoy my regexp one-liners:
>
> grep -ohP '\w+_BIT' build-out/sw/device/lib/**/*.h > bit_names
perl -pi -e 's/(\w+)_BIT/perl -pi -e '"'"'s#\\b$1\\b#$1_BIT#g'"'"' \$1/g' bit_names
for f in ...; do echo $f; ./bit_names $f; done

Could you please explain in the PR description what you use these one-liners for?

For me the `grep` on current master results in:
```
grep -ohP '\w+_BIT' build-out/sw/device/lib/**/*.h
USBDEV_INTR_COMMON_RX_BIT
USBDEV_INTR_STATE_RX_BIT
USBDEV_INTR_ENABLE_RX_BIT
USBDEV_INTR_TEST_RX_BIT
USBDEV_PHY_CONFIG_EOP_SINGLE_BIT
```

**Comment by gkelly** [comment]
Seems to have failed CI, can you take a look?

**Comment by mcy** [comment]
Should be fixed, but let's see if it does actually come back green.

**Review by lenary — APPROVED** [review]
LGTM, once CI is passing.

**Comment by mcy** [comment]
Looks like CI is green. =)

**Pull request merged**
