### PR TITLE
[prim, tlul, aes] Fix lint errors

### PR DESCRIPTION
**Pull request by vogelpi**
This PR contains three small commits to fix lint errors in some primitives, primgen, tlul and aes.

### CODE REVIEW

**Comment by imphil** [comment]
The generated abstract primitives shouldn't run through lint, but having them look nicer is certainly nice.

**Comment by vogelpi** [comment]
Thanks @imphil . In fact, the abstract primitives create a lot of lint errors. The wildcard in the port list causes 2 lint errors per port plus one for the port list.

**Comment by imphil** [comment]
My point would be that these files shouldn't run through lint (for example, we deliberately use wildcard port assignments, which are not allowed in our style guide). But that's for another day, thanks for the fixes!

**Comment by vogelpi** [comment]
Yes, I agree - we are on the same page here.

**Pull request merged**
