### PR TITLE
[ast] Update the useability of the Jitter model

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Signed-off-by: Jacob Levy <jacob.levy@nuvoton.com>

### CODE REVIEW

**Comment by Jacob-Levy** [comment]
Looks like a bazel issue on CI...

**Comment by timothytrippel** [comment]
> @timothytrippel Looks like a bazel issue on CI...

Looked like it might be a transient failure. I re-triggered CI.

**Comment by Jacob-Levy** [comment]
@timothytrippel Thanks!

**Comment by Jacob-Levy** [comment]
This is a follow up PR to the SYS clock drift that adds a rate mechanism that the random drift gets introduced.
The rate is randomize for each run.

**Comment by tjaychen** [comment]
lgtm, thanks @Jacob-Levy

**Comment by Jacob-Levy** [comment]
@tjaychen This PR does not change the 100MHx calibrated frequecy and max drift (-20%).
The rate of the drift update is reduced at the rate chosen for each run.
You can approve & merge this PR without it effecting the regression run.

**Comment by Jacob-Levy** [comment]
Please approve & merge...

**Comment by tjaychen** [comment]
> Please approve & merge...

i'll try to have a closer look today, sorry haven't had time to review.

**Comment by tjaychen** [comment]
@Jacob-Levy just curious how representative this is of the real design. Does that mean the jitter isn't necessarily per cycle? but could vary across a number of cycles? Is there any way also you can make use of the rng interface input into this function? Perhaps instead of just the initial random, pull the random from the incoming entropy interface?

That way we can test this in open source also.

**Comment by Jacob-Levy** [comment]
@tjaychen It represent the intent without giving the real implementation witch is using the rng for the randomization.

**Comment by tjaychen** [comment]
> @tjaychen It represent the intent without giving the real implementation which is using the rng for the randomization.
> 
> Can not give more then this, even this was a hard call from security point of view.
> 
> We will test the real implementation with the real AST.

right, but what i'm saying is we won't be able to check the edn->ast connection in open source.
Since it doesnt seem like this logic withdraws entropy from there.

Does that matter to you guys?

**Comment by Jacob-Levy** [comment]
@tjaychen The AST has one EDN requestor already in the OS. 
For checking the interface it will do the job.

**Comment by tjaychen** [comment]
sounds good, For the model purposes, does it withdraw EDN at "roughly" the same rate as the real thing? Because that will help stress our distribution, and i assume that jittery clock will withdraw at probably one of the higher rates.

**Comment by Jacob-Levy** [comment]
The simple answer is yes without devolging security information.

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
