### PR TITLE
[rom_ctrl,dv] Minor fixes for coverage improvement

### PR DESCRIPTION
**Pull request by ctopal**
1st commit sets `max_outstanding_req` of rom_ctrl register TLUL agent to 1. That is because TLUL agent for registers of rom_ctrl is autogenerated using `tlul_adapter_reg`. That module allows a `max_outstanding_req` of only 1.

2nd commit improves coverage score of `onehot_fault_cg` by setting `option.at_least` to 0 in coverpoints that we set `option.weight` 0.

Signed-off-by: Canberk Topal <ctopal@lowrisc.org>

Needed to close up functional coverage of `rom_ctrl`

### CODE REVIEW

**Comment by ctopal** [comment]
I added a second commit to this PR as it also improves coverage of `rom_ctrl`. It also improves coverage score of `onehot_fault_cg` by setting `at_least` option to 0 in coverpoints that we set `weight` 0. @weicaiyang I also added you as a reviewer as you might have a different idea about handling the second commit. Thanks for having a look in advance!

**Review by cindychip — APPROVED** [review]
lgtm

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by weicaiyang** [comment]
> I added a second commit to this PR as it also improves coverage of `rom_ctrl`. It also improves coverage score of `onehot_fault_cg` by setting `at_least` option to 0 in coverpoints that we set `weight` 0. @weicaiyang I also added you as a reviewer as you might have a different idea about handling the second commit. Thanks for having a look in advance!

I haven't used `at_least` before. I guess this PR can bring the overall score to 100% if all coverpoint with weight > 0 are covered. Without this fix, as below, we can have instance coverage of this group to 100%, but score is less than 100%. Please correct me if I'm wrong.
Screenshot 2023-01-10 at 11 19 24 AM

**Comment by weicaiyang** [comment]
Since you're improving coverage for rom_ctrl, can you take a look at this #16840 if you have a chance.

**Review by andreaskurth — COMMENTED** [review]
The first commit LGTM, as `outstanding_q` in `tlul_adapter_reg` is currently a single-bit signal.

(Can't comment on the second commit, though.)

**Comment by ctopal** [comment]
> > I added a second commit to this PR as it also improves coverage of `rom_ctrl`. It also improves coverage score of `onehot_fault_cg` by setting `at_least` option to 0 in coverpoints that we set `weight` 0. @weicaiyang I also added you as a reviewer as you might have a different idea about handling the second commit. Thanks for having a look in advance!
> 
> I haven't used `at_least` before. I guess this PR can bring the overall score to 100% if all coverpoint with weight > 0 are covered. Without this fix, as below, we can have instance coverage of this group to 100%, but score is less than 100%. Please correct me if I'm wrong. Screenshot 2023-01-10 at 11 19 24 AM

Yes that's the case @weicaiyang thanks for having a look. I'll merge this PRas it got approved and move to work on the issue you pointed. Thanks everyone!

**Comment by weicaiyang** [comment]
> > > I added a second commit to this PR as it also improves coverage of `rom_ctrl`. It also improves coverage score of `onehot_fault_cg` by setting `at_least` option to 0 in coverpoints that we set `weight` 0. @weicaiyang I also added you as a reviewer as you might have a different idea about handling the second commit. Thanks for having a look in advance!
> > 
> > 
> > I haven't used `at_least` before. I guess this PR can bring the overall score to 100% if all coverpoint with weight > 0 are covered. Without this fix, as below, we can have instance coverage of this group to 100%, but score is less than 100%. Please correct me if I'm wrong. Screenshot 2023-01-10 at 11 19 24 AM
> 
> Yes that's the case @weicaiyang thanks for having a look. I'll merge this PRas it got approved and move to work on the issue you pointed. Thanks everyone!

Great. That's quite annoying when reviewing coverage. Thanks for fixing that.

**Pull request merged**
