### PR TITLE
[ci] Disallow executable .hjson and .md files

### PR DESCRIPTION
**Pull request by rswarbrick**
Note: Don't merge this until #5830 has been merged (to stop Mark having to do another rebase).

### CODE REVIEW

**Review by imphil — APPROVED** [review]

**Comment by mcy** [comment]
I don't get it... why are we disallowing this, instead of banning it for all prefixes except .sh and .py?

(I'm not used to version control that tracks the x bit; Perforce doesn't. I'm kind of a luddite here.)

**Comment by rswarbrick** [comment]
Well, I think we've got some scripts that don't have suffixes. We could do it the other way around as you say (disallow `*.*` unless `*.py` or `*.sh`) but I struggled to get the find command right :-) Very happy to merge a change that does that.

**Comment by moidx** [comment]
It seems easier to audit a list that explicitly grants permissions. I agree, this means we need to make sure we add suffixes to all scripts, and/or have a mechanism to explicitly put the relative path in an allow list.

**Comment by moidx** [comment]
This command seems to think there is a lot of cleanup work related to this: 

```shell
$ find ./ -type f -perm /u=x,g=x,o=x -exec ls -l {} \;
```

**Comment by rswarbrick** [comment]
I'm not sure it's so bad:
```
> find ./ -type f -perm /u=x,g=x,o=x | grep -v vendor | grep -v '/\.git' | grep -vE '\.(py|sh)$'
./doc/ug/dv_methodology/dv_method_multi_gate.svg
./doc/ug/dv_methodology/dv_method_single_gate.svg
./hw/formal/rtl_diff
./hw/formal/rtl_diff_all
./hw/formal/fpv
./hw/formal/fpv_all
./hw/ip/entropy_src/data/entropy_src.hjson
./hw/ip/entropy_src/doc/_index.md
./hw/ip/entropy_src/doc/checklist.md
./hw/ip/otbn/util/otbn-as
./hw/ip/otbn/util/otbn-ld
./hw/ip/otbn/util/otbn-objdump
./hw/ip/otbn/dv/rig/otbn-rig
./hw/ip/csrng/doc/checklist.md
./hw/ip/edn/data/edn.hjson
./hw/ip/edn/data/edn.prj.hjson
./hw/ip/edn/doc/dv/edn_tb.svg
./hw/ip/edn/doc/checklist.md
./hw/ip/spi_host/doc/spi_host_block_diagram.svg
./hw/top_earlgrey/data/top_earlgrey.hjson
./util/opentitan-pgm-fpga/opentitan-pgm-fpga
```
The markdown and hjson files are being fixed as part of this PR, which just leaves some SVGs.

**Comment by moidx** [comment]
from an audit perspective, I think we care about the vendor folders as well.

**Comment by rswarbrick** [comment]
Hmm, but we're not going to be able to fix that without either adding lots of patches to our vendoring scripts or chasing people upstream. I've just pushed up an amended version of this PR that uses a whitelist instead (it was surprisingly easy). This still waives the vendored directories: let's figure out what to do about them separately?

**Comment by rswarbrick** [comment]
@imphil: Re-requesting review because I've just switched this PR around to work the other way, so don't really feel like I can keep the existing approval :-)

**Review by imphil — APPROVED** [review]

**Pull request merged**
