### PR TITLE
[staging, fpga] Route SPI signals to USR_DBG for debugging

### PR DESCRIPTION
**Pull request by alphan**

### CODE REVIEW

**Comment by tjaychen** [comment]
@alphan @colinoflynn just a quick question, are there no exposed headers on the cw310 where we can already probe the SPI device pins..? I vaguely remember asking about that, but I could be wrong.

**Comment by alphan** [comment]
> @alphan @colinoflynn just a quick question, are there no exposed headers on the cw310 where we can already probe the SPI device pins..? I vaguely remember asking about that, but I could be wrong.

I couldn't find anything in the schematics.

**Comment by colinoflynn** [comment]
@tjaychen no - the SPI pins between the SAM3X (which provides the USB support) & FPGA don't have a debug header. Will try to add that on the next spin as it seems like that could be handy (I guess we end up just using Xilinx ILA or route signals to spare header when we need debug pins so I didn't really think of it, but those solutions are not ideal when you want to keep a cleaner top-level design without these random debug things thrown in)

**Comment by tjaychen** [comment]
> @tjaychen no - the SPI pins between the SAM3X (which provides the USB support) & FPGA don't have a debug header. Will try to add that on the next spin as it seems like that could be handy (I guess we end up just using Xilinx ILA or route signals to spare header when we need debug pins so I didn't really think of it, but those solutions are not ideal when you want to keep a cleaner top-level design without these random debug things thrown in)

ah this might be a problem.. because the SPI dev, in addition to being the bootstrap protocol, will also need to become part of the passthrough testing. That one we have to hook-up to a host a capable of doing quad reads etc.  I'm not completely sure if we can emulate that on the SM3X.

**Comment by colinoflynn** [comment]
Got it! Not sure of the implication then, sounds like the "best" option would be for having a mux route them to two spots I think then, and a way to switch between them from within the FPGA. This could be an I/O strapping pin (either routed to DIP switch or SAM3X I/O pin).

>That one we have to hook-up to a host a capable of doing quad reads etc. 

It wouldn't be fast, but you could bit-bang anything you want on the SAM3X. I'm guessing though you want to do this at a more normal clock speed (at least eventually)? The SAM3X SPI peripheral doesn't support QSPI in hardware for sure though.

**Comment by alphan** [comment]
> Does it make sense for @alphan development, to just completely relocate the SPI dev pins (instead of doing debug ones?) Because if we move them to another header, we can eventually connect it to whatever hardware will be running `opentitan-tool` to do bootstrap and other things right?

Would it be an option to support both? I prefer keeping SAM3U <-> FPGA connection because it simplifies development setup and minimizes noise for SCA.

**Comment by tjaychen** [comment]
> > Does it make sense for @alphan development, to just completely relocate the SPI dev pins (instead of doing debug ones?) Because if we move them to another header, we can eventually connect it to whatever hardware will be running `opentitan-tool` to do bootstrap and other things right?
> 
> Can we support both? I prefer keeping SAM3U <-> FPGA connection because it simplifies development setup and minimizes noise for SCA.

I think it depends a bit on how you plan to use this. Because the spi_dev signals are dedicated, it means whenever the spi device drives on one interface, it will always drive them to both.  I'm not really sure if this matters... but I guess it will be up to the integration to not drive both interfaces at the same time.

**Comment by tjaychen** [comment]
> > > Does it make sense for @alphan development, to just completely relocate the SPI dev pins (instead of doing debug ones?) Because if we move them to another header, we can eventually connect it to whatever hardware will be running `opentitan-tool` to do bootstrap and other things right?
> > 
> > 
> > Can we support both? I prefer keeping SAM3U <-> FPGA connection because it simplifies development setup and minimizes noise for SCA.
> 
> I think it depends a bit on how you plan to use this. Because the spi_dev signals are dedicated, it means whenever the spi device drives on one interface, it will always drive them to both. I'm not really sure if this matters... but I guess it will be up to the integration to not drive both interfaces at the same time.

i'm sorry i completely misunderstood, you're not trying to drive from this new debug interface right? You're just trying to monitor it.

**Comment by alphan** [comment]
> > > > Does it make sense for @alphan development, to just completely relocate the SPI dev pins (instead of doing debug ones?) Because if we move them to another header, we can eventually connect it to whatever hardware will be running `opentitan-tool` to do bootstrap and other things right?
> > > 
> > > 
> > > Can we support both? I prefer keeping SAM3U <-> FPGA connection because it simplifies development setup and minimizes noise for SCA.
> > 
> > 
> > I think it depends a bit on how you plan to use this. Because the spi_dev signals are dedicated, it means whenever the spi device drives on one interface, it will always drive them to both. I'm not really sure if this matters... but I guess it will be up to the integration to not drive both interfaces at the same time.
> 
> i'm sorry i completely misunderstood, you're not trying to drive from this new debug interface right? You're just trying to monitor it.

Yes, currently I am using these changes just to monitor the SPI signals using a protocol analyzer. I will eventually need to drive them for a local test to make sure that we can use a generic programmer with the new bootstrap implementation. In that case what you said above would apply but for CW310 this shouldn't be an issue, i.e. we shouldn't try to program it using both the SAM3U and a separate programmer at the same time, right?

**Pull request closed without merging**
