### PR TITLE
[top] Slightly tweak peripheral grouping

### LINKED ISSUE #8220: [top] Peripheral memory grouping enhancements
- Group all crypto modules together
- Group anything that controls flash access together
- i2c and spi device (maybe?) - nice to have
- check peripheral memory alignment, is it NAPOT friendly? (it might not be at the moment) - nice to have

### PR DESCRIPTION
**Pull request by tjaychen**
Fixes #8220

Group all crypto modules together so they can be easily moved in one pmp region

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
LGTM

I take it the [spreadsheet](https://docs.google.com/spreadsheets/d/1ptfdrG5RWiYHKtjYyDO1ubGYPPlN_4YQfzRKO1G1Mls/edit#gid=0) has been updated as well (it looks like it - just wanted to double check)?

**Comment by mundaym** [comment]
Would it make sense to move csrng too? Maybe before aes so you can have csrng+crypto or crypto+keymgr be possible groupings.

**Review by moidx — APPROVED** [review]

**Comment by moidx** [comment]
> Would it make sense to move csrng too? Maybe before aes so you can have csrng+crypto or crypto+keymgr be possible groupings.

`csrng` and `keymgr` are considered part of the crypto complex.

**Comment by tjaychen** [comment]
> > Would it make sense to move csrng too? Maybe before aes so you can have csrng+crypto or crypto+keymgr be possible groupings.
> 
> `csrng` and `keymgr` are considered part of the crypto complex.

yeah the continuous region right now is

hmac -> kmac -> otbn -> keymgr -> csrng -> entropy_src -> edn0 -> edn1

so if we wanted to lump them all into one section we can do so.
I have a feeling it'll probably be everything but the edn's?

**Review by mundaym — APPROVED** [review]

**Pull request merged**
