### PR TITLE
[BLOCKFILE] Re-enable blockfile

### PR DESCRIPTION
**Pull request by msfschaffner**
This reverts commit a2e34042128fc48f24c1df92fbb9a3665c5450e0.

### CODE REVIEW

**Comment by msfschaffner** [comment]
CHANGE AUTHORIZED: BLOCKFILE

**Comment by moidx** [comment]
CHANGE AUTHORIZED: BLOCKFILE

**Review by moidx — APPROVED** [review]

**Comment by msfschaffner** [comment]
@GregAC are we ok merging this into master again?

**Comment by msfschaffner** [comment]
Merging for now - if this causes problems we can take it out again.

**Pull request merged**
