### PR TITLE
[fpga, doc, util] Remove refs and utils related to NexysVideo FPGA board

### PR DESCRIPTION
**Pull request by vogelpi**
The ChipWhisperer CW310 board is the main FPGA development board for OpenTitan. It has been decided to drop support for the NexysVideo board, see lowRISC/OpenTitan#7814. Thus, this commit removes references to the NexysVideo board from the documentation as well as tooling and utilities specific to the NexysVideo board.

This is related to lowRISC/OpenTitan#12221.
This resolves lowRISC/OpenTitan#12185.

### CODE REVIEW

**Comment by vogelpi** [comment]
For OpenOCD to work with the CW310, also #10625 is needed.

**Comment by vogelpi** [comment]
I wasn't sure what we want to do with `spiflash`. We originally used this to flash the firmware on the NexysVideo but we never added support for the CW310 and instead use `cw310_loader.py`. I noticed the [documentation says it also supports communication with Verilator](https://github.com/lowRISC/opentitan/blob/master/sw/host/spiflash/README.md) but I don't know what the current status is. WDYT? @msfschaffner @tjaychen

**Review by msfschaffner — APPROVED** [review]
Thanks a lot for the cleanup, @vogelpi!

**Comment by msfschaffner** [comment]
> I wasn't sure what we want to do with `spiflash`. We originally used this to flash the firmware on the NexysVideo but we never added support for the CW310 and instead use `cw310_loader.py`. I noticed the [documentation says it also supports communication with Verilator](https://github.com/lowRISC/opentitan/blob/master/sw/host/spiflash/README.md) but I don't know what the current status is. WDYT? @msfschaffner @tjaychen

This might actually be a better question for our SW folks... 
@timothytrippel @arunthomas @moidx @cfrantz

**Comment by timothytrippel** [comment]
regarding the `spiflash` tool, we will (eventually) be removing this as `opentitantool` already replaces this functionality for bootstrapping FPGA (and I believe Verilator too, if you want to go the bootstrap route rather than just backdoor loading the flash, though @cfrantz can probably confirm). The only remaining feature of the `spiflash` tool that has yet to be migrated to `opentitantool` is the ability to prep VMEM images for bootstrapping in DV sim.

**Pull request merged**
