### PR TITLE
[tools/dv] updated coverage common exclusions for new naming

### PR DESCRIPTION
**Pull request by rasmus-madsen**
This fix updated the common exclude files for xcelium and vcs to match the changes in 
https://github.com/lowRISC/opentitan/pull/5421/files#diff-e9ad6b3ed6329d4ac6ee1befb2d5e21f373bfc7d18269960ee07c915f3c118a1

### CODE REVIEW

**Comment by rasmus-madsen** [comment]
@weicaiyang 
I see these were updated in between my updated and my PR
I see a lot less of the TL signals being commonly excluded.
should I match this on xcelium.
what blocks are using the rsvd and the user signals?

**Comment by rasmus-madsen** [comment]
(I know the PR can't be merges I will fix once we agree what should be in the files)

**Comment by weicaiyang** [comment]
sorry, I removed those a/d_user related coverage exclusion for VCS at #5968. I forgot to update for Xcelium.
Maybe we can just remove entire a/d_user and consider to randomize `user.rsvd` if it doesn't affect anything.

**Comment by rasmus-madsen** [comment]
@weicaiyang that sounds like a great plan. 
I will exclude the user locally in aes then since it is not used.

**Comment by rasmus-madsen** [comment]
I will close this PR

**Pull request closed without merging**
