### PR TITLE
[doc] Add caching/splicing info to FPGA ref manual

### PR DESCRIPTION
**Pull request by dmcardle**
Add some documentation on bitstream caching and splicing.

Signed-off-by: Dan McArdle <dmcardle@google.com>

### CODE REVIEW

**Comment by a-will** [comment]
Thanks for documenting this!

Is there a more user-facing topic (or set of topics) that these sections could be grouped with? To me, a reference manual about just bitstreams doesn't match what I'd think of as a "primary key" for our users. Am I overthinking it?

**Comment by dmcardle** [comment]
> Thanks for documenting this!

No problem!

> Is there a more user-facing topic (or set of topics) that these sections could be grouped with? To me, a reference manual about just bitstreams doesn't match what I'd think of as a "primary key" for our users. Am I overthinking it?

No idea! I defer to literally anyone else's opinion on where this should go. Maybe the [FPGA reference manual](https://docs.opentitan.org/doc/rm/ref_manual_fpga/)? It's more about bitstream caching and the interface between CI and Bazel than it is directly about FPGAs.

**Comment by a-will** [comment]
> > Thanks for documenting this!
> 
> No problem!
> 
> > Is there a more user-facing topic (or set of topics) that these sections could be grouped with? To me, a reference manual about just bitstreams doesn't match what I'd think of as a "primary key" for our users. Am I overthinking it?
> 
> No idea! I defer to literally anyone else's opinion on where this should go. Maybe the [FPGA reference manual](https://docs.opentitan.org/doc/rm/ref_manual_fpga/)? It's more about bitstream caching and the interface between CI and Bazel than it is directly about FPGAs.

That might be the one. The boot rom development section does refer to splicing there. (Otherwise, you might need to stuff a link to the new markdown file in the right _index.md to get it on the website.)

**Comment by dmcardle** [comment]
Sounds good.  I'll also take the opportunity to mention the new Bazel route for defining splices rather than directly invoking the splicing script.

**Review by a-will — APPROVED** [review]

**Comment by dmcardle** [comment]
Thanks, @a-will! Please merge when you get a chance! (I say this so much, it needs an acronym: PMWYGAC.)

**Pull request merged**
