### PR TITLE
[adc_ctrl/dv] Re-enabled interrupts in clock gating test

### PR DESCRIPTION
**Pull request by NigelScales**
Signed-off-by: Nigel Scales <nigel.scales@gmail.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
should we just merge this in @NigelScales ? or do you prefer to keep this out until a fix is made?

**Comment by NigelScales** [comment]
> should we just merge this in @NigelScales ? or do you prefer to keep this out until a fix is made?

Hi @tjaychen I'd rather keep this out for now while we are closing on V2.

**Comment by NigelScales** [comment]
@tjaychen Linked issue https://github.com/lowRISC/opentitan/issues/11759

**Comment by tjaychen** [comment]
> @tjaychen Linked issue #11759

thank you! i will look at this today. Sorry I was a bit pre-occupied the last few days.

**Comment by NigelScales** [comment]
Given https://github.com/lowRISC/opentitan/pull/11904 I'll set this to be merged.

**Review by cindychip — APPROVED** [review]

**Pull request merged**
