### PR TITLE
[dv/common] Consolidate the dv/data and dv/tools directories 

### PR DESCRIPTION
**Pull request by weicaiyang**
as discussed in DV meeting, consolidate the dv/data and dv/tools directories as below
dv/tools/dvsim
|- sim.mk
|- tests/
|- testplans/
|- vcs.hjson
|- xcelium.hjson
|- fusesoc.hjson
|- common_sim_cfg.hjson, modes, etc
dv/tools/vcs
|- Cov, tcl, excl files
dv/tools/xcelium
dv/tools/riveira

I also changed formal, lint and syn to have similar directories.

Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Review by sriyerg — APPROVED** [review]

**Comment by sriyerg** [comment]
Prefer to have either `dv/data` or `dv/tools`, not both. Going forward we should consolidate all.

**Review by cindychip — APPROVED** [review]
Thanks for doing this. LGTM

**Comment by weicaiyang** [comment]
> Prefer to have either `dv/data` or `dv/tools`, not both. Going forward we should consolidate all.

sure, we can discuss this in meeting. Currently in `dv/tools` there are tool cfg and script. in `dv/data` mostly are hjson files. maybe we can move `dv/data/sim.mk` to `dv/tools`

**Comment by weicaiyang** [comment]
as discussed in DV meeting, consolidate the dv/data and dv/tools directories as below
dv/tools/dvsim
			|- sim.mk
                          |- tests/
 			|- testplans/
			|- vcs.hjson
			|- xcelium.hjson
			|- fusesoc.hjson
			|- common_sim_cfg.hjson, modes, etc
dv/tools/vcs
			|- Cov, tcl, excl files
  	dv/tools/xcelium
	dv/tools/riveira

I also changed formal, lint and syn to have similar directories. @msfschaffner @cindychip PTAL
	formal/tools/dvsim <- formal/data/*
	lint/tools/dvsim <- lint/data/*
	syn/tools/dvsim <- syn/data/*

**Comment by imphil** [comment]
@rswarbrick just to confirm: this does not help https://github.com/lowRISC/ibex/issues/985, but also doesn't make it worse?

**Comment by rswarbrick** [comment]
Yep, that's right. Actually we can probably make some progress with those Ibex bugs now, and I don't think this will break anything (doing so is somewhere on the N'th page of my TODO list...)

**Comment by sriyerg** [comment]
@imphil, @rswarbrick 
If there are no more concerns, is this PR good to go?

**Comment by imphil** [comment]
Yes, lgtm from my side!

**Comment by weicaiyang** [comment]
Thanks @imphil @sriyerg 

@msfschaffner can you take a look at this PR?

**Comment by msfschaffner** [comment]
LGTM, thanks @weicaiyang.

**Review by msfschaffner — APPROVED** [review]

**Comment by rswarbrick** [comment]
Yep, all good from me too. The CI failures are from Verible: it looks like a config file has been renamed but its path hasn't been updated in the Verible configuration?

**Comment by weicaiyang** [comment]
> Yep, all good from me too. The CI failures are from Verible: it looks like a config file has been renamed but its path hasn't been updated in the Verible configuration?

Thanks @rswarbrick. Some recent commits used the old directory structure. Rebased and fixed.

**Pull request merged**
