### PR TITLE
[sensor_ctrl] Update alert_list

### PR DESCRIPTION
**Pull request by tjaychen**
Change alert_list from a vector to individual bits.
The specific bit positions are now declared in `hjson` as it may be useful for software or DV in the future.

### CODE REVIEW

**Review by sriyerg — COMMENTED** [review]
LGTM

**Review by cindychip — APPROVED** [review]
LGTM, thanks so much for doing this Tim. Hope it does not cause too much inconvenience on your side.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by tjaychen** [comment]
Cindy actually i need to change this again.
Let me describe this briefly and get your opinion.

The alert_test registers are technically supposed to actuate the alert
senders to the alert handler right?
But for sensor control, there are effectively two alert arcs.  One from ast
-> sensor ctrl, and the other from sensor control to alert handler.

What i've done now is hook-up the alert test to ast...but i don't think
that's what you actually want.
It seems like I should keep two separate test functions, one that will
directly trigger the alert sender, and the another that will trigger the
ast.

what do you think?

**Comment by cindychip** [comment]
@tjaychen Thanks for letting me know. Yes `alert_test` I believe intended to check alerts triggered from `sensor_ctrl` to `alert_handler` via `prim_alert_sender`.
sorry I am not aware that `sensor_ctrl` has another sets of alerts triggered to ast.

**Comment by tjaychen** [comment]
yeah...the last part is why i'm trying to push ast to absorb sensor control
:)
otherwise.. they send their alerts to sensor control, and then sensor
control sends it to alert handler.

So we technically have two integration arcs we would need to test.
Let me split it up for now and continue working with nuvoton to see if
they're willing to absorb it.

I should say though, if they do absorb it, in the short term, it will be a
bit more top level work for us to massage the idea there can be exteranl
alerts / interrupts.

**Comment by weicaiyang** [comment]
> Cindy actually i need to change this again. Let me describe this briefly and get your opinion. The alert_test registers are technically supposed to actuate the alert senders to the alert handler right? But for sensor control, there are effectively two alert arcs. One from ast -> sensor ctrl, and the other from sensor control to alert handler. 

@tjaychen 
yes, we have 2 ways to trigger alert
ast -> sensor ctrl -> alert sender // this one will be tested separately by DV owner
alert_test in sensor ctrl -> alert sender // this is tested by Cindy's automatic alert_test

> What i've done now is hook-up the alert test to ast...but i don't think that's what you actually want. It seems like I should keep two separate test functions, one that will directly trigger the alert sender, and the another that will trigger the ast. what do you think?

do you mean to add this way to trigger alert? I feel alert_test just needs to directly trigger alert, so this way may be not needed.
alert_test in sensor ctrl -> ast -> sensor ctrl -> alert sender

**Comment by cindychip** [comment]
Yeah, it would be a little bit different from the IPs. I guess if ast absorbed the sensor_ctrl, we will see how the IRQ/alert reqs connected and from there figure out how to test it in top-level dv.
<I should say though, if they do absorb it, in the short term, it will be a
bit more top level work for us to massage the idea there can be exteranl
alerts / interrupts.

**Comment by tjaychen** [comment]
yes that's right.
So i'm think about splitting this up to two
alert_test in sensor_ctrl -> alert_handler ( cindy's automated test)
alert_trig in sensor_ctrl -> ast -> alert event -> sensor_ctrl ->
alert_handler (separate function and test)

**Comment by weicaiyang** [comment]
I see. if ast absorbs the sensor_ctrl, we don't need this one. It requires extra ports in top_earlgrey. if it's not easy to add this, we can just add TODO and implement it when we have more clear picture.

>  alert_trig in sensor_ctrl -> ast -> alert event -> sensor_ctrl -> alert_handler (separate function and test)

**Pull request merged**
