### PR TITLE
REP_RP for flash host read debug

### PR DESCRIPTION
**Pull request by jdonjdon**

### CODE REVIEW

**Comment by jdonjdon** [comment]
image
@tjaychen , I adjust test with rtl update. Now RTL return 1 response with error for 2 requests.

**Comment by tjaychen** [comment]
@jdonjdon i'm not able to reproduce this exactly, did the command change?

**Comment by jdonjdon** [comment]
> @jdonjdon i'm not able to reproduce this exactly, did the command change?

Command it the same but RP has been updated. Did you pull before you ran?

**Comment by tjaychen** [comment]
@jdonjdon i'm not sure exactly what you are expecting in the test.
It would help if you gave some more context. 

Are you expecting all the transactions to error back?

The problem is that in my run of the test (i can't reproduce your results) is the `ctrl_fsm_idle` is being forced low artificially.  When that happens, the incoming host requests are suppressed and an error is generated.   The logic at this point can no longer tell what's correct or not, so I opted to just error back everything.  There may be a slightly better way to do this, but it will require a bit more logic. 

But what are you expecting from your end? When you say 1 response with error and 2 requests, do you mean one doesn't come back?

**Comment by jdonjdon** [comment]
> @jdonjdon i'm not sure exactly what you are expecting in the test. It would help if you gave some more context.
> 
> Are you expecting all the transactions to error back?
> 
> The problem is that in my run of the test (i can't reproduce your results) is the `ctrl_fsm_idle` is being forced low artificially. When that happens, the incoming host requests are suppressed and an error is generated. The logic at this point can no longer tell what's correct or not, so I opted to just error back everything. There may be a slightly better way to do this, but it will require a bit more logic.
> 
> But what are you expecting from your end? When you say 1 response with error and 2 requests, do you mean one doesn't come back?

@tjaychen 
yes the 2nd response doesn't come back. From the figure you can see host_outstanding stays '1'. ctrl_fsm_idle are forced during   4150ns ~ 4550ns. After that, it does go up and down by itself.
Since we already set fatal_err, is there a way to abort from the host? Then I guess we can call it.

**Comment by tjaychen** [comment]
> > @jdonjdon i'm not sure exactly what you are expecting in the test. It would help if you gave some more context.
> > Are you expecting all the transactions to error back?
> > The problem is that in my run of the test (i can't reproduce your results) is the `ctrl_fsm_idle` is being forced low artificially. When that happens, the incoming host requests are suppressed and an error is generated. The logic at this point can no longer tell what's correct or not, so I opted to just error back everything. There may be a slightly better way to do this, but it will require a bit more logic.
> > But what are you expecting from your end? When you say 1 response with error and 2 requests, do you mean one doesn't come back?
> 
> @tjaychen yes the 2nd response doesn't come back. From the figure you can see host_outstanding stays '1'. ctrl_fsm_idle are forced during 4150ns ~ 4550ns. After that, it moves up and down by itself. Since we already set fatal_err, is there a way to abort from the host? Then I guess we can call it.

hmmm... is there something different about your setup? Because I can't reproduce it. The error I'm getting is that there's an unexpected error.

**Comment by jdonjdon** [comment]
> > > @jdonjdon i'm not sure exactly what you are expecting in the test. It would help if you gave some more context.
> > > Are you expecting all the transactions to error back?
> > > The problem is that in my run of the test (i can't reproduce your results) is the `ctrl_fsm_idle` is being forced low artificially. When that happens, the incoming host requests are suppressed and an error is generated. The logic at this point can no longer tell what's correct or not, so I opted to just error back everything. There may be a slightly better way to do this, but it will require a bit more logic.
> > > But what are you expecting from your end? When you say 1 response with error and 2 requests, do you mean one doesn't come back?
> > 
> > 
> > @tjaychen yes the 2nd response doesn't come back. From the figure you can see host_outstanding stays '1'. ctrl_fsm_idle are forced during 4150ns ~ 4550ns. After that, it moves up and down by itself. Since we already set fatal_err, is there a way to abort from the host? Then I guess we can call it.
> 
> hmmm... is there something different about your setup? Because I can't reproduce it. The error I'm getting is that there's an unexpected error.
> 
> There's no way to abort from host at this point, because we're too far into the transaction, and we just suddenly forced a signal. The error recovery here is going to be a bit tricky. I have an idea in mind, but I want to be able to reproduce all the failure cases first.

@tjaychen Did you check your waveform?
my test has been messy after fatal_err is set. So you already have reproduced in your wave.

**Comment by tjaychen** [comment]
> > > > @jdonjdon i'm not sure exactly what you are expecting in the test. It would help if you gave some more context.
> > > > Are you expecting all the transactions to error back?
> > > > The problem is that in my run of the test (i can't reproduce your results) is the `ctrl_fsm_idle` is being forced low artificially. When that happens, the incoming host requests are suppressed and an error is generated. The logic at this point can no longer tell what's correct or not, so I opted to just error back everything. There may be a slightly better way to do this, but it will require a bit more logic.
> > > > But what are you expecting from your end? When you say 1 response with error and 2 requests, do you mean one doesn't come back?
> > > 
> > > 
> > > @tjaychen yes the 2nd response doesn't come back. From the figure you can see host_outstanding stays '1'. ctrl_fsm_idle are forced during 4150ns ~ 4550ns. After that, it moves up and down by itself. Since we already set fatal_err, is there a way to abort from the host? Then I guess we can call it.
> > 
> > 
> > hmmm... is there something different about your setup? Because I can't reproduce it. The error I'm getting is that there's an unexpected error.
> > There's no way to abort from host at this point, because we're too far into the transaction, and we just suddenly forced a signal. The error recovery here is going to be a bit tricky. I have an idea in mind, but I want to be able to reproduce all the failure cases first.
> 
> @tjaychen Did you check your waveform? my test has been messy after fatal_err is set. So you already have reproduced in your wave. Let me know that is not the case. I can create a new rep_pr.

I couldn't reproduce your error. I saw another error.

**Comment by tjaychen** [comment]
ugh... i just realized this is redundant. In this test you are forcing `ctrl_fsm_idle`, but `ctrl_fsm_idle` is a directly decoded output from a sparse fsm... so there's no reason for me to cover it like this. 

I'm going to reduce this check just to the partition for now, since the other one is implicitly covered. If you actually managed to fault `ctrl_fsm_idle`, the flash controller would go into self escalation and everything would shut down.

**Comment by jdonjdon** [comment]
> ugh... i just realized this is redundant. In this test you are forcing `ctrl_fsm_idle`, but `ctrl_fsm_idle` is a directly decoded output from a sparse fsm... so there's no reason for me to cover it like this.
> 
> I'm going to reduce this check just to the partition for now, since the other one is implicitly covered. If you actually managed to fault `ctrl_fsm_idle`, the flash controller would go into self escalation and everything would shut down.

SG.

**Comment by tjaychen** [comment]
okay i have a version i am semi-okay with.
It does not cover all faults, because of course it can't... i think it does reasonably cover the scenario in your testing.
If an attacker hits the transaction count for example, everything is doomed and will definitely get stuck. I'm probably going to enhance that to a prim count.

**Comment by jdonjdon** [comment]
@tjaychen 
Test has been cleaned up #15186 
Please check in a RTL change.

**Comment by tjaychen** [comment]
let me make one more update and i'll merge the two commits into a PR.

**Comment by jdonjdon** [comment]
rtl update is in #15208

**Pull request closed without merging**
