### PR TITLE
[ottf] Allow printing cycle counts that don't fit in uint32_t.

### PR DESCRIPTION
**Pull request by jadephilipoom**
Ask me how I ran into this one (it was RSA key generation). Doing the arithmetic to get microseconds here would require importing `math.h` and using `udiv64_slow` and also be annoying to print, so for the large cycle counts I just didn't print the microseconds.

### CODE REVIEW

**Review by rswarbrick — APPROVED** [review]
I'm hoping you didn't hit this in simulation :-) Looks good to me!

**Review by engdoreis — APPROVED** [review]
I would never think anyone would need that when I added the profiler to this macro :)

**Review by jwnrt — APPROVED** [review]

**Comment by jadephilipoom** [comment]
> I'm hoping you didn't hit this in simulation :-) Looks good to me!

Luckily it was on FPGA, so I only had to wait 20 minutes or so :grinning:

**Comment by jwnrt** [comment]
This PR has timed out on the SWB&T job on all three CI attempts, but I can't imagine this change affecting CI times.

@jadephilipoom would you mind rebasing to see if that helps? Otherwise we might have to increase the timeout (all three attempts have been very close to finishing within the 3h limit).

**Comment by jadephilipoom** [comment]
> This PR has timed out on the SWB&T job on all three CI attempts, but I can't imagine this change affecting CI times.
> 
> @jadephilipoom would you mind rebasing to see if that helps? Otherwise we might have to increase the timeout (all three attempts have been very close to finishing within the 3h limit).

I've already done a few rebase attempts, I think it's not helping. Probably changing `check.h` means we can't use any cached test results?

**Comment by jwnrt** [comment]
> Probably changing `check.h` means we can't use any cached test results?

Yes that sounds right.

Please could you increase [the timeout](https://github.com/lowRISC/opentitan/blob/master/azure-pipelines.yml#L178) a small amount, perhaps just to 190 or 200 minutes? The actual tests finish, but uploading the results pushes it over 3 hours.

CC @mundaym

**Comment by jadephilipoom** [comment]
Rebased and updated the timeout to 3.5 hours. :crossed_fingers:

**Comment by jadephilipoom** [comment]
Seems to have worked! Only Kokoro is failing now. I'll merge this, then.

**Pull request merged**
