### PR TITLE
[entropy_src] regression fix and re-generate RTL

### PR DESCRIPTION
**Pull request by cindychip**
This PR has two commits:

1. Add entropy_src to Make flow
2. Regenerate RTL files for entropy_src

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
Thanks for the fixing

**Comment by sriyerg** [comment]
Thanks for the fix!

**Review by sriyerg — APPROVED** [review]

**Review by msfschaffner — APPROVED** [review]
LGTM, thanks!

**Comment by tjaychen** [comment]
o that's hilarious, so the issue is that we forgot to put this as part of autogen? thanks for the fix!

**Review by tjaychen — APPROVED** [review]

**Comment by cindychip** [comment]
Thanks you all for the quick review. Yeah.. it turns out to be a part of auto-gen, I think both me and Michael were thinking it was some functional issues....

**Comment by sriyerg** [comment]
> o that's hilarious, so the issue is that we forgot to put this as part of autogen? thanks for the fix!

Exactly why things should not be removed from CI once they've been added :)

**Pull request merged**
