### PR TITLE
[hw,soc_proxy,rtl] Sync soc_proxy from integrated_dev to master

### PR DESCRIPTION
**Pull request by Razer6**

### CODE REVIEW

**Comment by antmarzam** [comment]
**This is WIP**

I run the command:
```
../../mig_pr_review.py --source-branch integrated_dev  --target-branch master --migration-branch Razer6/soc-proxy-sync-to-master --path hw/top_darjeeling/ip/soc_proxy --show-diff=: | tee darjeeling_dif
```

List of commits which missed porting information:

1. [[hw/top_darjeeling] Add scaffold of SoC Proxy IP module](https://github.com/lowRISC/opentitan/pull/24442/commits/c6883541d8db362d190e7212ed812163622d3d4c)  [c688354](https://github.com/lowRISC/opentitan/pull/24442/commits/c6883541d8db362d190e7212ed812163622d3d4c)
This commit doesn't add `soc_proxy` to `util/reggen/ip_block.py`. Missing bits are in commit: https://github.com/lowRISC/opentitan/commit/6f37daa27915924122cb476653ee8a474a89582b 
2. asas
3. as

**This is WIP**

**Comment by Razer6** [comment]
> 1. This commit doesn't add `soc_proxy` to `util/reggen/ip_block.py`. Missing bits are in commit: [6f37daa](https://github.com/lowRISC/opentitan/commit/6f37daa27915924122cb476653ee8a474a89582b)  (file `util/reggen/ip_block.py`)

`soc_proxy` is already present in master as a placeholder: https://github.com/lowRISC/opentitan/blob/master/util/reggen/ip_block.py#L62

> * `/hw/top_darjeeling/doc/design/README.md` missing in branch.

That file is an artifact of the Darjeeling instantiation, which is not yet present (also not with this PR).

> * Check the autogenerated `hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson` in master matches the intended one from the integrated_dev branch [here](https://github.com/lowRISC/opentitan/blob/f7fdeae62551751eb70d89fd2df01b8a24ca2984/hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson)

That file is an artifact of the Darjeeling instantiation, which is not yet present (also not with this PR).

**Comment by antmarzam** [comment]
@Razer6 / @andreaskurth I just went through the entire dif. I've updated the comment [above](https://github.com/lowRISC/opentitan/pull/24442#issuecomment-2368364128)

**Comment by Razer6** [comment]
All the open changes will be addressed from other PRs. @rswarbrick Could you take a look at this as well to get it merged?

**Comment by rsahita** [comment]
May be good to add a diagram for this SOC Proxy - there is not much documentation, readme or ToO o/w.

**Comment by antmarzam** [comment]
I just went again through the diff after pulling the latest changes and I believe my diff comment above ([here](https://github.com/lowRISC/opentitan/pull/24442#issuecomment-2368364128)) still stand.

**Comment by Razer6** [comment]
> I just went again through the diff after pulling the latest changes and I believe my diff comment above ([here](https://github.com/lowRISC/opentitan/pull/24442#issuecomment-2368364128)) still stand.

@antmarzam What exactly are you referring to? `hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson` will not be generated with this PR. That will happen at a later point where Darjeeling will be actually created.

**Comment by Razer6** [comment]
> May be good to add a diagram for this SOC Proxy - there is not much documentation, readme or ToO o/w.

Agree. Documentation should be improved. I created https://github.com/lowRISC/opentitan/issues/24677 to track that and not block the pure migration PR here.

**Comment by antmarzam** [comment]
> > I just went again through the diff after pulling the latest changes and I believe my diff comment above ([here](https://github.com/lowRISC/opentitan/pull/24442#issuecomment-2368364128)) still stand.
> 
> @antmarzam What exactly are you referring to? `hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson` will not be generated with this PR. That will happen at a later point where Darjeeling will be actually created.

@Razer6 I just meant that I went through the 3-way diff after pulling your latest changes to see if my comment above with missing files still stand. 
Not saying they have to be part of this PR though, just flagging up the differences.

**Comment by Razer6** [comment]
> @Razer6 I just meant that I went through the 3-way diff after pulling your latest changes to see if my comment above with missing files still stand. Not saying they have to be part of this PR though, just flagging up the differences.

Gotcha, they'll be created with the Darjeeling instantiation. Can you formally approve this PR?

**Comment by antmarzam** [comment]
The PR looks good - happy to get it merged. 
I'm just copy-pasting down-here the post-merge action item list so it's not forgotten:
### Post merge Action items:

- Check the autogenerated hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson in master matches the intended one from the integrated_dev branch [here](https://github.com/lowRISC/opentitan/blob/f7fdeae62551751eb70d89fd2df01b8a24ca2984/hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson)

- add documentation (including a block-diagram) for soc-proxy

- Add testing environment for soc proxy

- Ensure missing files in this PR (which are being ported via a separate PR) make their way to master

**Review by antmarzam — APPROVED** [review]

**Comment by Razer6** [comment]
Thanks @antmarzam. Passing this over to @rswarbrick

**Review by rswarbrick — APPROVED** [review]
Thanks for the change, @Razer6, and thanks for the review, @antmarzam.

**Pull request merged**
