### PR TITLE
[reggen] Remove the devmode input

### PR DESCRIPTION
**Pull request by msfschaffner**
As discussed on #10311 we are removing the devmode input signal from the codebase, since it has been decided that this will not be used.

### CODE REVIEW

**Review by a-will — APPROVED** [review]

**Comment by msfschaffner** [comment]
@arnonsha @meisnere @sha-ron Quick heads-up that when you are switching to `master`, you have to regenerate your reg-nodes and remove the `devmode_i` input in your database as well inside the OTP and Flash wrappers.

CC @jdonjdon

**Comment by msfschaffner** [comment]
@vogelpi can you merge this if it looks good to you? Thanks!

**Review by rswarbrick — APPROVED** [review]
This all looks sensible to me. And its gets rid of lots of slightly-copy-paste code. Nice!

**Review by vogelpi — APPROVED** [review]
Awesome, thanks @msfschaffner !

**Comment by meisnere** [comment]
Hi,
I tried to run on latest DB:
util/regtool.py -r hw/ip/flash_ctrl//data/flash_ctrl.hjson --alias hw/foundry/ip/flash_ctrl/data/prim_tsmc40ulpef_flash.hjson -t hw/foundry/ip/prim_tsmc40ulpef/rtl/

devmode_i still exists on the created file: flash_ctrl_prim_tsmc40_reg_top

Am I missing something?

**Comment by vogelpi** [comment]
For reference, [this comment](https://github.com/lowRISC/opentitan/issues/10311#issuecomment-1783477568) summarizes the rationale for removing the `devmode_i` signal.

**Pull request merged**
