### PR TITLE
refactor(spid)!: Change `tpm_header_not_empty` to level

### PR DESCRIPTION
**Pull request by eunchan**
_Related Issue: https://github.com/lowRISC/opentitan/issues/15282_

**This change may affect SW ISR for TPM command handling**

The current interrupt scheme assumes the input is an event (pulse). If the input is a status, it was recommented to add an edge detector to create a pulse.

In certain cases, this may create unwanted (phantom) interrupts or missing interrupts depending on the SW approach to handling the interrupts.

To remove the race condition, HW now connects the status signal to the interrupt in this commit. With the change, now SW is responsible to mask the interrupt while the SW queues the interrupt to event queues.

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM

**Review by a-will — APPROVED** [review]
So the driver would do something like this:

```c
isr_return_t spi_tpm_isr() {
  uint32_t irq_deferred = 0;
  uint32_t irq_status = spi_tpm_get_irq_status();
  if (irq_status & kSpiTpmFifoIrq) {
    irq_deferred |= kSpiTpmFifoIrq;
    schedule_deferred_work(spi_tpm_deferred_work);
  }
  // ...
  spi_tpm_mask_irq(irq_deferred);
  return IRQ_HANDLED;
}

void spi_tpm_deferred_work() {
  uint32_t irq_handled = 0;
  uint32_t irq_status = spi_tpm_get_irq_status();
  if (irq_status & kSpiTpmFifoIrq) {
    spi_tpm_handle_fifo_irq();
    irq_handled |= kSpiTpmFifoIrq;
  }
  // ...
  // Now that we think the FIFO has been emptied, clear the latched status.
  spi_tpm_clear_irq_status(irq_handled);
  spi_tpm_unmask_irq(irq_handled);
  // If the FIFO received more data after handling, the interrupt would assert
  // again here.
}
```

**Comment by eunchan** [comment]
> So the driver would do something like this:
> 
> ```c
> isr_return_t spi_tpm_isr() {
>   uint32_t irq_deferred = 0;
>   uint32_t irq_status = spi_tpm_get_irq_status();
>   if (irq_status & kSpiTpmFifoIrq) {
>     irq_deferred |= kSpiTpmFifoIrq;
>     schedule_deferred_work(spi_tpm_deferred_work);
>   }
>   // ...
>   spi_tpm_mask_irq(irq_deferred);
>   return IRQ_HANDLED;
> }
> 
> void spi_tpm_deferred_work() {
>   uint32_t irq_handled = 0;
>   uint32_t irq_status = spi_tpm_get_irq_status();
>   if (irq_status & kSpiTpmFifoIrq) {
>     spi_tpm_handle_fifo_irq();
>     irq_handled |= kSpiTpmFifoIrq;
>   }
>   // ...
>   // Now that we think the FIFO has been emptied, clear the latched status.
>   spi_tpm_clear_irq_status(irq_handled);
>   spi_tpm_unmask_irq(irq_handled);
>   // If the FIFO received more data after handling, the interrupt would assert
>   // again here.
> }
> ```

BTW, `spi_tpm_clear_irq_status()` will not be needed if we want to make this strictly status interrupt. Status only can be cleared by alleviating the cause. In this case the FIFO should be emptied.

**Comment by a-will** [comment]
> > So the driver would do something like this:
> > ```c
> > isr_return_t spi_tpm_isr() {
> >   uint32_t irq_deferred = 0;
> >   uint32_t irq_status = spi_tpm_get_irq_status();
> >   if (irq_status & kSpiTpmFifoIrq) {
> >     irq_deferred |= kSpiTpmFifoIrq;
> >     schedule_deferred_work(spi_tpm_deferred_work);
> >   }
> >   // ...
> >   spi_tpm_mask_irq(irq_deferred);
> >   return IRQ_HANDLED;
> > }
> > 
> > void spi_tpm_deferred_work() {
> >   uint32_t irq_handled = 0;
> >   uint32_t irq_status = spi_tpm_get_irq_status();
> >   if (irq_status & kSpiTpmFifoIrq) {
> >     spi_tpm_handle_fifo_irq();
> >     irq_handled |= kSpiTpmFifoIrq;
> >   }
> >   // ...
> >   // Now that we think the FIFO has been emptied, clear the latched status.
> >   spi_tpm_clear_irq_status(irq_handled);
> >   spi_tpm_unmask_irq(irq_handled);
> >   // If the FIFO received more data after handling, the interrupt would assert
> >   // again here.
> > }
> > ```
> 
> BTW, `spi_tpm_clear_irq_status()` will not be needed if we want to make this strictly status interrupt. Status only can be cleared by alleviating the cause. In this case the FIFO should be emptied.

Yup! But until we make that infrastructure change, that code snippet shows when to do the clear.

**Comment by tjaychen** [comment]
thanks all for the fix. I don't remember if it's another PR already, but should we update the spi_device programmers model documentation to point out this particular interrupt bit needs to be handled a little differently?

I think usbdev has the same.

**Comment by eunchan** [comment]
> thanks all for the fix. I don't remember if it's another PR already, but should we update the spi_device programmers model documentation to point out this particular interrupt bit needs to be handled a little differently?
> 
> I think usbdev has the same.

I will steal @a-will 's snippet and paste the code into the programmer's guide section. hehe :)

**Comment by tjaychen** [comment]
thanks @eunchan !

**Pull request merged**
