### PR TITLE
[sw] Fix up all warn_unused_result warnings.

### PR DESCRIPTION
**Pull request by mcy**
I haven't upgraded this to a warning yet, though I feel like at this point it would not be unreasonable to ask DIF authors to do due diligence in fixing usages in their PRs; I can tack on a commit that does the upgrade.

In most places I just added a CHECK (since it's in "test" code), but I had to make some executive decisions on hwo to handle the errors.

### CODE REVIEW

**Comment by lenary** [comment]
If this PR fixes the warning everywhere, remove the `-Wno-error=warn-unused-result` from `meson.build`.

**Comment by mcy** [comment]
@lenary This actually surfaced a bug in `rv_timer_test`. Please glance at that before I merge.

**Comment by imphil** [comment]
build with GCC fails:

```
FAILED: /opt/buildcache/riscv/bin/riscv32-unknown-elf-gcc -Isw/device/lib/e287d45@@uart_ot@sta   -I/home/vsts/work/1/s -I/home/vsts/work/1/a/build-out -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c11 -g -nostdinc -isystem/home/vsts/work/1/s/sw/device/lib/base/freestanding -Os -fvisibility=hidden -Wa,--no-pad-sections -march=rv32imc -mabi=ilp32 -mcmodel=medany -MD -MQ 'sw/device/lib/e287d45@@uart_ot@sta/uart.c.o' -MF 'sw/device/lib/e287d45@@uart_ot@sta/uart.c.o.d' -o 'sw/device/lib/e287d45@@uart_ot@sta/uart.c.o' -c ../../s/sw/device/lib/uart.c
../../s/sw/device/lib/uart.c: In function 'uart_init':
../../s/sw/device/lib/uart.c:25:9: error: ignoring return value of 'dif_uart_init', declared with attribute warn_unused_result [-Werror=unused-result]
   25 |   (void)dif_uart_init(base_addr, &config, &uart0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../s/sw/device/lib/uart.c: In function 'uart_send_char':
../../s/sw/device/lib/uart.c:29:9: error: ignoring return value of 'dif_uart_byte_send_polled', declared with attribute warn_unused_result [-Werror=unused-result]
   29 |   (void)dif_uart_byte_send_polled(&uart0, (uint8_t)c);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by lenary** [comment]
Yeah, the GCC build issue is not great because that's supposed to be the way to explicitly ignore a result.

@mcy it seems you can do `if (<call>) {}` to ignore things in GCC, but it may just be we have to handle these, I'm not sure.

**Comment by lenary** [comment]
Oh, you need to fix the two issues in `sw/device/lib/uart.c` to use the `if (…) {}` ignore instead.

**Pull request merged**
