### PR TITLE
[sysrst_ctrl] Update CDC handling, reformat and clean up code

### PR DESCRIPTION
**Pull request by msfschaffner**

### CODE REVIEW

**Comment by tjaychen** [comment]
my....so much code reduction

**Comment by msfschaffner** [comment]
Jep, the new CDC handling scheme really pays off here ;)

**Comment by msfschaffner** [comment]
@tjaychen any objections to move this in? I will do some more Hjson cleanup and add the `wp_l` function in a follow-up.

**Comment by tjaychen** [comment]
no objections. let's merge.

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
