### PR TITLE
[ earlgrey ] Updating module memory map to better reflect future plans

### PR DESCRIPTION
**Pull request by martin-lueker**
Soon to be added modules should be added to the memory map in
their proper places.   This update rearranges top_earlgrey to
better align with the plan laid out in the following
spreadsheet:

https://docs.google.com/spreadsheets/d/1ptfdrG5RWiYHKtjYyDO1ubGYPPlN_4YQfzRKO1G1Mls/edit#gid=0

Signed-off-by: Martin Lueker-Boden <martin.lueker-boden@wdc.com>

### CODE REVIEW

**Comment by martin-lueker** [comment]
Hey everyone, 
   Since I'm in the process of adding pattgen in #4155, and soon I2C, I figured this would be a decent time to implement the new memory map in the spreadsheet you've been talking about.  This will clear up address space for adding these other IP's in their proper places.

Feel free to reject this PR if this is premature.

**Comment by martin-lueker** [comment]
Note: I realize that there is a second AON Xbar that is in these upcoming plans, and I did not update that.  My goal with this PR is to simply adjust the modules and Xbars that are already instantiated so that address space is clear for the new IP's.

-M

**Comment by imphil** [comment]
Thanks @martin-lueker, I'm fine with doing these changes now. Can you please address the CI issue (re-generate headers, ideally in a second commit for the duration of the review), and rebase to resolve the merge conflict?

**Comment by eunchan** [comment]
LGTM. Thanks for addressing this @martin-lueker !

**Comment by martin-lueker** [comment]
Hi @imphil,
   Yes.  Certainly.

**Comment by martin-lueker** [comment]
Thanks Everyone.  I've sorted out the merge conflict, which was a bit thorny, and regenerated the headers.   Let me know when you think it is ready.

**Comment by martin-lueker** [comment]
Also, the OTBN memory space is quite large, as @lenary pointed out in the spreadsheet.  So I've tentatively move OTBN to a base address of 0x4200_0000, and updated the spreadsheet.

**Comment by lenary** [comment]
@martin-lueker we should be careful to ensure that the address space for peripherals remain contiguous, or else managing PMP regions becomes more difficult than we want from software.

**Comment by msfschaffner** [comment]
@martin-lueker: @mwbranstad, @eunchan and I just had a quick chat regarding the EDN blocks, since they have not been reflected in the memory map yet. we added them right after CSRNG and entropy_src, including a reserved space of 0x2000 for future EDN instances. Could you take a look at the updated spreadsheet and check whether that is ok?

**Comment by mwbranstad** [comment]
The newly updated spaces look good (csrng, entropy_src, edn0, edn1), but there are appears to be other blocks that seem to not match the addresses in the memory map table. Not knowing the state of these blocks, I did not update the hjson for any of these blocks.

**Comment by msfschaffner** [comment]
@mwbranstad this is a different PR, I think you are referring to your changes in https://github.com/lowRISC/opentitan/pull/4211, right?

If I understand correctly, it is the purpose of this PR to align the addresses of all IPs according to the updated address map.

**Comment by mwbranstad** [comment]
@msfschaffner yes, I was referring to the address updates in PR #4211

**Comment by martin-lueker** [comment]
@lenary: I've moved OTBN closer to the other IPs.
@msfschaffner: I've made room for the entropy IPs as you annotated.
So WTYT? Anything else?

**Comment by msfschaffner** [comment]
Thanks for aligning. Looking at the memory map, I think we forgot to allocate space for the SRAM scrambling devices: 

- `sram_ctrl_main` on the main xbar 
- `sram_ctrl_ret` on the aon xbar. 

Since `nmi_gen` will soon be removed entirely, I believe we can reuse `0x411C_0000` for the  `sram_ctrl_main`. `sram_ctrl_ret` could be placed at `0x4051_0000`, and `ram_ret` at `0x4052_0000`. I have updated the spreadsheet, and I believe no further changes on your side are necessary.

**Review by msfschaffner — APPROVED** [review]
LGTM, but it would be good if others could double check as well.

**Comment by msfschaffner** [comment]
Ok CI has passed. I merge this now - otherwise it just gets stale again.

**Pull request merged**
