### PR TITLE
[sysrst_ctrl] Add sysrst_ctrl agent

### PR DESCRIPTION
**Pull request by patel-madhuri**
Signed-off-by: Madhuri.Patel <madhuri.patel@ensilica.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
Looks like this is most generated by script. it will be great if you can add some descriptions in the PR for the things that are modified after auto-gen.
otherwise, LGTM

**Comment by sriyerg** [comment]
Sysrst_controller only has bunch of wires as input and output. They don't follow any specific protocol. Can we simply make do with an interface instead? 
```systemverilog
interface sysrst_ctrl_if;
  logic pwrb_in_i;
  ...
  
endinterface 
```

**Comment by sriyerg** [comment]
> Sysrst_controller only has bunch of wires as input and output. They don't follow any specific protocol. Can we simply make do with an interface instead?
> 
> ```systemverilog
> interface sysrst_ctrl_if;
>   logic pwrb_in_i;
>   ...
>   
> endinterface 
> ```

IMO an agent is not needed - you can use this interface to directly drive inputs and sample outputs.

**Comment by patel-madhuri** [comment]
As sysrst_ctrl_agent is not needed, we are closing this PR.

**Pull request closed without merging**
