### PR TITLE
[dv/hmac] Hmac V2

### PR DESCRIPTION
**Pull request by cindychip**
Re-declare V2 in HMAC with the following steps:
1). Add wipe secret support in PR:  #10363
2). Issue reset in specific FSM states to increase FSM cvoerage in PR #10417
3). Remove old exclusion file due to the design change: PR #10427

Signed-off-by: Cindy Chen <chencindy@opentitan.org>

### CODE REVIEW

**Comment by cindychip** [comment]
https://github.com/lowRISC/opentitan/pull/10530

After this UNR exclusion PR is merged, the HMAC should reach 90% coverage as below:
image

**Comment by cindychip** [comment]
This is ready for review, the regression result is here: https://reports.opentitan.org/hw/ip/hmac/dv/latest/results.html

Coverage exclusion: https://github.com/lowRISC/opentitan/pull/10530
Only exclude adapter_sram because the msg fifo is write-only, and one FSM state because it is implemented for future throughput optimization.

Thanks!

**Review by weicaiyang — APPROVED** [review]
LGTM

**Review by matutem — APPROVED** [review]
LGTM

**Review by sriyerg — APPROVED** [review]

**Review by eunchan — APPROVED** [review]

**Comment by cindychip** [comment]
thanks everyone for reviewing

**Pull request merged**
