### PR TITLE
[OTBN] Mark OTBN as being in the D1/Functional design stage

### LINKED ISSUE #3361: [OTBN] Get design into D1 stage with regards to current specification
**With respect to the current version of the OTBN spec**, we need to get the design to D1 stage. See https://docs.opentitan.org/doc/project/development_stages/#hardware-design-stages for a detailed description of the design stages.

It is understood that there will be spec changes afterwards. We should use this exercise to get a better understanding of where we expect changes in the future, and mark those parts of the spec.

- [ ] Feature set finalized, spec complete
- [ ] CSRs identified; RTL/DV/SW collateral generated
- [ ] SW interface automation completed
- [ ] Clock(s)/reset(s) connected to all sub modules
- [ ] Lint run setup
- [ ] Ports Frozen 

It's probably best to go through this list of items in a meeting.

> estimate 4

### PR DESCRIPTION
**Pull request by imphil**
Work on OTBN has been ongoing for a while now and we're making rapid
progress in the specification and design efforts. To reflect that, we
propose to move the design into the D1 (Functional) design stage. See
https://docs.opentitan.org/doc/project/development_stages/#hardware-design-stages
for a detailed explanation of the design stages.

Importantly, the design stage only refers to the v0.1 version of the
design. This version is not ready for production silicon, but an
intermediate milestone that allows us to synchronize implementation,
verification, simulator, and software development work. There will be
future revisions to the specification. The Google Doc [OTBN Enhancement
Proposals](https://docs.google.com/document/u/3/d/1rgtPlXiJo21dq7gL_QZdV2XPISR78hkoLhJV8f1pt5M/edit)
lists high-level proposals to evolve the design, which will be addressed
in a subsequent version.

In short, the D1 design stage indicates that the design "does something,"
but isn't complete yet. Looking at the individual items in the hardware
design stages documentation:

* **Feature set finalized, spec complete.** We have identified a
  feature set for the v0.1 version which is a very solid starting point
  for fine-tuning the ISA in various ways. This feature set is
  documented well in the OTBN specification. We had success in running
  larger chunks of crypto code in a simulator implementing this
  specification, serving as a proof-point that the design is going in
  the right direction.

* **CSRs identified; RTL/DV/SW collateral generated**. All CSRs have
  been documented in the HJSON file, and regtool has generated
  appropriate bindings for it. UVM-based CSR tests run in CI and nightly
  regressions.

* **SW interface automation completed.** A DIF has been written and
  merged, which makes use of all auto-generated header files, e.g. to
  obtain information about the register layout.

* **Clock(s)/reset(s) connected to all sub modules.** This is the case.

* **Lint run setup.** Lint is setup and runs in CI and in nightly lint
  runs.

* **Ports Frozen.** OTBN has only a small set of top-level ports, which
  are fully hooked up into the earlgrey design.

The RTL implementation of the OTBN design has started, and we continue
to evolve it by implementing more and more instructions, as well as
improving the implementation of existing ones.

Fixes #3361

### CODE REVIEW

**Comment by sjgitty** [comment]
Any chance you could add a signoff doc ala [this one](https://docs.opentitan.org/hw/ip/i2c/doc/checklist/index.html#d1)

**Comment by cdgori** [comment]
From the technical definition of D1, OTBN seems to be in that state, assuming all the various linting things have passed.  But I'm not clear what it means for it to be 0.1, do we have some technical meaning for that (as opposed to 0.3 etc)?  Do we go all the way to D2 on 0.1 before starting on D0 (or D1?) of 0.3?  Did I miss a roadmap for the versions and what they mean?  (Entirely possible)

**Comment by sjgitty** [comment]
> I'm not clear what it means for it to be 0.1, do we have some technical meaning for that (as opposed to 0.3 etc)?

Ah, that's a good catch. We originally had version numbers < 1.0 to indicate goals for public launch, or other intermediate milestones not intended to be tapeout-ready. AFAIK this OTBN work should be heading towards tapeout-worthy quality, so should be marked as 1.0. WDYT @imphil ?

**Comment by imphil** [comment]
Thanks @sjgitty for pointing towards the checklist at https://docs.opentitan.org/doc/project/checklist/index.html, I've been following https://docs.opentitan.org/doc/project/development_stages/ which has similar, but slightly different content. I'll clean that up in the coming days (just want to get some preliminary fixes in first).

I filled out the checklist and added it to this PR.

On versioning:

My/our thinking was to use versions, as they are described in https://docs.opentitan.org/doc/project/development_stages/#versioning for two main goals:
- To help us synchronize between specification, RTL, simulator (ISS), software (DIF) and DV work.
- To avoid staying in the D1/V1 stages for a very long time with no in-between progress tracking, since we continuously "chase" an expanding specification.

My idea how this could work would be roughly as follows:

Let's call the scope of the OTBN specification as it is today version "0.1". No real meaning attached to it, other than "it's not tapeout ready". Let's call a subsequent version "0.2".

We would then have two things going on in parallel:

1. Make progress on implementing version 0.1 of the spec in the various domains (DV, RTL, DIF, sim). As part of this development process, we would
   - clarify this specification where needed (e.g. if we discover small-ish "bugs" in the spec),
   - potentially move in the development stages for the various domains, e.g. from V0 to V1, or from S0 to S1.
2. Prepare larger spec changes or the addition of new features for a subsequent version 0.2.

Once we're "sufficiently" done with implementing version 0.1 of the specification, and have a agreed on a "reasonably stable" 0.2 version of the spec, we can then switch over to implementing version 0.2, and prepare version 0.3 of the spec.

Some notes on that:
- There's a lot of vagueness in this description, and that's intentional.
  - We don't want to be bound to a process where we "know better". A good example is OTBN's hardware loop support: we know that we're not fully happy with the design as-is, and have ideas to improve it. Instead of implementing it only because it's in the 0.1 spec, and then potentially completely rewriting it in a 0.2 spec, we could choose to not implement this feature (and document that somewhere, e.g. in the checklist document). 
  - Not every version needs to be pushed to the same level of completeness regarding DIF, HW and DV stages. Likely only *0 and *1 will be reached for the non-1.0 versions.
- We don't really know when a good time for those version increments would be. Potentially aligning them with quarterly milestones could work, or simply on demand.
- I'd use the "1.0" version for a specification which is agreed to meet tapeout goals. 
- From what I've seen, the AES block is using a similar approach, and it seemed to work well for @vogelpi.

All of this is early thinking on how versioning could be useful for OTBN development (based on reading the development stages documentation), please let me know what you think!

**Comment by sjgitty** [comment]
@imphil your rationale makes. It might not jibe with the wording of versioning in the development stages document, but perhaps you could suggest a rewording there that makes sense. I wouldn't go into the depth of detail that you've done here, but perhaps indicate that until (D2? D3?) that the version might be used to indicate progression towards a final version when a) the design is large / complex b) the final version is not agreed upon but development wants to be in full gear.

In general we should aim to have a finalized spec agreed upon before going to D1, but I'm agreeing that in this case and some others that might not always be possible.

The content here lgtm, would like to see another OTBN designer and perhaps @felixmiller give the lgtm on the transition content.

**Comment by imphil** [comment]
@sjgitty I read the versioning docs a couple times, and in my understanding, I'm using the versions pretty much exactly as they were intended to be used. 

https://docs.opentitan.org/doc/project/development_stages/#versioning reads (highlights are mine):
> The Version of a design element indicates its progress towards its final feature set for expected product. Typically all designs are expected to simply be in 1.0 version, but there are reasons for exceptions. Designs which have a specification that defines an intermediate goal are indicated as < 1.0 version. There are many times where this is useful: **when the intermediate goal is a beneficial subset of functionality to enable other development; when the final feature set is not known but a sufficient set is ready for development; when the final feature set is postponed until a future date, but owners are keen to get the design started; etc.** In essence, the sub-1.0 designation indicates that it is understood that the stage metrics are temporary pending a final feature set.

Aren't all those points roughly matching what we're trying to achieve here? Given you probably wrote this part of the documentation, I must be misinterpreting things somewhere.

**Comment by sjgitty** [comment]
We must be prescient! I just assumed the wording wasn't written in this manner, because the original thinking was taking a 0.x design from D0 --> D3 at the same level (like what we did for faux-tapeouts of launch IP). Here you're considering using it to increment versions while within one D stage. Turns out the wording fits nicely for both, so sounds like it it WAI.

**Comment by felixmiller** [comment]
This LGTM but following disclaimer/notes:
- I haven't followed this transition process for any other IP yet
- I am not able to give a sound review on the `checklist.md` (therefore only this LGTM comment and not a full review)
- I read through the linked texts and the conversation here. If I understood everything correctly we are in agreement that it is a 0.1 version we are moving to D1 as still indicated in the json file in this PR. I would have my issue calling what we have today a 1.0 version since it is not a MVP yet. We ran some algorithmic primitives but not all required ones and we know that we will have to make adaptions.
- I can agree with everything @imphil is writing in the commit message

**Comment by imphil** [comment]
@rswarbrick can you also have a look at this transition and have a look if you feel the points in the checklist haven been adequately addressed? I'll then add you and Felix as reviewers in the checklist (and fix the doc build CI error).

**Comment by rswarbrick** [comment]
My only quibble is for the `SPEC_COMPLETE` target. I think we have a couple of open issues about things like call stack depth and loop behaviour. I understand that this part of the design is in flux, but I don't think it's completely nailed down in the v0.1 spec. Do you think we need to address these questions at this point, or is it a bit of a waste of time, since some of this might be ripped out before we implement it anyway?

**Comment by imphil** [comment]
> Do you think we need to address these questions at this point, or is it a bit of a waste of time, since some of this might be ripped out before we implement it anyway?

It really depends on how quickly we can come up with an alternative. If we can't do that within the next couple of weeks, I'm inclined to fully specify the LOOP instructions and the call stack.

For the purpose of the D1 status, I personally wouldn't see that as blocker. D1 requires "SPEC_COMPLETE: Spec complete, feature set finalized." I'd argue we have finalized the feature set (for v0.1), but there are (known and unknown) bugs/issues in the spec. 

How about we call out this fact more explicitly in the checklist? (We do have notes in the spec also pointing to cases where we know about problems.)

**Comment by rswarbrick** [comment]
Sounds like a plan to me.

**Comment by imphil** [comment]
@rswarbrick I updated the text to be more explicit about the spec status. PTAL.

**Comment by moidx** [comment]
LGTM as D1 v0.1. 

How many development iterations are we planning before reaching v1.0?

**Comment by imphil** [comment]
> How many development iterations are we planning before reaching v1.0?

I don't really know and don't have much of an opinion either. I'd expect an increase in the version number at least once per quarter/milestone, but I could also see reasons to increment it twice in a quarter if we're iterating more quickly. I see the version more as a useful, but ultimately "meaningless" number in our path to feature-complete spec. What would be your thoughts on that?

**Review by rswarbrick — APPROVED** [review]
Looks good to me.

**Pull request merged**
