### PR TITLE
DONOTMERGE flash rd arb issue

### PR DESCRIPTION
**Pull request by jdonjdon**
cmd 
./util/dvsim/dvsim.py ./hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i flash_ctrl_ro -v m -s 1 --waves

### CODE REVIEW

**Comment by tjaychen** [comment]
@jdonjdon one thing i noticed about the test.
Since the controller always issues fairly large reads, the host and controller interleaving fall into a pretty fixed pattern.

Ie, the host reads 5 (arbitration count limit), then the controller reads 1, rinse and repeat.

I think it would be good to have the controller reads vary in size as well (from very small to very big.. also making sure smaller controller reads can go back to back), This could create more stressful scenarios.

Also, in the test i was looking at, it looks like the host direct read always issued reads that are at least one cycle apart. I think it would be good to have some in consecutive cycles as well.

**Comment by jdonjdon** [comment]
> he controller reads vary in size as well (fr

This test sends controller request varies between  1x8  through 32x8 words.
Let me add 1x8 only controller request to compete with the host request as a start.
We can add more patterns always.

For the host request,
probably I need to talk you our DV team how to manipulate the agent, cause
it runs with 0 delay. @sriyerg , @weicaiyang  are there options to issue tlul transaction back to back
and still can capture response?

**Comment by tjaychen** [comment]
> > he controller reads vary in size as well (fr
> 
> This test sends controller request varies between 1x8 through 32x8 words. Let me add 1x8 only controller request to compete with the host request as a start. We can add more patterns always.
> 
> For the host request, probably I need to talk you our DV team how to manipulate the agent, cause it runs with 0 delay. @sriyerg , @weicaiyang are there options to issue tlul transaction back to back and still can capture response?

could we go all the way down to 1x4? :) 
The controller can technically issue a read of exactly 1 bus word. And yeah, maybe in this test I just happen to not see the 1x8 case. 

For the back to back..i thought there was a randomized bit controlling that in the tlul agent/drive. @weicaiyang showed my once..but i can't remember where it is.

**Comment by jdonjdon** [comment]
> exactly 1

1x4 can be done. So you want a half resolution access (s.t.   1.5,  3.5,   8.5...) ? or just 0.5 only?

**Comment by weicaiyang** [comment]
> This test sends controller request varies between 1x8 through 32x8 words. Let me add 1x8 only controller request to compete with the host request as a start. We can add more patterns always.
> 
> For the host request, probably I need to talk you our DV team how to manipulate the agent, cause it runs with 0 delay. @sriyerg , @weicaiyang are there options to issue tlul transaction back to back and still can capture response?

yes, just add this in run_opts and set `blocking` = 0 to have b2b TL accesses.
> run_opts: ["+zero_delays=1"]

```
tl_access(..., .blocking(0));
```

**Comment by jdonjdon** [comment]
> 

thanks @weicaiyang , but when I do  blocking =0, it doesn't receive data and return all 0 for rsp.
how can I capture return data with blocking = 0?

**Comment by weicaiyang** [comment]
> thanks @weicaiyang , but when I do blocking =0, it doesn't receive data and return all 0 for rsp. how can I capture return data with blocking = 0?

`tl_access(..., .blocking(0))` assumes data return and check are done in scb.
If you need to have the return data in a sequence, perhaps you can try to move this fork...join_none portion to your sequence.

```
// spawn N non-blocking threads
foreach (mem_data[i]) begin
  automatic int local_i = i;
  fork
    tl_access(..., .data(mem_data[local_i]) .blocking(1));
  join_none
  #0;
end
// wait all the tl_access to complete
csr_utils_pkg::wait_no_outstanding_access();
```

**Comment by jdonjdon** [comment]
> > thanks @weicaiyang , but when I do blocking =0, it doesn't receive data and return all 0 for rsp. how can I capture return data with blocking = 0?
> 
> `tl_access(..., .blocking(0))` assumes data return and check are done in scb. If you need to have the return data in a sequence, perhaps you can try to move this fork...join_none portion to your sequence.
> 
> ```
> // spawn N non-blocking threads
> foreach (mem_data[i]) begin
>   automatic int local_i = i;
>   fork
>     tl_access(..., .data(mem_data[local_i]) .blocking(1));
>   join_none
>   #0;
> end
> // wait all the tl_access to complete
> csr_utils_pkg::wait_no_outstanding_access();
> ```

forking solve the problem.
thanks @weicaiyang

**Pull request closed without merging**
