### PR TITLE
[sensor_ctrl] Updates based on latest AST integration

### PR DESCRIPTION
**Pull request by tjaychen**
- Based on recent nuvoton discussions
- Remove sensor_ctrl from always on domain
- Update sensor_ctrl alert event handling to assume async
- Remove 'ack modes' and replace with recoverable / fatal alerts
- Add software programming to categorize alerts into fatal or
  recoverable
- Add wakeup function

### CODE REVIEW

**Comment by tjaychen** [comment]
@eunchan / @msfschaffner can you guys have a quick look and let me know what you think?

**Comment by tjaychen** [comment]
probably need to make the configuration registers shadowed.

**Review by msfschaffner — APPROVED** [review]
LGTM in general.

Just for my understanding: does that mean that `sensor_ctrl` will only be able to raise a wakeup request while in "light" sleep where clocks are gated, but the power is not turned off?

**Comment by arnonsha** [comment]
@Jacob-Levy
We need to coordinate this change. Please aporove once youre available to make the ntil changes.

**Comment by tjaychen** [comment]
> LGTM in general.
> 
> Just for my understanding: does that mean that `sensor_ctrl` will only be able to raise a wakeup request while in "light" sleep where clocks are gated, but the power is not turned off?

yes that's right. I will add a note to the spec about this.

**Comment by tjaychen** [comment]
> @Jacob-Levy
> We need to coordinate this change. Please aporove once youre available to make the ntil changes.

@arnonsha i actually don't think there are any nuvoton required changes. This is mostly to align with the ast's async set, sync clear behavior while doing some clean-up on the digital end. 

Let me know if i missed something.  The other PR that adds the sense ports does indeed need to be coordinated.

**Pull request merged**
