### PR TITLE
[usbdev] Remove aon_usb_events_active from async reset

### LINKED ISSUE #10879: DFT - In usbdev_aon_wake block aon_usb_events_active reset should be controlled in scan-mode
aon_usb_events_active affecting ~12 FFs. In scan mode it is not controlled, hence these FFs are removed from scan.
SpyGlass-DFT message:
'chip_earlgrey_asic.top_earlgrey.u_pinmux_aon.u_usbdev_aon_wake.aon_usb_events_active' is not disabled for 12 flip-flop(s)
image

### PR DESCRIPTION
**Pull request by tjaychen**
- fixes #10879

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@a-will might need your help here, is there any reason we can't just qualify active events after the filter? 
Are there scenarios you think where the `active` can go low, but the filter result remains valid?

**Comment by tjaychen** [comment]
> @a-will might need your help here, is there any reason we can't just qualify active events after the filter? Are there scenarios you think where the `active` can go low, but the filter result remains valid?

If the concern is the filter delay, we could actually drop the existing `enable_i` input

**Comment by a-will** [comment]
> > @a-will might need your help here, is there any reason we can't just qualify active events after the filter? Are there scenarios you think where the `active` can go low, but the filter result remains valid?
> 
> If the concern is the filter delay, we could actually drop the existing `enable_i` input

I was mostly being conservative with residual state, both in the synchronizers and the filter, but it might not be necessary. At the current clock rate, we'd be looking at ~25 us of delayed samples when we suspend, but to trigger that, we'd have to see J continuously for at least 3 ms. It'd be impossible to see a bus reset (continuous SE0) during that period for a functioning device. For the residual VBUS removal case, that should also be impossible since we shouldn't be seeing J anymore (the pull-up should get disconnected, so it'd just be capacitive effects, I suppose).

If we wanted to cut that down even further (to allow for significantly lower AON clock frequencies), we could also gate the _input_ to the filters with `aon_usb_events_active`.

**Review by a-will — APPROVED** [review]
LGTM -- Thanks for taking care of that!

**Comment by tjaychen** [comment]
> > > @a-will might need your help here, is there any reason we can't just qualify active events after the filter? Are there scenarios you think where the `active` can go low, but the filter result remains valid?
> > 
> > 
> > If the concern is the filter delay, we could actually drop the existing `enable_i` input
> 
> I was mostly being conservative with residual state, both in the synchronizers and the filter, but it might not be necessary. At the current clock rate, we'd be looking at ~25 us of delayed samples when we suspend, but to trigger that, we'd have to see J continuously for at least 3 ms. It'd be impossible to see a bus reset (continuous SE0) during that period for a functioning device. For the residual VBUS removal case, that should also be impossible since we shouldn't be seeing J anymore (the pull-up should get disconnected, so it'd just be capacitive effects, I suppose).
> 
> If we wanted to cut that down even further (to allow for significantly lower AON clock frequencies), we could also gate the _input_ to the filters with `aon_usb_events_active`.

o yeah i thought about applying it at the input also. But mostly avoided because it would create CDC complaints (even though prim filter specific addresses that).

**Review by cindychip — APPROVED** [review]

**Pull request merged**
