### PR TITLE
[doc] Fixup paths in SUMMARY.md to some silicon_creator manuf docs

### LINKED ISSUE #20607: [top_darjeeling] Doc server fails to start
Is there a way to start the server even if some files are incomplete/invalid?

It would be really nice to be able to access the existing documentation even if some non-critical files are missing. It seems the issue here is about the test plan, which should not prevent from accessing the register definition files for example.
Thanks

```
git log -n 1
commit fcaf4d9c8862b8cbd88803bc4f812b25212bedac (HEAD -> integrated_dev, origin/integrated_dev)
Author: Adrian Lees <a.lees@lowrisc.org>
Date:   Thu Dec 7 13:57:37 2023 +0000

 ./bazelisk.sh clean
WARNING: Blaze clean does not support starlark options. Ignoring options: [--@rules_rust//rust/toolchain/channel=nightly, --@rules_rust//:clippy_flags=-Aclippy::bool_assert_comparison,-Aclippy::uninlined_format_args,-Dwarnings]
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

./util/site/build-docs.sh serve
Build Directory : /home/eblot/Sources/Git/Rivos/opentitan/build-site
Building doxygen...
warning: Tag 'HTML_TIMESTAMP' at line 112 of file '/home/eblot/Sources/Git/Rivos/opentitan/util/doxygen/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Doxygen build complete.
INFO: Analyzed target @crate_index//:mdbook__mdbook (293 packages loaded, 7930 targets configured).
INFO: Found 1 target...
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of @crate_index//:mdbook__mdbook up-to-date (nothing to build)
INFO: Elapsed time: 25.552s, Critical Path: 24.39s
INFO: 446 processes: 169 internal, 277 linux-sandbox.
INFO: Build completed successfully, 446 total actions
INFO: Build completed successfully, 446 total actions
2023-12-08 14:53:53 [INFO] (mdbook::book): Book building has started
Error: No testpoints or covergroups found in /home/eblot/Sources/Git/Rivos/opentitan/sw/device/silicon_creator/manuf/data/manuf_testplan.hjson
2023-12-08 14:54:04 [ERROR] (mdbook::utils): Error: The "testplan" preprocessor exited unsuccessfully with exit status: 1 status
```

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**
This has been a problem since those files were moved back in 2833b0c. This was causing the website build to break, but was not noticed since we were not building the site with changes for integrated in CI.

There are some code checks that the file exists before we parse it (the error was coming from the testplan preprocessor calling the dvsim Tesplan library), but looking at the build tree after attempting to build, these files now exist! This jolted my memory, that mdbook has this default behaviour where if you add a chapter to the SUMMARY.md and the file does not exist, mdbook will create a file there in it's place, presumably to avoid a dead link in the final book. @HU90m maybe we should add our own checks to one the existing pre-processors to check for dead links, and hopefully avoid this problem in the future?

### CODE REVIEW

**Comment by rivos-eblot** [comment]
I'm not sure this addresses the core issue reported in #20607: I think a missing link should trigger a warning at build time and/or a warning in the generated index, but should not make the whole build to fail. _i.e._ when desperately looking for doc on A, failing to generate doc on unrelated B is not a critical issue - at least at development stage.

**Comment by hcallahan-lowrisc** [comment]
I agree that this PR does not fix the issue as described. It does fix it according to the title at least ;) I’ll remove the link between the two for now. 

However, I’m not sure making the documentation build more robust i.e. working in-part when the inputs are broken/malformed is necessarily the best path forward. I think it would be better to actually get the CI setup for this, to prevent merges going in that break it unknowingly. Also, if CI published the docs to be hosted externally then you have access to a working version of them at any time, and theoretically at least that shouldn’t go down during development.
At least to me that seems the best thing to do, because we kind of have to do it anyway. Is that okay?

**Review by rswarbrick — APPROVED** [review]

**Comment by rivos-eblot** [comment]
> Is that okay?
Sure, as long as the existing documentation is available for "consumption" in the development stage, it is ok.

**Comment by hcallahan-lowrisc** [comment]
CI failures unrelated to this documentation change. Hence merging.

**Pull request merged**
