### PR TITLE
[entropy_src] Move ENTROPY_SRC version 2.0.0 verification_stage to V2S

### PR DESCRIPTION
**Pull request by vogelpi**
This resolves lowRISC/OpenTitan#22469.

### CODE REVIEW

**Comment by vogelpi** [comment]
CHANGE AUTHORIZED: hw/ip/entropy_src/data/entropy_src.hjson

**Comment by vogelpi** [comment]
We're currently fixing the last items for M5. Once those final PRs are merged, we can sign-off V2S.

**Review by h-filali — APPROVED** [review]
LGTM

**Comment by andreaskurth** [comment]
CHANGE AUTHORIZED: hw/ip/entropy_src/data/entropy_src.hjson

**Review by andreaskurth — APPROVED** [review]
Approving based on [this analysis](https://github.com/lowRISC/opentitan/issues/22469#issuecomment-2209496840) and [this review](https://github.com/lowRISC/opentitan/issues/22469#issuecomment-2211109660). Thanks a lot for all your work, @vogelpi and @h-filali!

**Pull request merged**
