### PR TITLE
[keymgr] Clarify the sideload_sel error function

### PR DESCRIPTION
**Pull request by tjaychen**
- clarifies some issues found in #15862, #15858
- This better describes what the check does and makes it slightly more useful.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
alright @weicaiyang , this is IMO more useful.
To test this, instead of randomly forcing the sideload_sel like before, you should force the valid from the actual key slot.

When you do this, if the intended function is not actually for it to be valid, an error will trigger.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by weicaiyang** [comment]
> alright @weicaiyang , this is IMO more useful. To test this, instead of randomly forcing the sideload_sel like before, you should force the valid from the actual key slot.
> 
> When you do this, if the intended function is not actually for it to be valid, an error will trigger.

sounds good, Thanks Tim
I think we still need to do the force during a sideload operation, right?

**Comment by tjaychen** [comment]
> > alright @weicaiyang , this is IMO more useful. To test this, instead of randomly forcing the sideload_sel like before, you should force the valid from the actual key slot.
> > When you do this, if the intended function is not actually for it to be valid, an error will trigger.
> 
> sounds good, Thanks Tim I think we still need to do the force during a sideload operation, right?

right, but this is intended for the attack..where at the end of the operation, someone tries to load the key into a slot that it was not intended for (for example kmac -> otbn).

**Pull request merged**
