### PR TITLE
[syn/upf] Add file that defines iso values for LC signals

### LINKED ISSUE #4244: [life cycle] Decide on strategy to handle life cycle related broadcasts across power domain boundaries
The life cycle controller may not always be in the always on domain (although we can discuss if it actually makes sense to keep it in the always on domain always). 

As a result of this, it means any consuming agent of life cycle that is in fact always on may need to have some way of knowing what the relevant values should be before power goes offline.  

So this issue is encompassing really two items

- Identify the always on modules that need to consume life cycle and whether there is a need for such modules to understand the life cycle information across power boundaries (there may not be).
- If the answer to the above bullet is yes, then we need to identity the correct strategy to ensure such a definition is consistent.

### PR DESCRIPTION
**Pull request by msfschaffner**
Fixes #4244.

@arnonsha let me know if this is an acceptable format or not.

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Review by tjaychen — APPROVED** [review]
lgtm, pending review from Arnon.
hmm... i do think long term maybe we need to generate this file though... otherwise if the "off" value ever changes, we might forget to modify this file.

**Comment by arnonsha** [comment]
Ah..
I was expecting a list of all signals (bits) that should be clamped to 1. Of course this info can be generated from the 2 variables using a tcl function however I believe an explicit list (as opposed to a generated list) will give more clarity and reduce risk of errors. Since we only have 3 such signals, this list would be short. Wouldn't you agree ?

**Comment by arnonsha** [comment]
Or maybe it should be generated asing a script that is executed when running the top level make file (or anybither stahe along the way) ?

**Comment by msfschaffner** [comment]
Ok that is possible - can you give an example for the exact syntax you expect (for one signal)?
I will do this manually for now - we can template this in the future.

**Comment by tjaychen** [comment]
@msfschaffner , shall we table this to M3? :)
i know you have a million things to do already.  For example Arnon, it would be good if you can specify the exact syntax of what you're looking for, and we can just help fill it in.  If you want to create the template file, might be even better!

**Comment by msfschaffner** [comment]
Yeah let's do this after M2. Important is that we have done the review.

**Comment by arnonsha** [comment]
Need to generate an explicit TCL list:
```
set UPF_ISO_LC_OFF_PORTS_CLAMP1 {
   top_earlgrey/u_aon_timer_aon/lc_escalate_en_i[3] \
   top_earlgrey/u_aon_timer_aon/lc_escalate_en_i[1] \
   top_earlgrey/u_pinmux_aon/lc_escalate_en_i[3]    \
   top_earlgrey/u_pinmux_aon/lc_escalate_en_i[1]    \
   top_earlgrey/u_pinmux_aon/lc_check_byp_en_i[3]   \
   top_earlgrey/u_pinmux_aon/lc_check_byp_en_i[1]   \
   }

```
I will then concat it to other "clamp to 1 signal" list that we're already have.

**Comment by msfschaffner** [comment]
Merging for now - let me know if things need to be amended.

**Comment by arnonsha** [comment]
Looks good. Thanks.
We will add to our upf

**Pull request merged**
