### PR TITLE
Cherry-pick to earlgrey 1.0.0: [sival/aes] Add aes_force_prng_reseed_test and aes_prng_reseed_test

### PR DESCRIPTION
**Pull request by github-gcontributor**
Manually created backport PR from PR #24574 to branch earlgrey_1.0.0.

### CODE REVIEW

**Comment by engdoreis** [comment]
I changed the base branch from master to earlgrey_1.0.0, @github-gcontributor can you please fix the conflict so that we can merge it.

**Comment by github-gcontributor** [comment]
> I changed the base branch from master to earlgrey_1.0.0, @github-gcontributor can you please fix the conflict so that we can merge it.

Hi @engdoreis, 
I am able to manually resolve the conflict. 
Kindly proceed to merge the PR and let me know if there is any other step required to make the test part of the regression.

**Review by engdoreis — APPROVED** [review]

**Comment by github-gcontributor** [comment]
Hi @engdoreis ,
Any thing on my side on this?

**Comment by engdoreis** [comment]
Merging since the CI error is not related to this PR.

**Pull request merged**
