### PR TITLE
[dv regr tool] Support for multi IP sim runs

### PR DESCRIPTION
**Pull request by sriyerg**
- Added support for running sims for multiple IPs in parallel
  Command line:
  ```console
  $ util/dvsim.py hw/dv/data/master_sim_cfgs_list.hjson -i sanity --reseed 1 [--purge]
  ```
  - The master_sim_cfgs_list.hjson only adds UART and HMAC hjsons - need to
  add the cfg hjsons for other IPs once they are available

- Added 'FlowCfg.py' which serves as base class implementation for hjson
based infrastructure specification - SimCfg now extends from it. This is
done in preperation to add support for other ASIC flows such as FPV,
lint, etc in future.

- Several optimizations to reduce run time (12x speedup!)

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

### CODE REVIEW

**Comment by weicaiyang** [comment]
@sriyerg 
just tried this PR. Somehow, the build options isn't correct for the 2nd build (hmac)
and it looks like build_opts is generated twice like `vcs build_opts build_opts`

And it's fine to run single IP - hmac

**Comment by sriyerg** [comment]
> @sriyerg
> just tried this PR. Somehow, the build options isn't correct for the 2nd build (hmac)
> and it looks like build_opts is generated twice like `vcs build_opts build_opts`
> 
> And it's fine to run single IP - hmac

Thanks for trying out. I have now fixed it. TL;DR; the problem was due to assignment of lists (which is passed by reference)

Long explanation:
If the input file passed to the tool is a master cfg list, then the tool creates a hierarchical SimCfg object (parent creates child for uart, hmac, etc and saves them to self.cfgs array). When the child cfgs are created, the original args (from the command line) need to be passed unmodified. This problem was with the lines like these in `SimCfg.__init__` function:
```
  self.build_opts = args.build_opts	
```
This actually only passes a reference of `build_opts` object in `args` to `self`. Eventually, `self.build_opts` is modified; due to pass by reference, args.build_opts gets modified too. This messes up the child cfgs completely.

**Comment by weicaiyang** [comment]
> I ran the following command to run sanity regression in HMAC and UART once:
> 
> ```
> $ util/dvsim.py hw/dv/data/master_sim_cfgs_list.hjson -i sanity --reseed 1
> 
> INFO: [SimCfg] Scratch path for uart: /edascratch/sriyer-opentitan/scratch/multi_cfgs.uart.sim.vcs
> INFO: [SimCfg] Scratch path for hmac: /edascratch/sriyer-opentitan/scratch/multi_cfgs.hmac.sim.vcs
> INFO: [Deploy] [dvsim]: build:
>  [default,   default]
> INFO: [Deploy] [dvsim]: [000010s] [build]: [..]
> INFO: [Deploy] [dvsim]: [000020s] [build]: [..]
> INFO: [Deploy] [dvsim]: [000030s] [build]: [..]
> INFO: [Deploy] [dvsim]: run:
>  [0.uart_sanity,   0.uart_csr_hw_reset,   0.uart_csr_rw]
> INFO: [Deploy] [dvsim]: [000033s] [build]: [P.]
> INFO: [Deploy] [dvsim]: run:
>  [0.hmac_sanity,   0.hmac_csr_hw_reset,   0.hmac_csr_rw]
> INFO: [Deploy] [dvsim]: [000034s] [build]: [PP]
> INFO: [Deploy] [dvsim]: [000034s] [run]: [...]
> INFO: [Deploy] [dvsim]: [000038s] [run]: [.FF...]
> INFO: [Deploy] [dvsim]: [000039s] [run]: [.FF.PP]
> INFO: [Deploy] [dvsim]: [000040s] [run]: [.FF.PP]
> INFO: [Deploy] [dvsim]: [000042s] [run]: [.FFPPP]
> INFO: [Deploy] [dvsim]: [000050s] [run]: [.FFPPP]
> INFO: [Deploy] [dvsim]: [000060s] [run]: [.FFPPP]
> INFO: [Deploy] [dvsim]: [000064s] [run]: [PFFPPP]
> 
> # UART Regression Results
>   Run on Wednesday January 15 2020 11:56:59PM 
> 
> ## Test Results
> |  Milestone  |        Name        |             Tests |  Results  |
> |:-----------:|:------------------:|------------------:|:---------:|
> |     V1      |       sanity       |       uart_sanity |    1/1    |
> |     V1      |        csr         | uart_csr_hw_reset |    0/1    |
> |             |                    |       uart_csr_rw |    0/1    |
> |     V1      |                    |             TOTAL |    1/3    |
> |     V2      |       parity       |       uart_sanity |    1/1    |
> |     V2      | outstanding_access | uart_csr_hw_reset |    0/1    |
> |             |                    |       uart_csr_rw |    0/1    |
> |     V2      |   partial_access   | uart_csr_hw_reset |    0/1    |
> |             |                    |       uart_csr_rw |    0/1    |
> |     V2      |                    |             TOTAL |    1/5    |
> |             |                    |             TOTAL |    2/8    |
> # HMAC Regression Results
>   Run on Wednesday January 15 2020 11:56:59PM 
> 
> ## Test Results
> |  Milestone  |                   Name                    |             Tests |  Results  |
> |:-----------:|:-----------------------------------------:|------------------:|:---------:|
> |     V1      |                  sanity                   |       hmac_sanity |    1/1    |
> |     V1      |                    csr                    | hmac_csr_hw_reset |    1/1    |
> |             |                                           |       hmac_csr_rw |    1/1    |
> |     V1      |                                           |             TOTAL |    3/3    |
> |     V2      |            outstanding_access             | hmac_csr_hw_reset |    1/1    |
> |             |                                           |       hmac_csr_rw |    1/1    |
> |     V2      |              partial_access               | hmac_csr_hw_reset |    1/1    |
> |             |                                           |       hmac_csr_rw |    1/1    |
> |     V2      |                                           |             TOTAL |    4/4    |
> |     V3      | write_config_and_secret_key_during_msg_wr |       hmac_sanity |    1/1    |
> |     V3      |                                           |             TOTAL |    1/1    |
> |             |                                           |             TOTAL |    8/8    |
> ```
> 
> UART CSR tests are failing and need to be debugged, in case you are not already on it.

UART failure is expected as design change for couple interrupts is still pending.

BTW, the new script made my machine crashed couple times. Not sure if we can improve it to use less cpu/mem, like lower the frequency of checking status, reduce parallel run when it's running in local.

**Comment by sriyerg** [comment]
> > I ran the following command to run sanity regression in HMAC and UART once:
> > ```
> > $ util/dvsim.py hw/dv/data/master_sim_cfgs_list.hjson -i sanity --reseed 1
> > 
> > INFO: [SimCfg] Scratch path for uart: /edascratch/sriyer-opentitan/scratch/multi_cfgs.uart.sim.vcs
> > INFO: [SimCfg] Scratch path for hmac: /edascratch/sriyer-opentitan/scratch/multi_cfgs.hmac.sim.vcs
> > INFO: [Deploy] [dvsim]: build:
> >  [default,   default]
> > INFO: [Deploy] [dvsim]: [000010s] [build]: [..]
> > INFO: [Deploy] [dvsim]: [000020s] [build]: [..]
> > INFO: [Deploy] [dvsim]: [000030s] [build]: [..]
> > INFO: [Deploy] [dvsim]: run:
> >  [0.uart_sanity,   0.uart_csr_hw_reset,   0.uart_csr_rw]
> > INFO: [Deploy] [dvsim]: [000033s] [build]: [P.]
> > INFO: [Deploy] [dvsim]: run:
> >  [0.hmac_sanity,   0.hmac_csr_hw_reset,   0.hmac_csr_rw]
> > INFO: [Deploy] [dvsim]: [000034s] [build]: [PP]
> > INFO: [Deploy] [dvsim]: [000034s] [run]: [...]
> > INFO: [Deploy] [dvsim]: [000038s] [run]: [.FF...]
> > INFO: [Deploy] [dvsim]: [000039s] [run]: [.FF.PP]
> > INFO: [Deploy] [dvsim]: [000040s] [run]: [.FF.PP]
> > INFO: [Deploy] [dvsim]: [000042s] [run]: [.FFPPP]
> > INFO: [Deploy] [dvsim]: [000050s] [run]: [.FFPPP]
> > INFO: [Deploy] [dvsim]: [000060s] [run]: [.FFPPP]
> > INFO: [Deploy] [dvsim]: [000064s] [run]: [PFFPPP]
> > 
> > # UART Regression Results
> >   Run on Wednesday January 15 2020 11:56:59PM 
> > 
> > ## Test Results
> > |  Milestone  |        Name        |             Tests |  Results  |
> > |:-----------:|:------------------:|------------------:|:---------:|
> > |     V1      |       sanity       |       uart_sanity |    1/1    |
> > |     V1      |        csr         | uart_csr_hw_reset |    0/1    |
> > |             |                    |       uart_csr_rw |    0/1    |
> > |     V1      |                    |             TOTAL |    1/3    |
> > |     V2      |       parity       |       uart_sanity |    1/1    |
> > |     V2      | outstanding_access | uart_csr_hw_reset |    0/1    |
> > |             |                    |       uart_csr_rw |    0/1    |
> > |     V2      |   partial_access   | uart_csr_hw_reset |    0/1    |
> > |             |                    |       uart_csr_rw |    0/1    |
> > |     V2      |                    |             TOTAL |    1/5    |
> > |             |                    |             TOTAL |    2/8    |
> > # HMAC Regression Results
> >   Run on Wednesday January 15 2020 11:56:59PM 
> > 
> > ## Test Results
> > |  Milestone  |                   Name                    |             Tests |  Results  |
> > |:-----------:|:-----------------------------------------:|------------------:|:---------:|
> > |     V1      |                  sanity                   |       hmac_sanity |    1/1    |
> > |     V1      |                    csr                    | hmac_csr_hw_reset |    1/1    |
> > |             |                                           |       hmac_csr_rw |    1/1    |
> > |     V1      |                                           |             TOTAL |    3/3    |
> > |     V2      |            outstanding_access             | hmac_csr_hw_reset |    1/1    |
> > |             |                                           |       hmac_csr_rw |    1/1    |
> > |     V2      |              partial_access               | hmac_csr_hw_reset |    1/1    |
> > |             |                                           |       hmac_csr_rw |    1/1    |
> > |     V2      |                                           |             TOTAL |    4/4    |
> > |     V3      | write_config_and_secret_key_during_msg_wr |       hmac_sanity |    1/1    |
> > |     V3      |                                           |             TOTAL |    1/1    |
> > |             |                                           |             TOTAL |    8/8    |
> > ```
> > 
> > 
> > UART CSR tests are failing and need to be debugged, in case you are not already on it.
> 
> UART failure is expected as design change for couple interrupts is still pending.
> 
> BTW, the new script made my machine crashed couple times. Not sure if we can improve it to use less cpu/mem, like lower the frequency of checking status, reduce parallel run when it's running in local.

Thanks for the feedback. I will reduce the default parallel from 32 to 8 so that it is less intensive when run locally. The end goal is to deploy in LSF / GCP which is what I am working on next.

**Pull request merged**
