### PR TITLE
[flash_ctrl] Increase flash rma program burst

### PR DESCRIPTION
**Pull request by tjaychen**
- addresses #15632
- increase the burstiness by 2x. This should be cleaned up to be more parameterizable in the future.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by jdonjdon — APPROVED** [review]
Looks good.
I ran rma tests and have one failure.
But it will pass with ToT.

**Comment by tjaychen** [comment]
hmm? sorry do you mean this change introduced a failure?

**Comment by jdonjdon** [comment]
> hmm? sorry do you mean this change introduced a failure?

No, I guess your tree is not uptodate so rma_err test fail, which is fixed in other PR.
Not relevant to this change.

**Comment by tjaychen** [comment]
ah okay sounds good.

**Pull request merged**
