### PR TITLE
[otp_ctrl] update outdated param

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
my top of tree was dying because of this.  Are you guys seeing the same?

**Comment by cindychip** [comment]
Thanks Tim, I just created a PR for that as well haha. https://github.com/lowRISC/opentitan/pull/4041

**Comment by cindychip** [comment]
sorry for the trouble.. We both modified the same parameters...

**Comment by tjaychen** [comment]
darn. too slow! let me close this one.

**Comment by tjaychen** [comment]
close since this is a duplicate PR.

**Pull request closed without merging**
