### PR TITLE
[site] Minor tweaks for the block diagram

### PR DESCRIPTION
**Pull request by jwnrt**
## Summary

Small PR with some minor tweaks for the site's block diagram:

* Hide the horizontal scrollbar when not needed.
* Centre domain titles vertically.
* Make the block diagram's title larger and Title Case.
* Add a link to the datasheet.

## Screenshot

image

### CODE REVIEW

**Comment by jwnrt** [comment]
@hcallahan-lowrisc does this match what you expected for the title?

**Comment by jwnrt** [comment]
@hcallahan-lowrisc Added that link to the datasheet.

**Review by hcallahan-lowrisc — APPROVED** [review]
Looks great! Thanks @jwnrt 
Having a couple problems with the deployment so it won't go live immediately when merged, but should hopefully fix those today.

**Review by HU90m — APPROVED** [review]
Runs great and looks good on my machine

**Review by marnovandermaas — APPROVED** [review]
Thanks for making these improvements and those who reviewed/tested these changes. Let's wait for CI to finish running before merging.

**Pull request merged**
