### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by tjaychen**

### CODE REVIEW

**Comment by tjaychen** [comment]
@imphil @mcy 
I accidentally merged #932 with riscv_testing reliant on execute_verilator_tests.

As I was testing to reverse this change however, I noticed that when both these jobs attempt to run, I seem to encounter random failures (which is consistent with something I've observed before).  Do you guys know how isolated these CI jobs actually are? It seems like one is affecting the other, and if I specifically serialize them, things seem to be okay.  

I know we can't run multiple verilator runs at the same time, but I thought the jobs would be pretty sandboxed, since we are installing dependencies separately for each?

**Comment by imphil** [comment]
The level of isolation depends on the runner.
- The "Default" runner use a weaker isolation in favor of setup speed (systemd-nspawn, effectively a light-weight container).  These machines are lowRISC-hosted.
- The cloud runners provided by Azure use separate VMs from what I understand, so they should provide rather strong isolation.

For this bug, the most likely fix is to switch to the Azure Cloud Pool, since there is nothing to be gained from using the Default pool.

```patch
diff --git a/azure-pipelines.yml b/azure-pipelines.yml
index adf17c7..9fd0b26 100644
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -209,7 +209,8 @@ jobs:
 
 - job: "execute_verilated_tests"
   displayName: "Execute tests on the Verilated system"
-  pool: "Default"
+  pool:
+    vmImage: "ubuntu-16.04"
   dependsOn:
     - top_earlgrey_verilator
     - sw_build
@@ -227,7 +228,8 @@ jobs:
 
 - job: "riscv_compliance_tests"
   displayName: "Execute RISC-V compliance tests"
-  pool: "Default"
+  pool:
+    vmImage: "ubuntu-16.04"
   dependsOn:
     - top_earlgrey_verilator
     - execute_verilated_tests
```

**Comment by asb** [comment]
Switching to using cloud-hosted runners may be a reasonable thing to do for these tests anyway. But I'm concerned about doing so without understanding the issue, as it's not unlikely we'll run into it again in the future outside of the CI environment. Do you have a hypothesis on what the problem is with these failures?

**Comment by tjaychen** [comment]
my current assumption is basically that we cannot run multiple verilator
instances in parallel.  I know this is something I've run into before, but
I haven't tested lately to see if that is still a problem.
So when two verilated jobs are invoked to run at the same time, one of them
will die.

**Comment by imphil** [comment]
@asb Running multiple Verilator instances in parallel requires isolation of /dev/pts* devices and TCP ports. Apparently systemd-nspawn isn't capable/configured to provide this isolation.

**Comment by asb** [comment]
I've created #1183 to track that wider issue.

**Comment by imphil** [comment]
@tjaychen can you add the proposed patch to your set here, or let me know if not? We need to get this fixed to unblock others who get CI failures due to that. (e.g. #1182)

**Comment by asb** [comment]
Temporarily limited number of runners on the same machine to avoid this problem. Not a good fix, but given I'm at a conference the best one to do right now.

**Comment by tjaychen** [comment]
O sorry I should have clarified. People should not be running into issues
right now. I've made the two jobs sequential so they won't conflict. This
PR was going to restore the parallel operation, and that's when issues
showed up.

**Comment by imphil** [comment]
Making these jobs parallel only reduces the likelyhood. It can still have two separate CI jobs running next to each other running into the same problem. So let's please get this one merged quickly.

**Comment by tjaychen** [comment]
O interesting, I did not think about different CI jobs. Sounds good.

**Comment by tjaychen** [comment]
Actually let's disable the compliance test for now. Mcy has another issue
related to the meson / make conversion that we need to fix anyways.

**Pull request closed without merging**
