### PR TITLE
[verible/style] This corrects several style linter warnings/errors

### PR DESCRIPTION
**Pull request by msfschaffner**
Another happy Friday cleanup coming... 

This corrects several Verible style linter warnings/errors throughout the whole codebase.

Not all warnings have been fixed yet, though, due to the following issues:
- First, there are several trivial warnings (like "exceeds line size") in generated files, which are a bit difficult to fix in the sources since the size is often dependent on module/variable names that are generated. 
- Second, we do not yet have a good waiver strategy in place yet which would allow us to precisely waive such warnings and errors using regexp matching. Such a solution could be added as a post processing step, if needed. 
- Finally, there are some style guide discrepancies between the lowRISC style and the style that is implemented by Verible. Some of them might be resolved in the future by aligning styles, but eventually it would also be good to have more controllability of the rules via a policy configuration.

@weicaiyang could you do me a favor and pipe this through a full DV regression?

@hzeller @fangism for visibility

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by fangism** [comment]
For those interested in parameterizable lint rules, https://github.com/google/verible/issues/133

**Comment by eunchan** [comment]
Sorry for my ignorance. Is `parameter` must in the package file? `localparam` isn't allowed syntactically?

**Comment by msfschaffner** [comment]
@sjgitty concerning the declaration of unpacked arrays, we kind of have it implicitly here in the example that is provided:
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#array-dimensions-in-declarations

**Comment by msfschaffner** [comment]
@eunchan No, localparam is allowed. It's just that the style linter currently requires localparams to be styled with UpperCamelCase. For parameters, both ALL_CAPS and UpperCamelCase is allowed. Further, in our style guide, we recommend to make everything a parameter inside the package:
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#constants

Hence I aligned everything to parameter in the packages.

**Comment by msfschaffner** [comment]
@fangism thanks for the hint, that feature will indeed be much appreciated!

**Comment by msfschaffner** [comment]
@imphil I had split out the makefile update to a different PR where I forgot to add you to the reviewers: https://github.com/lowRISC/opentitan/pull/1371

**Comment by msfschaffner** [comment]
Thanks @weicaiyang, pulling this one in.

**Pull request merged**
