### PR TITLE
[clkmgr] Allow software to control clock stepdown

### LINKED ISSUE #8027: [clkmgr change proposal] Update external clock selection logic
For manufacturing flexibility, we need to add more flexibility on how to select external clocks. 
Right now the step down and selection is driven largely automatically by hardware, but we would like to be able to control step down through software as well. 

See this [link](https://docs.google.com/presentation/d/1N-PBsD5dkEnHZCG5p0DEsTy6UcGgfqGZXzQSixDBWmM/edit?usp=sharing) (limited visibility and not open to public) for more details.

### PR DESCRIPTION
**Pull request by tjaychen**
- Fixes #8027

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
I've merged @matutem PR into a single commit, it looks good!

**Review by cindychip — APPROVED** [review]
LGTM

**Review by matutem — COMMENTED** [review]
Looks good, but I have a question: this means when the lc requests bypass the clock is always stepped down. Then what is the use case that needs to use the new step_down field? Or more generally, what is the use model for the software controlled external clock/step down? Is it described in the spec somewhere?

**Comment by tjaychen** [comment]
> Looks good, but I have a question: this means when the lc requests bypass the clock is always stepped down. Then what is the use case that needs to use the new step_down field? Or more generally, what is the use model for the software controlled external clock/step down? Is it described in the spec somewhere?

@matutem and i discussed this offline, since not all of the info can be made public.

**Comment by tjaychen** [comment]
i'm merging this PR now, thanks to @matutem for providing the necessary DV updates.

**Pull request merged**
