### PR TITLE
[otbn] Complete model

### PR DESCRIPTION
**Pull request by wallento**
Some fixes, cleanups and demo reworking

### CODE REVIEW

**Comment by rswarbrick** [comment]
I can review this if it would help, but I don't really know whether it makes sense. Eventually this needs to end up in master, which will need proper commit messages, and probably half of these bug-fix commits should be merged into the (still unmerged) patches that add the functionality.

Can we try to squash things together and start merging stuff into master?

**Comment by wallento** [comment]
Yeah, it will be rebased! I am still adding things right now, I can rebase when done, but want to avoid force pushing every couple of hours, so if someone looks at it, can check it. Would you prefer smaller PR and open a new one for the next couple of fixes?

**Comment by imphil** [comment]
@rswarbrick It makes sense to review the individual changes even if they go into otbn-dev; we don't want to re-review the whole thing if it goes to master, but mostly rubber-stamp it.

**Comment by wallento** [comment]
I think we can merge it now

**Comment by imphil** [comment]
@wallento can you fix the things CI wants you to fix? Seems the python-requirements.txt needs an update.

@rswarbrick can you approve if you're reasonably happy with it? We can then take all of it from otbn-dev and move it to master next week.

**Comment by wallento** [comment]
yep, fixed and force pushed

**Comment by imphil** [comment]
CI is failing for the license checker and clang-format. Can you look at those problems and fix them @wallento? CI output is at https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=18060&view=results.

**Comment by wallento** [comment]
amended and pushed as separate commit. Shall I rebase and create one commit?

**Comment by imphil** [comment]
Please fold the fixes into the commit where the main change lives and remove the separate fixup commit. Thanks!

**Pull request merged**
