### PR TITLE
[AST] USB Clock Calibrate Test Supports

### PR DESCRIPTION
**Pull request by Jacob-Levy**
USB Clock Calibrate Test Supports

USB_Drift_Calibration

@arnonsha @zi-v @sha-ron 
Signed-off-by: Jacob Levy <jacob.levy@nuvoton.com>

### CODE REVIEW

**Comment by Jacob-Levy** [comment]
@tjaychen The new PR is ready for your test and regardless it can be approve & merged.

**Comment by tjaychen** [comment]
@Jacob-Levy thanks, i will pull this down and give it a try.

**Comment by Jacob-Levy** [comment]
@msfschaffner I looked at the KOKORO lint errors and all can be waived.

**Comment by tjaychen** [comment]
> @msfschaffner I looked at the KOKORO lint errors and all can be waived.

@Jacob-Levy please have a look at the errors and the [existing ast waiver file](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/ip/ast/lint/ast.waiver).  It should be pretty self explanatory how to add more. 

Once you do so, you can push back to the PR, the kokoro checks run very quickly and should be able to give you feedback.

**Comment by Jacob-Levy** [comment]
@tjaychen @msfschaffner Added the Lint waivers and pushed the PR.
KOKORO passes now :) Unfortunatly unrelated  "OBTN Smoke Test" fails :(

Will try to rebase and push again later...

**Comment by Jacob-Levy** [comment]
Done! :)

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
