### PR TITLE
[kmac] Extend SCA countermeasures

### PR DESCRIPTION
**Pull request by vogelpi**
This PR contains two additional countermeasures originally developed, implemented and tested (DV, SCA experiments on FPGA) some time ago. The work has already been reviewed and approved previously by @cdgori and @cindychip (see PR linked below). It has been concluded that we want them in ES and now we also got the okay to do so.

### CODE REVIEW

**Comment by vogelpi** [comment]
FYI @m-temp @y-srini, this is what we've discussed earlier today.

**Review by moidx — APPROVED** [review]

**Review by cindychip — APPROVED** [review]

**Review by cdgori — APPROVED** [review]
LGTM!  I compared to the 2 "big" commits on the embargoed side and all looks to be the same.  The rest appears to be fishing through the ports hierarchically, more or less.

**Review by johannheyszl — APPROVED** [review]
thanks pirmin

**Comment by vogelpi** [comment]
Thanks everybody for your reviews, and for pushing for this! I am happy we can integrate these CMs for ES.

**Pull request merged**
