### PR TITLE
Fix CI C/C++ lint

### PR DESCRIPTION
**Pull request by GregAC**
Includes a separate commit to check functionality of the lint check, will resubmit when I've confirmed things are working as intended.

### CODE REVIEW

**Comment by GregAC** [comment]
Ok test looks good, when I added a C++ file that violated style guidelines I got a failure, altering it to meet style guidelines allowed the lint check to pass. I've now removed that commit.

**Comment by imphil** [comment]
Can you look through the azure-pipelines.yml file, the same error seems to be present a couple more times.

**Comment by GregAC** [comment]
I only saw another instance of this on the include guard check which I've now fixed also did you see any more?

**Comment by imphil** [comment]
The relevant CI passed, let's merge to reduce the load on the backlogged runner.

**Pull request merged**
