### PR TITLE
[site] Re-add OpenTitan themed header to mdbook

### PR DESCRIPTION
**Pull request by jwnrt**
This PR reintroduces the changes from https://github.com/lowRISC/opentitan/pull/17457 with the refactor of the `build-site.sh` script removed. I will submit that separately.

### CODE REVIEW

**Review by HU90m — APPROVED** [review]
Content looks good to me. Using `pushd` for the mdbooks was on my todo list, so pleased to see that change.

I can't test it though, will have to defer to @hcallahan-lowrisc for that.

**Comment by hcallahan-lowrisc** [comment]
Can we please remove the `build-docs.sh` refactor from this PR, other than the changes needed for the theme? As discussed offline I would like to talk about that a bit more first.
I would also change the name of this PR back to the original name.
Rest looks good running locally!

**Comment by jwnrt** [comment]
> Can we please remove the `build-docs.sh` refactor from this PR, other than the changes needed for the theme? As discussed offline I would like to talk about that a bit more first.

I still feel quite strongly about the refactor, would you mind leaving comments on it in a review if you have time? If they're show-stopping problems I can take the commit out

> I would also change the name of this PR back to the original name. Rest looks good running locally!

Oops, missed that, done!

**Comment by jwnrt** [comment]
Rebased and then removed the refactor commit. Will submit that in another PR.

**Comment by jwnrt** [comment]
Pushed to fix something I broke when removing the refactor.

**Review by hcallahan-lowrisc — COMMENTED** [review]
Tested locally and looks great. Let's get this merged (again)!

**Review by HU90m — APPROVED** [review]

**Review by andreaskurth — APPROVED** [review]
Approving as this is a fixed revision of the already approved PR #17457

Thanks and let's try again :crossed_fingers:

**Pull request merged**
