### PR TITLE
[lc_ctrl/otp_ctrl] Check whether a token is valid before performing a transition

### PR DESCRIPTION
**Pull request by msfschaffner**
This adds an additional check in the life cycle controller that checks whether the tokens have actually been provisioned and may be used. If a token is not valid, the corresponding state transitions guarded by that token will not be allowed.

This also slightly reworks how the ID state of the device is decoded.
I.e., the ID state is not something that is directly provisioned into OTP, but rather it is a condition that is inferred from the provisioning status of the secrets (creator root key).

### CODE REVIEW

**Comment by sriyerg** [comment]
@cindychip, please pull this PR locally and run full otp ctrl nightly to assess V2 readiness. If our coverage drops below V2 level, we will need to revert the D/V stage and do a version bump. @msfschaffner, i suppose you need to check the same for D2 readiness. 

Also, please assess the amount of work to account for this change and lets have the smartsheet updated to reflect that. 

@msfschaffner, are there any more changes anticipated in otp ctrl? We really ought to start freezing blocks so that we can make progress on other things in our (huge) list of pending items. Though i do understand it may be hard to foresee it. 

@dsandrs, do you agree?

**Comment by cindychip** [comment]
Thanks Sri for tagging me. I do need to add more checkings for this new `valid` output ports.
As for DV impact: I ran the DV nightly with this new change. The V1 and V2 tests are all passing. Only failing test is `otp_ctrl_tl_intg_err`.

Not much coverage impact for V2 either:
|  SCORE  |  LINE   |  COND   |  TOGGLE  |   FSM    |  BRANCH  |  ASSERT  |  GROUP  |
|:-------:|:-------:|:-------:|:--------:|:--------:|:--------:|:--------:|:-------:|
| 96.11 % | 99.24 % | 91.16 % | 97.73 %  | 100.00 % | 95.40 %  | 92.81 %  | 96.44 % |

**Comment by msfschaffner** [comment]
Sorry I should have communicated this better.

This is fixes a security bug. 

For context: 
The life cycle controller did not check the provisioning status of `SECRET2` upon life cycle transitions from `PROD*/DEV` into `RMA`, which opens up an undesirable loop hole. In particular:
- The HW currently does not  It is not enforced that `SECRET2` becomes unreadable by SW when moving through `PROD*/DEV` into `RMA`.
- Further, a life cycle transition to `RMA` can be initiated with an all-zero token in certain cases when the `SECRET2` partition is not locked right away, e.g.:
  - when only the root key is provisioned, but not the `RMA_UNLOCK_TOKEN` token.
  - when the `RMA_UNLOCK_TOKEN` is provisioned, but the chip is has not yet been reset.

There are provisioning flow workarounds for this, but it would be good to enforce this check directly in hardware. The `SECRET2` partition holds the root key which should not remain readable by SW when transitioning into `RMA`. Also, there should not exist another way to move from `PROD*/DEV` into `RMA` without providing a valid, non-zero `RMA` token.


Although the change does not look trivial in the diff, it is actually rather localized.
I.e., this change updates the OTP->LC_CTRL connection such that the (readily available) "digest locked status" is output alongside each life cycle token as a redundantly encoded "token valid" signal. 

This "token valid" signal is then used as an additional condition when the token comparison is made in the life cycle controller. If a token is not valid / has not been provisioned, this check would fail and abort the life cycle transition. 

That way it becomes impossible to move from `PROD*/DEV` -> `RMA` without provisioning and locking the `SECRET2` partition.


This change does not really add a new feature, but rather fixes existing mechanisms. 
As @cindychip confirmed, this change does not impact coverage adversely and can be tested with existing test sequences.

---------------------------------------------------------------------------
There are currently three other pending changes to OTP in addition to this PR:

1. Bus integrity alert hookup https://github.com/lowRISC/opentitan/pull/7151
2. Width alignment of OTBN scrambling nonce https://github.com/lowRISC/opentitan/pull/7144
3. Increase of background check timer reseed period https://github.com/lowRISC/opentitan/pull/7152

I'll comment more on the corresponding PRs, but 1. is a known enhancement that we have to add to all IPs, and 2./3. are minor adjustments that should not have an adverse impact on DV (these are not new features).

If nothing changes in the provisioning and production test flows, I do not expect additional changes at the moment.

**Review by cindychip — COMMENTED** [review]
LGTM from DV perspective.

**Review by cindychip — APPROVED** [review]

**Pull request merged**
