### PR TITLE
[spi_device] Connect SRAM arbiter grant signal

### PR DESCRIPTION
**Pull request by eunchan**
SW access port (TL-UL) can handle the grant signal. Other requesters
from the HW can't handle. The assertion catches the case but the better
approach is to lower the SW access priority in prim_sram_arbiter and
also block the requeset when SPI transaction is active.

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
LGTM

**Comment by tjaychen** [comment]
@eunchan i have a dumb question, maybe i just forgot how this works.
So this PR adds the software grant so that if software loses the grant it will wait.
But what about the other direction? Is it not possible that software / hardware come at the same time but software wins the grant, will the hardware side behave correctly if as you say it cannot handle the grant?

**Comment by tjaychen** [comment]
> @eunchan i have a dumb question, maybe i just forgot how this works. So this PR adds the software grant so that if software loses the grant it will wait. But what about the other direction? Is it not possible that software / hardware come at the same time but software wins the grant, will the hardware side behave correctly if as you say it cannot handle the grant?

o wait, you say you will lower software priority! sorry that must be a different PR.

**Comment by eunchan** [comment]
I've created an issue https://github.com/lowRISC/opentitan/issues/10065 . Looks like I need to connect the grant to the HW module (upload module).

**Comment by eunchan** [comment]
@tjaychen I revised this PR for SW to have lower priority. Could you please check the logic if it looks good?

**Pull request merged**
