### PR TITLE
[keymgr] Remove hmac sideload

### PR DESCRIPTION
**Pull request by tjaychen**
Remove hmac sideload as a feature.

### CODE REVIEW

**Review by eunchan — APPROVED** [review]

**Review by weicaiyang — APPROVED** [review]
can you also remove the `hmac` from the design spec? perhaps replace it with Otbn
otherwise, LGTM, thanks

**Comment by tjaychen** [comment]
ah, let me do that.

**Comment by tjaychen** [comment]
> can you also remove the `hmac` from the design spec? perhaps replace it with Otbn
> otherwise, LGTM, thanks

fixed!

**Comment by tjaychen** [comment]
could you guys give the parent PR (#7593) a review also?

**Pull request merged**
