### PR TITLE
[dv, edn] Add the test chip_sw_edn_entropy_reqs_jitter

### LINKED ISSUE #14784: [chip-test] chip_sw_edn_entropy_reqs jitter extension
### Test point name

[chip_sw_edn_entropy_reqs](https://github.com/lowRISC/opentitan/blob/d91fcd3dfe38cb80ab94778f1418ffb1e85bd26a/hw/top_earlgrey/data/chip_testplan.hjson#L2068)

The test exists, but a jitter variant of this test should be added to the `chip_sw_clkmgr_jitter` testpoint.

### Host side component

None Required

### OpenTitanTool infrastructure implemented

_No response_

### Contact person

@tjaychen

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

### PR DESCRIPTION
**Pull request by engdoreis**
This PR fixes #14784

### CODE REVIEW

**Review by tjaychen — APPROVED** [review]
thanks for adding. 
We may need to tweak the timeout for this later, but let's  see how nightly responds.

**Comment by engdoreis** [comment]
> thanks for adding. We may need to tweak the timeout for this later, but let's see how nightly responds.

This is the log of my local run:
```
          [   legend    ]: [Q: queued, D: dispatched, P: passed, F: failed, K: killed, T: total]                                     
00:02:54  [    build    ]: [Q: 0, D: 0, P: 1, F: 0, K: 0, T: 1] 100%                                                                 
00:30:00  [     run     ]: [Q: 0, D: 0, P: 3, F: 0, K: 0, T: 3] 100%    
```
Should I increase the timeout to 30ms?

**Comment by tjaychen** [comment]
no this is good i think. Let's see if there's any fallout for nightly. 
Most of the entropy distribution is using the jittery clock, so in theory turning on jitter could have a big impact on the run-time. But this test may have been really generous alread.

**Review by jdonjdon — APPROVED** [review]
LGTM

**Pull request merged**
