### PR TITLE
[aes, rtl] Update S-Box data/mask in sync with PRD

### PR DESCRIPTION
**Pull request by vogelpi**
Previously, it was possible that DOM S-Box instances would get new data and mask inputs without receiving new PRD / updating the internally buffered PRD which is not ideal from an SCA perspective. Even if the S-Box isn't evaluated this may create SCA leakage in the first multiplier stage.

This commit modifies the design as follows:
- A new input is added to the DOM S-Box to directly control the internal PRD buffering. Upon writing state / key registers also the buffering is now updated.
- Inside the key expand module, some signals are added to inhibit or enforce PRD buffer updates irrespective of key register updates because some operation modes require this.

With these changes, the non-linear logic inside the S-Boxes is always presented with both fresh data/masks and PRD except for the following special cases:
- Key expand module: Switching betweeen FWD and INV mode of operation, e.g. for decryption key generation and upon switching configuration (rare).
- Data path: The very first cycle of the initial round for encryptions and decryptions. This is not critical as in the initial round the masked plaintext/ciphertext (not secret) is presented to the S-Boxes but the S-Boxes aren't evaluated.

### CODE REVIEW

**Comment by vogelpi** [comment]
Note/background information: I have done many, many FPGA experiments with different bitstreams and SW binaries to test different hypotheses re where the newly observed leakage could come from. For a long time, these experiments haven't been conclusive. The patch in this PR is one of the things I tried out and as far as I can imagine it fixes the only remaining source of potential 1st-order leakage inherent to the RTL and that's why I believe we should get it in for M2.5. 

Regarding the overall status of my investigations: After doing many experiments modifying parts of the AES RTL, I've decided to take a different approach and try to reduce FPGA utilization to reduce P&R pressure. After a first couple of experiments in this direction it seems to me that the RTL design (with this patch) is indeed fine and that tool optimizations and P&R were responsible for introducing the leakage.

I will try to wrap up these experiments on THU but before that wanted people to give a chance to review this.

**Comment by vogelpi** [comment]
This is related to #17883.

**Comment by johannheyszl** [comment]
thank you this makes sense to me

**Review by msfschaffner — COMMENTED** [review]
Thanks @vogelpi. 

Are we introducing any registers as part of this change?
I don't think I've seen any added flops in the diff, but wanted to confirm.

**Comment by vogelpi** [comment]
> Thanks @vogelpi.
> 
> Are we introducing any registers as part of this change? I don't think I've seen any added flops in the diff, but wanted to confirm.

That's correct: no additional FFs. The are stays pretty much constant with this change (tested with Yosys + nangate45).

**Review by msfschaffner — APPROVED** [review]
discussed with @vogelpi offline - this patch should be safe to absorb at this point.
it has been validated with several SCA measurements, and there is no fallout in block-DV so far.

**Review by moidx — APPROVED** [review]

**Pull request merged**
