### PR TITLE
[uart] Wire up integrity alert

### PR DESCRIPTION
**Pull request by msfschaffner**
Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by imphil** [comment]
@msfschaffner did you intend to have this PR with UART and KMAC together? (In that case it might make sense to update the PR description.)

**Comment by imphil** [comment]
(LGTM for me, leaving the review to Eunchan, since he's most familiar with the RTL here.)

**Review by weicaiyang — COMMENTED** [review]
DV part LGTM, thanks

**Comment by msfschaffner** [comment]
Thanks for giving a look!

No, I was just going through many other IPs, and I accidentally left the `kmac` commit on this branch. 
It will be rebased out.

**Review by weicaiyang — APPROVED** [review]

**Pull request merged**
