### PR TITLE
[otp_ctrl] Do not deassert init done signals, once initialized

### PR DESCRIPTION
**Pull request by msfschaffner**
Fixes https://github.com/lowRISC/opentitan/issues/6937

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by cindychip** [comment]
Hey Michael, want to check the status of this PR - we are holding this PR until further discussion or are we planning to check this in?

**Comment by msfschaffner** [comment]
Hey @cindychip, let's wait with any further changes until we have agreement on whether we should simplify escalation behavior or not.

Sorry, this week may be a bit slower due to the consultancy reviews.

**Comment by cindychip** [comment]
SG, just want to make sure I did not miss this review :)

**Comment by msfschaffner** [comment]
Hey @cindychip, this now becomes obsolete with https://github.com/lowRISC/opentitan/pull/7014

**Pull request closed without merging**
