### PR TITLE
[flash] Minor refactoring of prim_flash

### PR DESCRIPTION
**Pull request by tjaychen**
Separate out some of the arbitration logic from prim_flash, as that
can be open sourced, while contents within prim_flash cannot.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by sjgitty** [comment]
@tjaychen I think this makes sense. Do you mind refreshing the file
`https://docs.opentitan.org/hw/ip/flash_ctrl/doc/flash_abstraction.svg`
to match to make sure my picture is correct?

**Comment by tjaychen** [comment]
o good catch, that should be updated. Thanks.

**Comment by eunchan** [comment]
LGTM

**Comment by tjaychen** [comment]
> @tjaychen I think this makes sense. Do you mind refreshing the file
> `https://docs.opentitan.org/hw/ip/flash_ctrl/doc/flash_abstraction.svg`
> to match to make sure my picture is correct?

hmmm... would you be okay if i updated this diagram a bit later? I just realized the diagrams i have right now are much more detail than what is available in the design (talks about scrambling / ECC), or much too general (only emphasizes the open source / vendor boundary).

Maybe what makes sense is that I add more text to explain that and add the open source / vendor boundary diagram.

**Comment by tjaychen** [comment]
> > @tjaychen I think this makes sense. Do you mind refreshing the file
> > `https://docs.opentitan.org/hw/ip/flash_ctrl/doc/flash_abstraction.svg`
> > to match to make sure my picture is correct?
> 
> hmmm... would you be okay if i updated this diagram a bit later? I just realized the diagrams i have right now are much more detail than what is available in the design (talks about scrambling / ECC), or much too general (only emphasizes the open source / vendor boundary).
> 
> Maybe what makes sense is that I add more text to explain that and add the open source / vendor boundary diagram.

I've updated the language in the spec to better describe the open vs closed boundaries. This document needs a lot of re-write...and might deserve an entire PR all on its own to describe the division best. Let me know if this looks okay for now.  The other svg you mentioned I will replace, but probably at the same time as the doc re-write to give the block diagram more life.

**Pull request merged**
