### PR TITLE
[usbdev] in_status_stage

### PR DESCRIPTION
**Pull request by Nadia-Hanif**
This draft PR contains in status stage sequence

### CODE REVIEW

**Comment by Nadia-Hanif** [comment]
@jdonjdon why CI checks are failing?

**Comment by rswarbrick** [comment]
Hmm, something seems to have gone wrong with a top-level test, and the problem is definitely not caused by your code! I'm rebasing onto the current head of `master` and force-pushing now.

**Comment by Nadia-Hanif** [comment]
@alees24 kindly review this draft PR. Thanks

**Comment by rswarbrick** [comment]
Thanks for pushing this as a PR with just one sequence. Before I understood how everything gets split up, I actually reviewed this sequence in #21326. Could you work through the comments that I left there and push the fixes to this PR? It's quite a short list: I'm hoping this is reasonably near being possible to merge.

**Pull request closed without merging**
