### PR TITLE
[otp_ctrl] Step up parity to ECC checks in buffer regs

### PR DESCRIPTION
**Pull request by msfschaffner**
This steps up byte parity to ECC for 64bit blocks in the OTP buffer registers for better glitch detection.

This is just a suggestion, not sure we should do it, as it does add to the complexity (even when error correction logic is not instantiated).

On an FPGA synthesis, LUT complexity increases by ~2.5k LUTs from 54'549 (parity) to 56'976 (ecc), which corresponds to a utilization increase from 40.5 % to 42.3 %.

Only look at the last commit - the others are from #3891. Will rebase once that one has been merged.

### CODE REVIEW

**Comment by tjaychen** [comment]
Thanks @msfschaffner ! can we discuss this a bit next week in the post-training sync-up?
I think this is something really worth talking about, because I feel like in general we need to codify ECC vs parity better somewhere in the project.

On that note, do you have any rough idea what happens when we get > 2 bit error from the perspective of the ECC? It's not as clear cut as parity to me.

**Comment by msfschaffner** [comment]
Yes, that's a good idea. Maybe this is something that should be articulated in the design guidelines?

I think it depends a bit where you land in the code space, and what the closest codeword is after the glitch.
However, since we are not using error correction here, the glitched word would have to land exactly on a valid code word - otherwise we would still detect the error.

The current encoding uses the minimum # of ECC bits for 64bit, which is 8bits. But I imagine you could add more ECC bits in order to make the code space more sparse, thereby reducing the probability that a glitch will result in a valid code word.

**Comment by tjaychen** [comment]
so the reason i ask is if we used parity, is it true we basically have a
50/50 chance of detecting a change? (just even or odd?)
to me whether ECC is worth it here boils down to whether the detection % is
higher or lower.

What do you think?

And yes, i think this should be articulated in the design guidelines.

**Comment by msfschaffner** [comment]
I believe it depends a bit how you model a glitch and how the parity bits are distributed.
in this case we would have 8 byte parity bits vs 8 ECC bits. 

assume for instance that all bits are uniformly affected by a glitch and may either fall into 0 or 1 state with equal probability. that means that each parity byte group has a 50% chance of being correct after a glitch, and if all byte groups are independent, the probability that the whole 64bit word has correct parity after a glitch would be 0.5^8.

now for ECC, we can look at this as follows  (if I am not mistaken): we have a 64bit word, to which we add 8bits. that makes the space of valid codewords sparse. i.e., only one in every 2^8 codewords is actually valid, which means that we get the same detection probability of 1/2^8 as above with parity.

however, this is only the case where the word is uniformly affected by a glitch. I believe that byte parity performs considerably worse when only a few byte groups are affected in this example. but to get a quantitative comparison I think we would have to run a few simulations.

@cdgori, what is your take on ECC vs parity?

**Comment by tjaychen** [comment]
wait, so are you saying that when when we land as one of the invalid code
words, it would always be detected..?
My understanding of ECC theory is a bit weak, but i thought the idea is
that you have multi-bit errors, it would try to correct it to the "closest"
code word since it would not be able to know for sure it's an error.

I could be wrong here though, would be great if someone corrected me.

**Comment by msfschaffner** [comment]
so if I understand this correctly, ECC behaves as follows:

while it is true that ECC will try to correct towards the closest code word, ECC will still flag if a correctable or uncorrectable error has occurred.

you can picture this as follows: for this 64bit+8bit example, we have only 2^64 unique 72bit code words. each of those code words has a "halo" around it containing the 72 words with a Hamming Distance (HD) of 1 with respect to the code word. all those 72 code words within this HD1 halo can be corrected towards the unique code word at the center of the halo. these are what we call "correctable" ECC errors. uncorrectable ECC errors have a HD of 2 and cannot be corrected towards one unique code word without ambiguity, since HD-2 halos of different code words may overlap. If the HD is greater than 2, we may land in the HD-1 halo of another code word.

so for example, if we glitched a valid code word A into the HD1-halo of a valid code word B via a multibit error, ECC would correct towards B, and report that this was a correctable error. this produces the ambiguity you mentioned in cases of multibit errors, since we have no way to tell after correction whether A == B. the only thing we now is that a correctable error has occurred, and that the corrected word is B.

note however that this ambiguity does not really matter here, since we do not rely on error correction in this particular case. we only look at the correctable / uncorrectable error signals. that means that even in the case above where the error can be corrected towards B, we would still be able to know that an error has occurred, even if A != B. only in case the glitch produced a code word that matched B (or any other valid code word for that matter) *exactly*, we would not be able to detect an error.

does that make sense?

**Comment by tjaychen** [comment]
yes that makes sense.  So then based on what you're saying... assuming we only affect a few byte groups, or worse, just 1, the probability of parity landing correctly is much higher, since it's 50 / 50  in that byte.  Whereas using ECC, since we're taking the entire 64b as a group, it's much more likely we'll end up as an invalid code word? 

Is that the right interpretation?

**Comment by msfschaffner** [comment]
yes that is basically what this boils down to, I think.

**Comment by tjaychen** [comment]
sounds good, then if it's that the case, it seems like in most cases, we should actually use ECC over parity then right? 
As long as the target has more than a byte for example, feels like the detecting rate using ECC would always be better.

**Comment by msfschaffner** [comment]
that is my take, yes. would be good to hear what @cdgori's experience with ECC vs parity is. 

we should note however that this comes at a cost of increased complexity (even if error correction is not used on the data).

**Comment by tjaychen** [comment]
> that is my take, yes. would be good to hear what @cdgori's experience with ECC vs parity is.
> 
> we should note however that this comes at a cost of increased complexity (even if error correction is not used on the data).

i think that's fine, especially for critical data.  The cost is really just more XOR's right?
I don't think that would be too harsh.

**Comment by msfschaffner** [comment]
indeed, it's just more xor's, plus potentially some muxing in case we have subword writes into an ECC word (e.g. 16bit write into a 64bit block), as in such a case we would need to read-modify write. 

this is currently not the case, but I might change that in order to streamline the OTP open-source interface (i.e., remove the `size_i` input of `prim_otp` and make the interface width just equal to the native OTP width).

**Comment by msfschaffner** [comment]
Rebased on top of master.

**Comment by tjaychen** [comment]
wouldn't we have to support that for OTP buffered components that are much
smaller? For example 3 / 4 bit values here and there?

**Comment by msfschaffner** [comment]
the partition sizes are aligned with 64bit due to the cipher and digest calculation mechanisms. hence, the buffer register file is currently always a multiple of 64bit words, and initial readout works on 64bit blocks.

**Comment by tjaychen** [comment]
so does that mean if we have a smaller use case for specific configuration,
they'll be compacted together..? or they'll just always take up 64b chunks?

**Comment by msfschaffner** [comment]
so the case you describe only becomes relevant in the `HW_CFG` use case since all the secrets are nicely aligned to 64bit, right? I thought it would be best to just compact all the `HW_CFG` bits since they do not have to be consumed by SW. so if we have three fields with 7bit, 3bit and 16bit each, we would only allocate one 64bit block out of which 26bits are utilized. does that make sense?

**Comment by tjaychen** [comment]
yeah that makes sense. As long as they can be distinguished at an interface
level, I think compacting them shouldn't be a problem.

**Comment by msfschaffner** [comment]
ok good. should we proceed and merge this in then?

**Comment by tjaychen** [comment]
could we hold off for just one more day? (if that's okay with you).
I think we should at least walk through with others tomorrow and maybe
formalize this and make a proposal to the design guidance.

**Comment by msfschaffner** [comment]
ah yeah sure, forgot that we had that meeting scheduled for tomorrow.

**Review by cindychip — APPROVED** [review]

**Comment by cindychip** [comment]
LGTM on the verification side, but probably wait until your meeting to merge.

**Comment by msfschaffner** [comment]
Ok, we've decided that we are in favor of ECC over parity in the context of these buffer registers, for the reasons discussed in the thread above.

**Comment by cdgori** [comment]
Sorry for not weighing in here on the PR until now.  We did discuss this in a meeting yesterday (in the context of rapid alert responses), and I agree/agreed with your reasoning above about ECC over parity for these structures.  

In general, summarizing from that meeting to the best of my memory:

-I think parity is too weak for all but the very smallest of structures (e.g. maybe a few-bit state-machine vector where ECC is kind of non-sensical to apply)
-Parity on larger widths has (potentially) the byte-lane issues that you identified above
-ECC has some better "consideration" (really, diffusion) of the full-width of the data item in generating its check code so it is better in that regard
-But, ECC is still not very diffuse compared to say even a (weak) hash function
-We need to discuss our policy around handling of correctable errors, due to the issues of HD>2 faults potentially masquerading as correctable errors
-The incremental area overhead of ECC vs parity was expected to be modest (seems to match up with your FPGA synthesis findings at the top of this PR), and the benefit of ECC over parity was tangible
-There was some discussion about implementation details if we do allow correctable errors to proceed (we were discussing if 1 or 2 extra pipeline stages/cycles were needed to detect errors and/or apply the correction, though it sounded like for our clock rate, process and typical data/ECC-widths it might be possible to merge correction into the detection pipeline stage, or even into the SRAM read cycle itself - but in any case this pipeline must be fixed and always allocate the same number of cycles for corrected and non-corrected read data).  This is (potentially) exacerbated if we use a more logically deep/complex hash function instead of ECC, but we don't have to worry about the correction application then, just the detection/error-handling.
-ECC does have particular value in situations where we have potential bit-degradation over the lifetime of the device (e.g. OTP or flash), but here we are actually using the correction aspect to compensate for the lossiness/BER of the medium, rather than to defend against a glitch attack.  The glitch defense is really the partition digest computation/check.  We need to give careful consideration to the failure modes of the underlying storage medium when applying corrections in these cases though.
-We probably want to think about some weak/medium-strength hash computation (basically stepping up from ECC) that can be performed inline/in-one-extra-cycle for data where we want integrity protection, as the general verdict from yesterday was to not proceed on correctable errors

(BTW, I like very much your description of the HD-1 "halo" of ECC above - I will likely point to this PR in the security design guidelines document, or possibly quote the language as the explanation is very intuitive.)

**Comment by cdgori** [comment]
(lost a huge comment here to a reboot cycle, trying to recreate from memory - apologies if this version of the comment is a little brief)

we spoke yesterday in a meeting about this topic, sorry for not writing in here until now

In general:

-parity is pretty weak and I guess we should not be using it except in cases where ECC application is non-sensical (like really small state machine state vectors)
-your description of the byte-lane issues of parity is exactly right to me
-ECC basically has greater "diffusion" than parity with respect to the checked data vector, basically it considers more of the full width of the data vector
-but, ECC still is pretty weak compared to almost any hash function (has the HD>2 fault masquerading as correctable-error issues you mention above, which a collision-resistant hash function should not)
-we will want to consider some weak/medium-strength hash function that can be computed inline for data values where we want integrity protection, as an "upgrade" to ECC
-we will still want to use ECC in some cases where there is a underlying ~lossy storage medium (flash, OTP primarily) to correct for over-the-lifetime bitflips/errors, but need to be aware of the interaction of the ECC with any redundancy mechanisms and/or the failure modes of the storage medium (which are likely not randomly distributed)
-read pipeline with ECC probably needs one, maybe two extra cycles allocated for error detection and/or correction (possible to combine into one extra cycle or even zero, depends on memory read access time).  This cannot be conditional in the pipeline, so whatever we schedule/allocate must always execute on all reads (no conditional correction cycle)
-we need to think about if want to allow the system to continue operation on correctable errors (other than potentially OTP/flash), or if these are fatal / cause transition to terminal end state (as I believe you have already done with partition digest failures, for example)

Lastly, I like your halo explanation of ECC very much and will probably link to this PR or copy-with-attribution your description, in the secure HW design guidelines, as this is a nice intuitive explanation.

**Comment by tjaychen** [comment]
thanks chris! yes it'll be great to have this in the guidance.
i think we should work on documenting the local vs system fault item next
too.

**Pull request merged**
