### PR TITLE
Enable Ibex icache

### PR DESCRIPTION
**Pull request by tomroberts-lowrisc**
Vendor-in latest version of Ibex and enable the icache

### CODE REVIEW

**Comment by imphil** [comment]
@tomroberts-lowrisc can you run a Vivado synthesis before and after this PR and post the area report (it would be nice to export this information from CI, but we currently don't unfortunately).

Should be in `build/lowrisc_systems_top_earlgrey_nexysvideo_0.1/synth-vivado/lowrisc_systems_top_earlgrey_nexysvideo_0.1.runs/impl_1/top_earlgrey_nexysvideo_utilization_placed.rpt`

**Comment by tomroberts-lowrisc** [comment]
Before
```
+----------------------------+-------+-------+-----------+-------+
|          Site Type         |  Used | Fixed | Available | Util% |
+----------------------------+-------+-------+-----------+-------+
| Slice LUTs                 | 57584 |     0 |    133800 | 43.04 |
|   LUT as Logic             | 56728 |     0 |    133800 | 42.40 |
|   LUT as Memory            |   856 |     0 |     46200 |  1.85 |
|     LUT as Distributed RAM |   856 |     0 |           |       |
|     LUT as Shift Register  |     0 |     0 |           |       |
| Slice Registers            | 28799 |     0 |    267600 | 10.76 |
|   Register as Flip Flop    | 28799 |     0 |    267600 | 10.76 |
|   Register as Latch        |     0 |     0 |    267600 |  0.00 |
| F7 Muxes                   |  1793 |     0 |     66900 |  2.68 |
| F8 Muxes                   |   320 |     0 |     33450 |  0.96 |
+----------------------------+-------+-------+-----------+-------+
+-------------------+------+-------+-----------+-------+
|     Site Type     | Used | Fixed | Available | Util% |
+-------------------+------+-------+-----------+-------+
| Block RAM Tile    |  220 |     0 |       365 | 60.27 |
|   RAMB36/FIFO*    |  174 |     4 |       365 | 47.67 |
|     RAMB36E1 only |  174 |       |           |       |
|   RAMB18          |   92 |     0 |       730 | 12.60 |
|     RAMB18E1 only |   92 |       |           |       |
+-------------------+------+-------+-----------+-------+
```
After
```
+----------------------------+-------+-------+-----------+-------+
|          Site Type         |  Used | Fixed | Available | Util% |
+----------------------------+-------+-------+-----------+-------+
| Slice LUTs                 | 59098 |     0 |    133800 | 44.17 |
|   LUT as Logic             | 58242 |     0 |    133800 | 43.53 |
|   LUT as Memory            |   856 |     0 |     46200 |  1.85 |
|     LUT as Distributed RAM |   856 |     0 |           |       |
|     LUT as Shift Register  |     0 |     0 |           |       |
| Slice Registers            | 29188 |     0 |    267600 | 10.91 |
|   Register as Flip Flop    | 29188 |     0 |    267600 | 10.91 |
|   Register as Latch        |     0 |     0 |    267600 |  0.00 |
| F7 Muxes                   |  1688 |     0 |     66900 |  2.52 |
| F8 Muxes                   |   256 |     0 |     33450 |  0.77 |
+----------------------------+-------+-------+-----------+-------+
+-------------------+------+-------+-----------+-------+
|     Site Type     | Used | Fixed | Available | Util% |
+-------------------+------+-------+-----------+-------+
| Block RAM Tile    |  223 |     0 |       365 | 61.10 |
|   RAMB36/FIFO*    |  176 |     4 |       365 | 48.22 |
|     RAMB36E1 only |  176 |       |           |       |
|   RAMB18          |   94 |     0 |       730 | 12.88 |
|     RAMB18E1 only |   94 |       |           |       |
+-------------------+------+-------+-----------+-------+
```
Will push a fix for the outstanding reqs assert failure shortly

**Comment by imphil** [comment]
So that's around +2k LUTs and +3 BRAM36 tiles. Should be OK for CW305, @vogelpi?

**Review by imphil — APPROVED** [review]
Thanks Tom!

**Comment by vogelpi** [comment]
Thanks for providing the data on area increase. I just triggered a CW305 build with AES masking enabled. I will report back.

**Comment by vogelpi** [comment]
The build for the CW305 with masked AES failes:
```
ERROR: [Place 30-640] Place Check : This design requires more Slice LUTs cells than are available in the target device. This design requires 65149 of such cell types but only 63400 compatible sites are available in the target device. Please analyze your synthesis results and constraints to ensure the design is mapped to Xilinx primitives as expected. If so, please consider targeting a larger device. Please set tcl parameter "drc.disableLUTOverUtilError" to 1 to change this error to warning.
```
Disabling the icache is not sufficient to make it fit. I am now also testing if the number of outstanding transactions (related to the icache) is disabled. But it could be that in the meantime something else increased in size, too.

Anyway, it would be good if you could expose the icache parameter to the top-level (like its done for the register file selection) and only enable more outstanding transactions if the icache is enabled. This would definitely help us on the CW305 board.

**Comment by tomroberts-lowrisc** [comment]
I can expose the parameter, but I don't think the outstanding transactions will make much difference, just 2 flops and a small amount of logic relating to the source field in the tlul host adapter.

**Comment by vogelpi** [comment]
Yes I agree, it does not make a big difference. The biggest cores are currently:
- aes 12 kLUTs (when masked)
- otbn 9 kLUTs
- otp_ctrl 11 kLUTs
- ibex 8 kLUTs
- xbar 7 kLUTs

Probably otp_ctrl and otbn grew a lot in the past couple of weeks. We really need to think how to reduce the size of the design / some IPs if they are not needed. But this is a separate discussion and should not block this PR.

But if you could add the parameter I would appreciate that!

**Comment by tomroberts-lowrisc** [comment]
Thanks @imphil and @vogelpi - I added the parameter and disabled the icache in the CW305

**Review by vogelpi — APPROVED** [review]
Awesome, thanks @tomroberts-lowrisc !

**Comment by tjaychen** [comment]
quick question, even with the icache included, it's not immediately enabled right? (I can't remember where i saw this).
So if we want to use, does that mean we'll need to do a boot_rom update for example to turn it on?

**Comment by tomroberts-lowrisc** [comment]
@tjaychen good point - I added an item to #3875 to track

**Pull request merged**
