### PR TITLE
[i2c, rtl] Removed SDA toggling when sending multiple bits of "1"s.

### PR DESCRIPTION
**Pull request by igk8**
Signed-off-by: Igor Kouznetsov <igor.kouznetsov@wdc.com>

### CODE REVIEW

**Comment by igk8** [comment]
This is to address Issue #10109.

**Comment by martin-lueker** [comment]
> This is to address Issue #10109.

Rephrasing to catch github's attention:
Fixes #10109

**Review by martin-lueker — COMMENTED** [review]
LGTM, thanks Igor!

**Review by martin-lueker — APPROVED** [review]

**Comment by martin-lueker** [comment]
Hi @igk8.  Just me know when this is ready to merge.

**Comment by igk8** [comment]
Hi @martin-lueker, I've rebased master and this is now ready to be merged.

**Pull request merged**
