### PR TITLE
[usb_diff_rx] Model pull-up behavior

### LINKED ISSUE #17986: [chip_earlgrey/usbdev] usb_dp|dn_pullup_en unconnected
### Description

Caveat: I'm exploring a lot of new territory here...

In the process of trying to construct a top-level DV smoke test for the usbdev, based upon the usbdpi being instantiated in the test bench and modified to operate only on the USB_P, USB_N (DIO pins) and SENSE (MIO) pin, I think I've discovered the following:

- usbdev_dp/dn_pullup_en arrive in top_earlgrey from the usbdev
- they pass into the pinmux to be modified by the usbdev_aon_wake module for our sleep mode
- they exit top_earlgrey via its output ports
- in chip_earlgrey_asic they are connected into the prim_usb_diff_rx differential receiver but are unused, and they seem to go nowhere else

It looks as though they do not have the capacity to pull up the USB_P/USB_N signals under hardware control, so my test bench is not spotting the device connection.

Have I missed something, please?

@johngt @a-will

### PR DESCRIPTION
**Pull request by msfschaffner**
This models the USB pullup behavior in open-source. 
Let me know if this aligns with your understanding.

Fixes #17986

### CODE REVIEW

**Review by a-will — APPROVED** [review]
There's a little friction between this module and the padring, but this strategy seems good enough to me.

If you wanted to leave room for modeling the host's pull down resistors, the drive strength could potentially be changed to (pull0, pull1), but I'd guess that isn't necessary.

**Comment by msfschaffner** [comment]
> There's a little friction between this module and the padring, but this strategy seems good enough to me.
> 
> If you wanted to leave room for modeling the host's pull down resistors, the drive strength could potentially be changed to (pull0, pull1), but I'd guess that isn't necessary.

yeah we could make it pull-strength. I left it at weak because that is what we use in the pad models (pull / strong is used to model different driving strengths).

**Comment by alees24** [comment]
> > There's a little friction between this module and the padring, but this strategy seems good enough to me.
> > If you wanted to leave room for modeling the host's pull down resistors, the drive strength could potentially be changed to (pull0, pull1), but I'd guess that isn't necessary.
> 
> yeah we could make it pull-strength. I left it at weak because that is what we use in the pad models (pull / strong is used to model different driving strengths).

I've found it necessary to model the host weak pull down in usb20_usbdpi which is a new module that contains the existing usbdpi module; this then allows usbdev to be detected by monitoring USB_P(/N) and I used 'pull' strength in my proposed change to the diff receiver, to prevent any Z/X being driven into the usbdev and causing assertions. Also note that I've then had to change the drive strength of the pad to overcome the pull up.

I should remark that I'm feeling my way around with chip pads and drive strengths; all of my previous experience has been with IP blocks internal to an ASIC, or FPGA work.

**Comment by msfschaffner** [comment]
Thanks @alees24 - I have commented directly on #18063.

**Pull request merged**
