### PR TITLE
[adc_ctrl] Fix adc interrupt synchronization

### LINKED ISSUE #11759: [adc_ctrl/rtl] Fix Interrupt clock domain crossing
Currently the interrupt clock domain crossing uses a primitive with the unfortunate property that multiple triggers on the always on clock side while the gated clock is off can cause difficult to predict results.
The first trigger sets the interrupt, a second occurring during a gated period clears the interrupt again, a third sets it again and so on.
This leads to unexpected results.

Perhaps a scheme where all the interrupt logic is performed on the always on side, then copied via a request/acknowledge type CDC to the gated side, would be preferable.

I've re-enabled interrupts for test adc_ctrl_clock_gating in this PR https://github.com/lowRISC/opentitan/pull/11760

### PR DESCRIPTION
**Pull request by tjaychen**
- fixes #11759
- switch to prim_reqack instead of prim_pulse_sync
- since many events can occur during low power, split
  the sync source into staging and request.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@NigelScales i ran this against 20 seeds on the clock gating test and it seemed to work okay.
I'll test it with some of the other tests tomorrow to make sure i didn't break anything.

**Comment by NigelScales** [comment]
> @NigelScales i ran this against 20 seeds on the clock gating test and it seemed to work okay. I'll test it with some of the other tests tomorrow to make sure i didn't break anything.

Great let me give it a go.

**Review by NigelScales — APPROVED** [review]
Looks good,
I ran 5 clock gating and 5 interrupts tests with interrupts enabled, as per https://github.com/lowRISC/opentitan/pull/11760, all passed.

I'll set https://github.com/lowRISC/opentitan/pull/11760 to be merged after this one is.

**Comment by NigelScales** [comment]
@tjaychen I've done a like for like test.
Found a failing seed without the RTL fix.
Retried same seed with RTL fix and the test passes.

**Comment by tjaychen** [comment]
> @tjaychen I've done a like for like test. Found a failing seed without the RTL fix. Retried same seed with RTL fix and the test passes.

thanks Nigel. Btw, when I ran the clock gating test 20~30 times, I did run into a random low power assertion failure. I did not look super closely into it, but let me know if you've seen something similar and if it's something i should investigate.

**Review by cindychip — APPROVED** [review]

**Pull request merged**
