### PR TITLE
[docker] use CI verilator build in docker instead of custom apt source

### PR DESCRIPTION
**Pull request by nbdd0121**

### CODE REVIEW

**Comment by nbdd0121** [comment]
No, it's not tested by the CI. You can do a local build with `docker build -t opentitan -f util/container/Dockerfile .`, and then `docker run -it opentitan bash` to enter it and see `verilator` is indeed available in the path.

**Review by jwnrt — APPROVED** [review]
Thanks a lot, that works. Using the version from CI seems more reliable.

LGTM

**Review by andreaskurth — APPROVED** [review]
LGTM (though I didn't run it through Docker myself), thx Gary

**Comment by jwnrt** [comment]
@nbdd0121 was the container image rebuilt and uploaded to the store after this change? It seems we're still depending on this repository and the keys have expired, causing CI failure

**Pull request merged**
