### PR TITLE
[chip, dv] Increase default reseed to 3

### PR DESCRIPTION
**Pull request by weicaiyang**
Make SW test failure more persistent in nightly, which helps test
failure triage

Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by eunchan** [comment]
Can we change nightly script to increase the seeds to 3 and maintain 1 here? otherwise, users need to add `-r 1` always to run a test once.

**Comment by weicaiyang** [comment]
> Can we change nightly script to increase the seeds to 3 and maintain 1 here? otherwise, users need to add `-r 1` always to run a test once.

If we change nightly script to run `-r 3`, it will force all tests to run 3 seeds, but some tests are configured to run 20 seeds.

For local debug, I would suggest always adding `-r 1`. You can add it in your alias. BTW, If you have an alias `alias mydvsim=dvsim.py ... -r 1`, use  `mydvsim -r 10`, the last reseed takes effect and it runs 10 seeds.

**Review by sriyerg — APPROVED** [review]

**Comment by eunchan** [comment]
If you run `sim` only, yep. adding `-r 1` to alias would be good. `dvsim` however, runs other tools too. I think this can be a stop-gap solution but don't think it is a good idea to change the default runs to 3 always.

Anyhow, this is just a minor opinion. Please don't weigh in my opinion much.

**Comment by weicaiyang** [comment]
> If you run `sim` only, yep. adding `-r 1` to alias would be good. `dvsim` however, runs other tools too. I think this can be a stop-gap solution but don't think it is a good idea to change the default runs to 3 always.
> 
> Anyhow, this is just a minor opinion. Please don't weigh in my opinion much.

Sorry, I can't think of a better approach... Many tests are not default to 1 seed. If you want to run it once, always using `-r 1` is much safer.

**Review by matutem — APPROVED** [review]
LGTM... brace up for triple the top-level test runs?

**Pull request merged**
