### PR TITLE
Update lowrisc_ibex to lowRISC/ibex@c862f10

### PR DESCRIPTION
**Pull request by tomroberts-lowrisc**
Update code from upstream repository
https://github.com/lowRISC/ibex.git to revision
c862f104afbc31f28dccff6210abe94df7e1a2bc

* [rtl] icache error signalling fix (Tom Roberts)
* [rtl] Fix jump signal stuck high during stall (Tom Roberts)
* [doc] Minor fixes (Pirmin Vogel)
* [rtl] Rework generation and use of mult/div_sel/en (Pirmin Vogel)
* [rtl] Switch multdiv_en to multdiv_sel where possible (Pirmin Vogel)
* Fixes to invalidation logic in icache core agent (Rupert Swarbrick)
* Increase length of icache tests (Rupert Swarbrick)
* Initial icache scoreboard (Rupert Swarbrick)
* [dv] makefile:cov LSF arg fix (Udi)
* [bitmanip] Add ZBP Instruction Group (ganoam)
* Re-enable PMP/MEM errors in icache testbench (Rupert Swarbrick)
* Always branch after an error in icache UVM tests (Rupert Swarbrick)
* Fix UVM Makefiles to match updated dvsim from previous patch (Rupert
  Swarbrick)
* Update dvsim to lowRISC/opentitan@1d17b122 (Rupert Swarbrick)
* Update dv_lib to lowRISC/opentitan@1d17b122 (Rupert Swarbrick)
* Don't fetch on the same cycle as a branch in the icache core agent
  (Rupert Swarbrick)
* Fix scheduling for PMP errors in icache testbench (Rupert Swarbrick)
* Delete stray debug print from ibex_icache_mem_resp_seq (Rupert
  Swarbrick)
* [rtl/icache] Fix typo in ram req (Tom Roberts)
* [dv] Enable verification of the Bitmanip Extension with OVPsim and
  Spike (Pirmin Vogel)
* Add a monitor to the icache <-> mem interface in UVM testbench
  (Rupert Swarbrick)
* Add SV assertions on icache <-> mem interface in UVM testbench
  (Rupert Swarbrick)
* Add a monitor to the icache <-> core interface in UVM testbench
  (Rupert Swarbrick)
* Add SV assertions to icache <-> core interface in UVM testbench
  (Rupert Swarbrick)
* Add heartbeat tracking to ICache testbench (Rupert Swarbrick)
* [dv] Fix Xcelium compilation (Weicai)
* [rtl/icache] Fix some issues in icache (Tom Roberts)
* Add RV32B parameter option (Tobias Wölfel)
* [bitmanip] Fix: Oversight in Tracer ZBT DV fail (ganoam)
* [rtl/lsu] Fix bug in pmp error clearing (Tom Roberts)
* [bitmanip] Add ZBS Instruction Group (ganoam)
* [dv] fix spurious LSF enabling (Udi)
* Add missing include (Pirmin Vogel)
* Update src_files.yml (Pirmin Vogel)
* [doc] Link to RISC-V Debug Specification (Philipp Wagner)
* [doc] Clean up Sphinx warnings (Philipp Wagner)
* [doc] Add note about debug system integration (Philipp Wagner)
* Reorder statements to prevent latch inference (Jonathan Kimmitt)
* Use Shared Imd Val Reg with Multdiv Slow (ganoam)
* Temporarily disable PMP/MEM errors in icache testbench (Rupert
  Swarbrick)
* Initial memory agent for ICache UVM testbench (Rupert Swarbrick)
* [dv] update directory paths for riscv-dv coverage (Udi)
* CI: Use packaged version of Verilator (Philipp Wagner)

Signed-off-by: Tom Roberts <tomroberts@lowrisc.org>

### CODE REVIEW

**Comment by imphil** [comment]
While you're at it, can you update some of the excludes to exclude everything which isn't strictly necessary? This should help #1231.

I'm not fully sure about the dependencies, but can you try to exclude the `vendor` and `shared` directories completely?

**Comment by imphil** [comment]
@GregAC mentioned in #1231 (keeping the discussion here, the other issue isn't really about Ibex vendoring details):

> lowrisc:ibex:sim_shared is needed. It includes various RTL files the ICache needs.

Does it really? All primitives we have in ibex:/shared should be copies from the ones from OT and they can (and should) be removed from the import. For example, we must use the OT RAM primitives in the icache as it is vendored into OT.

**Comment by tomroberts-lowrisc** [comment]
I think OT doesn't have the required SECDED modules, they can be added to OT, but then might need another core file for them

**Comment by tomroberts-lowrisc** [comment]
Also, some of the files in sim_shared have prim_assert `included, so might not be able to remove the prim_assert dependency

**Comment by imphil** [comment]
Looks great now! Thanks.

**Pull request merged**
