### PR TITLE
[otbn] Update block diagram for RND/URND

### LINKED ISSUE #6458: [otbn] Update block diagram to properly represent RND/URND
The OTBN block diagram at https://docs.opentitan.org/hw/ip/otbn/doc/index.html currently only mentions RND. We need to add URND to it as well, and maybe also the EDN connections.

### PR DESCRIPTION
**Pull request by GregAC**
Fixes #6458

Direct link to new SVG: https://github.com/GregAC/opentitan/blob/ebd50f28ba075796b665eaa951f137dee74ab595/hw/ip/otbn/doc/otbn_blockarch.svg

### CODE REVIEW

**Comment by imphil** [comment]
Thanks! Two suggestions:
* Add a label "seed" or so to the EDN -> LFSR connection.
* Add a label edn0 and edn1 to the arrows coming out of the EDN block, or alternatively duplicate that, to indicate that these numbers come from very different EDN sources that are configured differently.

**Comment by GregAC** [comment]
SVG direct link https://github.com/lowRISC/opentitan/blob/0a81fded4fcb22f68409230a284c4c38615d697f/hw/ip/otbn/doc/otbn_blockarch.svg

Should have checked the CI failures before pushing again but I've only changed the SVG so must be some transient issue (or CI is broken in master...)

**Comment by GregAC** [comment]
Or lack of a signed-off-by line...

**Review by imphil — APPROVED** [review]
Thanks a lot Greg! (Sometimes CI isn't broken, it seems :smile:)

**Pull request merged**
