### PR TITLE
[aes] De-assert idle after a new key becomes ready, flop idle_o

### PR DESCRIPTION
**Pull request by vogelpi**
This commit modifies the generation of the idle bit in the status register to prevent that writes to the main control, key and IV
registers following a write to the main control register or a key register collide with the start of a PRNG reseed operation thereby
getting lost. This is required as with the key_touch_forces_reseed feature, a write to the control register (if sideload is enabled) or the write of the last key register may trigger a PRNG reseed operation.

In addition, the idle_o status bit for the clock manager is flopped to match the corresponding bit in the status register. Previously, it was one clock cycle off.

This is related to lowRISC/OpenTitan#10518.

### CODE REVIEW

**Review by rasmus-madsen — COMMENTED** [review]
@vogelpi thank you for this, but I was wondering if it wouldn't make more sense to hold off on the reseed until the configuration has been updated successfully?
rather than blocking the second part of the update. (shadowed registers take two writes to update)

**Comment by vogelpi** [comment]
That could also be done but it requires more changes across hierarchies. Basically the shadow register phase value needs to be forwarded to the internal AES control such that the main controller FSM has an understanding in which phase the shadow register is. But this fix here would still be needed.

Functionally it only makes a difference if sideload is enabled. Because only with sideload the key can actually be updated upon the control register write. For non-sideload, the key is only updated upon writing the key registers themselves. Then the shadow register doesn't matter.

**Comment by rasmus-madsen** [comment]
> That could also be done but it requires more changes across hierarchies. Basically the shadow register phase value needs to be forwarded to the internal AES control such that the main controller FSM has an understanding in which phase the shadow register is. But this fix here would still be needed.
> 
> Functionally it only makes a difference if sideload is enabled. Because only with sideload the key can actually be updated upon the control register write. For non-sideload, the key is only updated upon writing the key registers themselves. Then the shadow register doesn't matter.

it makes a difference to the dv as the shared csr task assumes it can do the shadowed write immediately.
but if you don't want to change it I can make my own shadow write function

**Review by cdgori — APPROVED** [review]
This change LGTM, I'll leave it to @vogelpi and @rasmus-madsen to resolve the DV complication.

**Comment by vogelpi** [comment]
Ah, thanks for explaining @rasmus-madsen . After thinking a bit more about this and studying the RTL, I think I should be able to make the change without touching the primitive. I'll give this a try then you don't have to create a new shadow write function.

**Comment by vogelpi** [comment]
Update: I've now forwarded the phase signal from the shadow reg prim into the AES controller. This is the cleanest way of handling this. This should avoid that you need to create a custom shadow reg write function @rasmus-madsen . Please let me know if that works for you.

**Review by rasmus-madsen — APPROVED** [review]
LGTM

**Comment by vogelpi** [comment]
Thanks for your reviews @cdgori and @rasmus-madsen , I am merging this now.

**Pull request merged**
