### PR TITLE
[dv] Avoid using word "sanity" in DV testbenchs

### PR DESCRIPTION
**Pull request by cindychip**
After some discussion, DV engineers agreed to use `smoke test` to replace `sanity test`, and use `smoke regression` to replace `sanity regression`.

`OTBN` and `entropy_src` DV testbenchs have already made the updates.

This PR includes the IPs for:
aes (@rasmus-madsen), i2c, pattgen (@tunghoang290780), flash_ctrl (@sriyerg), uart, spi_device, keymgr(@weicaiyang), kmac, prim (@udinator), csrng(@senelson7)
Please FEEL FREE to open your own PR to update the change, I will simple remove the commits from this PR. Or feel free to let me know if you want to request any changes from this PR.

This PR also includes update from dv/common area, checklist, and FPV updates. I separate them in different commits for the ease of review.

### CODE REVIEW

**Review by sriyerg — APPROVED** [review]

**Comment by sriyerg** [comment]
Skimmed through, LGTM!

**Review by senelson7 — APPROVED** [review]
LGTM, I'll do this for the edn dv when PR# 4038 gets merged

**Review by weicaiyang — APPROVED** [review]
LGTM. Thanks for making this change

**Comment by cindychip** [comment]
Okay now private CI passed. @senelson7 if you do not mind, I have to merge your commit from #4247 into this PR in order pass the private CI. 
The issue for the private CI is that it is using: https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/dv/top_earlgrey_sim_cfgs.hjson and use `-i sanity or smoke` to trigger sanity/smoke regression. And from Rupert's update, the private CI will search available regression (either smoke or sanity) to trigger the check. But with any of our PR, it will return both sanity and smoke because we have both regressions within our partial updates. I guess to accommodate that, I will need to update dvism.py for that. But if you do not mind, here i just cherry-picked your commit and submit one PR. Then we can avoid temp changing dvsim.py :)

**Comment by senelson7** [comment]
OK by me. Should I close my PR #4247 then or wait until this one is merged to be sure?

**Comment by cindychip** [comment]
Great! Thanks! Maybe wait until this one merged to be sure.

**Review by tunghoang290780 — APPROVED** [review]
LGTM

**Review by rasmus-madsen — APPROVED** [review]
only reviewed AES LGTM

**Review by udinator — APPROVED** [review]
Only checked the common files and KMAC TB files - LGTM

**Comment by cindychip** [comment]
Thanks everyone for reviewing this PR! I will get it merged asap.

**Pull request merged**
