### PR TITLE
[sw, tock] Add Tock through Cargo with demo

### PR DESCRIPTION
**Pull request by jon-flatley**
This PR is a spin on #1488 with a demo included. The main difference here is that none of the Tock source is included. Instead, the `Cargo.toml` file simply references the upstream Tock repository. `Cargo.lock` is also included. The plan is to eventually have CI keep the `Cargo.lock` file tracking as close to `HEAD` on [`tock/master`](https://github.com/tock/tock/tree/master) as possible, but for now any changes will need to be done manually.

I've added a `meson.build` file and helper `util/build_tock.sh` script to build Tock as a Meson target by invoking Cargo. Right now it is intentionally set up so no Tock targets build by default. Eventually the Rust toolchain will be required for builds, but for now disabling `build_by_default` should be enough to prevent builds from breaking.

This PR comes with a little demo that flashes the LEDs on the FPGA in a binary counter pattern and puts the "ART" in UART by printing some lovely ASCII art to the console.

There are no userspace apps included, and the .apps section is removed as a part of creating the `.bin` file. This is to save space and time spent waiting on `spiflash`.

Next step will be to create bindings to the OT DIFs and start writing Tock drivers in Rust based on them. I would also like to create separate targets for release vs debug builds and targets that make it easier to build a local checkout of Tock.

### CODE REVIEW

**Comment by eunchan** [comment]
Hum, this breaks the top-level simulation. I will create a revert PR.

**Comment by jon-flatley** [comment]
@eunchan I think I see the problem. This PR creates an accidental dependency on cargo. I thought this wouldn't be a problem since none of the targets in the `meson.build` file build by default, but it appears that I was wrong. I'll remove this dependency.

**Comment by eunchan** [comment]
> @eunchan I think I see the problem. This PR creates an accidental dependency on cargo. I thought this wouldn't be a problem since none of the targets in the `meson.build` file build by default, but it appears that I was wrong. I'll remove this dependency.

@jon-flatley As I commented in the revert PR, I have installed cargo already (rustc ). Probably my issue may not related to this. I will dig more.

**Comment by jon-flatley** [comment]
> @jon-flatley As I commented in the revert PR, I have installed cargo already (rustc ). Probably my issue may not related to this. I will dig more.

I'm not sure how this PR could be the cause of any more breakage since all targets are set to not build by default. The cargo dependency is the only thing I could think of.

Regardless, the cargo thing was definitely broken, so that needed to be fixed.

**Comment by eunchan** [comment]
> could think of.
> 
> Regardless, the cargo thing was definitely broken, so that needed to be fixed.

Ah.. I dug this issue and it was my mistake of typo in the test case :) No worry.

**Pull request merged**
