### PR TITLE
[fpv] Remove unused scripting from hw/formal

### PR DESCRIPTION
**Pull request by imphil**
The `hw/formal` directory still had scripting to run formal tools. This scripting is now unused and replaced by dvsim. Remove it.

### CODE REVIEW

**Comment by imphil** [comment]
@cindychip I could only do very limited testing on this script since I don't have the ability to actually run the tools. Can you give it a try and let me know how it goes?

Also, is this scripting actually still in use, now that we (can) run FPV through dvsim?

**Review by cindychip — APPROVED** [review]
Thanks Philip. LGTM. We are actually not able to run this locally any more. We moved to use the dvsim version under batch script: `hw/top_earlgrey/formal/`.

**Comment by imphil** [comment]
Should we just remove it then, @cindychip? Maybe you can have a look at all things in the hw/formal folder and let me know which of the scripts are actually still needed?

**Comment by cindychip** [comment]
Sure that works! I believe we can remove the following items under `hw/formal`:
1). fpv
2). fpv_all
3). formal_conn.sh
4). fpv_vcf.tcl

On my side, TODOs after this PR will be:
1). Update the `hw/formal/README`
2). Figure out who is using/maintaining the formal Conformal LEC tool

**Comment by imphil** [comment]
Thanks @cindychip, removing things is even easier than fixing them :-) I updated the PR.

**Review by cindychip — APPROVED** [review]
Thanks again! LGTM

**Pull request merged**
