### PR TITLE
[dv/coverage_cfg] Remove coverage of prim_onehot_check

### PR DESCRIPTION
**Pull request by matutem**
The prim_onehot_check module is verified with FPV, so it needs no coverage collected. It is already excluded in the normal coverage config, but it was not for cover_reg_top, which created a coverage hole since the tests using cover_reg_top don't inject errors.

Signed-off-by: Guillermo Maturana <maturana@google.com>

### CODE REVIEW

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks

**Comment by sriyerg** [comment]
Could you also add this to `hw/top_earlgrey/dv/cov/chip_cover_reg_top.cfg`?

**Comment by sriyerg** [comment]
> Could you also add this to `hw/top_earlgrey/dv/cov/chip_cover_reg_top.cfg`?

And to `chip_cover.cfg`.

**Comment by matutem** [comment]
@sriyerg I added the files you suggested.

**Review by sriyerg — APPROVED** [review]

**Pull request merged**
