### PR TITLE
[sw] Move source files for Rust crates to src/ directories

### PR DESCRIPTION
**Pull request by jwnrt**
This PR ensures all Rust source files are in `src/` directories. This is functionally equivalent, and just for consistency.

Only `cryptotest` and `tests/chip/example_sival` needed updating.

### CODE REVIEW

**Comment by pamaury** [comment]
This convention tends to create a lot of almost empty directories with just `BUILD` and `src` with then a single file in it though.

**Comment by jwnrt** [comment]
Actually I do agree. I was thinking about moving to Cargo's test directory structure where you have one crate with:

```
Cargo.toml
tests/
  uart_tx_rx.rs
  flash_ctrl_host_rma_test.rs
  gpio.rs
  i2c_target.rs
  jtag.rs
  ...
```

Rather than all these tests having their own crate.

**Comment by pamaury** [comment]
Yes that would make a lot of sense.

**Comment by jwnrt** [comment]
I'll do something similar to this in the future, but closing for now.

**Pull request closed without merging**
