### PR TITLE
[rv_core_ibex] Move Ibex verification_stage to V2S

### PR DESCRIPTION
**Pull request by vogelpi**
This resolves lowRISC/OpenTitan#23542.

### CODE REVIEW

**Review by andreaskurth — APPROVED** [review]
LGTM based on the evidence collected in #23542. Thx!

**Comment by vogelpi** [comment]
CHANGE AUTHORIZED: hw/ip/rv_core_ibex/data/rv_core_ibex.hjson

**Comment by andreaskurth** [comment]
CHANGE AUTHORIZED: hw/ip/rv_core_ibex/data/rv_core_ibex.hjson

**Comment by vogelpi** [comment]
Merging as the relevant CI checks have passed.

**Pull request merged**
