### PR TITLE
[bazel] Use CRT for toolchain configuration

### PR DESCRIPTION
**Pull request by cfrantz**
Use [Compiler Repository Toolkit](https://github.com/lowRISC/crt) to
configure the RISC-V toolchain instead of bazel-embedded.

1. Bazel-embedded seems to be somewhat unmaintained.
2. Bazel-embedded wasn't well structured for the addition of the riscv compiler.  We never successfully upstreamed our fork.
3. CRT was written by the OpenTitan team.
4. CRT has a somewhat easier structure for supporting additional target architectures.
5. CRT is also being used by the provisioning project to cross compile for Win32/64 targets.

### CODE REVIEW

**Review by timothytrippel — APPROVED** [review]

**Review by alphan — COMMENTED** [review]
Thanks @cfrantz!

There seems to be an issue with the `clang-format` definition (just checked the CI)

I also checked the CRT repo to make sure that we have the recent changes from our `bazel-embedded` fork: It looks like CRT does not enable `-Werror -Wall -Wpedantic`.

**Comment by alphan** [comment]
> I also checked the CRT repo to make sure that we have the recent changes from our `bazel-embedded` fork: It looks like CRT does not enable `-Werror -Wall -Wpedantic`.

I'm not sure why github search doesn't work but it looks like we just need to enabled `-Werror` [here](https://github.com/lowRISC/crt/blob/c9463da5047b6047b46db43ed0071f6a8acae059/features/common/BUILD.bazel#L56) since `-Wall -Wpedantic` are already enabled.

**Review by alphan — APPROVED** [review]

**Comment by alphan** [comment]
Didn't merge because @cfrantz requested a review from @cindychip and wanted to give @cindychip the chance to take a look before this is merged.

**Comment by cfrantz** [comment]
> > I also checked the CRT repo to make sure that we have the recent changes from our `bazel-embedded` fork: It looks like CRT does not enable `-Werror -Wall -Wpedantic`.
> 
> I'm not sure why github search doesn't work but it looks like we just need to enable `-Werror` [here](https://github.com/lowRISC/crt/blob/c9463da5047b6047b46db43ed0071f6a8acae059/features/common/BUILD.bazel#L56) since `-Wall -Wpedantic` are already enabled.

I've updated the configuration in the CRT repo such that the riscv compiler is invoked with identical options to the current bazel-embedded configuration (modulo repository path differences).

**Comment by cfrantz** [comment]
> 

The request for @cindychip was automatically added when I updated some of the toolchain labels in the //hw/... scripts.  @cindychip , the changes are simple replacements.

@timothytrippel will merge this PR after it passes CI and he performs the needed updates to the internal EDA runtime images.

**Comment by timothytrippel** [comment]
Looks like we need to remove [this line](https://github.com/lowRISC/opentitan/blob/7fd5e8c34a6e313f554e61e40583c0c43fc2ad1b/util/prep-bazel-airgapped-build.sh#L143) in order to get the image building.

**Comment by yenkwang** [comment]
@ bazel_embedded is still in [.bazelrc](https://github.com/lowRISC/opentitan/blob/a1236a065c58149beb6785e26c98ff0a9cd1acc3/.bazelrc#L26)

**Comment by timothytrippel** [comment]
> @ bazel_embedded is still in [.bazelrc](https://github.com/lowRISC/opentitan/blob/a1236a065c58149beb6785e26c98ff0a9cd1acc3/.bazelrc#L26)

#14646 should fix.

**Pull request merged**
