### PR TITLE
[rv_core_ibex] Update crash_dump format

### PR DESCRIPTION
**Pull request by tjaychen**
- contains both current and previous crash dump.
- previous crash dump is populated only when a double fault is seen.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@GregAC let me know if this is what you had in mind.

**Review by GregAC — APPROVED** [review]
I was initially thinking we'd only make a copy of `exception_addr` from the crash dump but I guess making a copy of the whole thing can't hurt.

**Comment by GregAC** [comment]
What are we doing testing wise for the crash dump? We should probably have a test with a intentional fault where we can check the values from the crash dump are as expected. Maybe one with a normal exception and one with a double fault?

**Comment by tjaychen** [comment]
> What are we doing testing wise for the crash dump? We should probably have a test with a intentional fault where we can check the values from the crash dump are as expected. Maybe one with a normal exception and one with a double fault?

i think we need to add an item to the top level testplan. I'm actually a bit surprised it's not there, I thought it was something that was discussed before.

**Comment by matutem** [comment]
There are a couple full chip tests that intend to cause a watchdog reset due to CSR accesses to disabled units: chip_sw_clk_off_trans/peri, and to check the current_pc field corresponds to the CSR access that is meant to time-out. What is the spec for the four values in crash_dump_t?

**Comment by tjaychen** [comment]
> There are a couple full chip tests that intend to cause a watchdog reset due to CSR accesses to disabled units: chip_sw_clk_off_trans/peri, and to check the current_pc field corresponds to the CSR access that is meant to time-out. What is the spec for the four values in crash_dump_t?

i'll add a test plan item and add you to review @matutem 
i'll also update the documentation in `rstmgr` to point to something in the `rv_core_ibex` spec to clarify the crash dumps.

**Pull request merged**
