### PR TITLE
[hyper310] Move JTAG from the nucleo board to the JTAG header

### PR DESCRIPTION
**Pull request by a-will**
The hyperdebug firmware is incapable of performing JTAG at this time. Use an external debugger instead.

### CODE REVIEW

**Review by timothytrippel — APPROVED** [review]
Thanks @a-will

**Comment by timothytrippel** [comment]
Can we mark this non-draft and merge once I test it?

**Comment by a-will** [comment]
> Can we mark this non-draft and merge once I test it?

Certainly. Just tell me when (or click the button yourself), and thanks for testing!

**Comment by timothytrippel** [comment]
After discussion with @jesultra , we determined we should no move the routing of the JTAG pins back to the CW310 header pins for hyperdebug bitstream, as we want to be able to test the sysrst_ctrl operations with hyperdebug which uses some of the same OT pins.

Until the new hyperdebug shield is available, I will try to jumper out pins from the nucleo board to my olimex to see if I can get the JTAG setup working with the existing hyperdebug bitstream. Thanks @a-will

**Comment by jesultra** [comment]
Once you have found a working JTAG setup using the hyperdebug bitstream, I am highly interested. I am working on JTAG support in the Hyperdebug firmware, and would like to demonstrate it working with the swizzle board.

**Pull request closed without merging**
