### PR TITLE
[otbn] exclude hjson entries from general csr tests

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
I am currently seeing private CI failures. 
Not sure this fix is sufficient yet.

**Comment by sriyerg** [comment]
Merging because the private CI is clean.

**Comment by imphil** [comment]
@tjaychen where did you see the CI failures? master was green all the time.

**Comment by imphil** [comment]
And more importantly: Thank you for adding this exclusion. I was playing around with it when doing the initial work and thought it might be unnecessary for a start, but I agree that it is the right thing to do.

**Comment by tjaychen** [comment]
i saw it here (
https://dev.azure.com/lowrisc/opentitan-private/_build/results?buildId=16562&view=logs&j=89b1484e-e59b-56b8-bef8-ec534b74be7c&t=5028a3c4-0542-585a-b10c-81f6b79fff87
)
A completely unrelated PR of mine that I recently rebased on head of tree.

I was a bit surprised to see it honestly, but I guess the changing design
also changed the registers the sanity regression was touching, and it just
happened to fail for me.

**Pull request merged**
