### PR TITLE
[WIP] - Sensor control creation

### PR DESCRIPTION
**Pull request by tjaychen**
This adds the sensor_ctrl unit, which is basically just a front end to ast.

I will work on the ast structure in parallel and hopefully have a draft of that soon.
This is currently blocked by fpga timing, and i've filed #2274 to get everyone's opinion...

### CODE REVIEW

**Comment by tjaychen** [comment]
well looks like fpga timing is unstable now.... that's....not a good sign...

**Comment by sjgitty** [comment]
This all LGTM, but I'd rather @eunchan be one of the gate keepers here. And of course the FPGA timing issue, but I imagine that is somewhat unrelated (probably we're on the edge, and I know others are looking into it).

I imagine this is one of those that could go into bronze but likely you'll need it in master to sink all of the AST signals that are coming. Since this is going into master, perhaps you can write a one paragraph placeholder for the design spec so there is some reference for others to understand the purpose here.

**Comment by tjaychen** [comment]
yeah i'll add a doc, either this PR or another to gate this PR.

**Comment by imphil** [comment]
This PR probably will need a bit of refactoring once the AST changes are in, please ping me to do a re-review if needed.

**Comment by tjaychen** [comment]
yes will do.

**Comment by tjaychen** [comment]
closing this one down, will push a new PR later.

**Pull request closed without merging**
