### PR TITLE
[doc] CMDGEN based reggen content for AES

### PR DESCRIPTION
**Pull request by HU90m**
Started the move away from the `mdbook_reggen.py` preprocessor to using CMDGEN.

This will allow one to add extra context around the auto-generated content and will simplify the documentation build, as well as allowing register tables to be viewed in plain text and [on github](https://github.com/HU90m/opentitan/blob/cmdgen-reggen/hw/ip/aes/doc/registers.md).

### CODE REVIEW

**Review by jwnrt — APPROVED** [review]
LGTM, thanks 

Output looks good, and I much prefer having markdown vendored in than linking to hjson files. I haven't really reviewed the Python but doesn't look outrageous.

**Comment by HU90m** [comment]
Updated tables. Got caught out my own CMDGEN lint. Nice to know its working.

**Comment by HU90m** [comment]
> From first glance, looks good to me. Do we want to run this tool on all the existing IP blocks or just AES for now?

Yes, the plan is to use CMDGEN for all IP blocks. I'll move the rest across over the next two week (max)

**Comment by HU90m** [comment]
Rebased

**Review by hcallahan-lowrisc — APPROVED** [review]
Changes LGTM, thanks @HU90m!

I think it would be nice to have some what/why/how markdown documentation for the CMDGEN tooling, and then for cmdgen.py to automatically insert a comment right under the BEGIN block with a link to the docs page. Would you be able to do something like this alongside the work of migrating the rest of the docs over to using cmdgen?

**Comment by HU90m** [comment]
> I think it would be nice to have some what/why/how markdown documentation for the CMDGEN tooling, and then for cmdgen.py to automatically insert a comment right under the BEGIN block with a link to the docs page. Would you be able to do something like this alongside the work of migrating the rest of the docs over to using cmdgen?

Agreed, I've added CMDGEN to my notes that will become documentation on the documentation setup. Having a comment pointing to this page is a great idea! I'll put it on my todo list.

**Review by marnovandermaas — APPROVED** [review]
Approving this based on a brief look and because @jwnrt and @hcallahan-lowrisc have approved it (they are very knowledgeable on the docs).

**Pull request merged**
