### PR TITLE
[reggen] Make field 'qe' behavior consistent

### PR DESCRIPTION
**Pull request by tjaychen**
[reggen] Make field 'qe' behavior consistent
- if one field does not generate 'qe' for whatever reason (for example
  shadow update error), suppress qe generation for the entire register.

Originally this PR consolidated all the `qe` into one item in the struct instead of having it per field. 
However that turned out to disturb a bunch of ip blocks. 

I can still re-open and do that if people prefer.

### CODE REVIEW

**Review by cindychip — APPROVED** [review]
Thanks Tim, the kmac issue is not seen any more! But let me run a regression and make sure all other shadow regs are good ;)

**Comment by tjaychen** [comment]
> Thanks Tim, the kmac issue is not seen any more! But let me run a regression and make sure all other shadow regs are good ;)

sounds great, thanks cindy.

**Comment by tjaychen** [comment]
@eunchan can you have a look? This resolves that qe issue you were seeing with kmac.
Basically for shadow registers, if there's an update error, all `qe` are blocked.

**Review by eunchan — APPROVED** [review]
LGTM. So basically, this commit merges all `qe`s into one. :)

**Comment by tjaychen** [comment]
> LGTM. So basically, this commit merges all `qe`s into one. :)

yeah that's right. Originally I actually changed the `reg_pkg` to also be merged, but that ended up causing too much churn in the design. So I dropped down to this approach which would cause less churn overall.

If people really do prefer to see 1 qe only, I can revive that and make appropriate changes. I will update the commit message and PR and gather some opinions.

**Comment by eunchan** [comment]
I am OK with current change.

Maybe we can create an issue and ICEBOX in the design?

**Review by rswarbrick — APPROVED** [review]

**Comment by tjaychen** [comment]
@rswarbrick do you think we should go all the way and just merge into a single `qe` per reg?
I think you had filed an issue on that.  I want to make sure people are okay with the churn before I do that.

**Comment by rswarbrick** [comment]
I even had an implementation! I seem to remember that it was rather finicky and, as you say, introduced lots of churn. Maybe not worth it for now? (Hopefully, synthesis tools will collapse the signals anyway)

**Comment by tjaychen** [comment]
> I even had an implementation! I seem to remember that it was rather finicky and, as you say, introduced lots of churn. Maybe not worth it for now? (Hopefully, synthesis tools will collapse the signals anyway)

sounds good. I really want to one day refactor into enclosed regs :)

**Comment by tjaychen** [comment]
if there are no other objections, i'll merge this EOD.

**Pull request merged**
