### PR TITLE
[dv/clkmgr] Update naming to pass CI

### PR DESCRIPTION
**Pull request by cindychip**
Update clkmgr csr name from extclk_sel_regwen to extclk_ctrl_regwen

Signed-off-by: Cindy Chen <chencindy@opentitan.org>

### CODE REVIEW

**Comment by cindychip** [comment]
Close this and Matute will make an official fix ;)

**Comment by tjaychen** [comment]
btw, any reason we shouldn't merge this one first if it works? Because this will block all CI now right?

**Comment by cindychip** [comment]
I talked with Matute offline, and this requires more naming change, and he is preparing a PR for that.

**Comment by cindychip** [comment]
I guess this PR should work temporarily if ppl need to unblock their progress. But definitely needs more naming change on clkmgr DV function/variables.

**Comment by tjaychen** [comment]
it's okay, it looks like Philipp already reverted my PR. I'll coordinate
that one with Matute again.

**Pull request closed without merging**
