### PR TITLE
Fixes Issue #13120

### PR DESCRIPTION
**Pull request by senelson7**
Signed-off-by: Steve Nelson <steve.nelson@wdc.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@Jacob-Levy

**Review by tjaychen — APPROVED** [review]

**Review by mwbranstad — APPROVED** [review]
LGTM

**Review by martin-lueker — APPROVED** [review]
Thanks @senelson7!  LGTM.

**Comment by a-will** [comment]
Just an FYI: To get the auto-close behavior, you'd need to put the "Fixes #13120 " line in the description. It's in the PR title right now. :smile:

**Comment by martin-lueker** [comment]
Yeah I saw that too.  Mildly interesting.  Well regardless, if @Jacob-Levy tells us it's fixed it's no trouble to close it manually.

**Pull request merged**
