### PR TITLE
[all] updated assert rtl ifdef

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@mwbranstad this should address the `prim_count` lint warning you were seeing.

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks

**Review by cindychip — APPROVED** [review]

**Comment by mwbranstad** [comment]
has anybody testing this counter with a variably sized step? It does not count as I would expect - using this merged version.

**Comment by tjaychen** [comment]
Mark can you clarify a bit what you mean by variably sized step? do you
mean it changes throughout?

I think so far we've only tested this against a fixed count. Can you point
me to where you're seeing issues?

**Comment by mwbranstad** [comment]
hey Tim, looks like there was a bug in my translation from the original counter to this one. The "variable sized step" meant that  a logic signal input is used as the step, not a constant (like 1). The issue is that I was also including the counter value as well, which of course, is held within the prim_count module implementation. After fixing this, it appears to work as did the old logic did. Sorry about the false alarm.

**Comment by tjaychen** [comment]
yay! i'm just glad it works for you.

**Pull request merged**
