### PR TITLE
[flash_ctrl] Allow rma entry even if flash has not been initialized.

### PR DESCRIPTION
**Pull request by tjaychen**
As part of #10188, it was realized that rma entry is currently gated
by flash initilization.

This may not be a good idea because if flash initlization were to ever
stall (ROM could not program it for whatever reason), then rma entry
could never be done.

This PR allows RMA entry to happen even if initilization has not been
called.  If initilization has not been called, it is possible that
entropy is not properly behaving as part of the ROM routine, so the
reseeding is also skipped so that the flash can be directly wiped.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
hey all, need your input on my rationale here. Am I being too conservative?

**Review by TimEwins — APPROVED** [review]

**Comment by alphan** [comment]
> As part of #10188, it was realized that rma entry is currently gated by flash initilization.
> 
> This may not be a good idea because if flash initlization were to ever stall (ROM could not program it for whatever reason), then rma entry could never be done.
> 
> This PR allows RMA entry to happen even if initilization has not been called. If initilization has not been called, it is possible that entropy is not properly behaving as part of the ROM routine, so the reseeding is also skipped so that the flash can be directly wiped.

This seems reasonable to me. @moidx any thoughts?

**Review by moidx — APPROVED** [review]
I think this makes sense. I agree we don't want to block RMA entry on flash initialization. Skipping reseed is also a good idea at this stage.

**Review by a-will — APPROVED** [review]

**Comment by tjaychen** [comment]
thanks all for the review. I will merge this first.
@cdgori if you notice any problems later, please let me know and I will address accordingly.

@TimEwins this means we really should test RMA entry both before flash init and after. 
Do you want me to file an issue to add this description to the testplan?

**Comment by TimEwins** [comment]
@tjaychen "we really should test RMA entry both before flash init and after".  

It is probably best to file an issue, so we can cross reference this requirement, plus I believe Rashmi (PM) would prefer it recorded.

**Comment by tjaychen** [comment]
will do, i'll file an issue and assign to you.

**Pull request merged**
