### PR TITLE
[bazel] Move buildifier to bzlmod

### PR DESCRIPTION
**Pull request by jwnrt**
Switch from building buildifier ourselves to using the `buildifier_prebuilt` module. This also means we don't have to build it from source using a Go toolchain.

### CODE REVIEW

**Review by nbdd0121 — APPROVED** [review]
Implementation LGTM.

It's good that we can get rid of the go dependency, although I'll leave it to others to decide if it's acceptable to add new binary dependency.

**Comment by jwnrt** [comment]
Who would be best to get a review from?

For context, buildifier runs on the host for dev purposes (formatting Bazel code).

**Review by pamaury — APPROVED** [review]
Looks good. Switching to a prebuilt time will also save time because we routinely have to recompile it.

**Comment by jwnrt** [comment]
> Would this be needed for Airgapped environment, or would the use of Bzlmod make this a lazy dependency and won't be needed if buildifier_fix is not to be executed?

It’s loaded lazily, so I don’t think it’s needed

**Comment by jwnrt** [comment]
I think i’ll merge since the risk of a prebuilt Go binary on the host seems low (they don’t even link to libc do they?)

**Pull request merged**
