### PR TITLE
[RV_DM]rv_dm_ROM_read_access_vseq

### PR DESCRIPTION
**Pull request by BasitMehmood**
This is draft Pull request for review the sequence. I want to read contents of ROM but error i got that" Offset 'h800 exceeds size of memory, 'h200".Even offset is valid and in range. @jdonjdon can you review it?

### CODE REVIEW

**Comment by jdonjdon** [comment]
@BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up.
Back to your question, you don't need 0x800 to your offset.
`.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800.
Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.

**Comment by BasitMehmood** [comment]
> @BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up. Back to your question, you don't need 0x800 to your offset. `.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800. Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.

> @BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up. Back to your question, you don't need 0x800 to your offset. `.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800. Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.

i have given other offsets as well but it says "Access unexpected address->scoreboard line 303". I think in scoreboard  there is check for valid csr access but i am reading ROM and there is no check for rom in scoreboard.

**Comment by jdonjdon** [comment]
> > @BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up. Back to your question, you don't need 0x800 to your offset. `.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800. Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.
> 
> > @BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up. Back to your question, you don't need 0x800 to your offset. `.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800. Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.
> 
> i have given other offsets as well but it says "Access unexpected address->scoreboard line 303". I think in scoreboard there is check for valid csr access but i am reading ROM and there is no check for rom in scoreboard.

Look like this scoreboard only takes csr address. You can filter out your memory address by adding 

`if (is_mem_addr(item, ral_name)) return; `  at line  299 in the scoreboad.

**Comment by BasitMehmood** [comment]
> > > @BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up. Back to your question, you don't need 0x800 to your offset. `.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800. Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.
> > 
> > 
> > > @BasitMehmood, first of all this PR has some compile errors. You might want to rebase and clean up. Back to your question, you don't need 0x800 to your offset. `.ptr(tl_mem_ral.rom)` is equivalent to 0x800 here. So your offset should be distance from 0x800. Check out the wave `tb.dut.u_dm_top.i_dm_mem.gen_rom_snd_scratch.i_debug_rom` see how your offset and your read data are related.
> > 
> > 
> > i have given other offsets as well but it says "Access unexpected address->scoreboard line 303". I think in scoreboard there is check for valid csr access but i am reading ROM and there is no check for rom in scoreboard.
> 
> Look like this scoreboard only takes csr address. You can filter out your memory address by adding
> 
> `if (is_mem_addr(item, ral_name)) return; ` at line 299 in the scoreboad.

Now it is passing . i have made changes in vseq and scoreboard. Just to add checks to vseq to finalize it and made PR with testplan entry.

**Pull request closed without merging**
