### PR TITLE
[doc/otbn] Documented instruction count feature.

### PR DESCRIPTION
**Pull request by vrozic**
Signed-off-by: Vladimir Rozic <vrozic@lowrisc.org>

### CODE REVIEW

**Review by imphil — COMMENTED** [review]
Thanks for your documentation update, @vrozic! 

The section this content appears in is a high-level overview section. For example, the Data Integrity Protection section below describes in 5 sentences a rather complex topic.

To keep it that way, let's keep the instruction counter description at a single line or so and place it below the data integrity protection section (it's clearly less important).

You can then add the longer text you have right now in the design details section further down.

Further comments:

* Editorial: One sentence per line, please.
* Link to the relevant register using {{< regref "INSN_CNT" >}}
* Avoid duplicating information; things which are already in the register reference shouldn't appear again at the same level of detail in the design details section.

**Comment by vrozic** [comment]
There's not much to say about the instruction counter without repeating the information that is already in the register reference. For now, For now, I've added the subsection "Instruction Counter". 
Perhaps, we should have a subsection "Countermeasures Against Fault Attacks", which would contain Instruction Counter description and everything else we do to prevent FA?

**Review by imphil — APPROVED** [review]
LGTM, thanks!

**Comment by imphil** [comment]
Let's keep it that simple for now and group things together as we add more content.

**Pull request merged**
