### PR TITLE
[ci] Move code for quick lint job into bash scripts

### PR DESCRIPTION
**Pull request by rswarbrick**
This shouldn't cause any changes to behaviour, but I have done a bit
of cleaning up (using the magic pathspec arguments to git diff to
simplify some things, and avoiding creating files in $PWD, to make
this nicer to run locally).

The idea is that a developer can now run

    ci/jobs/quick-lint.sh

to get roughly the same tests as are run by the quick lint step for a
pull request in CI.

@tjaychen: This PR conflicts with your #5004. I'll rebase it on top of that when that's merged.

### CODE REVIEW

**Review by mcy — APPROVED** [review]
Very nice. =)

**Review by imphil — APPROVED** [review]
Thanks!

**Comment by tjaychen** [comment]
> This shouldn't cause any changes to behaviour, but I have done a bit
> of cleaning up (using the magic pathspec arguments to git diff to
> simplify some things, and avoiding creating files in $PWD, to make
> this nicer to run locally).
> 
> The idea is that a developer can now run
> 
> ```
> ci/jobs/quick-lint.sh
> ```
> 
> to get roughly the same tests as are run by the quick lint step for a
> pull request in CI.
> 
> @tjaychen: This PR conflicts with your #5004. I'll rebase it on top of that when that's merged.

thanks @rswarbrick !

**Comment by msfschaffner** [comment]
Nice!

**Pull request merged**
