### PR TITLE
[manuf] Clean up runfile path handling in orchestrator

### PR DESCRIPTION
**Pull request by nmoroze**
This PR updates the provisioning orchestrator to use the `runfiles` library from rules_python to resolve paths to Bazel runfiles. This simplifies the instructions for running the packaged orchestrator. The previous instructions had a few small issues that caused some trouble.

Some hackery was required to preserve the scheme used previously for referring to the main repo vs external repos. We could remove this logic if openocd was the only external reference, but I have a hunch this may be required for supporting provisioning extensions.

### CODE REVIEW

**Review by moidx — APPROVED** [review]
Nice change @nmoroze!

I think you still have to update some unittests, but otherwise LGTM.

**Comment by nmoroze** [comment]
Thanks! I think those tests were previously failing, I've rebased now that #25502 is in and they should get cleaned up.

**Review by milesdai — APPROVED** [review]

**Review by timothytrippel — APPROVED** [review]

**Review by milesdai — APPROVED** [review]
LGTM!

**Comment by timothytrippel** [comment]
@nmoroze can you rebase this on latest `earlgrey_1.0.0`?

**Comment by nmoroze** [comment]
@timothytrippel done! Rebased and this is passing tests.

**Pull request merged**
