### PR TITLE
[otbn] Add support for the "la" (load absolute address) pseudo-instruction

### LINKED ISSUE #6185: [otbn,tooling] Teach otbn-as about relocations
Add support for passing through the various `%foo(...)` RISC-V assembler modifiers (as defined in the GNU As manual). This will only work for instructions that we can generate as `.insn` lines, but that should be enough for anything that cares about addresses.

Then add an `la` pseudo-instruction, matching what RISC-V does (but we can cheat and depend on our small address space to avoid needing the AUIPC).

> estimate 8

### PR DESCRIPTION
**Pull request by rswarbrick**
See commit messages for more detail. Fixes #6185.

### CODE REVIEW

**Comment by felixmiller** [comment]
Thanks a lot @rswarbrick for picking this up so quickly!
It works flawlessly with the test routines and the P-384 lib.

I noticed though that there is an issues with symbols beyond a 2k boundary. I think those should still be in the supported range, right?

Looking at a minimal example:
```
.section .text
la x2, foo
li x3, 2048
ecall

.section .data
.org 2048
foo:
.word 0x0
```
Both `x2` and `x3` should have 2048 loaded, however the `la` instruction seems to omit the `lui` somehow. I think we came across a similar issue back when we were implementing the `li` pseudo instruction.

```
00000000 | addi           x2, x0, -2048                  | [x02 = 0xfffff800]
00000004 | lui            x3, 1                          | [x03 = 0x00001000]
00000008 | addi           x3, x3, -2048                  | [x03 = 0x00000800]
0000000c | ecall                                         | [otbn.INTR_STATE |= 0x00000001 (from HW) (now 0x00000001), otbn.STATUS &= ~ 0x00000001 (from HW) (now 0x00000000), otbn.ERR_BITS = 0x00000000 (from HW) (now 0x00000000)]
 x0  = 0x00000000
 x1  = 0x00000000
 x2  = 0xfffff800
 x3  = 0x00000800

```

**Comment by rswarbrick** [comment]
Oh drat. I got the ranges wrong! I'll update `la` to do a 2-instruction sequence instead.

**Comment by rswarbrick** [comment]
Right, this should work now. Thanks, @felixmiller, for the testcase (which is now in the test directory, to make sure it keeps working).

**Comment by felixmiller** [comment]
Thanks @rswarbrick! One last question: Is it correct to assume that `la` will always have to expand to two instructions because the final value to be loaded is only known after linking?

If I change the example from above, now to load a constant of 1024 instead (both the address and the immediate for reference) I get the following, where `li` expands to a single and `la` to two instructions.
```
00000000 | lui            x2, 0                          | [x02 = 0x00000000]
00000004 | addi           x2, x2, 1024                   | [x02 = 0x00000400]
00000008 | addi           x3, x0, 1024                   | [x03 = 0x00000400]
```

**Comment by rswarbrick** [comment]
Yep, that's right. I don't think you can do better without linker relaxation (out of scope for OTBN!). Of course, if you've got a block of data, there's nothing to stop you putting the address of the first item into the register and then using immediate offsets to address the rest. Sadly, I don't think we can easily add tool support for that.

**Review by felixmiller — APPROVED** [review]

**Comment by felixmiller** [comment]
Thanks! Not a big deal actually, we use the `la` instruction actually only in the external callable wrappers and keep the addresses in regs from there on. Was just curious.

**Comment by rswarbrick** [comment]
Merging despite the broken Docker build: this is unrelated (and there's a PR in progress to fix it).

**Pull request merged**
