### PR TITLE
[ast/sensor_ctrl] Turn ast_init_done_o to Mubi and remove flash/otp alerts from AST

### PR DESCRIPTION
**Pull request by Jacob-Levy**
This PR replaces PR "[ast/sensor_ctrl] Remove unused OTP/Flash alert signals https://github.com/lowRISC/opentitan/pull/14721"

* Turn ast_init_done_o to Mubi, and 
* Remove flash/otp alerts from AST

@tjaychen @msfschaffner  @arnonsha @zi-v 

Signed-off-by: Jacob Levy <jacob.levy@nuvoton.com>

### CODE REVIEW

**Comment by Jacob-Levy** [comment]
This PR replaces PR "[ast/sensor_ctrl] Remove unused OTP/Flash alert signals #14721"

**Comment by tjaychen** [comment]
assigning myself to make sure I review.

**Comment by msfschaffner** [comment]
I will take a look at the alerts part also today.

**Comment by tjaychen** [comment]
this lgtm, i'll merge it now and make the `sensor_ctrl` changes.

**Review by tjaychen — APPROVED** [review]

**Comment by msfschaffner** [comment]
Thanks for making the changes, @Jacob-Levy. LGTM, too!

**Pull request merged**
