### PR TITLE
[rtl] Change instance name of reg module to u_reg

### PR DESCRIPTION
**Pull request by weicaiyang**
Apply this change to all IPs for backdoor access support.
Refer to #2406 for detail

Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
thanks for doing this @weicaiyang !

@msfschaffner @eunchan 
quick question to you guys...this is something i keep on getting confuse... does our style mandate which prefix we're supposed to use in general? is it `u_` or `i_`? Because i know when i first started on the project i saw a lot of the former, but now im' seeing lots of the latter.  Does this seem like something that should be standardized?

**Comment by sriyerg** [comment]
> Apply this change to all IPs for backdoor access support.
> Refer to #2406 for detail
> 
> Signed-off-by: Weicai Yang [weicai@google.com](mailto:weicai@google.com)

Thanks for doing this! Need this to also limit the scope of coverage for the CSR tests.

**Comment by msfschaffner** [comment]
> thanks for doing this @weicaiyang !
> 
> @msfschaffner @eunchan
> quick question to you guys...this is something i keep on getting confuse... does our style mandate which prefix we're supposed to use in general? is it `u_` or `i_`? Because i know when i first started on the project i saw a lot of the former, but now im' seeing lots of the latter. Does this seem like something that should be standardized?

Indeed, I have been thinking the same thing for some time. I am using mostly `i_` to reflect that this is an  **i**nstance, but if we think that this looks too much like the `_i` signal postfixes, I am fine with standardizing on `u_` as well. Would this be something we want to add to our style guide?

**Comment by tjaychen** [comment]
IMO yes. Should we ask to bring it up in the silicon meeting?
I personally don't really care which way we go as long it's consistent.

**Comment by sriyerg** [comment]
> thanks for doing this @weicaiyang !
> 
> @msfschaffner @eunchan
> quick question to you guys...this is something i keep on getting confuse... does our style mandate which prefix we're supposed to use in general? is it `u_` or `i_`? Because i know when i first started on the project i saw a lot of the former, but now im' seeing lots of the latter. Does this seem like something that should be standardized?

I wonder what value does having the prefix add? 

> > thanks for doing this @weicaiyang !
> > @msfschaffner @eunchan
> > quick question to you guys...this is something i keep on getting confuse... does our style mandate which prefix we're supposed to use in general? is it `u_` or `i_`? Because i know when i first started on the project i saw a lot of the former, but now im' seeing lots of the latter. Does this seem like something that should be standardized?
> 
> Indeed, I have been thinking the same thing for some time. I am using mostly `i_` to reflect that this is an **i**nstance, but if we think that this looks too much like the `_i` signal postfixes, I am fine with standardizing on `u_` as well. Would this be something we want to add to our style guide?

What value does the having the prefix bring in? (There probably is a reasoning to have it, I am not sure what it is). Modules instantiated in `top_earlgrey_asic` for instance, do not have a prefix, and that seems perfectly fine to me.

**Comment by mwbranstad** [comment]
To be clear on the part about better debug: using the @sriyerg example, i was suggesting using the format of "foo u_foo_bar", which then in the sim tool hierarchy viewer shows both the module name and the usage. For signals, It gets somewhat longer for full hierarchy view mode for signals, but that is generally the exception case for most users.

**Comment by weicaiyang** [comment]
Thanks for all the inputs. Looks like most people prefers to use `u_`. I will make the change in this PR and merge it for enabling the backdoor test

We can continue to discuss if we should change the other instance name and the format.

**Comment by weicaiyang** [comment]
@tjaychen @eunchan 

CI failed with these errors. Is the vivado bitstream pre-built so that I can't just change the instance name?

> Bitstream generation completed
> ERROR: Implementation and bitstream generation step failed.
> INFO: [Common 17-206] Exiting Vivado at Fri Jun 12 18:28:51 2020...
> Makefile:8: recipe for target 'lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit' failed
> make: *** [lowrisc_systems_top_earlgrey_nexysvideo_0.1.bit] Error 1
> ERROR: Failed to build lowrisc:systems:top_earlgrey_nexysvideo:0.1 : 'make' exited with an error code

**Comment by tjaychen** [comment]
o boy the timing just failed in yours (by 36ps). 
It has nothing to do with what you did probably... just a random thing.

Could you try running CI again and see if it goes away?
You'd need to open up vivado to get the failing path, since our flow doesn't generate the failing report if it fails (i feel like we should fix that). 

@imphil 
@tomroberts-lowrisc

**Comment by cdgori** [comment]
> The prevailing form that I have seen in the industry is u_, for unit I suppose. 

I always thought the u (or U) convention for instance names came from schematic reference designators (U is used for ICs): https://en.wikipedia.org/wiki/Reference_designator
But perhaps I have back-inferred something that's not really true.

**Comment by weicaiyang** [comment]
> o boy the timing just failed in yours (by 36ps).
> It has nothing to do with what you did probably... just a random thing.
> 
> Could you try running CI again and see if it goes away?
> You'd need to open up vivado to get the failing path, since our flow doesn't generate the failing report if it fails (i feel like we should fix that).
> 
> @imphil
> @tomroberts-lowrisc

@tjaychen it doesn't go away after rerun.

**Comment by weicaiyang** [comment]
@imphil @tjaychen 
any thought on the CI failure?

**Comment by imphil** [comment]
@weicaiyang The FPGA build was close to failing timing, you were just unlucky it seems. Let's try again now that timing failures are ignored (since #2508)

**Comment by weicaiyang** [comment]
> @weicaiyang The FPGA build was close to failing timing, you were just unlucky it seems. Let's try again now that timing failures are ignored (since #2508)

Thanks @imphil. CI is passing now.

**Pull request merged**
