### PR TITLE
[spi_host, doc] control.sw_rst clarification

### PR DESCRIPTION
**Pull request by antmarzam**

### CODE REVIEW

**Review by rswarbrick — COMMENTED** [review]
This looks reasonable, but you'll actually have to make the change in `spi_host.hjson` and then update this file with `make -C hw`.

**Comment by antmarzam** [comment]
> This looks reasonable, but you'll actually have to make the change in `spi_host.hjson` and then update this file with `make -C hw`.
@rswarbrick 
I did what you suggested, but that wasn't generating a `registers.md` file. 
Do I need to add more flags to the make command?

Will drop the first commit once this is ready to merge.

**Comment by rswarbrick** [comment]
I think you've done it! :-) You can see the diff by hitting this button:
image

Otherwise, I'm very happy with this. Will ping a second committer to allow the change (because it touches a file where some changes should be blocked)

**Review by rswarbrick — APPROVED** [review]

**Comment by rswarbrick** [comment]
CHANGE AUTHORIZED: hw/ip/spi_host/data/spi_host.hjson

**Comment by hcallahan-lowrisc** [comment]
CHANGE AUTHORIZED: hw/ip/spi_host/data/spi_host.hjson

**Pull request merged**
