### PR TITLE
[csrng] Make reseed counters always readable, allow locking down internal state access per instance

### PR DESCRIPTION
**Pull request by vogelpi**
As discussed here: https://github.com/lowRISC/opentitan/issues/21141#issuecomment-2082289550

### CODE REVIEW

**Review by moidx — APPROVED** [review]

**Comment by moidx** [comment]
Thanks @vogelpi. This LGTM.

**Comment by vogelpi** [comment]
Thanks for your review @moidx . As discussed in the triage meeting yesterday it would be better to allow locking the read enable settings until the next reset in ROM_EXT . I've now modified the PR accordingly.

**Review by moidx — APPROVED** [review]
Thanks for adding the `REGWEN` changes. This LGTM.

**Comment by vogelpi** [comment]
All tests except for `spi_passthru_test_fpga_cw310_rom_with_fake_keys` which also fails for other unrelated PRs. I am merging this.

**Pull request merged**
