### PR TITLE
[fpga] Optimize AES placement to speed up place and route on CW310

### PR DESCRIPTION
**Pull request by vogelpi**
This placement constraint can have a notable impact on the time needed for place and route and thus overall FPGA implementation time. The now chosen location should improve place and route times by roughly 10-20%.

### CODE REVIEW

**Comment by vogelpi** [comment]
For reference, I tested the most suitable locations based on previous results and got the following:
```
X0Y4 <- previous location
  place_design: Time (s): cpu = 00:20:30 ; elapsed = 00:10:17 . Memory (MB): peak = 6517.738 ; gain = 0.000 ; free physical = 42968 ; free virtual = 121264
  route_design: Time (s): cpu = 00:21:53 ; elapsed = 00:09:17 . Memory (MB): peak = 6517.738 ; gain = 0.000 ; free physical = 41926 ; free virtual = 120666
X0Y2 <- new location
  place_design: Time (s): cpu = 00:19:23 ; elapsed = 00:09:25 . Memory (MB): peak = 6517.176 ; gain = 0.000 ; free physical = 43192 ; free virtual = 122676
  route_design: Time (s): cpu = 00:17:12 ; elapsed = 00:07:20 . Memory (MB): peak = 6517.176 ; gain = 0.000 ; free physical = 42294 ; free virtual = 122044
X1Y6
  place_design: Time (s): cpu = 00:23:00 ; elapsed = 00:10:08 . Memory (MB): peak = 6509.629 ; gain = 0.000 ; free physical = 42377 ; free virtual = 122607
  route_design: Time (s): cpu = 00:17:53 ; elapsed = 00:07:52 . Memory (MB): peak = 6509.629 ; gain = 0.000 ; free physical = 42512 ; free virtual = 123009
X1Y5
  place_design: Time (s): cpu = 00:22:54 ; elapsed = 00:10:09 . Memory (MB): peak = 6524.844 ; gain = 0.000 ; free physical = 42675 ; free virtual = 123614
  route_design: Time (s): cpu = 00:18:54 ; elapsed = 00:08:23 . Memory (MB): peak = 6524.844 ; gain = 0.000 ; free physical = 41740 ; free virtual = 122946 
```

**Review by GregAC — APPROVED** [review]
(Approved assuming we see improvement in CI run-time for the FPGA build)

**Review by andreaskurth — APPROVED** [review]
Thanks @vogelpi. And agree with @GregAC's comment.

**Comment by vogelpi** [comment]
Thanks for approving this @andreaskurth and @GregAC . This seems to help quite a lot indeed. The Bitstream build step now takes roughly 2h10min, previously timed out after 3 hours. I'll merge this once CI finishes.

**Pull request merged**
