### PR TITLE
[doc] Add troubleshooting note to FPGA user guide.

### PR DESCRIPTION
**Pull request by jadephilipoom**
This fixed an issue I was having getting the FPGA board set up, and it seems like a good idea to document it.

Thanks to @moidx for suggesting the fix!

### CODE REVIEW

**Review by rswarbrick — COMMENTED** [review]
We've had at least one issue raised by an outside contributor complaining about exactly this message. I wonder whether this is related to https://github.com/lowRISC/opentitan/issues/9200.

**Comment by jadephilipoom** [comment]
> We've had at least one issue raised by an outside contributor complaining about exactly this message. I wonder whether this is related to #9200.

The message there does look exactly like the one I got, so possibly yes!

**Comment by moidx** [comment]
CC @colinoflynn

**Review by moidx — APPROVED** [review]

**Comment by colinoflynn** [comment]
We had been toggling the PLL still sometimes, the `USB RST` would reinitialize everything. In theory this could be done quasi-automatically too if required in the future.

If there is a consistent requirement to hit the `USB RST` button maybe open an issue on https://github.com/newaetech/cw310-bergen-board/issues too so it's tracked somewhere more specific to that board!

**Pull request merged**
