### PR TITLE
[sparse-fsm-encode] Expand error and help messages

### PR DESCRIPTION
**Pull request by msfschaffner**
Added some more error and help messages for user guidance.
Also, the script disallows all-zero and all-one encodings now.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Output of help message:
```
usage: ./sparse-fsm-encode -m <#states> -n <#bits> -d <minimum HD> -s <seed>

This script generates sparse FSM encodings that fulfill a minimum
Hamming distance requirement. It uses a heuristic that
opportunistically draws random state encodings and checks whether they
fulfill the requirements.

Depending on the parameterization, the script may not find a solution
right right away. In such cases, either rerun the script and/or adjust
the d/m/n parameters. E.g. make the state space more sparse by
increasing n, or lower the minimum Hamming distance threshold d.

Note that the Hamming distance d should be set to 3 minimum. It is
recommended to set this value to 4-5.

The custom seed s can be used to make subsequent runs of the script
deterministic. The script randomly picks a seed, if not specified.

optional arguments:
  -h, --help  show this help message and exit
  -d D        Minimum Hamming distance between encoded states.
  -m M        Number of states to encode.
  -n N        Encoding length [bit].
  -s S        Custom seed for RNG.

```


Output with default parameterization:
```systemverilog
-------------------------------------------------------
 COPY PASTE THE CODE TEMPLATE BELOW INTO THE RTL
 IMPLEMENTATION, INLUDING THE COMMENT AND THE
 PRIM_FLOP TO EASE AUDITABILITY AND REPRODUCIBILITY.
-------------------------------------------------------

// Encoding generated with ./sparse-fsm-encode.py -d 5 -m 7 -n 10 -s 4000245082
// Hamming distance histogram:
//
// 0: --
// 1: --
// 2: --
// 3: --
// 4: --
// 5: |||||||||||||||||||| (42.86%)
// 6: |||||||||||||||||||| (42.86%)
// 7: |||||| (14.29%)
// 8: --
// 9: --
// 10: --
//
// Minimum Hamming distance: 5
// Maximum Hamming distance: 7
//
localparam int StateWidth = 10;
typedef enum logic [StateWidth-1:0] {
  State0 = 10'b1111110111,
  State1 = 10'b0101111100,
  State2 = 10'b0100100001,
  State3 = 10'b0010001111,
  State4 = 10'b1010111000,
  State5 = 10'b0011000000,
  State6 = 10'b1101001011
} state_e;

state_e state_d, state_q;
always_comb begin : p_fsm
  // Default assignments
  state_d = state_q;

  unique case (state_q)
    State0: ;
    State1: ;
    State2: ;
    State3: ;
    State4: ;
    State5: ;
    State6: ;
    default: ; // Consider triggering an error or alert in this case.
  endcase
end

// This primitive is used to place a size-only constraint on the
// flops in order to prevent FSM state encoding optimizations.
prim_flop #(
  .Width(StateWidth),
  .ResetValue(StateWidth'(State0))
) u_state_regs (
  .clk_i,
  .rst_ni,
  .d_i ( state_d ),
  .q_o ( state_q )
);

```

**Comment by msfschaffner** [comment]
@cdgori can you think of any other specific error message or user guidance that we should add to the script output?

**Review by lenary — APPROVED** [review]
LGTM. This does seem to get rid of (or explain away) some of the sharper edges of the tool.

**Comment by msfschaffner** [comment]
I''ll merge this such that @lenary can make progress. We can amend things later if needed.

**Comment by cdgori** [comment]
> @cdgori can you think of any other specific error message or user guidance that we should add to the script output?

Sorry for late reply but I think this is very good now, nothing comes to mind.

**Pull request merged**
