### PR TITLE
[prim_ram_2p] Add write mask

### PR DESCRIPTION
**Pull request by imphil**
Copy the write mask logic from the single port RAM.

### CODE REVIEW

**Comment by imphil** [comment]
Ah, this requires more changes to the adv wrapper. I'll have a look later today.

**Comment by eunchan** [comment]
Maybe it is worth to make separate module or make bitmask totally turning off-able is nice to have as we eventually have SRAM with/without bitmask.

**Comment by imphil** [comment]
I think we can keep a single prim_ram_2p, and provide optimizations like "use a SRAM macro without or with reduced write mask support" inside the actual implementation of prim_ram_2p for a specific technology. All necessary information to make this optimization is available.

For example, to build a 2p RAM implementation (e.g. prim_myasictech_ram2p), which doesn't support write masks at all, simply assert that `DataBitsPerMask == Width`. If you have a SRAM macro which only supports byte enables (and not bit enables), then you can do `DataBitsPerMask == 8`. Or don't assert, but use a generate block to target different macros depending on that setting.

By staying with one single interface, we can easily make such optimizations at any time without changing the wider system.

**Comment by imphil** [comment]
@eunchan would you mind having another look?

**Pull request merged**
