### PR TITLE
[rv_dm V1] Certify V1 milestone for RV_DM

### PR DESCRIPTION
**Pull request by sriyerg**
This commit updates the RV_DM V1 checklist to show all V1 tasks are
complete, and advances the block from V0 to V1.

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

### CODE REVIEW

**Comment by sriyerg** [comment]
This PR depends on #11623 and #11654 which add the smoke test and update the testplan respectively.

**Comment by sriyerg** [comment]
> This PR depends on #11623 and #11654 which add the smoke test and update the testplan respectively.

Both of these are now merged.

**Review by weicaiyang — APPROVED** [review]
LGTM

**Review by cindychip — APPROVED** [review]
LGTM! Congrats!

**Review by tjaychen — APPROVED** [review]

**Pull request merged**
