### PR TITLE
[tlul] Adapter reg fix

### PR DESCRIPTION
**Pull request by tjaychen**
This PR qualifies `reg_we` and `reg_re` with `reg_error`.  This ensures that on any type of error (including integrity error), a transaction cannot happen. 

Please see #5434

### CODE REVIEW

**Comment by tjaychen** [comment]
ah this one doesn't work as is. 

Turns out... reg_we -> wr_err
So i cannot also use wr_err to qualify the generation of reg_we.  I'll fix this differently.

**Review by vogelpi — APPROVED** [review]
Thanks @tjaychen this looks good!

It's good to also gate the read enable signal in case of integrity errors. Because some modules use the (delayed) read enable for internal status tracking.

**Comment by tjaychen** [comment]
thanks for the review! I'll wait on merging this in until the earlier commits are merged

**Review by cindychip — APPROVED** [review]
The assertion passed, thanks Tim for the quick fix.

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks for the fix

**Comment by tjaychen** [comment]
actually the other PR might take longer during reviews. I'll split out the dependencies and try to get this one merged.
Thanks for the patience everyone.

**Pull request merged**
