### PR TITLE
[chip,dv] Fix compilation for private CI

### PR DESCRIPTION
**Pull request by rswarbrick**
This code come from PR 9740 (commit c1cf4a8), which needed updating
for commit 28b1ab1451, merged in the meantime.

### CODE REVIEW

**Review by GregAC — APPROVED** [review]

**Comment by senelson7** [comment]
This is affecting everybody. How does an error like this even get through?

**Comment by rswarbrick** [comment]
@senelson7: Please read the commit message. The problem is that we don't check PRs after rebase and before merge. Systems like [Bors](https://bors.tech/) do that, but imply significantly more CI runtime. At the moment, at least, the OpenTitan project accepts the occasional breakage to avoid that cost.

**Comment by senelson7** [comment]
@rswarbrick @rasmus-madsen @mwbranstad Hey Rupert, I don't mean to be a pain but we're implementing CI on our WDC-internal project and I just want to learn/understand. I did read the commit message and I kind of get it but still don't really understand how a compile error ever got through and didn't show up the first time somebody tried to get this in. I don't want to waste everybody's time so we can either take it offline or I can go read/learn more about CI on my own.

**Comment by rswarbrick** [comment]
What we saw is what the Bors team call "merge skew". They have the following example linked on their homepage which shows what's going on: https://bors.tech/essay/2017/02/02/pitch/.

**Pull request merged**
