### PR TITLE
[ spi_host ] Remove cmd_len_q register to clean up DC logs

### PR DESCRIPTION
**Pull request by martin-lueker**
Cleans up a problem discussed in a similar PR #6326 

The `spi_host` register `cmd_len_q` is never used and gets optimized away at synthesis. This commit explicitly
removes that register (and comments the code as such) to clean up the logs.

Signed-off-by: Martin Lueker-Boden <martin.lueker-boden@wdc.com>

### CODE REVIEW

**Comment by martin-lueker** [comment]
Thanks @tjaychen for explaining the origin of this message!

**Review by tjaychen — APPROVED** [review]
thanks for fixing @martin-lueker !

**Comment by mateenfaisal** [comment]
@martin-lueker, do linting (Ascentlint,...) tools catch this issue?

**Comment by rswarbrick** [comment]
@mateenfaisal: I don't think any existing lint tools would catch this. To see that `cmd_len_q` is unused, the tool would need to trace dependencies to see that `cmd_len` is only used to compute `byte_cntr_d` and that only happens when `command_valid_i && command_ready_o`: a signal which is also called `new_command`.

@martin-lueker: If we're touching this code anyway, maybe it would make sense to replace that expression with `new_command` in the definitions of `clk_cntr_d` and `byte_cntr_d`?

**Comment by martin-lueker** [comment]
Merging with @rswarbrick's recommended change.

**Pull request merged**
