### PR TITLE
Minor lint fixes in OTBN DV code

### PR DESCRIPTION
**Pull request by rswarbrick**
These are all minor tweaks that silence Xcelium warnings when building OTBN DV code. There's nothing that will change behaviour, but it makes it a bit easier to read through a compilation log when something else has gone wrong.

### CODE REVIEW

**Comment by rswarbrick** [comment]
Hmm, it looks like Verible doesn't like my "eh, let's explicitly ignore the results" change :-D I'll push again in a bit with something more sensible.

**Comment by rswarbrick** [comment]
Right, this should be more sensible.

I spent a load of time trying to factor things out with macros... which was not very successful! It turns out that SystemVerilog's support for string literals in macros is not particularly helpful (and I think some of our other macros like DV_CHECK_FATAL would need tweaking to make that work). Boo! Anyway, this version is the "simple, obvious" approach that should work, at least.

**Review by marnovandermaas — APPROVED** [review]
These changes look good to me. Are any of these added UVM fatal errors triggered during our DV?

**Comment by rswarbrick** [comment]
I don't think the fatal errors actually get triggered in our DV: I got lots of passing tests in a "ci" run yesterday, with none of the errors. Well done, us! :-D

**Pull request merged**
