### PR TITLE
[i2c, rtl] Lint Fixes

### PR DESCRIPTION
**Pull request by igk8**
Fixes to Ascent and Verilator errors and warnings

Signed-off-by: Igor Kouznetsov <igor.kouznetsov@wdc.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
@igk8 it looks like you also have to update the DIF unit tests in `sw/device/lib/dif/dif_i2c_unittest.cc`.
The error message is:
```
[----------] 6 tests from OverrideTest (0 ms total)

[----------] 6 tests from FifoTest
[ RUN      ] FifoTest.GetLevels
../../s/sw/device/lib/dif/dif_i2c_unittest.cc:553: Failure
Expected equality of these values:
  rx
    Which is: 'G' (71, 0x47)
  0x7
    Which is: 7
../../s/sw/device/lib/dif/dif_i2c_unittest.cc:565: Failure
Expected equality of these values:
  rx
    Which is: 'G' (71, 0x47)
  0x7
    Which is: 7
```

You can run
```
./meson_init.sh
ninja -C build-out test
```
to reproduce this error locally.

**Review by martin-lueker — APPROVED** [review]
LGTM.  Thanks @igk8.

**Review by tunghoang290780 — APPROVED** [review]
LGTM, @martin-lueker @msfschaffner Could you merge this into the upstream? I would like to debug the csr_* test with the latest RTL code which currently causes the CI tests failed

**Comment by martin-lueker** [comment]
Hi Tung, 
   I think we need to massage the CI checks a bit first.   My guess is that if Igor runs ninja (as described above) that will point out the issues.   @igk8, I think if you the load proj/opentitan module that should give you all the support you need to run the testsuite.

**Comment by tunghoang290780** [comment]
@igk8 I think you can force push this PR to restart CI check

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
Thanks!

**Comment by martin-lueker** [comment]
Excellent!

**Pull request merged**
