### PR TITLE
Small refactor of util/autogen_md.py, bikeshed on the name

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**
I'm trying to write some documentation for this, and was looking at the code so took the opportunity to do a small refactor, mostly adding docstrings.

---

However I do want to have a brief bikeshed on the name before it is more formally documented.
I think AUTOGEN is too-generic, we already have `ip_autogen` in the repo for ip that is rendered by topgen/ipGen, so I think we could have a more-specific name for this. Thoughts?

I would vote for DOCGEN, but are there any other ideas?

@HU90m @pamaury @jwnrt @timothytrippel @andreaskurth

### CODE REVIEW

**Comment by HU90m** [comment]
That's a good point, `DOCGEN` sounds good

**Review by jwnrt — APPROVED** [review]
I can't comment on the Python, but the docs and code look clearer, great work

**Comment by jwnrt** [comment]
I agree `DOCGEN` is better than `AUTOGEN`

**Comment by pamaury** [comment]
I think docgen is a good name and it's a good idea to avoid overloading the term autogen.

**Comment by pamaury** [comment]
With the new commit it's harder to see the diff between autogen_md.py and docgen_md.py but when I looked at the diff previously it looked good to me.

**Pull request merged**
