### PR TITLE
[clkmgr] Allow software to control clock stepdown

### LINKED ISSUE #8027: [clkmgr change proposal] Update external clock selection logic
For manufacturing flexibility, we need to add more flexibility on how to select external clocks. 
Right now the step down and selection is driven largely automatically by hardware, but we would like to be able to control step down through software as well. 

See this [link](https://docs.google.com/presentation/d/1N-PBsD5dkEnHZCG5p0DEsTy6UcGgfqGZXzQSixDBWmM/edit?usp=sharing) (limited visibility and not open to public) for more details.

### PR DESCRIPTION
**Pull request by tjaychen**
- Fixes #8027

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
This PR needs an associated documentation update.

**Comment by zi-v** [comment]
Thanks Tim. LGTM.

**Review by matutem — APPROVED** [review]
I need to update the clkmgr testplan for this, the frequency counters, and moving more stuff to SVA

LGTM

**Comment by tjaychen** [comment]
> I need to update the clkmgr testplan for this, the frequency counters, and moving more stuff to SVA
> 
> LGTM

let me know if you want me to file an issue.

**Pull request merged**
