### PR TITLE
[sw/silicon_creator] Harden OTBN error codes in mask ROM.

### PR DESCRIPTION
**Pull request by jadephilipoom**
Change the error enum for OTBN routines to use an encoding with higher Hamming distance.

### CODE REVIEW

**Review by alphan — APPROVED** [review]

**Review by mcy — APPROVED** [review]
@moidx Do we want u32 or u12 error codes (so we can cram them into immediates)?

**Comment by moidx** [comment]
> > @moidx Do we want u32 or u12 error codes (so we can cram them into immediates)?
> 
> `kErrorOk` is 11 bits but rest of the error codes in `error.h` are not.

`kErrorOk = kHardenedBoolTrue`, and we have an unittest to make sure the hamming distance of the error codes `HD(kErrorOk, error) > 4`.  I think in most cases we check the condition `a != kErrorOk`, so it may be worth to keep the OK value consistent (u12).

**Comment by jadephilipoom** [comment]
Okay, sounds like it makes sense to change `kOtbnErrorOk` to match `kErrorOk` and add a hamming distance unittest, to keep everything consistent.

**Comment by alphan** [comment]
> How does it sound if I close this PR, accelerate the HMAC/OTBN driver work (e.g. #9764) so I can actually move the cryptolib code and break this silly dependency, then change this driver to use `rom_error_t`?

SGTM

**Pull request closed without merging**
