### PR TITLE
Uart status interrupts

### PR DESCRIPTION
**Pull request by GregAC**
This includes a commit from https://github.com/lowRISC/opentitan/pull/21226 which is a cip_lib change required for all status type interrupts. So need to ensure one of the PRs gets rebased if the other has gone in.

### CODE REVIEW

**Comment by msfschaffner** [comment]
Thanks @GregAC - maybe it makes sense to split out the CIP fixes into a separate PR since those will benefit others as well.
I believe we need to introduce a similar masking in the generated "all interrupts" TLT.
Sorry that I did not get to this yet, will try to look into it on Monday.

CC @andreaskurth @vogelpi @alees24

**Comment by GregAC** [comment]
Latest push addresses CI failures, will address the splitting out/merging with other work of the CIP changes separately.

This PR should not be merged until the CIP change work is addressed.

**Comment by GregAC** [comment]
I've spun out the first commit, which is a CIP fix that is useful for status interrupt in general to another PR: https://github.com/lowRISC/opentitan/pull/21804

As there's some CI issues with the CW310 tests that may take a little longer to solve it'd be good to get the CIP fix in sooner.

**Comment by GregAC** [comment]
@timothytrippel could you check out the OTTF change? (Final commit)

**Comment by timothytrippel** [comment]
> @timothytrippel could you check out the OTTF change? (Final commit)

OTTF changes LGTM.

**Review by timothytrippel — APPROVED** [review]

**Review by andreaskurth — APPROVED** [review]
DD & DV changes LGTM. Thanks @GregAC :+1:

**Pull request merged**
