### PR TITLE
[pwm,SiVal] Silicon validation tests for PWM module

### PR DESCRIPTION
**Pull request by marnovandermaas**
This is an initial go at silicon validation tests for PWM.

### CODE REVIEW

**Review by pamaury — APPROVED** [review]
This looks good to me.

**Comment by marnovandermaas** [comment]
CHANGE AUTHORIZED: hw/ip/pwm/data/pwm.hjson

**Comment by rswarbrick** [comment]
CHANGE AUTHORIZED: hw/ip/pwm/data/pwm.hjson

**Comment by marnovandermaas** [comment]
Created an issue to track the silicon validation work of the one test in here: https://github.com/lowRISC/opentitan/issues/19841

**Pull request merged**
