### PR TITLE
[site] Fix dashboards to 2023.07.19 regression (revert me)

### PR DESCRIPTION
**Pull request by hcallahan-lowrisc**
Annoyingly each block hosts its report under urls with different timestamps.

### CODE REVIEW

**Review by GregAC — APPROVED** [review]

**Review by marnovandermaas — APPROVED** [review]
Thanks for this change!

**Comment by hcallahan-lowrisc** [comment]
Force-pushed to fix lint failure

**Comment by marnovandermaas** [comment]
Lint fix looks good to me.

**Comment by GregAC** [comment]
Merging now as we want this fixed ASAP and remaining CI checks aren't relevant to the change.

**Pull request merged**
