### PR TITLE
Fix pin names of uart/gpio in artys7 toplevel

### PR DESCRIPTION
**Pull request by olofk**
Signed-off-by: Olof Kindgren <olof.kindgren@gmail.com>

### CODE REVIEW

**Comment by imphil** [comment]
Thanks Olof! Did you try the Arty example? (I have not played around with it in ages.)

**Comment by olofk** [comment]
I don't have an Arty board. Was just trying to build it to see if it worked, and potentially to use it as a base to port to Nexys A7.

**Comment by imphil** [comment]
Makes sense, thanks!

**Comment by eunchan** [comment]
Thanks @olofk !

**Pull request merged**
