### PR TITLE
[sw] Fix embedded linking not including .crt or .vectors.

### LINKED ISSUE #1058: [sw] sha256_test and rv_timer_test failing at HEAD
I broke CI some time last night, and since then two SW tests have started failing. Two SystemVerilog changes went by since I broke CI, so I suspect one of them broke it.

@tjaychen Can you take a look (or delegate to another hadware person who knows what's up?).

### PR DESCRIPTION
**Pull request by mcy**
Fixes #1058.

### CODE REVIEW

**Comment by imphil** [comment]
@mcy can you add a signed-off-by line to this one and ensure that CI succeeds?

**Comment by mcy** [comment]
Oops, accidentally hit "close".

Also, I'd really appreciate it if someone with more linker expertise can comment with a better solution: the problem I'm seeing is that, before this change, meson generates a linker call similar to
```sh
ld -o sw.elf sw.c.o \
  --no-undefined --as-needed --nostdlib
  -( /* static library dependencies as .a archives */ -)
  -rpath-link build-out/...
```
For reasons unclear to me, the linker script does not correctly pull the `.crt` section out of libcrt.a, nor the `.vector` section out of libirq.a. For now I've rearranged Meson so that the object files with the sections I care about are .o "input files", rather than .a libraries being linked in; however, I think that this solution is wrong and that there should be a way to do this just by pulling out specific sections out of the .a files.

@imphil do you have any clues (or know who someone who might)?

**Comment by imphil** [comment]
How did the linker call look with make?

**Comment by mcy** [comment]
Make emits .a files, but those do not participate in linking; it instead links in *every* .o file is builds for every binary (which is where I got my idea for this bandaid).

**Comment by imphil** [comment]
From what I remember, static libraries (*.a files) are only searched for undefined references. Object files are unconditionally used. So you either need to make sure that `_crt` is being searched for, or link the .o file. Linking crt.o is rather common, so I'd go for that. Otherwise, you can either add `EXTERN(_crt)` to the linker script, or add ` -Wl,--undefined=_crt` as linker flag.

(I did give it a try and that theory seems to be correct. It additionally runs into a problem with the `/DISCARD/ : { *(*) }` statement in our linker file preventing linking. I didn't debug that further; removing that statement does the trick for me, let me know if you get stuck and I'll have a look. The discard part was added to prevent the build id showing up in the binary, but that's something that we already prevent by `-Wl,--build-id=none`, so removing this line again shouldn't hurt.)

**Pull request merged**
