### PR TITLE
[spi_host] Correct TXFULL description

### PR DESCRIPTION
**Pull request by kupiakos**
Cc @timothytrippel

### CODE REVIEW

**Comment by kupiakos** [comment]
Looks like I need to change the HJSON register definition? Not sure where to start here

**Review by rswarbrick — COMMENTED** [review]
This is rather confusing to fix because we check in some generated code (grr!). The source for this line is actually `hw/ip/spi_host/data/spi_host.hjson` and we have a Makefile that regenerates the Markdown docs to match. The CI check is failing because the Markdown docs no longer match :-)

I'll push a fixed version in a second (getting this right is a real pain, especially because the failing part of CI in a bit that isn't visible to external contributors yet). I'll ask someone else who knows more about `spi_host` to review it technically.

**Review by hcallahan-lowrisc — APPROVED** [review]
Thanks for the fix @kupiakos :)

**Comment by hcallahan-lowrisc** [comment]
CW310 Test Failures in CI are known and unrelated to this documentation-only change. Hence merging.

**Pull request merged**
