### PR TITLE
Workaround for Icache tests from Ibex Core

### PR DESCRIPTION
**Pull request by dawidzim**
Hey!
In this pull request I changed assign on variable declaration. This is needed for run Icache tests from Ibex Core on Riviera-PRO
Signed-off-by: Dawid Zimonczyk <dawidz@aldec.com.pl>

### CODE REVIEW

**Comment by rswarbrick** [comment]
Hmm, this is odd. Was the previous code incorrect according to the SystemVerilog spec? I would have thought that this is just an example of a "Variable declaration assignment" as described in section 10.5.

**Comment by weicaiyang** [comment]
Agree with @rswarbrick
perhaps explain why the tool doesn't support it, so that we can change our coding style to avoid this.

**Comment by dawidzim** [comment]
@rswarbrick You are right, this code is allowed by LRM. Simulator have problem with assign extern function with class type to variable at declaration, that's why I separate this, to declaration and then assign to this variable

**Comment by weicaiyang** [comment]
> @rswarbrick You are right, this code is allowed by LRM. Simulator have problem with assign extern function with class type to variable at declaration, that's why I separate this, to declaration and then assign to this variable

@dawidzim do you plan to fix this issue in the tool soon? I'm OK with the current fix, but I feel we don't want to force this rule in our code guide, so we may see it later and you may need to fix it again.

**Review by sriyerg — COMMENTED** [review]
I am averse to accepting workarounds in our codebase just to get around a bug in the tool. Is it hard to fix this in the tool?

**Comment by rswarbrick** [comment]
This PR appears to have been abandoned (and we're not really open to taking workarounds for bugs in tools we don't use). Closing.

**Pull request closed without merging**
