### PR TITLE
Vendor ibex

### PR DESCRIPTION
**Pull request by GregAC**

### CODE REVIEW

**Review by nasahlpa — APPROVED** [review]
Thanks Greg, LGTM!

**Review by moidx — APPROVED** [review]

**Review by vogelpi — APPROVED** [review]
LGTM, thanks @GregAC !

**Comment by moidx** [comment]
CI failed test `spi_passthru_test_fpga_cw310_rom_with_fake_keys` has been flaky this week and not related to this change.

**Comment by moidx** [comment]
Thanks @GregAC!

**Pull request merged**
