### PR TITLE
[sysrst_ctrl,sival] Backport to earlgrey + testplan + small fix

### PR DESCRIPTION
**Pull request by pamaury**
This is a backport of three test, it also enables tests on silicon and updates the testplan. There is also a tiny fix to a test that could be flaky. Only review the last 3 commits which are the only non-backported changes.

### CODE REVIEW

**Comment by jwnrt** [comment]
> Only review the last 3 commits which are the only non-backported changes.

Do you mean that all the other commits are exact matches of merged commits from `master` and these three are new commits?

**Review by jwnrt — APPROVED** [review]
Those last three commits look fine and the rest look relevant to the tests, so all good with me as long as the tests pass. Thanks

**Review by rswarbrick — APPROVED** [review]
I've looked properly at the last three commits (which look good to me). If the earlier commits are just cherry-picks, this looks great.

**Comment by nbdd0121** [comment]
> Only review the last 3 commits which are the only non-backported changes.

Do these commits need to land on master as well?

**Comment by jwnrt** [comment]
CI failures look like they could be related, so worth looking at @pamaury

**Comment by pamaury** [comment]
> > Only review the last 3 commits which are the only non-backported changes.
> 
> Do these commits need to land on master as well?

Yes I will backport them to master as well.

**Comment by pamaury** [comment]
Indeed, I enabled the tests on too many exec envs, the test requires hyperdebug so it can't run on plain cw310.

**Pull request merged**
