### PR TITLE
[ top_earlgrey, i2c ] Add single I2C instance to top_earlgrey

### PR DESCRIPTION
**Pull request by martin-lueker**
Adding I2C as a muxed IO peripheral, with a base address of 0x401d0000.

### CODE REVIEW

**Comment by martin-lueker** [comment]
Dear Reviewers,
   Please note that most of these files are auto generated.  To see _just_ the human edited files, please look at commit 37f5834f68c0c228fcc19e49060f79c7fb2c492e.

**Comment by eunchan** [comment]
LGTM for Hjson

**Comment by martin-lueker** [comment]
@silvestrst: For changes to plic unittest.

**Review by lenary — APPROVED** [review]
SW Changes LGTM.

**Comment by martin-lueker** [comment]
Thanks @eunchan and @lenary!

**Comment by martin-lueker** [comment]
One minor change (related to clang-format complaints), but is now squashed and rebased.   CI-willing this is GTG from my perpective.

**Review by silvestrst — APPROVED** [review]
@martin-lueker thank you for the PR!

SW PLIC changes look good to me!

**Pull request merged**
