### PR TITLE
Update lowrisc_misc-linters to lowRISC/misc-linters@091a2fe

### PR DESCRIPTION
**Pull request by hcindyl**
Update code from upstream repository https://github.com/lowRISC/misc-
linters.git to revision 091a2fe9c6cc8d8057c254ce3a6a565847f6e737

* [licence-checker] Add vlt template file support (Cindy Liu)
* [CI] Use Bazel rules for CI instead of manual calls (Miguel Young de
  la Sota)
* [yapf] Add Bazel rules for yapf formatting (Miguel Young de la Sota)
* [doc] Add README note about Bazel rules (Miguel Young de la Sota)
* [licence-checker] Add Bazel support for calling into the licence
  checker (Miguel Young de la Sota)
* [licence-checker] Add support for Go, Protobuf, and Bazel (Miguel
  Young de la Sota)

Signed-off-by: Cindy Liu <hcindyl@google.com>

### CODE REVIEW

**Comment by hcindyl** [comment]
To be used by https://github.com/lowRISC/opentitan/pull/11810

**Review by drewmacrae — CHANGES_REQUESTED** [review]
Can all `BUILD`, `*.bzl` and `WORKSPACE` files be omitted, or can we work to exclude them from execution of bazel build/test and starlark linting phases in the OT repo? We've had problems with it in the past.

To avoid building and testing the copied in vendored bazel files, you'd add `util/lowrisc_misc-linters` to `.bazelignore`
and to avoid starlark linting you'd add `"./util/lowrisc_misc-linters/**"` to the list of exclude patterns for the `buildifier_fix` and `buildifier_check` rules in `BUILD.bazel`

**Review by rswarbrick — APPROVED** [review]
Looks good.

@drewmacrae: Will merging this actually break things for you? If so, I guess we have to add the ignore files first (probably in a separate PR). If not, I suggest merging this and then filing follow-ups to sort things out.

**Comment by drewmacrae** [comment]
It will break things, but we can fix them afterwards. We’re planning to
roll out CI that will block pull requests like this in the future so I
wanted to write up the issue and the strategy to manage these things before
they block people.

**Comment by rswarbrick** [comment]
Ok, thanks! Let's merge to keep things going for now. As you say, our CI will stop us playing fast and loose soon enough :-D

**Pull request merged**
