### PR TITLE
[csrng] V2 and V2S signoff

### PR DESCRIPTION
**Pull request by vogelpi**
~There are just very few outstanding PRs that need to pass CI to be merged, we need to re-collect coverage with these changes (currently ongoing), and then we can hopefully hit V2/V2S. For now I make this a draft.~
All things are merged, the next nightly should show the updated coverage results.

### CODE REVIEW

**Review by senelson7 — APPROVED** [review]
LGTM

**Comment by vogelpi** [comment]
The last important DV and RTL fixes got merged this morning, all V1/V2/V2S tests have a pass rate of +90%, and we get the following coverage numbers:

Score | Block | Branch | Statement | Expression | Toggle | Fsm | Assertion | CoverGroup
-- | -- | -- | -- | -- | -- | -- | -- | --
96.75 % | 97.73 % | 93.80 % | 98.68 % | 91.07 % | 92.18 % | 100.00 % | 96.97 % | 97.76 %

This should also be reflected in the next nightly regression results.

**Review by mwbranstad — APPROVED** [review]
L:GTM

**Review by marnovandermaas — APPROVED** [review]
Great work getting this over the line!

**Comment by vogelpi** [comment]
The regression results are now out: https://reports.opentitan.org/hw/ip/csrng/dv/latest/report.html

Once also @weicaiyang, @msfschaffner or someone else from Google approves this, I will merge the PR.

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
Well done!

**Comment by marnovandermaas** [comment]
Great work everyone! The teamwork was amazing :)

**Pull request merged**
