### PR TITLE
[dv/doc] Fix minor diagram arrow

### PR DESCRIPTION
**Pull request by cindychip**
Fix gpio, hmac, i2c, rv_timer, spi_device, tlul, and uart

Signed-off-by: Cindy Chen <chencindy@google.com>

### CODE REVIEW

**Comment by cindychip** [comment]
This PR is to finish item #2 of the issue: https://github.com/lowRISC/opentitan/issues/1133.

**Comment by sriyerg** [comment]
Thank you very much for fixing these!

**Comment by gaurangchitroda** [comment]
LGTM!

**Comment by cindychip** [comment]
Thank you all for the quick responses, you are very welcome :)

**Pull request merged**
