### PR TITLE
[prim_lfsr] Add option to specify custom output permutation

### PR DESCRIPTION
**Pull request by msfschaffner**
In some places in OpenTitan (e.g. alert handler ping timer and OTP controller partition check timer), we've added a custom state output permutation in order to break linear shifting patterns. This patchset absorbs this functionality into `prim_lfsr` such that it can be reused more conveniently. The feature is turned off by default, hence existing instances in OpenTitan should not be affected.

I have updated the DV testbench in order to cover this feature, while in the corresponding FPV testbench this is currently disabled. @udinator let me know if you think we need to test this better.

The LFSR usage in OTP and the alert handler has been updated as well in order to leverage this new feature. @cindychip, does that in any way affect the existing DV environment of the alert handler?

CC: @vogelpi @mwbranstad for your info, since there are a couple of LFSRs in your designs.

### CODE REVIEW

**Review by cindychip — APPROVED** [review]
Thanks Michael for checking with me. The alert_handler dv works fine and it LGTM.

**Review by udinator — APPROVED** [review]
LGTM, thanks Michael!

I can add another test to the LFSR nightly regression with `StatePermEn` enabled so we test this in simulation.
@cindychip should we test this in formal?

**Comment by cindychip** [comment]
Thanks @udinator  yeah I will add the FPV support for `StatePermEn` to make sure the coverage is 100%

**Comment by msfschaffner** [comment]
Cool, thanks @cindychip and @udinator! Merging this in once @tjaychen and/or @cdgori gave their blessings ;).

**Review by tjaychen — APPROVED** [review]
LGTM!

**Review by cdgori — COMMENTED** [review]
late, but LGTM

**Comment by mwbranstad** [comment]
@msfschaffner - just getting back to this. I am pretty sure I would not need this function. I looked at the otp usage and see how it works, but can you tell me why this is useful. thanks!

**Comment by msfschaffner** [comment]
Hey @mwbranstad. Since LFSRs produce (mostly) linearly shifted output bits, it can be beneficial in some cases to additionally "whiten" the output by passing it through an add-on function such as a lightweight block cipher. This permutation is basically just a cheap alternative of doing that.

**Pull request merged**
