### PR TITLE
[doc] Refine description of D1 checklist item IP_INSTANTIABLE

### PR DESCRIPTION
**Pull request by msfschaffner**
Draft for updated IP_INSTANTIABLE item - to be discussed in the TC.

This also fixes a bunch of typos.

Addresses #91.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
@cindychip @weicaiyang can you take a look to see whether this makes sense?

**Review by weicaiyang — APPROVED** [review]
The update makes sense. LGTM

**Review by vogelpi — APPROVED** [review]
This looks good to me and is in line with what we've discussed in the last Silicon meeting. Thanks @msfschaffner !

**Review by rswarbrick — APPROVED** [review]
This looks like a great improvement, thanks.

**Pull request merged**
