### PR TITLE
[ibex] Connect dft bypass controls

### LINKED ISSUE #6058: [ibex] Add DFT override for shadow core reset
As noted in #6033 we'll need some way of controlling the reset to the second lockstep core.

### PR DESCRIPTION
**Pull request by tjaychen**
Fixes #6058

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
@tjaychen @dsandrs @imphil @vogelpi 

Looks like we've finally hit the wall with the current FPGA size:

```
To attempt placement at higher effort levels at the expense of runtime, please use the following tcl command, setting the value of limit to 2000 or more.
set_param place.sliceLegEffortLimit limit
```

The reason for that is all the recently added IP, as well as the synthesis fixes that now prevent intentional redundant logic from being optimized away (like multibit signals etc).

Given the schedule, I think may have to consider taking out FPGA CI for the time being to unblock further development towards the netlist drop.

**Comment by msfschaffner** [comment]
> @tjaychen @dsandrs @imphil @vogelpi
> 
> Looks like we've finally hit the wall with the current FPGA size:
> 
> ```
> To attempt placement at higher effort levels at the expense of runtime, please use the following tcl command, setting the value of limit to 2000 or more.
> set_param place.sliceLegEffortLimit limit
> ```
> 
> The reason for that is all the recently added IP, as well as the synthesis fixes that now prevent intentional redundant logic from being optimized away (like multibit signals etc).
> 
> Given the schedule, I think may have to consider taking out FPGA CI for the time being to unblock further development towards the netlist drop.

Another option would be to temporarily stub out big leaf blocks.
@tjaychen is about to run an experiment.

**Comment by msfschaffner** [comment]
@mateenfaisal

**Comment by msfschaffner** [comment]
Edit: if we decide to take FPGA CI out temporarily, we could still build a bitstream for a larger device to have at least the synthesis check there.

**Comment by tjaychen** [comment]
> Edit: if we decide to take FPGA CI out temporarily, we could still build a bitstream for a larger device to have at least the synthesis check there.

i'm also investigating stubbing out some of our larger modules (aes / otbn) on fpga, so at least we test for boot strap capability and allow for some basic software development.

**Comment by vogelpi** [comment]
We've just discussed this. The synthesis check itself is not that useful. There is a high risk that we will have to invest substantial effort for debugging when we want to enable full FPGA CI again.

Thus we are in favor of stubbing out OTBN (or also AES if needed) on FPGA until we have the bigger FPGA board. We should get it soon but will also require some time to set up everything.

**Comment by tjaychen** [comment]
Pirmin, indeed to your point, AES is not the next highest consumer.
entropy_src is.  So I'm going to look into that one first.
I don't believe for FPGA purposes we need the entropy src in its full
glory.

**Comment by msfschaffner** [comment]
Ok this passes now - pulling in!

**Pull request merged**
