### PR TITLE
[edn] Hold csrng_req_valid until valid/ready handshake completes

### PR DESCRIPTION
**Pull request by vogelpi**
Previously, EDN could immediately de-assert the valid upon getting an ACK error thereby violating the valid/ready handshake protocol between EDN and CSRNG.

### CODE REVIEW

**Comment by vogelpi** [comment]
This resolves #23526.

**Comment by vogelpi** [comment]
Just in case: please wait with merging this. I am not yet fully done with the DV side for this and would like to run some more tests. Just to be sure. I'll post an update later today.

**Review by moidx — APPROVED** [review]

**Comment by vogelpi** [comment]
I've now updated the PR to also fix the updating of the hw_cmd_sts register (this is currently broken on master as additional data words sent to CSRNG update the cmd_type field with invalid data).

I've spent quite some time verifying this but the DV isn't ready yet. I'll file a separate PR tomorrow for the DV side. A block-level regression with a reduced number of seeds did not lead to test failures except for the edn_alert sequence which I am still adjusting. The sequences not triggering error cases all keep passing.

**Comment by vogelpi** [comment]
CI passes except for `boot_policy_flash_ecc_error:a_valid_b_corrupt_manifest_security_version_fpga_cw310_rom_with_fake_keys` which I've seen also failing for other unrelated PRs. I will now push a small DV update to push up the FSM coverage and will then hit merge.

**Pull request merged**
