### PR TITLE
[fpga] Fix top_englishbreakfast on CW305 

### PR DESCRIPTION
**Pull request by vogelpi**
This PR reconnects the DIO signals and the precise capture trigger that got accidentally disconnected when moving the JTAG mux into the pinmux IP. This re-enables SCA on the CW305 board. In addition, top_englishbreakfast is slightly realigned to top_earlgrey in order to ease future diffs.

### CODE REVIEW

**Review by moidx — APPROVED** [review]
LGTM

**Comment by alphan** [comment]
Thanks for fixing this @vogelpi.

**Comment by vogelpi** [comment]
Thanks guys for the quick review!

**Review by msfschaffner — APPROVED** [review]
Thanks @vogelpi! And sorry for the collateral damage. These large top-level changes are always a bit brittle...

**Comment by vogelpi** [comment]
No worries @msfschaffner , this is kind of expectable given we don't have a CW305 board in CI and things keep changing at a very high pace.

**Pull request merged**
