### PR TITLE
[flash_ctrl] rd_empty status stays high forever

### PR DESCRIPTION
**Pull request by jdonjdon**
cmd:
./util/dvsim/dvsim.py ./hw/ip/flash_ctrl/dv/flash_ctrl_sim_cfg.hjson -i flash_ctrl_ro_derr -r 1 -v m -s 300753592 --waves -ro "+test_timeout_ns=2000000"

Test runs read only traffics (ctrl and direct) with double bit error injected random time.
@158704.6ns 
flash_ctrl_rd detects error and fifo_incr_wptr is asserted 2 extra cycles than normal state.
But fifo_incr_rptr seems assert 16 cycles always and causes
tb.dut.rd_fifo_rvalid stays low forever.

### CODE REVIEW

**Comment by jdonjdon** [comment]
waveform is added.
image

**Comment by tjaychen** [comment]
let me have a look, i can't quite tell from what this what's going on.
Are you saying this behavior only shows up when an error is seen?

**Comment by jdonjdon** [comment]
> let me have a look, i can't quite tell from what this what's going on. Are you saying this behavior only shows up when an error is seen?

When double bit error is seen.

**Comment by tjaychen** [comment]
it looks like the reason this is happening "should" be fixed by #13691. 
is there any way you can merge that into your PR for now and give it a try?

**Comment by jdonjdon** [comment]
> it looks like the reason this is happening "should" be fixed by #13691. is there any way you can merge that into your PR for now and give it a try?

It passes with #13691

**Comment by tjaychen** [comment]
> > it looks like the reason this is happening "should" be fixed by #13691. is there any way you can merge that into your PR for now and give it a try?
> 
> It passes with #13691

excellent. I'm almost ready to merge that one.  I discovered some other potential issues along the way..stay tuned...

**Pull request closed without merging**
