### PR TITLE
[clkmgr] Change external clock switch qualifying condition

### LINKED ISSUE #9294: [clkmgr] Change software external clock control
Currently software external clock control is qualified with `lc_dft_en`.  This creates some complications during the secure manufacturing process and potentially makes it significantly more difficult to ship parts. 

To resolve this, we need to change this to `lc_hw_debug_en`. Since `clkmgr` has already reached D2, we need to double check the impact on DV, although this change is required for production.

### PR DESCRIPTION
**Pull request by tjaychen**
- Fixes #9294
- Now software is able to request external clock during TEST_UNLOCKED,
  DEV and RMA states.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Review by matutem — CHANGES_REQUESTED** [review]
In the functional spec there are mentions of dft enabling external clocks, so they should instead mention hw debug. Could you update the spec? This is also mentioned in the clkmgr DV doc, but I should update that myself since there are many more changes it needs, given all the changes we have had.

**Comment by tjaychen** [comment]
> In the functional spec there are mentions of dft enabling external clocks, so they should instead mention hw debug. Could you update the spec? This is also mentioned in the clkmgr DV doc, but I should update that myself since there are many more changes it needs, given all the changes we have had.

o good catch. let me update that.

**Comment by tjaychen** [comment]
> > In the functional spec there are mentions of dft enabling external clocks, so they should instead mention hw debug. Could you update the spec? This is also mentioned in the clkmgr DV doc, but I should update that myself since there are many more changes it needs, given all the changes we have had.
> 
> o good catch. let me update that.

I fixed these as part of #9348. Can you have a look?

**Review by matutem — APPROVED** [review]
LGTM

**Pull request merged**
