### PR TITLE
[spi_device] Connect Readbuffer flip event to interrupt

### PR DESCRIPTION
**Pull request by eunchan**
This commit connects the readbuf flip event into the interrupt line.
The flip event may be high for multiple SCK cycles. The logic converts
the signal into single cycle pulse to use prim_pulse_sync.

### CODE REVIEW

**Comment by eunchan** [comment]
If anyone has time, could you please review??

**Comment by rswarbrick** [comment]
Sorry, but I don't know enough about the spi_device design to review this.

**Review by tjaychen — APPROVED** [review]
lgtm over all. Just the same question as #9344 and whether we need to think about how the reset releases are handled.

**Comment by eunchan** [comment]
Merging now.

**Pull request closed without merging**
