### PR TITLE
[flash_ctrl,dv] Sign off V2S

### PR DESCRIPTION
**Pull request by jdonjdon**
All v2s review items are address (#15340)
See #15340 for details.

Signed-off-by: Jaedon Kim <jdonjdon@google.com>

### CODE REVIEW

**Comment by weicaiyang** [comment]
Looks like nightly regression passing rate and fcov are below V2S criteria.https://reports.opentitan.org/hw/ip/flash_ctrl/dv/latest/report.html

**Comment by jdonjdon** [comment]
> Looks like nightly regression passing rate and fcov are below V2S criteria. https://reports.opentitan.org/hw/ip/flash_ctrl/dv/latest/report.html
With #15909, 
image

**Review by weicaiyang — APPROVED** [review]
Congrats! LGTM

**Comment by tjaychen** [comment]
@jdonjdon does this cover the mub stuff you identified yesterday or the day before?

**Review by tjaychen — APPROVED** [review]

**Comment by jdonjdon** [comment]
> @jdonjdon does this cover the mub stuff you identified yesterday or the day before?

yes it is updated in #15909 without it, group coverage was 60%.

**Pull request merged**
