### PR TITLE
[WIP] [sw] Add Tock Repository

### PR DESCRIPTION
**Pull request by jon-flatley**
This change adds Tock as a submodule under `sw/device` and hooks it up to build with Meson.

The upstream Tock repository already has an opentitan board definition and a [huge amount of effort has already gone into supporting Ibex + OpenTitan on Tock](https://github.com/tock/tock/pull/1460). In parallel the OpenTitan software team has been developing [Device Interface Functions (DIFs)](https://github.com/lowRISC/opentitan/blob/master/sw/device/lib/dif/README.md) that are to become the universally recommended way to actuate OpenTitan hardware. The goal of integrating the Tock submodule in the OpenTitan tree is to join these two efforts, using the OpenTitan DIFs to actuate hardware from within Tock.

Tock and OpenTitan DIFs each have their own requirements and quirks which makes it difficult to combine the two. For example, Tock is written in Rust and DIFs are written in C. It's important to keep the DIFs in C and checked in to the OpenTitan repository where DV can easily access and keep up to date as hardware designs iterate.

To accommodate these requirements the plan is as follows:
- [x] Add Tock to the OpenTitan repository
- [x] Integrate Tock with OpenTitan build system
- [ ] Create a Rust crate in the OpenTitan repository that implements Tock drivers based on OpenTitan DIFs
- [ ] Setup linking between the Rust crate and C DIFs
- [ ] Documentation

Once these steps are complete the plan is to setup automation to keep the Tock submodule up to date with the upstream repository in a way that doesn't break CI.

This approach is being used only to cover the DV period where DIFs are changing with their underlying hardware. Once the DIFs are no longer expected to change they can be rewritten in Rust and committed to upstream Tock.

I'd love to collect feedback on how the build is setup in this PR. I'm not sure any solution for calling Cargo from Meson will ever be clean, but I'm new to both so it's possible I'm not leveraging useful features.

### CODE REVIEW

**Comment by jon-flatley** [comment]
I intended to tag this as WIP, but I don't see how I can do that now.

Not surprisingly CI isn't liking this change very much. I still need to look into how to get the Rust toolchain setup.

**Comment by eunchan** [comment]
Normally, `vendor-in` process is preferred as far as I know. 

FYI, if you created the PR as normal PR, you can't change it to Draft (WIP), need to close and create again.

**Comment by jon-flatley** [comment]
> Normally, `vendor-in` process is preferred as far as I know.

I'll start off by admitting that I'm not totally informed about how we do vendoring. I've checked [what documentation I could find](https://docs.opentitan.org/doc/rm/vendor_in_tool/), read through the `util/vendor.py` script, and checked the existing git history in `sw/vendor`. From what I can tell, the vendoring process isn't great for including Tock in the OT repo for a few reasons:

1. Vendoring destroys history. Tock has thousands of commits including commits directly pertaining to Ibex and OpenTitan support.
2. We are actively contributing to Tock, and an important part of that is being able to test changes made to Tock in a local checkout of both the Tock and OpenTitan repositories that can carry local changes.
3. Changes made to Tock should be submitted upstream and upstream only. With vendoring this makes requirement (2) challenging.

The other solution I considered was making it possible within our build system to reference a local Tock checkout somewhere else, but submodules seemed to be preferable to this.

I'm not a huge fan of submodules myself. There are pitfalls and they can be confusing to those who haven't worked with them before, but from what I can tell they do seem to accommodate this use case better than the alternatives. I'm certainly willing to explore vendoring or other alternatives, I just thought this PR might be a good place to start.

> 
> FYI, if you created the PR as normal PR, you can't change it to Draft (WIP), need to close and create again.

Sigh, I don't really want to close this, I'll add `[WIP]` to the title at the very least.

**Comment by gkelly** [comment]
While this isn't the normal approach for vendoring I think this is the best choice for tracking Tock upstream.  I think the other choice is probably just to use a `Cargo.toml` reference to the external repository, but that does break the a-single-checkout-is-buildable model.  Last time this came up @phw had concerns, so I'm adding him to make sure this is satisfactory to him.

**Comment by asb** [comment]
Hi Jon - thank you for your work on this, and for better explaining the rationale behind using a git submodule. I don't quite agree that there is sufficient motivation to move away from our normal vendoring model though, and have a different view on your main points. Let me outline that below, as that seems like a useful next step:

* I agree that vendoring squashes history. I don't see that as a big concern. Right now, if you want detailed Ibex revision history you go to the Ibex repo. If we vendor in Tock and you want detailed Tock history, you'll go to the Tock repo.
* I don't think vendoring really does harm the experience of trying out changes locally much. There's nothing stopping you from copying changes across to the local OpenTitan checkout in order to do a wider "integration test", and I've done this before on the OpenTitan proejct. I personally find this more straightforward than fighting sub-modules (I've spent quite a lot of time with the sub-modules used in the RISC-V software repos, and not found it a pleasant experience)
* Vendoring in changes orthogonal to whether we carry downstream patches or not.

Of course if you think I'm off the mark on any of the above - do feel free to jump in with further comments!

Given that submodules aren't all that intuitive and aren't used elsewhere in OpenTitan, I'd rather that either:
1) We do a simple vendoring in of Tock as we've done with other IP/software
2) We just use a Cargo.toml to reference the external repo, as Garret suggests

I assume Tock also has external create / other Tock repo dependencies, so vendoring in wouldn't actually combine everything into the same repo anyway? Is that the case?

**Comment by jon-flatley** [comment]
Hey Alex,

Thanks for the comments, let me try my best to address them inline.

> * I agree that vendoring squashes history. I don't see that as a big concern. Right now, if you want detailed Ibex revision history you go to the Ibex repo. If we vendor in Tock and you want detailed Tock history, you'll go to the Tock repo.

I understand that the history is available somewhere, but when working inside the repository history provides more than just documentation. In a true git repository I can revert commits that broke something, pull in changes from other remotes such as my upstream tock repository that I base pull requests out of, apply patches, ect. Vendoring does more than squash commit history -- though I would argue that's still a pretty big deal -- it makes it impractical to do development within the vendored directory.

> * I don't think vendoring really does harm the experience of trying out changes locally much. There's nothing stopping you from copying changes across to the local OpenTitan checkout in order to do a wider "integration test", and I've done this before on the OpenTitan proejct. I personally find this more straightforward than fighting sub-modules (I've spent quite a lot of time with the sub-modules used in the RISC-V software repos, and not found it a pleasant experience)

I get that, and I really wish submodules were more intuitive. For instance, it's a major pitfall in my opinion that submodules can't (that I know of) stay in sync with the rest of the repository by default, and individuals need to add `--recurse-submodules` or run `git submodule update`. If someone fails to do this and the result is a broken build I think that's a bug in how the build is setup; this PR doesn't address this issue currently, and I'm not sure how it best can.

That being said, I don't think it's necessarily best to go with the intuitive option at the expense of important features. Git, and VC in general, isn't very intuitive but even simple projects are much better off using it. I strongly dislike having to manually carry changes between the vendored Tock repository and a git repository. It's cumbersome and will make it difficult to convince those working OT+Tock to use the OT repository. This is a big deal, since this is the whole reason for adding Tock to the OT repository in the first place.

> * Vendoring in changes orthogonal to whether we carry downstream patches or not.
> 
> Of course if you think I'm off the mark on any of the above - do feel free to jump in with further comments!
> 
> Given that submodules aren't all that intuitive and aren't used elsewhere in OpenTitan, I'd rather that either:
> 
> 1. We do a simple vendoring in of Tock as we've done with other IP/software

Since this makes local development cumbersome, I'm not sold on this idea. If local development wasn't a driving factor for using submodules we would just leverage Cargo features and not have the Tock source in OT at all.

> 2. We just use a Cargo.toml to reference the external repo, as Garret suggests

We could, but then once again local development becomes difficult.

> 
> Does Tock have any external create / other Tock repo dependencies, meaning vendoring in wouldn't actually combine everything into the same repo anyway?

I do not believe so, at least not for Ibex/OpenTitan. Though external crates used in Tock are more likely to be stable. I don't expect working on crates external to Tock and OT will be a typical workflow, even if they're used in the project. The goal isn't to have _all_ code in one place, just code that's actively undergoing development as part of the OT project.

One final point in favor of submodules: It's the recommended approach for maintaining out-of-tree subsystems according to the [Tock documentation](https://github.com/tock/tock/blob/master/doc/OutOfTree.md#structure).


If it's the consensus that submodules are not to be used in the OT repository then there are other options I've been considering. The best of which I think would be to by default use Cargo features to build the Tock crate without holding the Tock source in the OT repository. The build script for Tock could check for a `TOCK_TREE` environment variable and opt to build Tock from that directory instead. This would keep the OT repository submodule-free, enable building Tock as a part of OT, and still allow developers to point to a local Tock checkout to build against. This adds a fair amount of complexity to the build system. I haven't looked into this option in any depth yet, so it may have unforeseen complications.

**Comment by GregAC** [comment]
Would it be possible to change our vendoring setup so that those who want a 'proper' repository where something is vendored in can have that option, others just get the repository copy?

Though implementing this probably looks something like re-implementing submodules but with an option to either have a separate repository checked-out or just have the in OT-tree copy which sounds like it could be messy.

I'd note that there's plenty of users of this repository that aren't working on tock related development, they'll just want whatever works so the software build. By including tock as a sub-module we're complicating the repository setup only for the benefit of a subset of the repository users.

Some of those users will be coming from a HW background where git is already new to them so for them it's better to keep things as simple as possible (i.e. no sub-modules).

**Comment by GregAC** [comment]
Or as an alternative to my suggested frankenstein's monster of sub-modules and our current vendoring setup some scripting to make keeping the vendored repository in sync with a local copy of the actual repository as painless as possible?

I.e. with sub-modules your workflow might look like this

```
cd /path/to/ot/sw/device/tock/third_party/tock
git cherry-pick hot_fix
git revert bad_commit
... etc
```

Where with the scripting setup you have a seperate tock repository somewhere and the script will just copy things over for you that have changed

```
cd /seperate/tock/repo
git cherry-pick hot_fix
git revert bad_commit
... etc

cd /path/to/ot
./update_vendored_mirror --repo tock
```

You'll have a local dotfile that specifies where the mirror lives (could be a local repo could point to a remote tock repository)

**Comment by jon-flatley** [comment]
> Would it be possible to change our vendoring setup so that those who want a 'proper' repository where something is vendored in can have that option, others just get the repository copy?
> 
> Though implementing this probably looks something like re-implementing submodules but with an option to either have a separate repository checked-out or just have the in OT-tree copy which sounds like it could be messy.

I don't see the benefit of having Tock source code in the OT tree if it isn't treated properly by git. I don't think it adds any value apart from making the source code navigable without any VC features. Rather than taking the vendoring approach our build can just reference the Tock upstream repository in Cargo.

As for the copying approach, I think it's much cleaner to just have the build reference the local Tock repository (outside of the OT tree) directly as a dependency if we wanted to go in this direction. A variation of this could work, where Cargo references the submodule if present or the upstream Tock repository if not. This way everything would work just fine if an individual didn't checkout the submodule, and checking out the submodule would enable building from the local source. Those who don't work on Tock wouldn't even be aware of the submodule, and those who do work on Tock would understand that OT is following the [Tock recommendation to use submodules](https://github.com/tock/tock/blob/master/doc/OutOfTree.md#structure).

> 
> I'd note that there's plenty of users of this repository that aren't working on tock related development, they'll just want whatever works so the software build. By including tock as a sub-module we're complicating the repository setup only for the benefit of a subset of the repository users.
> 
> Some of those users will be coming from a HW background where git is already new to them so for them it's better to keep things as simple as possible (i.e. no sub-modules).

I completely agree with this. I think whatever solution is used here needs to build without any special workflow. For those who are working on Tock, however, there will need to be _something_ individuals will need to setup to get a local Tock repository building as a part of OT. I think there needs to be two Tock targets with some means of switching between them. One used by default that just builds Tock according to the revision referenced in the `Cargo.lock` file, and the alternative target that builds from a local repository. The first would be for those who don't develop on Tock and don't want to think about it, and the latter for those who are developing in Tock and would like to target a repository with their WIP changes. It would be great to have both targets in the OT tree so we can control things like which remote repository is targeted and at what revision.

**Comment by moidx** [comment]
Please let me know if I should ask this question in a different forum: Are we planning to eventually integrate system level tests based on Tock in the OpenTitan repo? Or, is the main intent to just add Tock while we stabilize the DIFs and create a Rust version. 

Based on how things are developed, OpenTitan will hit a set of freeze milestones for a particular design, which usually results in a set of hardware releases which get integrated into OS repos.  In other words, a particular DIF version is what the OS will actually run in production for a particular silicon target. 

Just thinking as an option, and ignoring the system tests coverage question for a second, would it make more sense to create an integration repo that has two submodules? One for OpenTitan and one for Tock? This would require some refactoring of the CI components, but nothing too crazy... Another alternative is to do what most hardware companies do, which is to setup a hardware snapshot release. Both options have pros and cons. 

From a system validation perspective, it may be interesting to have support for integration repos, which would contain as I said above hw and sw components + system tests and other stuff.

**Comment by jon-flatley** [comment]
As was discussed in a meeting last week, we will be simply adding Tock as a set of Cargo dependencies rather than vendoring the source. Modifying or adding a separate `Cargo.toml` file for local development should be relatively painless, and it accomplishes everything I was trying to do in this PR without the use of submodules. New PR is #1612, so I am closing this.

**Pull request closed without merging**
