### PR TITLE
[lc_ctrl/doc] Update checklist and move to D2S

### PR DESCRIPTION
**Pull request by msfschaffner**
This should not be merged before #10360 and #10392 have landed.

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
This should be good to go if we decide that https://github.com/lowRISC/opentitan/issues/10445 is a don't fix.

**Review by rswarbrick — APPROVED** [review]
Not completely sure about #10445, but happy for this to land as soon as a decision is made.

**Comment by msfschaffner** [comment]
Quick update:  #10445 has now been addressed in #10496. So this should be ready to go.

**Comment by cdgori** [comment]
I put one (post-merge, sorry) comment on #10360 but we can resolve that separately as it probably doesn't change anything.  This LGTM and is good to move to D2S.

**Review by cdgori — APPROVED** [review]
It helps if I actually hit approve :)

**Comment by msfschaffner** [comment]
Thanks @cdgori and everyone for helping to get this to D2S - merging!

**Pull request merged**
