### PR TITLE
[tlul] Move to V2

### PR DESCRIPTION
**Pull request by weicaiyang**
All common TLUL verification items have been completed.
Xbar coverage has reached V2 status
SCORE	LINE	COND	TOGGLE	FSM	BRANCH	ASSERT	GROUP
98.47	100.00	95.59	98.47	--	97.30	99.50	100.00

Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Review by cindychip — APPROVED** [review]

**Comment by sriyerg** [comment]
This is a little tricky. TLUL represents not just the XBARs, but also the widgets that actually do not exist in the XBARs (such as the adapters). 

We cannot be certifying the adapters (for example) to V2 since they are verified as a part of the IPs they are instantiated in. 

There needs to be a clear disclaimer that only the XBARs (and hence the TLUL components that went into it) are V2. The TLUL components that are not in the XBARs are not V2.

Maybe @eunchan or @tjaychen have some suggestions here?

**Comment by weicaiyang** [comment]
> This is a little tricky. TLUL represents not just the XBARs, but also the widgets that actually do not exist in the XBARs (such as the adapters).
> 
> We cannot be certifying the adapters (for example) to V2 since they are verified as a part of the IPs they are instantiated in.
> 
> There needs to be a clear disclaimer that only the XBARs (and hence the TLUL components that went into it) are V2. The TLUL components that are not in the XBARs are not V2.
> 
> Maybe @eunchan or @tjaychen have some suggestions here?

DV_DOC has mentioned that this is to verify xbar features. Perhaps I can also clarify that the verification milestone is only certified for xbars. The other TLUL components are verified in the IPs that instantiate them (which is true as we don't exclude those TLUL adapter in IP-level test).

**Comment by sriyerg** [comment]
Maybe clarify this in the `notes` section so that it is front and central in the HW dashboard. I propose adding:
```
Only the XBAR instances (and TLUL components that went into them) are certified to V2. For exceptions see <link-to-dv-doc-section-containing-exceptions>". 
```

In DV doc, explicitly indicate which TLUL modules are exceptions to V2 (or any verification level for that matter).

**Comment by matutem** [comment]
Weicai, is there a PR for the DV docs as requested by Sri? Perhaps it should be attached to this PR?

**Comment by weicaiyang** [comment]
> Maybe clarify this in the `notes` section so that it is front and central in the HW dashboard. I propose adding:
> 
> ```
> Only the XBAR instances (and TLUL components that went into them) are certified to V2. For exceptions see <link-to-dv-doc-section-containing-exceptions>". 
> ```
> 
> In DV doc, explicitly indicate which TLUL modules are exceptions to V2 (or any verification level for that matter).

sounds good. Updated. PTAL

**Comment by weicaiyang** [comment]
> Weicai, is there a PR for the DV docs as requested by Sri? Perhaps it should be attached to this PR?

Updated the dv_doc in this PR. PTAL

**Review by matutem — APPROVED** [review]
LGTM

**Review by sriyerg — APPROVED** [review]
Thanks!

**Pull request merged**
