### PR TITLE
[rstmgr] update rstmgr header generation

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@silvestrst this switches the header generation and fixes the related issues. But obviously now the `difs` no longer compile.
Do you want to have a look and fix?

**Comment by silvestrst** [comment]
@tjaychen thank you for the change. I think it makes easier to catch HW changes with static asserts, and in general extending the DIF (if/when new peripherals come along).

I am about to submit the pull request that is based on this one. To make CI happy and make this change mergeable, could you do the following in `sw/device/lib/dif/meson.build`:
```
# Reset Manager DIF library (dif_rstmgr)
#sw_lib_dif_rstmgr = declare_dependency(
#  link_with: static_library(
#    'sw_lib_dif_rstmgr',
#    sources: [
#      hw_ip_rstmgr_reg_h,
#      'dif_rstmgr.c'
#    ],
#    dependencies: [
#      sw_lib_bitfield,
#      sw_lib_mmio,
#    ],
#  )
#)
```

**Comment by tjaychen** [comment]
thanks @silvestrst.  I've fixed as you instructed, please let me know if this looks okay.

**Review by silvestrst — APPROVED** [review]
@tjaychen it looks good to me! Separate thank you for `top_earlgrey_reset_manager_sw_resets_t`.

One small question - the `RESET_INFO` register used to have `CAUSES` field, but know the whole register is dedicated to the reset causes. Is this an indication that we will have many more SW reset bits coming in future?

**Comment by tjaychen** [comment]
yes that's right, there will be a few more in the future.
It won't be "many", but I expect 2~3 more once those peripherals are designed.

**Pull request merged**
