### PR TITLE
[bazel] Update success pattern for sram_program_fpga_cw310_test

### PR DESCRIPTION
**Pull request by dmcardle**
Signed-off-by: Dan McArdle <dmcardle@google.com>

### CODE REVIEW

**Review by alphan — APPROVED** [review]

**Comment by alphan** [comment]
Requested "[Test an airgapped Bazel build)](https://github.com/lowRISC/opentitan/pull/15306/checks?check_run_id=8773503468)" to be rerun. Not sure why it failed in the first place since this PR doesn't touch anything related to it.

**Comment by alphan** [comment]
@timothytrippel can you take a look at the failure in "Test an airgapped Bazel build" and let us know if it should block this PR?

**Comment by alphan** [comment]
confirmed with @timothytrippel that this is a transient failure, merging now.

**Comment by timothytrippel** [comment]
This is a transient failure, this change should have no impact on airgapped builds.

**Pull request merged**
