### PR TITLE
[rv_dm] update register description

### PR DESCRIPTION
**Pull request by jdonjdon**
`HALTED` and `RESUMING` register take index of hart, but it is ambiguous from the register description. 
Update the description align with the implementation to clarify it.

### CODE REVIEW

**Comment by jdonjdon** [comment]
cc: @BasitMehmood

**Review by vrozic — APPROVED** [review]

**Comment by jdonjdon** [comment]
@rswarbrick look like you wrote [lint exclusion](https://github.com/lowRISC/opentitan/blob/6a6a03e2115f5000b35f1af7ff03062b61a8cbf0/hw/vendor/lint/pulp_riscv_dbg.vlt#L19-L26)
Do you know why these signals are declared size of 2**HartSelLen from the beginning?

**Review by msfschaffner — APPROVED** [review]

**Comment by msfschaffner** [comment]
CHANGE AUTHORIZED: hw/ip/rv_dm/data/rv_dm.hjson

**Comment by jdonjdon** [comment]
CHANGE AUTHORIZED: hw/ip/rv_dm/data/rv_dm.hjson

**Pull request merged**
