### PR TITLE
[test] Connectivity simulation test for rom_cfg signal

### PR DESCRIPTION
**Pull request by davebwil**
Tests that the rom_cfg signal from the AST is connected to the ROM_CTRL block using simulation.
All possible values of rom_cfg are tested by forcing values at the source and confirming receipt at the destination.

Signed-off-by: Dave Williams <dave.williams@ensilica.com>

### CODE REVIEW

**Comment by sriyerg** [comment]
This is already covered in formal connectivity test, and is as such, not necessary to replicate in simulation. See:
https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/formal/conn_csvs/ast_mem_cfg.csv

Lets discuss this in the next sync up meeting.

**Comment by cindychip** [comment]
Thanks for pointing that out Sri. When Dave first sent the email to @timothytrippel  and I, we did not find the correct reference to the top-level test spreadsheet. When we declared the intention in this monday's meeting, Dave has already finished this PR. So we thought it won't hurt to have one more simulation test to verify this.
Happy to discuss it more during the next meeting!

**Comment by cindychip** [comment]
Thanks TIm, +1 for the naming convention with a common prefix.

**Comment by sriyerg** [comment]
> Yeah, sorry about that. We misunderstood what Dave said originally. But we clarified in this past Monday's meeting as @cindychip mentioned.
> 
> I think some of the confusion stems from the mix of the SW and connectivity test types in the [test plan](https://docs.opentitan.org/hw/top_earlgrey/doc/dv/#testplan). Aside from the spreadsheet which details which tests are of what type (SW vs FPV connectivity, etc.), perhaps some naming conventions in the test plan HJSON itself may help. For instance, all chip-level software tests have a test point name that begins with the prefix `chip_sw_`, while those that are not software tests just begin with the prefix `chip_`. Moreover, making matters worse some connectivity test point names have the suffix `_conn` (e.g., `chip_flash_jtag_conn`), others have the entire word `connectivity` somewhere in the test point name (e.g., `chip_spi_device_connectivity_with_ast`), and others (like this test point, `chip_rom_ctrl_ast_rom_cfg` do not have any indication its a connectivity test in the name. Upon reading the _description_ field for a test point it becomes clear if a test should be a connectivity test or not, but perhaps a common prefix like `chip_fpv_` or `chip_conn_` would make this distinction more clear. WDYT @sriyerg @cindychip ?

Anything that says "connectivity" in the description implies formal, which is super fast and super simple to setup. Yes, we should cleanup the names, but lets also seek the right information before proceeding with test development if there are doubts.

**Comment by sriyerg** [comment]
I am leaning towards closing this PR, considering there are several other things that are to be verified with connectivity. It would be arbitrary to just test these signals in simulation and not the others; and adding the rest would be a lot of unnecessary work.

**Comment by timothytrippel** [comment]
@sriyerg do you still want to close this? Or should we merge? either is OK with me.

**Comment by sriyerg** [comment]
Prefer to close this, thanks!

**Pull request closed without merging**
