### PR TITLE
WIP: [mask_rom/sig_verify] Implement Signature Verification mask ROM module.

### PR DESCRIPTION
**Pull request by alphan**
This change introduces the signature verification (sig_verify) mask ROM module.

Signed-off-by: Alphan Ulusoy <alphan@google.com>

### CODE REVIEW

**Comment by alphan** [comment]
Jon and I will be working on this in parallel on this PR. We will squash the commits once this is ready for review.

**Comment by alphan** [comment]
Todo:
- [ ] ...

**Comment by tjaychen** [comment]
@sriyerg 
hey all, since the brom is shared between actual software and DV, do we have any ideas on what would be a clean / secure way to bypass RSA verification for DV? I think we want to avoid doing a lengthy RSA verification unless the environment explicitly calls for it.

**Comment by sriyerg** [comment]
> @sriyerg
> hey all, since the brom is shared between actual software and DV, do we have any ideas on what would be a clean / secure way to bypass RSA verification for DV? I think we want to avoid doing a lengthy RSA verification unless the environment explicitly calls for it.

One possible solution is to use a symbol from `device.h`. We would however want it to be controllable though.

**Comment by lenary** [comment]
@tjaychen @sriyerg I'm pretty worried about including any code that allows us to bypass RSA verification, as our build system doesn't really compile in/out code depending on the device (we substitute in link-time definitions, but these aren't secure enough to be used for something this sensitive).

In the short term, I we can keep `sw/device/boot_rom` around for DV tests that don't care what the ROM does, they just need to load a flash image and execute it with the ibex core, which means `sw/device/mask_rom` would be the ultra-secure system which matches production mask rom chips, and which you cannot bypass verification in. In the longer term, I don't want `sw/device/boot_rom` to exist, which would make DV's life harder, in that I also don't want RSA bypass code in the Mask ROM. 

We do intend to provide tools to easily create images signed for development, from within the build system, but that doesn't solve the "RSA takes forever" problem, it only solves the "it's hard to create signed images" problem.

**Comment by tjaychen** [comment]
Is there some way to provide some kind of compile time flag that skips
around certain portions of the ROM?
If it's compile time, we can at least prior to tapeout verify the right ROM
went out (with the appropriate configurations).

I do agree that having something IN the code that skips around verification
would be bad.
I'm guessing the entire verification flow would take up to 5ms? Do you
think that's something we could tolerate Sri?

**Comment by lenary** [comment]
@tjaychen #3563 has the way we're going, which is a build directory configuration flag. It's not quite compile-time, but it effectively is. The plan is to swap out whole translation units when linking, rather than individual lines of code with an ifdef during preprocessing, based on arguments to `./meson_init.sh`.

**Comment by tjaychen** [comment]
sounds good.
Thank you Sam!

**Comment by alphan** [comment]
Last update: Added initial implementation for decoding encoded messages.

**Comment by sriyerg** [comment]
> @sriyerg
> hey all, since the brom is shared between actual software and DV, do we have any ideas on what would be a clean / secure way to bypass RSA verification for DV? I think we want to avoid doing a lengthy RSA verification unless the environment explicitly calls for it.

I prefer leaving this to the SW team to figure out :)

**Comment by sriyerg** [comment]
> @tjaychen @sriyerg I'm pretty worried about including any code that allows us to bypass RSA verification, as our build system doesn't really compile in/out code depending on the device (we substitute in link-time definitions, but these aren't secure enough to be used for something this sensitive).
> 
> In the short term, I we can keep `sw/device/boot_rom` around for DV tests that don't care what the ROM does, they just need to load a flash image and execute it with the ibex core, which means `sw/device/mask_rom` would be the ultra-secure system which matches production mask rom chips, and which you cannot bypass verification in. In the longer term, I don't want `sw/device/boot_rom` to exist, which would make DV's life harder, in that I also don't want RSA bypass code in the Mask ROM.
> 
> We do intend to provide tools to easily create images signed for development, from within the build system, but that doesn't solve the "RSA takes forever" problem, it only solves the "it's hard to create signed images" problem.

Yeah that sounds fair. But we definitely do need to have a way to swap out bits and pieces of functionality of the boot ROM / mask ROM that we can control externally, without having to use a completely customized version. Please suggest a path forward that makes sense and is easy to implement.

**Comment by moidx** [comment]
@alphan @jon-flatley,  are we still planning to continue work on this PR?

**Pull request closed without merging**
