### PR TITLE
i2c_coverage waver draft

### PR DESCRIPTION
**Pull request by jdonjdon**
This is just for the file review purpose.
After review I will reformat .el file and create PR.

This is the draft of coverage waiver with #16955 
All UNR generated exclusion has  ANNOTATION: "VC_COV_UNR"

After these, (from line 55 of file i2c_excl_010322.el), manual wavers are added.
Transition from
{Active, PopFmtFifo,  SetupStart, SetupStop, Hold*, Clock*, ReadClock*, ReadHoldBit } to AcquireStart
;; These are excluded because they are from host function state to target function state.
AcquireAck* -> AcquireStart
;; To create acquire start condition, scl should be high from both tb and rtl. Also sda_o from dut should be high
to accept tb toggling. But Ack requires sda_o low, so 'start'  cannot be following by these states.
Any state -> Idle
This was discussed in other block review, it can be excluded. But if you think there is necessary transition to check
we can add directed test case ( like random reset test.)

### CODE REVIEW

**Comment by tjaychen** [comment]
i think the * -> start probably can be waived. The * -> Idle we might need to think a bit more.  Because we probably need to disable I2C arbitrarily and be able to re-enable it without the entire design getting stuck somehow. This is definitely true in host mode, and probably target mode to some extent.  

Of course, it's not really a huge issue, since I2C has an external software controlled reset we can make use of (precisely for situations if the block gets stuck).   

@a-will any thoughts?

**Comment by jdonjdon** [comment]
> i think the * -> start probably can be waived. The * -> Idle we might need to think a bit more. Because we probably need to disable I2C arbitrarily and be able to re-enable it without the entire design getting stuck somehow. This is definitely true in host mode, and probably target mode to some extent.
> 
> Of course, it's not really a huge issue, since I2C has an external software controlled reset we can make use of (precisely for situations if the block gets stuck).
> 
> @a-will any thoughts?

Host mode *-> idle is covered by "i2c_host_error_intr". So we need to discuss whether we need this for target mode dut.

**Comment by tjaychen** [comment]
i feel like it doesn't make a ton of sense for target. Because we can't just unilaterally decide to just..disable ourselves when we don't know the state of the host. So assuming we have some higher protocol governing the interface with the host, the software could just as easily reset the whole block. 

what do you think @a-will ? This does mean @jdonjdon that the target mode enable -> disable is probably a transition that will be missing from coverage.

**Comment by a-will** [comment]
> i think the * -> start probably can be waived. The * -> Idle we might need to think a bit more. Because we probably need to disable I2C arbitrarily and be able to re-enable it without the entire design getting stuck somehow. This is definitely true in host mode, and probably target mode to some extent.
> 
> Of course, it's not really a huge issue, since I2C has an external software controlled reset we can make use of (precisely for situations if the block gets stuck).
> 
> @a-will any thoughts?

Since we don't support multi-host, `(active host) -> AcquireStart` transitions can be waived. However, I think we should show _some_ coverage of the `(active target) -> AcquireStart` transition: The host is allowed to change targets at will. We don't necessarily have to cover all of them, though, and some transitions are impossible, since a start condition can only be detected when SCL is high.

The same is true for transitions to Idle occurring from an unexpected stop condition (while OT's i2c is in a target state).

For the spurious target_enable_i going from 1->0, it's kind of the same as the stop case. We might want to ensure that the transition happens, and we can't stretch clocks anymore. However, I'd agree that this is probably superfluous.

**Comment by tjaychen** [comment]
ah thanks @a-will , so * (subset) -> start makes sense to do.

**Comment by tjaychen** [comment]
hmmm.... @jdonjdon i guess we'll need to be a bit careful on the expected data.  For example, if you get a start / stop in the middle of a byte, that will affect what we expect to show up inside the device (in a write for example).

**Comment by jdonjdon** [comment]
> , if you get a start / stop in the middle

Yes, so when I got another start before stop,  I clear my on-going expected transaction and create a new expected txn.

**Pull request closed without merging**
