### PR TITLE
[aes, pre_syn, pre_sca] Fix Yosys synthesis and Alma formal security verification setups

### PR DESCRIPTION
**Pull request by vogelpi**
This PR contains a couple of commits to re-enable Yosys synthesis for AES and Alma formal security verification.

### CODE REVIEW

**Comment by nasahlpa** [comment]
Not sure if my setup is not working, but I get an error when running the _pre_syn_ flow:
`ERROR: Module `\prim_sparse_fsm_flop_378FE_346F8' referenced in module `\aes_cipher_control_fsm' in cell `\u_state_regs' is not part of the design.`
It seems that the prim_spare_fsm modules are not getting properly renamed.

**Comment by vogelpi** [comment]
> Not sure if my setup is not working, but I get an error when running the _pre_syn_ flow: `ERROR: Module "\prim_sparse_fsm_flop_378FE_346F8" referenced in module "\aes_cipher_control_fsm" in cell "\u_state_regs" is not part of the design.` It seems that the prim_spare_fsm modules are not getting properly renamed.

Hm. This problem should actually be avoided by the following changes added in #9632:
https://github.com/vogelpi/opentitan/blob/498b600427af12133967708e3aeae2bc619258bf/hw/ip/aes/pre_syn/syn_yosys.sh#L114-L117

and
https://github.com/vogelpi/opentitan/blob/498b600427af12133967708e3aeae2bc619258bf/hw/ip/aes/pre_syn/syn_yosys.sh#L144-L146

Did you check out this PR here or maybe just cherry-pick onto an outdated master branch?

**Comment by nasahlpa** [comment]
I checkout out this PR (gh pr checkout 9762) and the two changes in the file you mentioned are also in the script. I think Yosys is complaining as in the converted _aes_cipher_control_fsm.v_ file there still is the prim_sparse_fsm with the suffix:
```aes_cipher_control_fsm.v
prim_sparse_fsm_flop_378FE_346F8 #(
  .StateEnumT_StateWidth(StateWidth),
  ..
```
Shouldn't this be _prim_sparse_fsm_flop_ ? Adding something like this to line 143:
`sed -i 's/prim_sparse_fsm_flop_.*/prim_sparse_fsm_flop \#(/g' $LR_SYNTH_OUT_DIR/generated/${module}.v`
fixes this for me and the synthesis script is working for me.
Additionally, I also had to add this to line 147:
`sed -i '/\.StateEnumT_StateWidth(.*/d' $LR_SYNTH_OUT_DIR/generated/${module}.v`

**Comment by vogelpi** [comment]
Thanks for getting back Pascal. You are right, these suffixes should be removed (that's also the intention of the other patch). 
It's strange that I don't see this. Most likely it's related to the specific sv2v (v0.0.7-17-g499bd58) and Yosys (0.9+4306 - git sha1 3931b3a03) version I am using.

I'll try out your suggested changes locally first and then push another commit to this PR.

**Comment by nasahlpa** [comment]
Thanks Pirmin, now it works!
Yeah, I just recently updated to the latest version of Yosys (0.10+1 (git sha1 7a7df9a3)) as I needed some features from there.

**Review by nasahlpa — APPROVED** [review]

**Review by msfschaffner — APPROVED** [review]

**Comment by vogelpi** [comment]
Thanks for Pascal for having another look, and you both for approving this. Merging now.

**Pull request merged**
