### PR TITLE
[ci] reset the cw310 at the end of the tests so it's not left in a bad state for the next test

### PR DESCRIPTION
**Pull request by drewmacrae**
This requires the CW310 to be running firmware version 0.40.1 and will
make the content of
https://github.com/newaetech/chipwhisperer/pull/410 be available in
chipwhisperer to work

Fixes: #13106 

There's a compromise here, the reset occurs after failing tests, to restore the cw310 to a good state. I'd like it to happen at the beginning, but the container is connected to the serial ports before the test runs so that's not an option.

We reset after successful tests to check the reset is working.

Signed-off-by: Drew Macrae <drewmacrae@google.com>

### CODE REVIEW

**Comment by vogelpi** [comment]
CI is currently failing. There seems to be an issue with chipwhisperer-minimal. I've opened an issue on GitHub here: newaetech/chipwhisperer-minimal#2

**Comment by drewmacrae** [comment]
I used #13174 to hit this and verify the reboot script rand with appropriate access to the FPGA.

**Comment by drewmacrae** [comment]
This should work once merged. It's all in the source tree so subsequent PRs will rebase onto it as soon as it's merged in.

**Review by cfrantz — APPROVED** [review]

**Comment by drewmacrae** [comment]
@timothytrippel Can you review and merge if this looks acceptable?

**Comment by timothytrippel** [comment]
This will require upgrading the bazel custom image on our nightly regression infrastructure (otherwise it will break all nightly regressions), since this will change the custom ot_python_wheels Bazel repo cache. If we could hold off on merging this change until we can upgrade the bazel custom image (and announce it to the DV folks) that would be great. I should have the update out in a couple hours. Sorry for any inconvenience. (Note: #13064 is already tracking the need for a way to detect / automatically update said infrastructure when changes like this are made.)

**Pull request merged**
