### PR TITLE
[AST] Update internal AST logic

### PR DESCRIPTION
**Pull request by Jacob-Levy**
Signed-off-by: Jacob Levy <jacob.levy@opentitan.org>

### CODE REVIEW

**Comment by Jacob-Levy** [comment]
The CI (private) now fails on 45 minute timeout…. 
All the other checks passed!

Can the AST PR approved & merged with this non-specific iail?

Regards,
Jacob

**Comment by arnonsha** [comment]
Check failure on line 486 in Build log 

@azure-pipelinesazure-pipelines
/ CI (private)
Build log #L486
**The operation was canceled.**

**Comment by arnonsha** [comment]
@msf
Need your help with this pr. Not sure what is wrong

Thanks

**Comment by tjaychen** [comment]
it seems like there are 2 top level tests that got stuck. 
Are you able to follow our instructions and run sims directly with dvsim? 

It's not clear which test got stuck, so I would try some of the top level tests.

**Comment by Jacob-Levy** [comment]
I ca not run dvsim nor any of the test inside CI (private). That's why I asked for a waver on this check.

**Comment by tjaychen** [comment]
ah yes. I'll have to pull down your PR and have a look then.
I couldn't tell immediately which test hung.
We most likely cannot waive this, because it appears some tests have gotten
stuck.  (assuming i was looking at the right output).

Can you let us know what blocks you from running dvsim? Sri made the tool
pretty generic, and the intent was that multiple partners should be able to
run it.
If you have specific difficulties, it would be great if you can file issues
on it so we can see what's going on.

**Comment by msfschaffner** [comment]
I have restarted private CI on Azure (sometimes these tests time out). let's see if it passes now.

**Comment by Jacob-Levy** [comment]
Michell,
How did you restart only the CI (Private)? 
I was looking for it when I noticed it timeoutt....

**Comment by msfschaffner** [comment]
Hey Jacob, when you click on "Details" you will see a "re-run" link that can be clicked right next to the failed tests (still on the GitHub test summary page https://github.com/lowRISC/opentitan/pull/7043/checks?check_run_id=2879140143). When you follow "View more details on Azure Pipelines" link to the Azure dashboard, there is also a button somewhere at the top-right that allows you to "Rerun Failed Jobs".

**Comment by Jacob-Levy** [comment]
Will wait for issue #7056 to be resolved  and reissue the PR with latest OS AST.

**Pull request closed without merging**
