### PR TITLE
[ci,doc] Add lld as a package requirement

### PR DESCRIPTION
**Pull request by marnovandermaas**
Add `lld` to `apt-requirements.txt`.
This is to avoid an error raised by `rustc` during bazel builds:
```
collect2: fatal error: cannot find 'ld' compilation terminated.
```

### CODE REVIEW

**Comment by milesdai** [comment]
It might also be good to add it to `yum-requirements.txt`

**Comment by marnovandermaas** [comment]
> NIT: apt-requirements.txt configures CI to perform installation so this isn't merely a doc change. Given it's a small change to fix an issue that's existed for a while, if it's compatible with our CI systems: SGTM

Good point, I've changed the tag of the PR and commit to `[ci,doc]`

**Comment by marnovandermaas** [comment]
> It might also be good to add it to `yum-requirements.txt`

Thanks for pointing this out to me, I have now added `lld` to the yum requirements.

**Review by ctopal — APPROVED** [review]
Thanks @marnovandermaas for opening up a PR for this

**Pull request merged**
