### PR TITLE
[sw] Bring back debug symbols in ELF files

### PR DESCRIPTION
**Pull request by imphil**
ELF files did get their debug symbols stripped by our linker script. That's not really intended; we want to use the ELF files for debugging, and the ELF loader should take care that only required sections will end up being loaded. Thankfully the build id section was already removed with a linker flag, so the linker script part was unnecessary. Revert that commit and add a couple more cleanups along the way.

### CODE REVIEW

**Comment by imphil** [comment]
@silvestrst can you try this PR to see if debugging works for you now?

**Comment by imphil** [comment]
Note: previous discussion on this was happening in #1002 and #966. The [discussion indicates](https://github.com/lowRISC/opentitan/pull/966#issuecomment-554537797) that having only the `DISCARD` linker file  patch doesn't work, but having only `--build-id=none` should work (and it does in my testing).

**Comment by towoe** [comment]
I guess the main point of having `DISCARD` is to only have the specified sections in the output. So another option would be to explicitly specify that we want to have the debug symbols included by naming them.
But I agree that we need debug symbols.
Default linker script `elf32riscv.x` does:
```
  /* DWARF debug sections.
     Symbols in the DWARF debugging sections are relative to the beginning
     of the section so we begin them at 0.  */
  /* DWARF 1 */
  .debug          0 : { *(.debug) }
  .line           0 : { *(.line) }
  /* GNU DWARF 1 extensions */
  .debug_srcinfo  0 : { *(.debug_srcinfo) }
  .debug_sfnames  0 : { *(.debug_sfnames) }
  /* DWARF 1.1 and DWARF 2 */
  .debug_aranges  0 : { *(.debug_aranges) }
  .debug_pubnames 0 : { *(.debug_pubnames) }
  /* DWARF 2 */
  .debug_info     0 : { *(.debug_info .gnu.linkonce.wi.*) }
  .debug_abbrev   0 : { *(.debug_abbrev) }
  .debug_line     0 : { *(.debug_line .debug_line.* .debug_line_end) }
  .debug_frame    0 : { *(.debug_frame) }
  .debug_str      0 : { *(.debug_str) }
  .debug_loc      0 : { *(.debug_loc) }
  .debug_macinfo  0 : { *(.debug_macinfo) }
  /* SGI/MIPS DWARF 2 extensions */
  .debug_weaknames 0 : { *(.debug_weaknames) }
  .debug_funcnames 0 : { *(.debug_funcnames) }
  .debug_typenames 0 : { *(.debug_typenames) }
  .debug_varnames  0 : { *(.debug_varnames) }
  /* DWARF 3 */
  .debug_pubtypes 0 : { *(.debug_pubtypes) }
  .debug_ranges   0 : { *(.debug_ranges) }
  /* DWARF Extension.  */
  .debug_macro    0 : { *(.debug_macro) }
  .debug_addr     0 : { *(.debug_addr) }
  .gnu.attributes 0 : { KEEP (*(.gnu.attributes)) }
  /DISCARD/ : { *(.note.GNU-stack) *(.gnu_debuglink) *(.gnu.lto_*) }
```

**Comment by imphil** [comment]
The ELF contents shouldn't matter, as "ELF" is not the "output" format we're caring about; the loader needs to take care to only put relevant sections into memory. The loader in our case (currently) is either the ELF -> VMEM conversion tooling, or the Verilator ELF loader.

**Comment by towoe** [comment]
But doesn't the ELF content matter as the placement of the sections in ELF will influence the values of relative addresses? Not sure if objcopy does any update here.

I am not trying to say we should specify everything, because if something unexpected like the build ID does come up it will "just" result in an error which can then be fixed.

**Comment by imphil** [comment]
Yes, that's true. So would we be OK with only the `/DISCARD/ : { *(.note.GNU-stack) *(.gnu_debuglink) *(.gnu.lto_*) }` line?

**Comment by towoe** [comment]
Well, I think it only makes sense to discard all or just leave it as you proposed in this PR.
Sorry for the noise, I just wanted to raise awareness to the fact that discarding might make sense, but this is not a necessity. And to be honest I do not know all the impacts `/DISCARD/` could have as to suggest its safe usage.

**Comment by mcy** [comment]
Phillip, could you break up this PR into two? One to fix up the .ld format, one to actually make the linker script changes.

Also, seeing as we're apparently having an opinion on .ld format... is it worth it to write like, a paragraph of .ld style guide?

**Comment by imphil** [comment]
@mcy Sure #1114 created

**Pull request merged**
