### PR TITLE
[doc] Move logical security doc to fix resource links

### PR DESCRIPTION
**Pull request by tjaychen**

### CODE REVIEW

**Comment by tjaychen** [comment]
just noticed on opentitan all the image links were broken. I'm not sure if this is the "right" fix, but seems like 'a fix'?

**Comment by tjaychen** [comment]
just noticed on opentitan all the image links were broken. I'm not sure if this is the "right" fix, but seems like 'a fix'?

**Comment by eunchan** [comment]
> just noticed on opentitan all the image links were broken. I'm not sure if this is the "right" fix, but seems like 'a fix'?

Right fix.

**Comment by eunchan** [comment]
If you have time, could you please quickly create a `_index.md` in `doc/security/` directory pointing `logical_security_model`? It makes the document not orphan.

**Comment by tjaychen** [comment]
sounds good @eunchan , i'll make sure to do that.

**Pull request merged**
