### PR TITLE
Backport 21366 to master

### PR DESCRIPTION
**Pull request by engdoreis**
This is cherry-pick of https://github.com/lowRISC/opentitan/pull/21366 to branch master, with an additional commit to port the test with the removal of spi dev generic mode.

### CODE REVIEW

**Comment by jwnrt** [comment]
I think you introduced a merge commit to this PR by mistake.

Not your fault, GitHub's "Update branch" button isn't very good.

**Comment by engdoreis** [comment]
> I think you introduced a merge commit to this PR by mistake.
> 
> Not your fault, GitHub's "Update branch" button isn't very good.

Thanks for pointing out. Fixed.

**Review by pamaury — APPROVED** [review]
Looks good to me

**Comment by engdoreis** [comment]
This should be fixed by the [PR](https://github.com/lowRISC/opentitan/pull/21947#event-12077432749)

**Comment by jwnrt** [comment]
I think there are separate errors, e.g. https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=145163&view=logs&jobId=e104506b-be5e-50ae-ac5d-124eed5f0ced&j=e104506b-be5e-50ae-ac5d-124eed5f0ced&t=71a0f33e-acce-54f0-d280-121553f0b501

**Comment by jwnrt** [comment]
You're right, thanks.

"Rerun failed jobs" in Azure does not use the latest commit, so I was still seeing the failures.

**Pull request merged**
