### PR TITLE
[top, dv] Update ext clk frequency

### PR DESCRIPTION
**Pull request by weicaiyang**
Update ext clk freq to 48 and 96Mhz based on this [spec](https://github.com/lowRISC/opentitan/blob/master/hw/ip/clkmgr/doc/_index.md#clock-frequency-summary) [#12095](https://github.com/lowRISC/opentitan/pull/12095)

The freq can be controlled via plusarg

Also add a uart test to run with higher freq on the uart core clock

Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Review by matutem — COMMENTED** [review]
I don't quite understand if you are only setting the external clock frequency... My understanding is that you need to configure the clkmgr EXTCLK_CTRL.SEL to use the external clock, and you may also need to set EXTCLK_CTRL.HI_SPEED_SEL to enable/disable the clock dividers.

**Comment by tjaychen** [comment]
i thought the idea for this PR was mostly to allow for correct setting of external clock through a plusarg?

**Comment by weicaiyang** [comment]
> I don't quite understand if you are only setting the external clock frequency... My understanding is that you need to configure the clkmgr EXTCLK_CTRL.SEL to use the external clock, and you may also need to set EXTCLK_CTRL.HI_SPEED_SEL to enable/disable the clock dividers.

This is to fix the ext clock setting in DV side. It was fixed to use 100Mhz.
EXTCLK_CTRL.* still need to be set in C test. (the uart test already sets them)

**Comment by weicaiyang** [comment]
> i thought the idea for this PR was mostly to allow for correct setting of external clock through a plusarg?

yeah, also fixed uart test that used 100Mhz for ext clock.

**Review by matutem — APPROVED** [review]
I understand now. This doesn't yet change tests, just the mechanism for configuring the external clock frequency.
LGTM

**Pull request merged**
