### PR TITLE
[vendor] Update to handle branch names

### PR DESCRIPTION
**Pull request by tjaychen**
- This is added specifically to address a problem seen with --refresh-patches

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
Not really sure if this is the right fix...but `refresh-patches` on riscv_compliance wasn't working for me...so i just added something to get it going.

**Comment by imphil** [comment]
Is this the same problem as in https://github.com/lowRISC/opentitan/pull/2208? Probably #2208 with a small modification is the better fix, @lenary can you have a look?

**Comment by tjaychen** [comment]
ah yes it is the same problem, didnt realize there was something in flight.
I'll close mine down and let you guys sort it out. My local fix is enough
to generate the patches anyways.

**Comment by imphil** [comment]
I'm sorry @tjaychen, I think you asked me somewhere about this problem, but I cannot even find the request any more (or I was dreaming about it).

**Comment by lenary** [comment]
This is the same problem, and i'm not sure this is the correct fix. I think using `git checkout --force '<user input>'` is the correct approach, because this will automatically create a downstream branch based on the upstream one if one exists, and otherwise it will checkout the sha revision, without having us specify whether it's a revision or a branch when parsing.

I need to update my branch to do this, let me do so now.

**Comment by tjaychen** [comment]
thanks @lenary and @imphil 
i think what you're saying make sense, and I will close this now.

**Pull request closed without merging**
