### PR TITLE
[lc_ctrl/dv] Updated checklist and moved project to V2S

### PR DESCRIPTION
**Pull request by NigelScales**
- Updated checklist for V2S
- Moved project to V2S

Signed-off-by: Nigel Scales <nigel.scales@gmail.com>

### CODE REVIEW

**Review by msfschaffner — APPROVED** [review]
Defer to @cindychip to merge it.

**Comment by weicaiyang** [comment]
if all the checklist items are addressed, please also update this to V2S. We could do it in a separate PR.

https://github.com/lowRISC/opentitan/blob/5215920fc4cf7a455328682d3deff5caec1370b1/hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson#L14

**Comment by NigelScales** [comment]
> if all the checklist items are addressed, please also update this to V2S. We could do it in a separate PR.
> 
> https://github.com/lowRISC/opentitan/blob/5215920fc4cf7a455328682d3deff5caec1370b1/hw/ip/lc_ctrl/data/lc_ctrl.prj.hjson#L14

No problem @weicaiyang I'll do that.

**Comment by cindychip** [comment]
awesome, thanks Nigel, let me check nightly regression tonight since we just merged PR #12324. Will come back to merge this once the numbers meet expectation.

**Pull request merged**
