### PR TITLE
[sw/test_rom] Add AST init to test ROM

### PR DESCRIPTION
**Pull request by timothytrippel**
This commit adds the blind-data-copy initialization if the AST to the test ROM to enable it for chip-level testing. The same initialization procedure used in the mask ROM is added to the test ROM.

Signed-off-by: Timothy Trippel <ttrippel@google.com>

### CODE REVIEW

**Comment by drewmacrae** [comment]
Can you add the new dependencies to the Bazel rules too please?

I'm seeing regressions in the following tests:

- //sw/device/lib/testing/test_rom:verilator_test_rom_test FAILED TO BUILD
- //sw/device/silicon_creator/lib/drivers:verilator_alert_functest FAILED TO BUILD
- //sw/device/silicon_creator/lib/drivers:verilator_hmac_functest FAILED TO BUILD
- //sw/device/silicon_creator/lib:verilator_boot_data_functest FAILED TO BUILD
- //sw/device/silicon_creator/lib:verilator_irq_asm_functest FAILED TO BUILD

They can be run with the command
```
bazel test //sw/device/lib/testing/test_rom:verilator_test_rom_test --test_tag_filters=-cw310,-failing_verilator --disk_cache=~/bazel_cache --local_test_jobs=HOST_CPUS*0.2
```

**Comment by timothytrippel** [comment]
> Can you add the new dependencies to the Bazel rules too please?
> 
> I'm seeing regressions in the following tests:
> 
> * //sw/device/lib/testing/test_rom:verilator_test_rom_test FAILED TO BUILD
> * //sw/device/silicon_creator/lib/drivers:verilator_alert_functest FAILED TO BUILD
> * //sw/device/silicon_creator/lib/drivers:verilator_hmac_functest FAILED TO BUILD
> * //sw/device/silicon_creator/lib:verilator_boot_data_functest FAILED TO BUILD
> * //sw/device/silicon_creator/lib:verilator_irq_asm_functest FAILED TO BUILD
> 
> They can be run with the command
> 
> ```
> bazel test //sw/device/lib/testing/test_rom:verilator_test_rom_test --test_tag_filters=-cw310,-failing_verilator --disk_cache=~/bazel_cache --local_test_jobs=HOST_CPUS*0.2
> ```

Ah, my apologies. Fixed.

**Review by drewmacrae — COMMENTED** [review]
Thanks for adding the Bazel rules. Looks good from a Bazel perspective.

**Review by sriyerg — COMMENTED** [review]
LGTM, given that this is exactly what's being done in mask ROM. I will add the backdoor load counterpart to this.

**Review by sriyerg — APPROVED** [review]

**Pull request merged**
