### PR TITLE
[edn/rtl] D2S review updates

### PR DESCRIPTION
**Pull request by mwbranstad**
Feedback from the D2S review reflected back into the design.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Review by tjaychen — APPROVED** [review]
lgtm

**Review by msfschaffner — APPROVED** [review]

**Comment by mwbranstad** [comment]
If more reviews arrive, will address them. Since a new bug required this version of EDN, accepting this PR as of now.

**Review by vogelpi — COMMENTED** [review]
LGTM, too!

**Review by cdgori — COMMENTED** [review]
post-merge but LGTM

**Pull request merged**
