### PR TITLE
[rv_dm] Move to D2S

### PR DESCRIPTION
**Pull request by msfschaffner**
~~This should not be merged before #10866 has landed.~~

Closes https://github.com/lowRISC/opentitan/issues/10860

Signed-off-by: Michael Schaffner <msf@opentitan.org>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Related #10860

**Comment by msfschaffner** [comment]
The items in https://github.com/lowRISC/opentitan/issues/10860 have been addressed, so this is now up for review.

**Review by GregAC — APPROVED** [review]

**Comment by GregAC** [comment]
Can we get this merged @msfschaffner ?

**Comment by msfschaffner** [comment]
This is pending a final crosscheck from @cdgori.

**Comment by msfschaffner** [comment]
Moving this to D2S to get this out of the way.
@cdgori if there is anything here that we missed, please let us know.

**Pull request merged**
