### PR TITLE
[top/chip] Rename chip-level tops

### PR DESCRIPTION
**Pull request by msfschaffner**
This renames all target specific toplevels such that they are prefixed with `chip_*` instead of `top_*`. 
This is done to distinguish the target-specific chiplevel wrappers from the actual functional toplevel, which contains all the IPs, crossbar, etc.

Note that another option would have been to rename `top_<name>` -> `<name>`, but we refrained from doing so as this would change the definition of what we have so far referred to as `top_<name>`, and would have a more profound impact on tooling scripts, generated headers and packages that use the name `top_<name>` inline (e.g. hierarchical paths) or as part of the file name.

This is dependent on #5793, so only the last commit is actually relevant.

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Let me know what you think.

We can still go the other route and rename the `top_<earlgrey>` -> `<earlgrey>` - however I do think that the `top_*` -> `chip_*` renaming has less overall impact (also in terms of how we have so far referred to "the toplevel", as it does not change its definition).

**Comment by rswarbrick** [comment]
I don't have strong feelings about this naming. Honestly, I think it might be better to rename the other stuff that we're clashing with (so that a "top" is actually a top-level), but if that's going to be difficult then this seems like a reasonable way to go.

**Comment by vogelpi** [comment]
Another option we previously discussed in #295 was to use `base_earlgrey` for the functional top and `top_earlgrey` for the real, target-specific top. But I see that this could cause a lot more work with the scripts. And to be honest, I don't really mind. The proposed chip/top naming sounds very reasonable to me. That's how we used to do it at ETH as well.

**Comment by tjaychen** [comment]
> I don't have strong feelings about this naming. Honestly, I think it might be better to rename the other stuff that we're clashing with (so that a "top" is actually a top-level), but if that's going to be difficult then this seems like a reasonable way to go.

this is my sentiment as well.  So this LGTM.

**Review by imphil — APPROVED** [review]
Thanks! This gives us more distinction between the "two types of toplevels". Any naming we chose will ultimately be convention, so whatever is easiest when doing the renaming will do the trick for me.

**Pull request merged**
