### PR TITLE
[aes] Exclude SVA helper logic from synthesis

### PR DESCRIPTION
**Pull request by msfschaffner**
This fixes a DC elab issue.

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Review by eunchan — APPROVED** [review]

**Comment by alphan** [comment]
cancelled cw310 jobs to bump up the fix in the queue. apologies for the inconvenience.

**Comment by alphan** [comment]
@msfschaffner I didn't close and reopen it looks like this PR since it doesn't seem to need cw310 tests but I'll leave the final decision to you.

**Comment by msfschaffner** [comment]
No worries - this should not touch the FPGA, so it should be ok to merge.

**Review by matutem — COMMENTED** [review]
Michael, we don't want to instrument this code for coverage, so could you also add
//VCS coverage off
// pragma coverage off
right after `ifdef INC_ASSERT
and corresponding "coverage on" comments before the `endif?

**Comment by msfschaffner** [comment]
Ah I completely forgot about that, PR here: https://github.com/lowRISC/opentitan/pull/16149

**Pull request merged**
