### PR TITLE
[dv,usbdev] usbdev Sequence PR

### PR DESCRIPTION
**Pull request by Saad22386**
This PR contains usbdev_nak_trans seq

### CODE REVIEW

**Comment by Saad22386** [comment]
@jdonjdon Why are CI checks failing?

**Comment by jdonjdon** [comment]
@Saad22386 #21296 has been filed.

**Comment by jdonjdon** [comment]
> @Saad22386 #21296 has been filed.

Please rebase with master.

**Comment by Saad22386** [comment]
> > @Saad22386 #21296 has been filed.
> 
> Please rebase with master.


cc: @jdonjdon

**Review by jdonjdon — APPROVED** [review]
Please rebase with master

**Comment by Saad22386** [comment]
cc: @jdonjdon

**Review by jdonjdon — APPROVED** [review]

**Pull request merged**
