### PR TITLE
[fpv/conn] setup connectivity test script

### PR DESCRIPTION
**Pull request by cindychip**
Add script and basic support for top level connectivity test, I would like to confirm if this is the correct format/code that you are looking for.

1. To run the connectivity test, 
  Go to `hw/formal/formal_conn`
  Run `./formal_conn -gui`

2. Current issue:
   `inout` support: the tool has some issue supporting `inout` behavior, the FPV team confirmed the issue and suggested to use a wrapper with ifdef to use fpv-friendly code instead. I am working on it.
 
Signed-off-by: Cindy Chen <chencindy@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
i have a dumb question, is this meant to be a check that top level is hooked up the way we like?

**Comment by cindychip** [comment]
Hi Tim,
I think the goal is to check if top_level is hooked up as we planned.
For example, if you look at the `top_earlgrey_conn.csv`
https://github.com/lowRISC/opentitan/blob/7b18d634f979e1ac715c55c528098dc5beb9fb43/hw/formal/formal_conn/top_earlgrey_conn.csv#L34
This line intends to check if signal `USBDP` from `top_earlgrey_asic` goes
to `usbdev`'s signal `cio_dp_i`.
Cindy Chen

**Comment by tjaychen** [comment]
thanks! but then how do we provide the "golden" reference for how it should be connected? Do we maintain that manually via the csv?

**Comment by cindychip** [comment]
Yes I believe so. I do not think right now there is a very good automation for this connectivity test. But we are keeping this option open to be explored.

**Pull request closed without merging**
