### PR TITLE
[top] Switch USB pads to new dual pad type 

### PR DESCRIPTION
**Pull request by msfschaffner**
This is a refactor of #9755 and adds a new pad type for the USB.

### CODE REVIEW

**Comment by arnonsha** [comment]
LGTM
Tessent tests passed (with the foundry changes as well)
I'd appreciate if this PR and the foundry one could be approved and merged before the end of the year vacations.

Merry Xmas

**Comment by msfschaffner** [comment]
I'll merge the internal foundry PR.
If anyone has a chance to give this a quick look, please merge if it looks ok :).

Merry X-Mas!

**Review by matutem — COMMENTED** [review]
Sorry, I am not familiar with this to provide a real review.

**Review by vogelpi — APPROVED** [review]
This LGTM!

Just to make sure I understand what this is about: previously, we were using two pads for each P and N to have the possibility of driving two different voltages. But how would we do the selection? If I understood correctly, always both pads were enabled together.

**Comment by arnonsha** [comment]
Thanks @vogelpi 
Yes, each set of pads is enabled together. This was also the previous design before this 
change. Our current vendor IOs won't meet the USB electrical spec with one pad only.

**Pull request merged**
