### PR TITLE
[dv/uart] Update scb for WO type reg

### PR DESCRIPTION
**Pull request by weicaiyang**
Since we updated reg model to not store write value for WO reg, need to
update uart scb accordingly
Signed-off-by: Weicai Yang <weicai@google.com>

### CODE REVIEW

**Comment by sriyerg** [comment]
Would you also please check and update other scoreboards?

**Comment by sriyerg** [comment]
Does this get UART passing?

**Comment by weicaiyang** [comment]
> Would you also please check and update other scoreboards?

will update scoreboards in rv_timer and gpio. Cindy has updated the hmac

**Comment by weicaiyang** [comment]
> Does this get UART passing?

sanity will pass with this PR. Will still see interrupt mismatch on tx_empty and tx_watermark which is still under discussion.

**Comment by cindychip** [comment]
Thanks Weicai

**Comment by weicaiyang** [comment]
> > Would you also please check and update other scoreboards?
> 
> will update scoreboards in rv_timer and gpio. Cindy has updated the hmac

Updated and test passed

**Pull request merged**
