### PR TITLE
[bazel] Annotated disassembly

### PR DESCRIPTION
**Pull request by alphan**
This PR disables the sandbox during disassembly to be able to produce annotated disassemblies.

Thanks for the pointers @cfrantz! I'm marking this as ready for review since the flag changes will go in a separate PR to lowRISC/bazel-embedded.

### CODE REVIEW

**Comment by alphan** [comment]
@cfrantz, I've just created lowRISC/bazel-embedded#9 which modifies fastbuild -- my goal was to produce these disassemblies in the default mode. Unfortunately, bazel strips debug symbols by default in fastbuild so we either have to add `build --strip="never"` to `.bazelrc` or define a separate mode. Please let me know what you think.

**Comment by luismarques** [comment]
(oops, I edited my own previous comment instead of quoting it. trying again)

> I'm not sure I understand why `-O` was turned into `-Os`, could you please clarify that?

Oh, thinking more about it, I'm guessing that you want to be able to match the disassembly with the regular build, which uses `-Os`. Duh :)

In any case, if it's not too hard to create a new mode let's create one. But if it is, personally it seems fine to to me to abuse "fastbuild".

**Review by drewmacrae — APPROVED** [review]

**Comment by alphan** [comment]
> (oops, I edited my own previous comment instead of quoting it. trying again)
> 
> > I'm not sure I understand why `-O` was turned into `-Os`, could you please clarify that?
> 
> Oh, thinking more about it, I'm guessing that you want to be able to match the disassembly with the regular build, which uses `-Os`. Duh :)

Exactly :) We will have a more formal doc that explains the choices but I just wanted to back to `Os` which we've been using so far in meson.

> In any case, if it's not too hard to create a new mode let's create one. But if it is, personally it seems fine to to me to abuse "fastbuild".

I don't think it's hard. I just wasn't sure if it would be worth it since I'd like the device code to be built with that new mode so why not modify the current default? But this was before learning about the interaction between `fastbuild` and `--strip`.

**Comment by timothytrippel** [comment]
This will require upgrading the bazel custom image on our nightly regression infrastructure (otherwise it will break all nightly regressions). If you could hold off on merging this change until we can upgrade the bazel custom image (and announce it to the DV folks) that would be great. Sorry for any inconvenience. (Note: https://github.com/lowRISC/opentitan/issues/13064 is already tracking the need for a way to detect / automatically update said infrastructure when changes like this are made.)

**Comment by alphan** [comment]
@timothytrippel I figured this can have some implications for that setup. PLMK when we can merge this.

**Review by timothytrippel — APPROVED** [review]

**Pull request merged**
