### PR TITLE
[top/fpga] Make sure SW is aware of reduced flash size on small FPGAs

### PR DESCRIPTION
**Pull request by vogelpi**
This PR modifies the script for reducing the flash size on smaller FPGAs to also edit the `flash_ctrl.h` accordingly. This way, software is aware of the reduced flash size. In addition, the script now also triggers the regeneration of the boot ROM.

This is related to lowRISC/OpenTitan#2171.

With this change, we can regenerate a working bitstream for the ChipWhisperer FPGA board for SCA from the master branch.

### CODE REVIEW

**Review by imphil — APPROVED** [review]
Wow, that's ugly -- but consistent with existing code. Given that all of this is what I'd call a "giant hack" but a proper fix will take time, let's get this in. Thanks Pirmin!

**Comment by vogelpi** [comment]
Thanks @imphil ! Yeah I know it's ugly. But we need to push this forward. Already this required a lot of work (debugging, low observability, many dependencies etc.) and things that got merged in the meantime caused the setup to stop working again... I think I had to do about 4 or 5 PRs of weakly related stuff. Once this is in and we have a stable setup in CI, we can start to clean up.

**Comment by tjaychen** [comment]
i'm actually going to template flash soon, hopefully we'll find a happier
solution!

**Comment by vogelpi** [comment]
> i'm actually going to template flash soon, hopefully we'll find a happier solution!

Yes, this will improve the situation. I am looking forward to that!

**Pull request merged**
