### PR TITLE
[topgen] Remove alert_module and interrupt_module from top_*.hjson

### PR DESCRIPTION
**Pull request by rswarbrick**
*EDIT: PR message and title edited to match the newer version of the commit*

These lists actually had code to populate them in topgen/merge.py's
`amend_alert` function, but this didn't ever run because it already has
a value. That value means that you need to remember to update it
whenever you add a new instance of an IP block.

The original motivation behind listing these explicitly was that the
top-level might not want to wire up all the alerts / interrupts from
the modules that it instantiates. We're not doing that at the moment
and, if we start doing that again, it's probably cleaner to explicitly
disable things rather than to have to add everything twice.

With this patch, we fix the code in `amend_interrupt` and `amend_alert` to
add everything. Now the only difference between that and the manual
list is the exact ordering of the bits in the signal. Since we access
these bits through auto-generated named constants anyway, we can
dispense with the manual step entirely.

### CODE REVIEW

**Comment by tjaychen** [comment]
ah i actually had a convo with Eunchan about this some time ago (there is a
similar situation with interrupts).
And the idea was that if there are modules that has alerts / interrupts but
do not actually want to be hooked up.

As it turns out we don't really have that situation right now, but wanted
to clarify the historical reasons.
Do you want to fix the interrupt case also? :)

**Comment by rswarbrick** [comment]
Oh, good point. I was being lazy and just fixing the thing that had confused me :-) I'll try to sort that out now.

**Comment by tjaychen** [comment]
no i actually meant to go connect that one.
That's what i meant by we don't really have a situation that currently
requires "have interrupt, but don't want it hooked up".
But just wanted to clarify what the original intent was.

There may be a situation where this comes up.

**Comment by rswarbrick** [comment]
Cool, I'll push up a version that does interrupts too. I've also amended the commit message a bit to reflect what you said, thanks.

**Comment by rswarbrick** [comment]
@silvestrst: Changing the number of interrupts requires associated changes to `dif_plic_unittest.cc`. I can change the magic numbers, of course, but I'm not completely sure why this needs updating manually. Is there something else that I need to be careful to keep in sync?

**Comment by imphil** [comment]
No, it's only the one assert.

**Review by silvestrst — COMMENTED** [review]
LGTM! From PLIC changes perspective!

**Comment by imphil** [comment]
@silvestrst is there an issue open to get rid of the requirement to manually change the test, either by auto-generating parts of it, or by writing the test in another way? This is rather painful to maintain and will be in the way to support toplevels with different interrupt configurations.

**Review by msfschaffner — APPROVED** [review]

**Pull request merged**
