### PR TITLE
[aes] clear status and trigger register upon fatal alerts

### LINKED ISSUE #6437: [aes/alert] some aes state information available upon fatal alert
When injecting a bit flip to cause a fatal alert in the AES engine - reading the status register will give information on the status of the core. Idle, data_in_ready, stall etc.

could this be a security risk?
I imagine that running the AES module in manual mode and injecting errors at different times then reading the status could potentially give away information.

The aes_alert_reset test currently do not fail on this - but maybe we want to force an all 0's or a random value on the status register in case of a fatal?

I have tried to read the other registers but I don't see any feasible way of trying to correlate this to internal round keys etc.

### PR DESCRIPTION
**Pull request by vogelpi**
Upon a fatal alert, all other bits in the status register as well as the trigger register should be cleared to not give away information on the internal status of the module when the fatal alert condition has been detected.

This resolves #6437.

### CODE REVIEW

**Review by rasmus-madsen — APPROVED** [review]
LGTM thank you for this update

**Comment by rasmus-madsen** [comment]
@cdgori are you ok with this solution, it would be nice to get this in a close #6437

**Comment by vogelpi** [comment]
Sorry for keeping you waiting @rasmus-madsen , I forgot a bit about this PR. Let's merge this now. @cdgori already "approved" the approach when discussing in #6437. If additional feedback comes in, I am happy to do a follow-up PR.

**Comment by cdgori** [comment]
Sorry @rasmus-madsen I did not remember this associated PR!  

Yes, this (blanking error bits) is a good solution as I said in #6437

**Pull request merged**
