### PR TITLE
[doc] Removed old documentation build script.

### PR DESCRIPTION
**Pull request by HU90m**
The old build script was left in the repository. It no longer works after `difgen` was moved and causes confusion. This PR removes it.

### CODE REVIEW

**Review by jwnrt — APPROVED** [review]
Looks good to me!

**EDIT**: actually there are a couple of references to `build_docs.py` in some files, would you mind swapping those out for `util/site/build-docs.sh`?

You could also delete `site/docs` while you're here if you felt like it

**Comment by HU90m** [comment]
* Updated the build docs getting started guide's page.
* Added `readme2index` preprocessor to getting started guide, so the link I added works.
* Deleted the old Hugo assets in `./site/docs`

**Review by engdoreis — APPROVED** [review]
LGTM, thanks Hugo

**Review by marnovandermaas — APPROVED** [review]
LGTM, thanks Hugo!

**Pull request merged**
