### PR TITLE
[lc_ctrl] Make RMA and token checks more robust

### PR DESCRIPTION
**Pull request by msfschaffner**
It has been found that the detection window for unstable RMA bits is very short (just 2 cycles, see #11874).
This patch makes the check more robust by extending the token check window from 2 to 4 cycles, and by introducing a background check for the RMA signals during the programming phase.

### CODE REVIEW

**Comment by tjaychen** [comment]
so if i understand this correctly, what's happening is that the sync delay is 2 cycles, so if the tb randomly injects a bad value on the boundary of `lc_ctrl`, it doesn't show up until 2 cycles later, at which point we are past this particular state?

but it seems like even if we extend it to 4 cycles, the dv stimulus here could still get an unexpected result if for example a bad value were injected on cycle 3?  I wonder if it would be better to make the check more static in the background once we get beyond the `FlashRmaSt`.

**Comment by msfschaffner** [comment]
> so if i understand this correctly, what's happening is that the sync delay is 2 cycles, so if the tb randomly injects a bad value on the boundary of `lc_ctrl`, it doesn't show up until 2 cycles later, at which point we are past this particular state?
> 
> but it seems like even if we extend it to 4 cycles, the dv stimulus here could still get an unexpected result if for example a bad value were injected on cycle 3? I wonder if it would be better to make the check more static in the background once we get beyond the `FlashRmaSt`.

Indeed, this is what the last commit in this PR aims at. It introduces another check during the programming phase (granted, we could technically forego the additional token checks with the last commit in place...).

**Comment by msfschaffner** [comment]
Let me remove the additional states and just add the crosschecks inside the programming phase state.
That should be enough to address this issue.

**Comment by msfschaffner** [comment]
@tjaychen @cindychip can you take another look at this one?
I removed the additional token check states and only kept the crosschecks in the programming state.

**Comment by msfschaffner** [comment]
ping :)

**Review by tjaychen — APPROVED** [review]
lgtm! sorry for the late review.

**Comment by msfschaffner** [comment]
Thanks, and no worries!

**Pull request merged**
