### PR TITLE
Correct documentation typo

### PR DESCRIPTION
**Pull request by jayeshaarish**
Signed-off-by: Jayesh Patel <jayesh@aarishtech.com>

### CODE REVIEW

**Comment by jayeshaarish** [comment]
No problem.
I thought I already included the sign-off line:
[image: image.png]
However, I typed it in manually, not using "git commit -s".  Does that make
a difference?

**Comment by rswarbrick** [comment]
Oh, good point! Sorry, I didn't read the CI logs properly. If you click on "details" above:
image
then you'll see the 3 messages that are coming out. The problem is actually with your name and email.

You can reproduce locally (and check you've fixed things without having to re-push) with the `ci/scripts/lint-commits.sh` script like this:
```
> ci/scripts/lint-commits.sh master
Checking commit messages since 3281bd3cf497853245a7d59678ae5ceeb4d411c7
Checking commit fd7e415533038e795c4ed65f2c8d9ca360c6cdfe
##vso[task.logissue type=error]Commit fd7e415533038e795c4ed65f2c8d9ca360c6cdfe: Commit author has no valid email address set: {commit.author.email!r}. Use "git config user.email user@example.com" to set a valid email address, then update the commit with "git rebase -i" and/or "git commit --amend --signoff --reset-author". Also check your GitHub settings at https://github.com/settings/emails: your email address must be verified, and the option "Keep my email address private" must be disabled. This command will also sign off your commit indicating agreement to the Contributor License Agreement. See CONTRIBUTING.md for more details.
##vso[task.logissue type=error]Commit fd7e415533038e795c4ed65f2c8d9ca360c6cdfe: The commit author name 'jayeshaarish' contains no space. Use "git config user.name 'Johnny English'" to set your real name, and update the commit with "git rebase -i " and/or "git commit --amend --signoff --reset-author". This command will also sign off your commit indicating agreement to the Contributor License Agreement. See CONTRIBUTING.md for more details.
##vso[task.logissue type=error]Commit has one or more Signed-off-by lines, but not the one we expect. We expected to find "Signed-off-by: jayeshaarish <100145097+jayeshaarish@users.noreply.github.com>". The commit message must contain a Signed-off-by line that matches the commit author name and email, indicating agreement to the Contributor License Agreement. See CONTRIBUTING.md for more details. You can use "git commit --signoff" to ask git to add this line for you.
##vso[task.logissue type=error]Commit lint failed.
```

**Comment by jayeshaarish** [comment]
Thanks for you patience in explaining everything @rswarbrick .  I think I've satisfied the CI requirements now but please let me know if I missed something.

**Review by rswarbrick — APPROVED** [review]
Looks great! Thank you very much for the change (and I hope our CI causes less hassle for you next time!)

**Pull request merged**
