### PR TITLE
[flash_ctrl] Switching tool from VCS to XCELIUM

### PR DESCRIPTION
**Pull request by nikola-miladinovic**
Change default tool from vcs to xcelium since xcelium is
sign off tool. Exclusions needs to be added only for one tool. Also we have enough Xcelium licenses to do small local regressions.

Signed-off-by: Nikola Miladinovic <nikola.miladinovic@ensilica.com>

### CODE REVIEW

**Comment by rswarbrick** [comment]
Have you clieared this change of tool with the Google team? (@msfschaffner, @tjaychen)

**Comment by nikola-miladinovic** [comment]
> Have you cleared this change of tool with the Google team? (@msfschaffner, @tjaychen)

I think that we clarified this topic long time ago but in this PR are everybody included. Please do not merge before someone from Goggle team confirms.Thanks.

**Comment by rasmus-madsen** [comment]
> Have you cleared this change of tool with the Google team? (@msfschaffner, @tjaychen)
@rswarbrick I have told @nikola-miladinovic to change the tool as he does not have access to vcs.
the alternative is to ask someone inside Google to do the coverage and exclusions.

**Comment by rasmus-madsen** [comment]
@nikola-miladinovic you might want to add to the description that you do not have VCS access.

**Comment by nikola-miladinovic** [comment]
> @nikola-miladinovic you might want to add to the description that you do not have VCS access.

Done. Thanks.

**Comment by nikola-miladinovic** [comment]
> the alternative is to ask someone inside Google to do the coverage and exclusions.

 @weicaiyang @tjaychen: This would be the best option if someone of you could generate exclusion file for exclusions given in https://github.com/lowRISC/opentitan/issues/12325

**Comment by weicaiyang** [comment]
It's probably easier to do coverage closure with Xcelium since @nikola-miladinovic side only has very limit VCS license.

@eshapira may want to use VCS to run close-source simulation. We can override `tool` with `vcs` in hsjon file.

@tjaychen WDYT?

**Review by weicaiyang — APPROVED** [review]
LGTM

**Pull request merged**
