### PR TITLE
Docs toc

### PR DESCRIPTION
**Pull request by towoe**
"Depends" on #1624, will drop the commit "[doc] Make links.." here. Should have thought about this first...

WIP as I just wanted to get some feedback for the design changes.
My plan was to add some orientation the left side, like a global table of content, but then I liked the local ToC on the right side on its own already.

I like the more concise overview of the current page, I think this make it actually more useful as the original could be at some point quite overwhelming.

WDYT?
toc-orig

toc-right

### CODE REVIEW

**Comment by imphil** [comment]
I like the design!

**Comment by towoe** [comment]
Thanks Philipp.

I just saw while switching to a smaller screen that to fixed position is not correct.
So it is truly WIP.

**Comment by sjgitty** [comment]
I do like the cleaner right hand side and it could prepare the way for some
of the other requests. Have you looked at #1419, #1420, and #1421? Those might
play into any final design.

**Comment by towoe** [comment]
@sjgitty yes, I have those in mind and that's why I wanted to check how people feel about some layout changes. I am off for a few days, didn't want to assign myself if I am not gonna work on it now.

**Comment by towoe** [comment]
Move the commit from #1624 to this one, and fixed the small screen problem.
I think this PR can go in on its own. It does improve the design a bit.

**Pull request merged**
