### PR TITLE
[lint,spi_device] Fix various Verilator lint issues in SPI device

### PR DESCRIPTION
**Pull request by marnovandermaas**

### CODE REVIEW

**Comment by marnovandermaas** [comment]
CI timed out, but I don't think this is due to the changes in this PR.

**Review by GregAC — APPROVED** [review]
LGTM, I'd suggest rebasing this on latest master to bring in the CI changes to use the faster FPGA build.

**Comment by marnovandermaas** [comment]
Rebase onto main

**Review by andreaskurth — APPROVED** [review]
LGTM, though let's get CI checks to pass (just re-ran them because the failure seemed to be spurious)

**Comment by andreaskurth** [comment]
All CI checks except AscentLint (kokoro) have passed. The failures in the AscentLint check are spurious and not related to the changes in this PR. Merging

**Pull request merged**
