### PR TITLE
[lc_ctrl] Add linear control flow SVA property

### PR DESCRIPTION
**Pull request by msfschaffner**
Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
Thanks @NigelScales for the suggested SVA! 
I have piped this through formal and it passes.

**Review by cindychip — APPROVED** [review]
lgtm, thanks Michael and Nigel

**Review by weicaiyang — APPROVED** [review]

**Comment by NigelScales** [comment]
> Thanks @NigelScales for the suggested SVA! I have piped this through formal and it passes.

If you want to make sure the assertion works try adding a branch back in the LC_CTRL FSM and see if the format tool spots the problem.
I did that for simulation.

**Review by NigelScales — APPROVED** [review]
If you are including the FSM flow assertion in the RTL I'll remove it from the bind module in https://github.com/lowRISC/opentitan/pull/12203.

**Comment by msfschaffner** [comment]
Thanks for the tip! I have inserted a loopback in the FSM and the assertion was able to catch that.

**Pull request merged**
