### PR TITLE
I2C/DV] Host Test Name Change

### PR DESCRIPTION
**Pull request by visbaz**
- Modified Host Testcase Name
- Removed Test host_rw_loopback Not Possible
- Host Test i2c_host_TestName Target Test i2c_target_TestName

### CODE REVIEW

**Review by jdonjdon — COMMENTED** [review]
Are you going to create target mode in separate tests?
or these tests are just for host mode only?

**Comment by visbaz** [comment]
> Are you going to create target mode in separate tests? or these tests are just for host mode only?

Yes these tests are Host mode only.
Design has never been tested in target mode and UVM agent was never in Host mode.
These will be changes in further PR's

**Comment by jdonjdon** [comment]
> > Are you going to create target mode in separate tests? or these tests are just for host mode only?
> 
> Yes these tests are Host mode only. Design has never been tested in target mode and UVM agent was never in Host mode. These will be changes in further PR's

Ok, thanks.

**Review by jdonjdon — APPROVED** [review]
LGTM

**Comment by visbaz** [comment]
> LGTM

@jdonjdon i am not clear why CI failed ...can you help me understand that

**Review by cindychip — APPROVED** [review]

**Pull request merged**
