### PR TITLE
[flash/dv] Add dependency in otf_sb when using vendor flash

### PR DESCRIPTION
**Pull request by eshapira**
When running otf tests with the vendor flash this check isn't valid so in this PR a dependency added in the use_vendor_flash variable.
This PR along with small PR in the foundry is fixing failing seeds of test flash_ctrl_disable.

### CODE REVIEW

**Comment by eshapira** [comment]
Hi @matutem , can you please review this PR?
Thanks

**Comment by eshapira** [comment]
Hi @rswarbrick , can you please review this PR?
@matutem seems to be unavailable.

**Comment by matutem** [comment]
@eshapira this avoids data checks in foundry, probably because it is not supported? Should we try to support these checks at some point to tighten up checking?

**Review by matutem — APPROVED** [review]
This change looks okay, but the real question is whether we plan to perform the corresponding checks against the foundry repo.

LGTM

**Comment by eshapira** [comment]
@matutem thanks for your review!
As you maybe noticed this change is disabling checks that are already disabled in the foundry.
I think Jaedon disabled them when he worked on the flash IP DV, not sure why.
In order to support those checks there some work that should be done to make the otf_scoreboard more flexible, because currently its checks aren't compatible with the foundry flash model behavior.
We need to see how we can improve those checks.

**Pull request merged**
