### PR TITLE
[flash_ctrl] Various clean-up to prepare for d2s

### PR DESCRIPTION
**Pull request by tjaychen**
- complete TODOs and TBDs
- remove unnecessary features
- update scripts to properly generate 2 layered ECC vmem
- 3rd fix for vivado's erroneously inferred loops

### CODE REVIEW

**Comment by tjaychen** [comment]
@a-will can you have a look at the feature i removed?
I don't feel like it is really necessary.  Since one can just disable the ecc option on a page boundary and have the same effect.

@alphan @moidx 
with this update, we can now turn on ECC in both `mask_rom` and `test_rom`.
Scramble still isn't quite there yet though in terms of scripting.

**Review by a-will — APPROVED** [review]
LGTM

**Comment by alphan** [comment]
> @alphan @moidx
> with this update, we can now turn on ECC in both `mask_rom` and `test_rom`.
> Scramble still isn't quite there yet though in terms of scripting.

Thanks @tjaychen, it looks like we don't need to update the silicon_creator flash_ctrl driver code: Scrambling, ECC, and HE (INFON_PAGE_CFG_SHADOWED registers) are controlled by OTP values and we leave phy config at its reset values.

**Review by msfschaffner — APPROVED** [review]
LGTM

**Pull request merged**
