### PR TITLE
Update lowrisc_ibex to lowRISC/ibex@9e3989f2

### PR DESCRIPTION
**Pull request by msfschaffner**
Update code from upstream repository
https://github.com/lowRISC/ibex.git to revision
9e3989f20505e406fc9656424ec7d076ba8b3df4

* [dvsim] Make sure results_html_name key is defined (Michael
  Schaffner)
* [testplan] Align milestone/stage terminology (Michael Schaffner)
* [dv] Double timeout for an RTL run in regression flow (Greg
  Chadwick)
* [dv,pmp] Minor fixes to PMP full random test (Marno van der Maas)
* Update google_riscv-dv to google/riscv-dv@68e3bca (Marno van der
  Maas)
* [dv] Stop write PMP CSR routine when using full randomization (Marno
  van der Maas)
* Bring back +disable_cosim to instead de-escalate fatal to info
  (Harry Callahan)
* Remove the final cosim flags from core_ibex uvm environment (Harry
  Callahan)
* Change method to locate ibex root to relative paths (Harry Callahan)
* [dv] Use lowRISC IP dir from imports instead of re-deriving it
  (Marno van der Maas)
* [dv] Made dedicated gitignore file and add coverage files (Marno van
  der Maas)
* [rtl] Cannot add M mode executable PMP regions when MML = 1 (Greg
  Chadwick)
* [dv] Add sim selection to icache make file (Greg Chadwick)
* [dv] Add MCAUSE and MSTATUS to the riscv_csr_test (Greg Chadwick)
* Made values of mcause 32 bits (Marno van der Maas)
* Fix isinstance error with Union types (Harry Callahan)
* Switch to using pathlib3x to get backported features (Harry
  Callahan)
* Fix using built-in types as type hints not supported before Python
  3.9 (Harry Callahan)
* core_ibex dv build system refactor (Harry Callahan)
* [dv] Reduce riscv_pmp_full_random_test iterations (Greg Chadwick)
* [rtl] Make PMP CSRs illegal in non PMP configurations (Greg
  Chadwick)
* [cosim] Pass PMP configuration through to spike (Greg Chadwick)
* [rtl] Fix MaxOutstandingDSideAccessesCorrect assertion (Greg
  Chadwick)
* [rtl, icache] Rework invalidation logic (Greg Chadwick)
* Add special-case signature for test_done in riscv_csr_test (Harry
  Callahan)
* Change test_done mechanism to use riscvdv handshake, not ecall
  (Harry Callahan)
* [rtl] Alter some CSR WARL behaviour to match spike (Greg Chadwick)
* [rtl] Fix MISA (Greg Chadwick)
* [dv,cosim] Add memory region to match UVM env (Canberk Topal)

Signed-off-by: Michael Schaffner <msf@google.com>

### CODE REVIEW

**Comment by msfschaffner** [comment]
This is done to fully align the milestone -> stage terminology.

**Review by tjaychen — APPROVED** [review]

**Comment by vogelpi** [comment]
Thanks @msfschaffner for the PR. CI for English Breakfast is currently failing. Most likely it's because English Breakfast doesn't implement PMP (due to resource constraints) and in the meantime we corrected upstream Ibex to trigger an illegal instruction exception upon PMP CSR accesses if PMP isn't supported. I am currently looking into how to modify the software accordingly to hopefully unblock your PR.

**Review by vogelpi — APPROVED** [review]
The PMP config access inside `test_rom_start.S` were indeed the problem. I've now fixed this and tested it locally. I've directly amended the fix to your commit in this PR. CI should now pass.

**Comment by tjaychen** [comment]
@vogelpi just curious, was the fix done inside ibex to not emit such errors when pmp's aren't enabled as a feature?

**Comment by GregAC** [comment]
The change was to make accessing the PMP CSRs an illegal instruction for non PMP configs. Both this and the prior behaviour (where the CSRs would exist but ignore writes and read as 0) are permissible under the architecture. However spike goes for the illegal instruction option and we need to match for the cosim. Tweaking our behaviour (rather than having to maintain a difference in behaviour between our spike fork and upstream spike) seemed simplest.

**Comment by vogelpi** [comment]
> @vogelpi just curious, was the fix done inside ibex to not emit such errors when pmp's aren't enabled as a feature?

This goes back to a misunderstanding of the spec from our side. IIRC the spec differentiates between (un)implemented PMP CSRs and (un)implemented PMP regions. Implementations can feature any number (up to 64) of PMP regions but either 0, 16 or 64 PMP CSRs. Accesses to unimplemented CSRs always trigger illegal instruction exceptions. Where CSRs are implemented, unimplemented regions should have WARL behavior. E.g., say you implement 8 regions, this means you need 16 CSRs. The upper 8 CSRs then have WARL behavior. The other 48 registers will trigger illegal instruction exceptions.

In Ibex, PMP CSRs would always be WARL even if PMP was disabled via SV parameter / no PMP CSRs implemented. This is what we've now fixed.

**Comment by tjaychen** [comment]
thanks for the explanation!

**Comment by msfschaffner** [comment]
Cool, thanks for the detailed explanation and the fix, @GregAC and @vogelpi!

**Pull request merged**
