### PR TITLE
[top_level, tests] Fix chip_sw_rstmgr_cpu_info test

### PR DESCRIPTION
**Pull request by matutem**
Allow cases where the current pc is not updated due to pipe stalls.

### CODE REVIEW

**Comment by matutem** [comment]
This test was failing in closed-source tests.

**Comment by matutem** [comment]
Perhaps we should add a flag to check_state for this allowance to be effective only for double fault tests?

**Review by HU90m — APPROVED** [review]
LGTM, thanks @matutem

**Comment by HU90m** [comment]
> Perhaps we should add a flag to check_state for this allowance to be effective only for double fault tests?

I think this would be better, but what's currently here is good enough to go in for now in my opinion.

**Review by moidx — APPROVED** [review]

**Pull request merged**
