### PR TITLE
[sw] Add a library to provide CHECK and friends.

### PR DESCRIPTION
**Pull request by mcy**
I keep finding myself wanting such things in non-DIF code, at any rate.

### CODE REVIEW

**Comment by gkelly** [comment]
I should have also made it more clear: I don't think we should have `CHECK`/`QCHECK`.  I think all CHECKs are silent in production builds probably.

**Comment by mcy** [comment]
I think the main thing I expected it for is for doing *something* with the return values of DIFs. In the *vast* majority of cases I've encountered, the return value is completely useless, and an immediate log-and-crash is the appropriate response (like, if I fail to set up UART in main, I need to bail, and having to write out a full conditional for this is kind of silly).

I agree with your point on CHECK/QCHECK, though. Unfortunately, I don't think there is a global "is_debug" bit yet, and I don't know what the best UI for it should be.

**Comment by gkelly** [comment]
> I think the main thing I expected it for is for doing _something_ with the return values of DIFs. In the _vast_ majority of cases I've encountered, the return value is completely useless, and an immediate log-and-crash is the appropriate response (like, if I fail to set up UART in main, I need to bail, and having to write out a full conditional for this is kind of silly).
> 
> I agree with your point on CHECK/QCHECK, though. Unfortunately, I don't think there is a global "is_debug" bit yet, and I don't know what the best UI for it should be.

To that end I think drop the `QCHECK` and we can submit this.  We'll add the debug flag stuff later, as it's not currently blocking anything.

**Comment by sriyerg** [comment]
This looks fine to me. Need to align `abort()` with a  standardized end-of-test signaling.

**Comment by gkelly** [comment]
> I think the main thing I expected it for is for doing _something_ with the return values of DIFs. In the _vast_ majority of cases I've encountered, the return value is completely useless, and an immediate log-and-crash is the appropriate response (like, if I fail to set up UART in main, I need to bail, and having to write out a full conditional for this is kind of silly).
> 
> I agree with your point on CHECK/QCHECK, though. Unfortunately, I don't think there is a global "is_debug" bit yet, and I don't know what the best UI for it should be.



> This looks fine to me. Need to align `abort()` with a standardized end-of-test signaling.

I think we'll provide an implementation of `abort` that does this on test platforms.

**Comment by mcy** [comment]
That sounds good. Done.

**Pull request merged**
