### PR TITLE
[sw, silicon_creator] Place mask_rom and rom_ext under a common dir

### PR DESCRIPTION
**Pull request by silvestrst**
```
cd $REPO_TOP
mkdir sw/device/silicon_creator
mv sw/device/mask_rom sw/device/silicon_creator
mv sw/device/rom_exts sw/device/silicon_creator

sed -i 's/sw\/device\/rom_exts/sw\/device\/silicon_creator\/rom_exts/' \
`grep -ril sw/device/rom_exts --exclude-dir=build* --exclude-dir=.git*`

sed -i 's/sw\/device\/mask_rom/sw\/device\/silicon_creator\/mask_rom/' \
`grep -ril sw/device/mask_rom --exclude-dir=build* --exclude-dir=.git*`

git clang-format

HEADERS=`find ./sw/device/ -name *.h`
for i in $HEADERS; do ./util/fix_include_guard.py $i; done
```

- Common functionality and more sub-directories can be created within
  the Silicon Creator directory

### CODE REVIEW

**Comment by alphan** [comment]
Comments from the meeting:
* Could the directory structure reflect "ownership" e.g. creator_code, silicon_creator, or silicon_creator_code?

**Comment by moidx** [comment]
> Comments from the meeting:
> 
> * Could the directory structure reflect "ownership" e.g. creator_code, silicon_creator, or silicon_creator_code?

**Comment by moidx** [comment]
oops, sorry, closed the PR by mistake, ... and just reopened. :)

**Comment by silvestrst** [comment]
> Could the directory structure reflect "ownership" e.g. creator_code, silicon_creator, or silicon_creator_code?

**Review by moidx — APPROVED** [review]
LGTM. Thanks @silvestrst!

**Review by asb — APPROVED** [review]
LGTM (once the conflict is resolved), thanks Silvestrs. It might be worth adding a sentence or two to the commit message to explain the motivation for the change.

**Pull request merged**
