### PR TITLE
[topgen] Fix enum type warnings

### PR DESCRIPTION
**Pull request by eunchan**
enum for top package did not define any type. Change them to `int
unsigned`.

### CODE REVIEW

**Comment by tjaychen** [comment]
this lgtm. Just FYI, if ever we need to pack these into arrays, we probably want to change them to `logic`. I recently debugged another warning where these were ints and then used for array packing.. the bit widths got all out of wack (I guess we could cast it too..).

**Review by tjaychen — APPROVED** [review]

**Comment by eunchan** [comment]
> this lgtm. Just FYI, if ever we need to pack these into arrays, we probably want to change them to `logic`. I recently debugged another warning where these were ints and then used for array packing.. the bit widths got all out of wack (I guess we could cast it too..).

Yeah. I agree. int or int unsigned is 32bit data. Need to convert it into `logic` or `logic [W-1:0]`. If this enum is used as index for arrays, then int should be fine.

**Comment by eunchan** [comment]
I think we can merge this as it only changes the type of enum. WDYT @tjaychen

**Review by msfschaffner — APPROVED** [review]
I think these are only used as signal indices at the moment, so LGTM.

**Pull request merged**
