### PR TITLE
DO NOT MERGE -- rstmgr consistency easy reproduce

### PR DESCRIPTION
**Pull request by jdonjdon**
Signed-off-by: Jaedon Kim <jdonjdon@google.com>

### CODE REVIEW

**Comment by jdonjdon** [comment]
run command : 
./util/dvsim/dvsim.py ./hw/ip/rstmgr/dv/rstmgr_sim_cfg.hjson -i rstmgr_leaf_rst_cnsty -r 1 -v m -w fsdb
see following signals:
tb.dut.u_daon_por_io_div4.gen_rst_chk.u_rst_chk.parent_rst_ni
tb.dut.u_daon_por_io_div4.gen_rst_chk.u_rst_chk.child_rst_ni
tb.dut.u_daon_por_io_div4.gen_rst_chk.u_rst_chk.err_o
image

**Comment by tjaychen** [comment]
ah is this related to #11858 ?

If yes, @jeoongp the fix might be less of a logic fix..and more how we inform rstmgr that its local reset and the child reset are the same in this case.  The problem with rstmgr right now is it does not directly pluck its reset from the reset tree, but instead lets the top level dictate it.  So it doesn't know which one belongs to it without additional information.

There might be other possible fixes as well.

**Comment by jdonjdon** [comment]
> ah is this related to #11858 ?

Yes,

> 
> If yes, @jeoongp the fix might be less of a logic fix..and more how we inform rstmgr that its local reset and the child reset are the same in this case. The problem with rstmgr right now is it does not directly pluck its reset from the reset tree, but instead lets the top level dictate it. So it doesn't know which one belongs to it without additional information.
> 
> There might be other possible fixes as well.

**Comment by jeoongp** [comment]
@tjaychen, @jdonjdon thanks for comments. We can think two options here.
1. rstmgr knows u_daon_por_io_div4 is a leaf that generates rst_ni. So, we can add one bit input at rstmgr_leaf_tst to indicate it's the root that generates rst_ni and propagate it through por_io_div4. Leaf FSM needs to be updated to skip Error state when the current leaf is used as the root. 

2. we can add another delay logic like a simple pipeline to avoid direct loopback at top_earlgrey. This delay logic is supposed to add additional delay onto the existing rst_ni (rstmgr_aon_resets.rst_por_io_div4_n). The delayed output is connected to rst_ni input to rstmgr. The delay amount will be SecMaxSyncDelay. (delayed_rst_ni | rst_ni) will be working as a glitch filter, too. 

I think both options are OK. Let me know your opinion.

**Comment by jeoongp** [comment]
I and @jdonjdon removed some TB assertions on skipped leaves to resolve these errors. New PR was created in https://github.com/lowRISC/opentitan/pull/12729
Details : https://github.com/lowRISC/opentitan/issues/11858

**Review by jeoongp — COMMENTED** [review]
Thanks @jdonjdon for creating simple branch for this test

**Pull request closed without merging**
