### PR TITLE
[otbn] An initial user guide that shows how to run the OTBN tooling

### LINKED ISSUE #2930: [otbn] Document software toolchain
We now have a almost complete toolchain for OTBN, we should start documenting how to use it from the perspective of a software developer.

I'm proposing to create a "OTBN software developer user guide" document at https://github.com/lowRISC/opentitan/tree/master/doc/ug.

> estimate 4

### PR DESCRIPTION
**Pull request by rswarbrick**
This is rather incomplete. For example, it doesn't explain things like
how to generate a binary blob and include that blob into an Ibex
image. But I don't think we've actually decided how best to do that
yet!

Closes #2930.

### CODE REVIEW

**Comment by rswarbrick** [comment]
Force-push fixes silly typo (calling the linker `otbn-as`)

**Comment by rswarbrick** [comment]
Cool, I'll merge it in. @GregAC: Re linking, it will appear as part of the list of user manuals. Maybe the OTBN readme makes sense? This feels "higher level" than the technical specification, so I'd rather not include a back-link there.

**Comment by GregAC** [comment]
Ah hadn't realised the doc generation would grab it. Still I think highlighting it's existence in the README would be a good idea it's easy for stuff to get lost when browsing through the many links in the OT docs.

**Comment by rswarbrick** [comment]
Cool. Added in #3092.

**Pull request merged**
