### PR TITLE
[aes/dv] added some exclusions to the fsm coverage due to new fsm sta…

### PR DESCRIPTION
**Pull request by rasmus-madsen**
This PR adds some exclusions that will go away again for V2s.
they are all addressing the error states in the FSM and the transitions to and from the error states.

Signed-off-by: Rasmus Madsen <rasmus.madsen@wdc.com>

### CODE REVIEW

**Comment by rasmus-madsen** [comment]
@rswarbrick @vogelpi  oh my the change somehow rearranged the exclusions so it looks like old where removed and then 3000 new was added.

anyhow this is all for V2 and will go away for V2s so I don't think we need a line by line review here

**Comment by rswarbrick** [comment]
Eugh, I **hate** tool-generated files. 1MiB of guff, which doesn't generate sensible diffs. Aaargh!

I've just messed around with re-sorting the lines in the <rules> list. It doesn't help, because the file numbers change as well. I guess we should just commit this temporary hack if we feel it's necessary, but I strongly believe that we need a better way to sign stuff off before we're seriously talking about verification being done. (I suspect we have the same problem on the VCS side)

@sriyerg: Have you spent any time thinking about this? I wonder whether we could have e.g. an hjson file with exclusions and then some flow that converts it into a simvision/verdi exclusion file on the fly.

About this PR itself: It looks fine to me, but I think I should let @vogelpi check it over before merge.

**Review by vogelpi — APPROVED** [review]
Once we are working towards V2S and have a first set of tests for the FI CMs in place, it's expected that the number of exclusions will drop significantly. So, I didn't bother to look at the new exclusions here in detail. LGTM.

**Comment by rasmus-madsen** [comment]
> Eugh, I **hate** tool-generated files. 1MiB of guff, which doesn't generate sensible diffs. Aaargh!
> 
> I've just messed around with re-sorting the lines in the `<rules>` list. It doesn't help, because the file numbers change as well. I guess we should just commit this temporary hack if we feel it's necessary, but I strongly believe that we need a better way to sign stuff off before we're seriously talking about verification being done. (I suspect we have the same problem on the VCS side)
> 
> @sriyerg: Have you spent any time thinking about this? I wonder whether we could have e.g. an hjson file with exclusions and then some flow that converts it into a simvision/verdi exclusion file on the fly.
> 
> About this PR itself: It looks fine to me, but I think I should let @vogelpi check it over before merge.

HI Rupert 80% of this will go away it.
but I think going forward I will not regerenate refines but create new ones and then manually copy/paste the additional lines in.. I think that would work.

**Pull request merged**
