### PR TITLE
[csrng/rtl] improved cmd rdy status bit

### PR DESCRIPTION
**Pull request by mwbranstad**
Always de-assert ready status after every cmd word write.
The tilelink poll should not see a false ready indication.

Signed-off-by: Mark Branstad <mark.branstad@wdc.com>

### CODE REVIEW

**Review by senelson7 — APPROVED** [review]
LGTM, ran 100 simulations w/ double cmd_rdy wait removed, no fails.

**Comment by tjaychen** [comment]
@mwbranstad just a quick question (because i dont know enough about how this works). It looks like rdy will de-assert after every write (presumably to wait until things are ready again).  But after that, is there no condition that might cause ready to drop other than another valid write? Perhaps an actual read or something? Or is this only the command, so we are always ready to accept another?

**Comment by mwbranstad** [comment]
the later case, this not ready scenario is only used for the cmd write on the sw port. the important thing is to drop ready as soon as the write occurs, so that a read that is pending right behind (maybe because of a bridge on the tilelink side for example) cannot capture the "old" ready status. In terms of restoring ready, this is not timing critical, so it can rely on a flopped version of the FIFO ready.

**Comment by tjaychen** [comment]
> the later case, this not ready scenario is only used for the cmd write on the sw port. the important thing is to drop ready as soon as the write occurs, so that a read that is pending right behind (maybe because of a bridge on the tilelink side for example) cannot capture the "old" ready status. In terms of restoring ready, this is not timing critical, so it can rely on a flopped version of the FIFO ready.

sounds good, thanks for the explanation.

**Review by tjaychen — APPROVED** [review]

**Comment by mwbranstad** [comment]
Closing #9677

**Pull request merged**
