### PR TITLE
[rstmgr] Fix several controllable reset issues

### PR DESCRIPTION
**Pull request by tjaychen**
See #5601 and #5602

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@NoamGottlieb

**Comment by tjaychen** [comment]
Arnon, can you and others from Nuvoton have a look and approve?

**Comment by NoamGottlieb** [comment]
checked with SG-DFT, all looks good.

**Review by eunchan — APPROVED** [review]
So, basically, adding scanmux for generated resets? LGTM.

**Comment by tjaychen** [comment]
yea that's right.

**Comment by NoamGottlieb** [comment]
In rstmgr_ctl block rst_aon_n resets should be also controlled in scan-mode 
rst_aon_n affecting ~2 FFs. In scan mode it is not controlled, hence these FFs are removed from scan.
SpyGlass-DFT messages: 
'chip_earlgrey_asic.top_earlgrey.u_rstmgr_aon.u_lc_src.rst_aon_n' is not disabled for 1 flip-flop(s) 
'chip_earlgrey_asic.top_earlgrey.u_rstmgr_aon.u_sys_src.rst_aon_n' is not disabled for 1 flip-flop(s) 
image

**Comment by imphil** [comment]
@NoamGottlieb Thanks for reporting this issue. It's easy to loose track of such reports in closed pull requests, since they are hidden from all default views. Could you instead open a new issue?

**Comment by NoamGottlieb** [comment]
Yes, I will open a new one.

**Pull request merged**
