### PR TITLE
[rust] Upgrade to rust 1.55.0

### PR DESCRIPTION
**Pull request by cfrantz**
1. Rust-1.53.0 has [`IntoIterator` for arrays](https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#intoiterator-for-arrays) which is needed for the `collection!` macro.
2. Rust-1.54.0 re-enabled incremental compilation, which was disabled in 1.52.1.
3. Rust-1.55.0 updates `std::io::ErrorKind` variants and supports open ranges in patterns.

Signed-off-by: Chris Frantz <cfrantz@google.com>

### CODE REVIEW

**Comment by mundaym** [comment]
I think the following files also need to be updated:

azure-pipelines.yml
tool_requirements.py

**Comment by imphil** [comment]
... and at https://github.com/lowRISC/opentitan-private-ci/blob/master/jobs.yml#L17

And please announce this change to all partners and ensure they're OK with the version bump and have time to update before merging.

@martin-lueker @arnonsha

**Comment by arnonsha** [comment]
@imphil 
Where is rust being used ? Only in CI ?
I am not sure we have it installed at all. I Need to check.

**Comment by imphil** [comment]
It's used if you want to build software. But I think the build system checks if Rust is available and doesn't build the Rust parts otherwise (which are host software only, e.g. opentitantool). So for now you're OK without Rust if you don't use these tools.

**Comment by arnonsha** [comment]
Thanks for clarifying. I'll check with the rest of the Nuvoton teams to make sure all are OK with this change and let you know.

**Review by mcy — APPROVED** [review]

**Comment by cfrantz** [comment]
> I think the following files also need to be updated:
> 
> azure-pipelines.yml
> tool_requirements.py
> ... and at https://github.com/lowRISC/opentitan-private-ci/blob/master/jobs.yml#L17

Updated.

**Comment by cfrantz** [comment]
Announcement: https://groups.google.com/u/1/a/opentitan.org/g/opentitan-all/c/ts4ykVX5O4k

**Comment by martin-lueker** [comment]
Hi @cfrantz, 
   Thanks, I've installed this on our side and I'm testing it now.

-Martin

**Comment by martin-lueker** [comment]
> Hi @cfrantz,
> Thanks, I've installed this on our side and I'm testing it now.
> 
> -Martin

Looks good from our side.

**Pull request merged**
