### PR TITLE
[rv_core_ibex] Re-venor Ibex

### LINKED ISSUE #20788: RFC: Removing the S&P Layer in Scrambling for Top Earl Grey
### Description

This is a [Draft RFC doc](https://docs.google.com/document/d/18jwkg_I3-3DgLvJDd4Q6CWWeS-sAp9wBvOYVQVkhoLc/edit?usp=sharing) for consideration of the TC after discussion in the Security WG and multiple iterations on the doc.

### PR DESCRIPTION
**Pull request by msfschaffner**
This will fix #20788

### CODE REVIEW

**Comment by rswarbrick** [comment]
This looks sensible to me. Other people might notice the line count diff as I did. But it's not as dramatic as it looks.
- The are some small RTL changes
- There are some UVM changes in `dv/uvm/core_ibex`
- There's a whopping load of code that we "double vendor" from riscv-dv, which has changed.

I don't know why we have this ugly nested vendoring structure, but I just looked and it's due to me back in April 2022(!) Long term, maybe we can get rid of the silliness, but it's definitely not a problem for this PR.

**Review by rswarbrick — APPROVED** [review]

**Review by vogelpi — APPROVED** [review]
LGTM!

**Comment by vogelpi** [comment]
This supersedes #20850 and is thus also takes care of #20715. I was thinking to also include another RTL improvement for the lockstep comparison enable (see #20779) but fixing this inside Ibex related in some tooling challenges. We'll thus do another vendor PR to get the lockstep comparison enable improvement.

**Comment by vogelpi** [comment]
Hm, most likely this PR also misses an update to the [hw/ip/rv_core_ibex/lint/rv_core_ibex.waiver](https://github.com/lowRISC/opentitan/pull/20850/files#diff-00cabf64a0f6fffb1d6e573d47429b244a9727ee4fd229ea8e1f1f0680f8d985) file. I'll include the fix in this PR.

**Comment by msfschaffner** [comment]
Thanks for pushing this through, @vogelpi!

**Pull request merged**
