### PR TITLE
[sysrst_ctrl] Add flash_wp_l input path

### LINKED ISSUE #10773: [sysrst_ctrl] Change request: add input path for flash_wp_l
It has been determined that for added system security, the dedicated `flash_wp_l` output should have a read-back path so that firmware can determine whether the write protect signal has been overridden by an external driver.

The simplest way to implement this is to add an input path for `flash_wp_l` to `sysrst_ctrl` so that firmware can sample its value and configure edge detectors with interrupt request functionality.
The design change does touch the CSRs - but added complexity is minimal, since the functionality can be replicated (there are other inputs with exactly the same functionality).

In terms of added DV work, the impact should therefore also be small since the functionality is not new per se, and can be replicated.

I drafted the changes in [this PR](#10774).
This also includes updates to the documentation and DV environment.
In particular, the DV test `sysrst_ctrl_pin_access` has already been aligned.

The only DV test that still needs to be aligned is the key interrupt test, which is still under development for V2.

@tjaychen and @weicaiyang can you take a look in order to determine whether it is ok to move on with this test at this point? The IP is currently at D2S / V1 - hence the change request issue.

### PR DESCRIPTION
**Pull request by msfschaffner**
Fixes #10773

### CODE REVIEW

**Comment by msfschaffner** [comment]
CC @toshaq

**Review by weicaiyang — COMMENTED** [review]
DV portion LGTM, defer to @tjaychen for approval

**Comment by msfschaffner** [comment]
Can someone take a quick look so that we can move this in :)?

**Review by tjaychen — APPROVED** [review]

**Comment by msfschaffner** [comment]
Thanks!

**Pull request merged**
