### PR TITLE
stretch test

### PR DESCRIPTION
**Pull request by jdonjdon**
enable restart

add setup time checker, fix timeing constraint for thigh

### CODE REVIEW

**Comment by tjaychen** [comment]
@jdonjdon it looks like in the read case, we never hit the `StretchTxEmpty` case.
I think this is because the test always bursts in a ton of data at once near the start.

I think it would be helpful to follow a model similar the write case where we just slowly fill in TX fifo so we can hit more cases.

On another note, are we going to do a test where the stretching is mixed between read/writes?

**Comment by jdonjdon** [comment]
> @jdonjdon it looks like in the read case, we never hit the `StretchTxEmpty` case. I think this is because the test always bursts in a ton of data at once near the start.
> 
> I think it would be helpful to follow a model similar the write case where we just slowly fill in TX fifo so we can hit more cases.
> 
> On another note, are we going to do a test where the stretching is mixed between read/writes?

Test updated [here](https://github.com/lowRISC/opentitan/pull/16291/commits/80407709a9b9dc0cfcf2f25dcd24f37a614b9c3e)
It hangs after receives 2 bytes.

Once we clean read + restart, I can create a new combined wr/rd like target_smoke

**Comment by tjaychen** [comment]
> > @jdonjdon it looks like in the read case, we never hit the `StretchTxEmpty` case. I think this is because the test always bursts in a ton of data at once near the start.
> > I think it would be helpful to follow a model similar the write case where we just slowly fill in TX fifo so we can hit more cases.
> > On another note, are we going to do a test where the stretching is mixed between read/writes?
> 
> Test updated [here](https://github.com/lowRISC/opentitan/pull/16291/commits/80407709a9b9dc0cfcf2f25dcd24f37a614b9c3e) It hangs after receives 2 bytes.
> 
> Once we clean read + restart, I can create a new combined wr/rd like target_smoke

sounds great, let me debug.

**Comment by tjaychen** [comment]
> > > @jdonjdon it looks like in the read case, we never hit the `StretchTxEmpty` case. I think this is because the test always bursts in a ton of data at once near the start.
> > > I think it would be helpful to follow a model similar the write case where we just slowly fill in TX fifo so we can hit more cases.
> > > On another note, are we going to do a test where the stretching is mixed between read/writes?
> > 
> > 
> > Test updated [here](https://github.com/lowRISC/opentitan/pull/16291/commits/80407709a9b9dc0cfcf2f25dcd24f37a614b9c3e) It hangs after receives 2 bytes.
> > Once we clean read + restart, I can create a new combined wr/rd like target_smoke
> 
> sounds great, let me debug.

@jdonjdon 
hmmm.. was this run against a stale version of the rtl? Mine doesn't actually hang. 
I'll double check if I missed anything.. but i didn't think so.

**Comment by tjaychen** [comment]
@jdonjdon i've made another update in #16249.
Please give it a try.

While the `wr_stress` passes if i give it enough time, the `rd_stress` seems to get stuck. It looks like the tb does a bunch of transactions, sends a stop, but then does nothing else.

**Comment by jdonjdon** [comment]
@tjaychen 
With https://github.com/lowRISC/opentitan/pull/16291/commits/8267d0d5faecb2ce6f28ffd09751ba17426d64f8
read test pass too.

I ran read/write mixed test.
cmd:
./util/dvsim/dvsim.py ./hw/ip/i2c/dv/i2c_sim_cfg.hjson -i i2c_target_stretch -r 1 -s 1 -w fsdb

I ran with your https://github.com/lowRISC/opentitan/pull/16249
Please see following sigals.

@ 7962566864 ps,
tb.start_cnt[31:0]    =  'd22
tb.byte_cnt[31:0]     =   1 
tb.bit_idx[3:0]       =   0 
tb.dut.i2c_core.scl_i =   1
tb.dut.i2c_core.sda_i =   1
tb.dut.i2c_core.scl_o =   1
tb.dut.i2c_core.sda_o =   1

This is 22nd transaction. After address byte, the 1st data byte should be 0x3d but rtl sends 0xbd

**Comment by tjaychen** [comment]
> @tjaychen With [8267d0d](https://github.com/lowRISC/opentitan/commit/8267d0d5faecb2ce6f28ffd09751ba17426d64f8) read test pass too.
> 
> I ran read/write mixed test. cmd: ./util/dvsim/dvsim.py ./hw/ip/i2c/dv/i2c_sim_cfg.hjson -i i2c_target_stretch -r 1 -s 1 -w fsdb
> 
> I ran with your #16249 Please see following sigals.
> 
> @ 7962566864 ps, tb.start_cnt[31:0] = 'd22 tb.byte_cnt[31:0] = 1 tb.bit_idx[3:0] = 0 tb.dut.i2c_core.scl_i = 1 tb.dut.i2c_core.sda_i = 1 tb.dut.i2c_core.scl_o = 1 tb.dut.i2c_core.sda_o = 1
> 
> This is 22nd transaction. After address byte, the 1st data byte should be 0x3d but rtl sends 0xbd

nice, this test caught a bug i was wondering about.  Basically we had two stretch states chain on each other.
I had a minor fix for it.  Now the test gets beyond but hangs again.  It looks like the test is not supplying data for a read transaction so the controller is just forever stretching. I double checked the log and I didn't see anyone trying to drive a stop.

The fixes are pushed to #16249

**Comment by jdonjdon** [comment]
@tjaychen I fixed my test in local and it all looks good now.
I will create PR for stretch test.

**Comment by tjaychen** [comment]
awesome, thank you for pushing through this @jdonjdon

**Pull request closed without merging**
