### PR TITLE
Require VCS 2020.12-SP2

### PR DESCRIPTION
**Pull request by imphil**
VCS 2020.12-SP2 contains fixes for critical issues in our verification
environment.

### CODE REVIEW

**Comment by imphil** [comment]
Please let me know when everybody is ready for this change, we don't need to get it in immediately.

The private CI update is prepared at https://github.com/lowRISC/opentitan-private-ci/pull/10 and can go in together with this PR once we're ready.

**Comment by martin-lueker** [comment]
@senelson7 has volunteered to interact with our IT department on this.  (Thanks Steve!)

**Review by senelson7 — APPROVED** [review]
WD is using vcs/2020.12-SP2 now

**Comment by martin-lueker** [comment]
Thanks @senelson7!

**Review by martin-lueker — APPROVED** [review]
WDC is ready for these changes

**Comment by imphil** [comment]
Great, thanks @martin-lueker and @senelson7! @sriyerg let me know when you're ready as well.

**Comment by sriyerg** [comment]
We are ready as well. @sha-ron, please let us know if we are ready to switch to the version. Thanks!

**Comment by sha-ron** [comment]
@sriyerg yes we are ready as well. thanks

**Comment by imphil** [comment]
The private CI runners are now using VCS 2020.12-SP2, re-running CI in here to ensure it's working as expected.

**Pull request merged**
