### PR TITLE
[dv/sysrst] Sysrst z3 test

### PR DESCRIPTION
**Pull request by cindychip**
Only the last commit is relevant.

This PR is based on comment: https://github.com/lowRISC/opentitan/pull/17247/files#r1102650481
@crteja please let me know if this meets your suggestion?

### CODE REVIEW

**Comment by crteja** [comment]
@cindychip , Thanks for the change, this should cover the timing check for `z3_wakeup_o`. Looks good to me.

**Review by marnovandermaas — COMMENTED** [review]
Great work thanks, would you mind squashing these two commits into one?

**Comment by cindychip** [comment]
> Great work thanks, would you mind squashing these two commits into one?

Thank you! Done, squashed into one commit.

**Review by marnovandermaas — APPROVED** [review]
LGTM, @crteja what do you think?

**Comment by crteja** [comment]
Looks good to me

**Review by crteja — APPROVED** [review]

**Review by timothytrippel — APPROVED** [review]

**Pull request merged**
