### PR TITLE
[dv/otp_ctrl] collect some functional coverage through interface

### PR DESCRIPTION
**Pull request by cindychip**
This PR collects OTP_CTRL I/O coverage via otp_cov_if.

Signed-off-by: Cindy Chen <chencindy@opentitan.org>

### CODE REVIEW

**Comment by sriyerg** [comment]
So you are splitting coverage between this interface and the uvm component. Do document this well in the DV doc.

**Comment by cindychip** [comment]
Thanks Sri, that is a good reminder. I will update all the changes in OTP_CTRL's DV doc.

**Review by udinator — APPROVED** [review]

**Comment by matutem** [comment]
I assume these covergroups are already in the testplan, or is that a separate PR?

**Comment by cindychip** [comment]
Hey Matute, yes the covergroups are in this PR: https://github.com/lowRISC/opentitan/pull/6677.
Still trying to see what is the best syntax for the array of covergroups.

**Review by matutem — APPROVED** [review]
LGTM

**Pull request merged**
