### PR TITLE
[otbn,dv] Recoverable alert support

### PR DESCRIPTION
**Pull request by rswarbrick**
*The first commit is just a slight refactoring in a base class to make things easier to hook into. The meat of the PR is the second commit, whose commit message is below:*

This was a bit awkward to fit into the existing DV alert framework
because running a binary will trigger a recoverable error if the code
does something naughty (jumping to a bad address / overflowing a stack
etc.). Unfortunately, we don't know ahead of time that this is going
to happen, which makes the `cip_base_scoreboard::set_exp_alert()`
function rather difficult to use.

So we do things a bit differently, disabling the base class alert
tracking and handling alerts ourselves. The basic idea is that if you
want to prove

    expected alert   <->  seen alert

you can do it with two implications:

    expected alert -> seen alert
    seen alert -> expected alert

The "expected alert" event happens when OTBN stops with a status of
LOCKED (implying a fatal alert) or with a nonzero set of error
bits (implying a recoverable alert). The "seen alert" event happens
when we see an alert. In each case, we set some flags and then spawn a
checker process that will wait a short time and then check that the
other event has happened.

For recoverable alerts, we also reset the flags to make sure that we
can cope with subsequent recoverable alerts without having to see a
reset in between.

The scoreboard gets a `phase_ready_to_end` function that checks we don't
accidentally stop the test while we're still waiting for an expected
alert. In practice, I suspect this will never matter because of the
drain time in the base monitor class, but it probably doesn't hurt to
be careful.

The final change is to simplify the `otbn_imem_err` sequence: now that
the scoreboard handles alerts, there's much less of a dance required
to get the timing right.

### CODE REVIEW

**Comment by rswarbrick** [comment]
@cindychip: In order to allow recoverable errors without triggering a check in the DV base sequences, I had to do a rather ugly hack. See `check_no_fatal_alerts` in `otbn_base_vseq`. I know you're working on the base class version of that task. Is there a cleaner way to achieve this, do you know?

**Comment by cindychip** [comment]
> @cindychip: In order to allow recoverable errors without triggering a check in the DV base sequences, I had to do a rather ugly hack. See `check_no_fatal_alerts` in `otbn_base_vseq`. I know you're working on the base class version of that task. Is there a cleaner way to achieve this, do you know?

Thanks for the PR :) Do you think this PR: https://github.com/lowRISC/opentitan/pull/9566 help with your OTBN issue? It waits 200 cycles until recoverable alerts are done, then check if there is any more fatal alerts.

**Review by cindychip — APPROVED** [review]
LGTM, I hope this PR https://github.com/lowRISC/opentitan/pull/9566 could also fix the recoverable alert check.

**Comment by rswarbrick** [comment]
> Thanks for the PR :) Do you think this PR: #9566 help with your OTBN issue? It waits 200 cycles until recoverable alerts are done, then check if there is any more fatal alerts.

I'm not sure that it will. If I understand rightly, this is still asserting that no alerts (of any type) happen in a particular fixed time window from the start of the test. Makes sense for the common sequences where we control whether alerts are being triggered. Less so for the actual dut testing. I wonder whether there's a bit of a refactoring needed: I'd have thought that every other IP block with recoverable alerts is going to have the same problem if they want to write any tests that trigger them at "interesting times".

**Pull request merged**
