### PR TITLE
[dv/cdc] Enable cdc instrumentation in three IPs and top_earlgrey

### PR DESCRIPTION
**Pull request by matutem**
Add cdc instrumentation to aon_timer, flash_ctrl, and alert_handler. Increase wait times by one cycle in two assertions due to CDC delay.

Partially addresses #16689

### CODE REVIEW

**Comment by cindychip** [comment]
thanks @matutem, you probably need to do a `make` under `hw` directory to update auto-generated alert_handler code.

**Comment by matutem** [comment]
Thanks Cindy: I just updated the PR after make -C hw.

**Comment by matutem** [comment]
And nice to work with you again.

**Review by cindychip — APPROVED** [review]
lgtm, hope not too many regression failure haha

**Comment by matutem** [comment]
@cindychip I will remove this PR and replace it by https://github.com/lowRISC/opentpitan/pull/17952 in hope it will fix the metadata check CI failure. They are identical otherwise: could you approve that instead?

**Pull request closed without merging**
