### PR TITLE
[dv] Split out the logic to connect a sequencer to a monitor

### PR DESCRIPTION
**Pull request by rswarbrick**
*Note: This is in draft because it depends on #5861. That is a quick bodge to get things working again; this is supposed to be a more considered fix.*

This connection is handy, but not very generic. In particular, it
implies some slightly unnecessary parameterisations for types in the
dv_lib base classes: not impossible, but a cost to users who don't
want the feature.

This patch splits that logic into a new "dv_seq_agent" core file. This
subclasses the parts of an agent that need to know about the special
behaviour (the agent itself, its configuration, the monitor and the
sequencer). Now, the code that uses this feature (csrng, i2c, spi and
push_pull) can use it explicitly, and the rest of the code doesn't see
it.

### CODE REVIEW

**Review by sriyerg — CHANGES_REQUESTED** [review]
Most interface agents need to operate in both, host & device modes. In device mode, it is very typical to want to automatically (controllably) react to a request from the host (DUT) and send a response back. The sequencer to monitor TLM connection achieves that. It is very typical - most interface agents need to have this capability. 

The UVM agent is basically an encapsulating layer that allows an interface modeling entity to behave in a variety of different ways (host / device mode, active / passive mode, reactive /non-reactive device mode etc.). In you case (OTBN model), it will only operate as a passive monitor. My suggestion would be to get rid of `otbn_model_agent` entirely since it is not needed - you can directly instantiate the `otbn_model_monitor` in your env instead, and circumvent these features that you don't need.

I very much prefer not adding yet another layer - there already are control knobs to disable it if not required.

**Comment by rswarbrick** [comment]
The problem with the control knobs is that **in order to compile**, an agent that uses different types for its sequence and its monitored transactions has to instantiate e.g. the monitor with the sequence item types. This seems a bit crazy to me: if I'm not using this functionality, it's kind of odd to have to pass sequence item types to the monitor.

You're right that there's another way of doing things for OTBN, but I actually ran into this when trying to vendor OT into Ibex, where the ICache testbench uses different types for sequence request, sequence response and monitored bus item.

**Comment by weicaiyang** [comment]
agree with Sri. seems a bit waste to add another layer to just have the req/rsp port and fifo connected.

otbn agent is a bit special. It only has monitor but no driver no sequencer, so that we need a bit workaround for it. perhaps try to supply dummy types to make it compile

**Comment by rswarbrick** [comment]
As I said above, this is not really about the OTBN agent. Anyway, it seems you guys feel strongly, so I'll just accept what I think is a slightly broken data model: it's not a big deal.

**Pull request closed without merging**
