### PR TITLE
[UART] Update Uart tx interrupt handling

### PR DESCRIPTION
**Pull request by tjaychen**
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@weicaiyang i've updated the interrupt handling (sorry it took me awhile).
The empty is basically qualified with idle as you suggested, and the threshold is changed to 2 and edge based.

Let me know if this looks okay to you and i can change rx full and rx lvl to match, since software prefers edge based interrupts anyways.

**Comment by weicaiyang** [comment]
> @weicaiyang i've updated the interrupt handling (sorry it took me awhile).
> The empty is basically qualified with idle as you suggested, and the threshold is changed to 2 and edge based.
> 
> Let me know if this looks okay to you and i can change rx full and rx lvl to match, since software prefers edge based interrupts anyways.

Thanks for the update. 
Seems better to change rx_full and rx_water edge triggered. Also make the same change on rx watermark threshold?

**Comment by tjaychen** [comment]
yeah i can change that, just wanted to make sure you had a chance to look.
For the rx threshold, since the comparison is `>=`, i dont think it makes sense to change.  Since that one basically is there to tell us the rx fifo is no longer empty, and there are definitely cases where that might be useful.  Whereas if we had `>= 2`, we could have a single entry sitting in the rx fifo without knowing (although there is also the timeout mechanism).

Note one big change is on the watermark is that they are now edge events.  Meaning, if you do not write a burst of data that is `>=` the threshold, it will never trigger.  This makes things a little unfriendly for DV, but in reality is how I imagine software would use it.

**Comment by weicaiyang** [comment]
> yeah i can change that, just wanted to make sure you had a chance to look.
> For the rx threshold, since the comparison is `>=`, i dont think it makes sense to change. Since that one basically is there to tell us the rx fifo is no longer empty, and there are definitely cases where that might be useful. Whereas if we had `>= 2`, we could have a single entry sitting in the rx fifo without knowing (although there is also the timeout mechanism).
> 
> Note one big change is on the watermark is that they are now edge events. Meaning, if you do not write a burst of data that is `>=` the threshold, it will never trigger. This makes things a little unfriendly for DV, but in reality is how I imagine software would use it.

thanks for the explanation. consistent behavior on both tx and rx watermark actually makes DV easier and less confusing, although some update is needed. I have figured out a way to check tx_watermark. It will be the similar change for rx_watermark.

**Comment by tjaychen** [comment]
sounds good @weicaiyang.  I'll make the modifications and update this PR.

**Comment by tjaychen** [comment]
@weicaiyang 
sorry it took me so long. i've updated rx to behave the same, and i've also added some notes in the spec.

**Comment by weicaiyang** [comment]
> @weicaiyang
> sorry it took me so long. i've updated rx to behave the same, and i've also added some notes in the spec.

Thanks Tim. The change looks good to me.

**Pull request merged**
